/*
 * $RCSfile: ${java.className}.java,v $
 * $Revision: 1.1 $
 * $Date: ${build.date} $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: ${template.home}
 * path: ${template.path}
 * lastModified: ${template.lastModified}
 * options: -fastJstl ${options.fastJstl}
 * template.dependencies
${template.dependencies}
 *
 * JSP generated by JspCompiler-${compiler.version} (built ${build.time})
 */
package ${java.packageName};

import java.io.Writer;
import com.skin.ayada.ExpressionContext;
import com.skin.ayada.JspTemplate;
import com.skin.ayada.JspWriter;
import com.skin.ayada.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.util.ELUtil;
${jsp.directive.import}

/**
 * <p>Title: ${java.className}</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ${java.className} extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args) {
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ${java.className} template = new ${java.className}();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }
${jsp.declaration}
    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /**
         * 自定义隐含变量, 允许不同的运行环境定义不同的隐含变量
         * 如果需要定义隐含变量请配置编译模板: ayada.properties
         * ayada.compile.java-template=com/skin/ayada/compile/class.jsp
         * 重新指定一个新的模板文件即可
         * 例如在web环境可定义如下的隐含变量:
         * 
         * ServletContext servletContext = (ServletContext)(pageContext.getAttribute("servletContext"));
         * HttpServletRequest request = (HttpServletRequest)(pageContext.getAttribute("request"));
         * HttpServletResponse response = (HttpServletResponse)(pageContext.getAttribute("response"));
         * 注: 隐含变量必须在模板运行之前由应用方注入到pageContext中.
         */

${jsp.method.body}
        out.flush();
        jspWriter.flush();
    }
${jsp.subclass.body}
${jsp.static.declaration}
}
