/*
 * $RCSfile: CommandTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2014-04-02 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * LastModified: 2014-04-02 11:21:08 265
 * JSP generated by JspCompiler-0.1.1 (built 2014-04-02 11:30:43 046)
 *
 */
package _jsp.webapp;

import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;

/**
 * <p>Title: CommandTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
public class CommandTemplate extends JspTemplate
{
    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    public void _execute(final PageContext pageContext) throws Throwable
    {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /* jsp:directive.page: lineNumber: 1 */
        /* <jsp:directive.page contentType="text/html; charset=UTF-8"/> */
        /* jsp:directive.page END */

        /* TEXT: lineNumber: 2 */
        out.write("<!--\r\nt:import: 编译指令\r\n1. 可以放在任何位置, 但必须在使用之前引入\r\n2. 如果多次引入同一个tag, tag的bodyContent以最后一次引入的为准, 引擎在编译结束之后才会根据bodyContent的类型做一次紧缩处理\r\n   bodyContent: jsp|tagdependent|empty\r\n   如果是tagdependent, 那么该tag内部的所有文本节点和表达式节点都会被清除, 其子节点的内容不会清除(但是会根据子节点的bodyContent决定是否清除)\r\n   如果是empty, 那么内部的任何节点都会被清除\r\n   如果是jsp, 则保持现有内容不变\r\n   因此所有的引入操作最好放在文件头, 并且对同一个tag只引入一次\r\n\r\n3. className不是必选项, 可以为空, 如果为空则使用ayada-taglib-default.xml或者ayada-taglib.xml文件中配置的className, 因此下面的两种写法都是合法的\r\n    ");

        /* NODE START: lineNumber: 13, offset: 3, length: 2, tagClassName: com.skin.ayada.jstl.core.ImportTag, tagInstanceName: _jsp_ImportTag_4 */
        /* <t:import name="c:if" bodyContent="tagdependent" description="重写c:if标签, 不输出内容"/> */
        /* pageContext.getTagLibrary().setup("c:if", "null"); */
        /* jsp.jstl.core.ImportTag END */
        /* NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.ImportTag, tagInstanceName: _jsp_ImportTag_4 */

        /* TEXT: lineNumber: 14 */
        out.write("    ");

        /* NODE START: lineNumber: 14, offset: 6, length: 2, tagClassName: com.skin.ayada.jstl.core.ImportTag, tagInstanceName: _jsp_ImportTag_7 */
        /* <t:import name="c:if" className="com.skin.ayada.jstl.core.IfTag" bodyContent="tagdependent" description="重写c:if标签, 不输出内容"/> */
        /* pageContext.getTagLibrary().setup("c:if", "com.skin.ayada.jstl.core.IfTag"); */
        /* jsp.jstl.core.ImportTag END */
        /* NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.core.ImportTag, tagInstanceName: _jsp_ImportTag_7 */

        /* TEXT: lineNumber: 16 */
        out.write("4. bodyContent和description都不是必选项, 可以为空, bodyContent默认为jsp\r\n-->\r\n");

        /* NODE START: lineNumber: 18, offset: 9, length: 2, tagClassName: com.skin.ayada.jstl.core.ImportTag, tagInstanceName: _jsp_ImportTag_10 */
        /* <t:import name="c:if" bodyContent="tagdependent" description="重写c:if标签, 不输出内容"/> */
        /* pageContext.getTagLibrary().setup("c:if", "null"); */
        /* jsp.jstl.core.ImportTag END */
        /* NODE END: lineNumber: 18, tagClassName: com.skin.ayada.jstl.core.ImportTag, tagInstanceName: _jsp_ImportTag_10 */

        /* NODE START: lineNumber: 19, offset: 11, length: 2, tagClassName: com.skin.ayada.jstl.core.ImportTag, tagInstanceName: _jsp_ImportTag_12 */
        /* <t:import name="c:if" className="com.skin.ayada.jstl.core.IfTag" bodyContent="tagdependent" description="重写c:if标签, 不输出内容"/> */
        /* pageContext.getTagLibrary().setup("c:if", "com.skin.ayada.jstl.core.IfTag"); */
        /* jsp.jstl.core.ImportTag END */
        /* NODE END: lineNumber: 19, tagClassName: com.skin.ayada.jstl.core.ImportTag, tagInstanceName: _jsp_ImportTag_12 */

        /* TEXT: lineNumber: 21 */
        out.write("<h1>tag.bodyContent</h1>\r\n<p>1. jsp: any content</p>\r\n<p>2. tagdependent: tag only</p>\r\n<p>3. empty: ignore any content</p>\r\n\r\n<!-- 使用重新定义的c:if标签, 该标签内部的所有文本内容在编译期都会被清除, 但是自标签的文本仍然可以输出 -->\r\n");

        /* NODE START: lineNumber: 27, offset: 14, length: 5, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_15 */
        /* <c:if test="${1 == 1}">...</c:if> */
        if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")){
            /* NODE START: lineNumber: 29, offset: 15, length: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_16 */
            /* <c:out escapeXml="true">...</c:out> */
            out = pageContext.pushBody();
            /* TEXT: lineNumber: 29 */
            out.write("\"I\'m here !\"");
            pageContext.printBodyContent((BodyContent)out, true);
            out = pageContext.popBody();
            /* jsp.jstl.core.OutTag END */
            /* NODE END: lineNumber: 29, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_16 */

        } /* jsp.jstl.core.IfTag END */
        /* NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_15 */

        /* TEXT: lineNumber: 30 */
        out.write("\r\n\r\n<!-- c:command的bodyContent被定义为tagdependent，因此内部的文本内容都会被忽略。-->\r\n");

        /* NODE START: lineNumber: 33, offset: 20, length: 16, tagClassName: com.skin.ayada.jstl.core.DependentTag, tagInstanceName: _jsp_DependentTag_21 */
        /* <c:command>...</c:command> */
        com.skin.ayada.jstl.core.DependentTag _jsp_DependentTag_21 = new com.skin.ayada.jstl.core.DependentTag();
        _jsp_DependentTag_21.setParent((Tag)null);
        _jsp_DependentTag_21.setPageContext(pageContext);
        int _jsp_start_flag_21 = _jsp_DependentTag_21.doStartTag();

        if(_jsp_start_flag_21 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_21 != Tag.SKIP_BODY){
            int _jsp_flag_21 = 0;

            do{
                /* NODE START: lineNumber: 35, offset: 21, length: 14, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_22 */
                /* <c:if test="${1 == 2}">...</c:if> */
                if(ExpressionUtil.getBoolean(expressionContext, "${1 == 2}")){
                    /* NODE START: lineNumber: 36, offset: 22, length: 2, tagClassName: com.skin.ayada.jstl.io.CopyTag, tagInstanceName: _jsp_CopyTag_23 */
                    /* <io:copy file="E:/WorkSpace/ayada/webapp/test1" todir="E:/WorkSpace/ayada/webapp/test2"/> */
                    com.skin.ayada.jstl.io.CopyTag _jsp_CopyTag_23 = new com.skin.ayada.jstl.io.CopyTag();
                    _jsp_CopyTag_23.setParent((Tag)null);
                    _jsp_CopyTag_23.setPageContext(pageContext);
                    _jsp_CopyTag_23.setFile("E:/WorkSpace/ayada/webapp/test1");
                    _jsp_CopyTag_23.setTodir("E:/WorkSpace/ayada/webapp/test2");
                    int _jsp_start_flag_23 = _jsp_CopyTag_23.doStartTag();

                    if(_jsp_start_flag_23 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_23 != Tag.SKIP_BODY){
                        _jsp_CopyTag_23.doAfterBody();
                    }
                    _jsp_CopyTag_23.doEndTag();
                    _jsp_CopyTag_23.release();
                    /* NODE END: lineNumber: 36, tagClassName: com.skin.ayada.jstl.io.CopyTag, tagInstanceName: _jsp_CopyTag_23 */

                    /* NODE START: lineNumber: 37, offset: 24, length: 2, tagClassName: com.skin.ayada.jstl.io.DeleteTag, tagInstanceName: _jsp_DeleteTag_25 */
                    /* <io:delete file="E:/WorkSpace/ayada/webapp/test2/style.css"/> */
                    com.skin.ayada.jstl.io.DeleteTag _jsp_DeleteTag_25 = new com.skin.ayada.jstl.io.DeleteTag();
                    _jsp_DeleteTag_25.setParent((Tag)null);
                    _jsp_DeleteTag_25.setPageContext(pageContext);
                    _jsp_DeleteTag_25.setFile("E:/WorkSpace/ayada/webapp/test2/style.css");
                    int _jsp_start_flag_25 = _jsp_DeleteTag_25.doStartTag();

                    if(_jsp_start_flag_25 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_25 != Tag.SKIP_BODY){
                        _jsp_DeleteTag_25.doAfterBody();
                    }
                    _jsp_DeleteTag_25.doEndTag();
                    _jsp_DeleteTag_25.release();
                    /* NODE END: lineNumber: 37, tagClassName: com.skin.ayada.jstl.io.DeleteTag, tagInstanceName: _jsp_DeleteTag_25 */

                    /* NODE START: lineNumber: 38, offset: 26, length: 2, tagClassName: com.skin.ayada.jstl.io.MakeDirTag, tagInstanceName: _jsp_MakeDirTag_27 */
                    /* <io:mkdir file="E:/WorkSpace/ayada/webapp/test2/empty1"/> */
                    com.skin.ayada.jstl.io.MakeDirTag _jsp_MakeDirTag_27 = new com.skin.ayada.jstl.io.MakeDirTag();
                    _jsp_MakeDirTag_27.setParent((Tag)null);
                    _jsp_MakeDirTag_27.setPageContext(pageContext);
                    _jsp_MakeDirTag_27.setFile("E:/WorkSpace/ayada/webapp/test2/empty1");
                    int _jsp_start_flag_27 = _jsp_MakeDirTag_27.doStartTag();

                    if(_jsp_start_flag_27 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_27 != Tag.SKIP_BODY){
                        _jsp_MakeDirTag_27.doAfterBody();
                    }
                    _jsp_MakeDirTag_27.doEndTag();
                    _jsp_MakeDirTag_27.release();
                    /* NODE END: lineNumber: 38, tagClassName: com.skin.ayada.jstl.io.MakeDirTag, tagInstanceName: _jsp_MakeDirTag_27 */

                    /* NODE START: lineNumber: 39, offset: 28, length: 2, tagClassName: com.skin.ayada.jstl.io.MakeDirTag, tagInstanceName: _jsp_MakeDirTag_29 */
                    /* <io:mkdir file="E:/WorkSpace/ayada/webapp/test2/empty2"/> */
                    com.skin.ayada.jstl.io.MakeDirTag _jsp_MakeDirTag_29 = new com.skin.ayada.jstl.io.MakeDirTag();
                    _jsp_MakeDirTag_29.setParent((Tag)null);
                    _jsp_MakeDirTag_29.setPageContext(pageContext);
                    _jsp_MakeDirTag_29.setFile("E:/WorkSpace/ayada/webapp/test2/empty2");
                    int _jsp_start_flag_29 = _jsp_MakeDirTag_29.doStartTag();

                    if(_jsp_start_flag_29 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_29 != Tag.SKIP_BODY){
                        _jsp_MakeDirTag_29.doAfterBody();
                    }
                    _jsp_MakeDirTag_29.doEndTag();
                    _jsp_MakeDirTag_29.release();
                    /* NODE END: lineNumber: 39, tagClassName: com.skin.ayada.jstl.io.MakeDirTag, tagInstanceName: _jsp_MakeDirTag_29 */

                    /* NODE START: lineNumber: 40, offset: 30, length: 2, tagClassName: com.skin.ayada.jstl.io.DeleteTag, tagInstanceName: _jsp_DeleteTag_31 */
                    /* <io:delete file="E:/WorkSpace/ayada/webapp/test2/empty2"/> */
                    com.skin.ayada.jstl.io.DeleteTag _jsp_DeleteTag_31 = new com.skin.ayada.jstl.io.DeleteTag();
                    _jsp_DeleteTag_31.setParent((Tag)null);
                    _jsp_DeleteTag_31.setPageContext(pageContext);
                    _jsp_DeleteTag_31.setFile("E:/WorkSpace/ayada/webapp/test2/empty2");
                    int _jsp_start_flag_31 = _jsp_DeleteTag_31.doStartTag();

                    if(_jsp_start_flag_31 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_31 != Tag.SKIP_BODY){
                        _jsp_DeleteTag_31.doAfterBody();
                    }
                    _jsp_DeleteTag_31.doEndTag();
                    _jsp_DeleteTag_31.release();
                    /* NODE END: lineNumber: 40, tagClassName: com.skin.ayada.jstl.io.DeleteTag, tagInstanceName: _jsp_DeleteTag_31 */

                    /* NODE START: lineNumber: 41, offset: 32, length: 2, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_33 */
                    /* <c:exit test="${1 == 1}"/> */
                    if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")){
                        return;
                    }
                    /* jsp.jstl.core.ExitTag END */
                    /* NODE END: lineNumber: 41, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_33 */

                } /* jsp.jstl.core.IfTag END */
                /* NODE END: lineNumber: 35, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_22 */

                _jsp_flag_21 = _jsp_DependentTag_21.doAfterBody();
            }
            while(_jsp_flag_21 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_DependentTag_21.doEndTag();
        _jsp_DependentTag_21.release();
        /* NODE END: lineNumber: 33, tagClassName: com.skin.ayada.jstl.core.DependentTag, tagInstanceName: _jsp_DependentTag_21 */

        /* TEXT: lineNumber: 43 */
        out.write("\r\n\r\n<h1>sql:execute</h1>\r\n<h2>connection</h2>\r\n<p>1. get from attribute, example: connection=\"${expression}\"</p>\r\n<p>2. get from pageContext by name: connection</p>\r\n<p>3. get from parent tag</p>\r\n<p>4. throws exception</p>\r\n<p>template.home: ");
        /* EXPRESSION: lineNumber: 51 */
        out.write(expressionContext.getString("template.home"));
        /* TEXT: lineNumber: 51 */
        out.write("</p>\r\n\r\n<!-- use external connection -->\r\n");

        /* NODE START: lineNumber: 54, offset: 39, length: 2, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_40 */
        /* <sql:connect var="connection2" connection="${myConnection}">...</sql:connect> */
        com.skin.ayada.jstl.sql.ConnectTag _jsp_ConnectTag_40 = new com.skin.ayada.jstl.sql.ConnectTag();
        try{
            _jsp_ConnectTag_40.setParent((Tag)null);
            _jsp_ConnectTag_40.setPageContext(pageContext);
            _jsp_ConnectTag_40.setVar("connection2");
            _jsp_ConnectTag_40.setConnection((java.sql.Connection)(ExpressionUtil.evaluate(expressionContext, "${myConnection}", java.sql.Connection.class)));
            int _jsp_start_flag_40 = _jsp_ConnectTag_40.doStartTag();

            if(_jsp_start_flag_40 == Tag.SKIP_PAGE){
                return;
            }
            if(_jsp_start_flag_40 != Tag.SKIP_BODY){
                _jsp_ConnectTag_40.doAfterBody();
            }
            _jsp_ConnectTag_40.doEndTag();
            _jsp_ConnectTag_40.release();
        }
        catch(Throwable throwable){
            _jsp_ConnectTag_40.doCatch(throwable);
        }
        finally{
            _jsp_ConnectTag_40.doFinally();
        }
        /* NODE END: lineNumber: 54, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_40 */

        /* TEXT: lineNumber: 54 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 56, offset: 42, length: 12, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_43 */
        /* <c:if test="${1 == 1}">...</c:if> */
        if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")){
            /* NODE START: lineNumber: 57, offset: 43, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_44 */
            /* <c:set var="createDatabaseUrl" value="jdbc:mysql://10.3.254.97:3307?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnection=true"/> */
            pageContext.setAttribute("createDatabaseUrl", "jdbc:mysql://10.3.254.97:3307?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnection=true");
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 57, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_44 */

            /* NODE START: lineNumber: 58, offset: 45, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_46 */
            /* <c:set var="url" value="jdbc:mysql://10.3.254.97:3307/mytest2?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;autoReconnection=true"/> */
            pageContext.setAttribute("url", "jdbc:mysql://10.3.254.97:3307/mytest2?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnection=true");
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 58, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_46 */

            /* NODE START: lineNumber: 59, offset: 47, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_48 */
            /* <c:set var="driverClass" value="com.mysql.jdbc.Driver"/> */
            pageContext.setAttribute("driverClass", "com.mysql.jdbc.Driver");
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 59, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_48 */

            /* NODE START: lineNumber: 60, offset: 49, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_50 */
            /* <c:set var="userName" value="bookAdmin"/> */
            pageContext.setAttribute("userName", "bookAdmin");
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 60, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_50 */

            /* NODE START: lineNumber: 61, offset: 51, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_52 */
            /* <c:set var="password" value="bookAdmin"/> */
            pageContext.setAttribute("password", "bookAdmin");
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 61, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_52 */

        } /* jsp.jstl.core.IfTag END */
        /* NODE END: lineNumber: 56, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_43 */

        /* TEXT: lineNumber: 62 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 64, offset: 55, length: 12, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_56 */
        /* <c:if test="${1 == 2}">...</c:if> */
        if(ExpressionUtil.getBoolean(expressionContext, "${1 == 2}")){
            /* NODE START: lineNumber: 65, offset: 56, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_57 */
            /* <c:set var="createDatabaseUrl" value="jdbc:mysql://localhost:3306?user=root&amp;password=1234&amp;characterEncoding=utf8"/> */
            pageContext.setAttribute("createDatabaseUrl", "jdbc:mysql://localhost:3306?user=root&password=1234&characterEncoding=utf8");
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 65, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_57 */

            /* NODE START: lineNumber: 66, offset: 58, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_59 */
            /* <c:set var="url" value="jdbc:mysql://localhost:3306/mytest2?user=root&amp;password=1234&amp;characterEncoding=utf8"/> */
            pageContext.setAttribute("url", "jdbc:mysql://localhost:3306/mytest2?user=root&password=1234&characterEncoding=utf8");
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 66, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_59 */

            /* NODE START: lineNumber: 67, offset: 60, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_61 */
            /* <c:set var="driverClass" value="com.mysql.jdbc.Driver"/> */
            pageContext.setAttribute("driverClass", "com.mysql.jdbc.Driver");
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 67, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_61 */

            /* NODE START: lineNumber: 68, offset: 62, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_63 */
            /* <c:set var="userName" value=""/> */
            pageContext.setAttribute("userName", ExpressionUtil.evaluate(expressionContext, ""));
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 68, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_63 */

            /* NODE START: lineNumber: 69, offset: 64, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_65 */
            /* <c:set var="password" value=""/> */
            pageContext.setAttribute("password", ExpressionUtil.evaluate(expressionContext, ""));
            /* jsp.jstl.core.SetTag END */
            /* NODE END: lineNumber: 69, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_65 */

        } /* jsp.jstl.core.IfTag END */
        /* NODE END: lineNumber: 64, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_56 */

        /* TEXT: lineNumber: 70 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 72, offset: 68, length: 10, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_69 */
        /* <sql:connect var="connection" url="${createDatabaseUrl}" driverClass="com.mysql.jdbc.Driver" userName="${userName}" password="${password}">...</sql:connect> */
        com.skin.ayada.jstl.sql.ConnectTag _jsp_ConnectTag_69 = new com.skin.ayada.jstl.sql.ConnectTag();
        try{
            _jsp_ConnectTag_69.setParent((Tag)null);
            _jsp_ConnectTag_69.setPageContext(pageContext);
            _jsp_ConnectTag_69.setVar("connection");
            _jsp_ConnectTag_69.setUrl(ExpressionUtil.getString(expressionContext, "${createDatabaseUrl}"));
            _jsp_ConnectTag_69.setDriverClass("com.mysql.jdbc.Driver");
            _jsp_ConnectTag_69.setUserName(ExpressionUtil.getString(expressionContext, "${userName}"));
            _jsp_ConnectTag_69.setPassword(ExpressionUtil.getString(expressionContext, "${password}"));
            int _jsp_start_flag_69 = _jsp_ConnectTag_69.doStartTag();

            if(_jsp_start_flag_69 == Tag.SKIP_PAGE){
                return;
            }
            if(_jsp_start_flag_69 != Tag.SKIP_BODY){
                int _jsp_flag_69 = 0;

                do{
                    /* TEXT: lineNumber: 72 */
                    out.write("\r\n    ");

                    /* NODE START: lineNumber: 73, offset: 70, length: 3, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_71 */
                    /* <sql:execute out="${pageContext}">...</sql:execute> */
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_71 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_71.setParent(_jsp_ConnectTag_69);
                    _jsp_SqlTag_71.setPageContext(pageContext);
                    _jsp_SqlTag_71.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext}"));
                    int _jsp_start_flag_71 = _jsp_SqlTag_71.doStartTag();

                    if(_jsp_start_flag_71 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_71 != Tag.SKIP_BODY){
                        int _jsp_flag_71 = 0;
                        if(_jsp_start_flag_71 == BodyTag.EVAL_BODY_BUFFERED){
                            BodyContent _jsp_body_content_71 = (BodyContent)(pageContext.pushBody());
                            _jsp_SqlTag_71.setBodyContent(_jsp_body_content_71);
                            _jsp_SqlTag_71.doInitBody();
                            out = _jsp_body_content_71;
                        }

                        do{
                            /* TEXT: lineNumber: 73 */
                            out.write("\r\n        drop database if exists mytest2;\r\n        create database mytest2 character set utf8;\r\n    ");
                            _jsp_flag_71 = _jsp_SqlTag_71.doAfterBody();
                        }
                        while(_jsp_flag_71 == IterationTag.EVAL_BODY_AGAIN);
                        if(_jsp_start_flag_71 == BodyTag.EVAL_BODY_BUFFERED){
                            out = pageContext.popBody();
                        }
                    }
                    _jsp_SqlTag_71.doEndTag();
                    _jsp_SqlTag_71.release();
                    /* NODE END: lineNumber: 73, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_71 */

                    /* TEXT: lineNumber: 76 */
                    out.write("\r\n    ");

                    /* NODE START: lineNumber: 77, offset: 74, length: 2, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_75 */
                    /* <c:exit/> */
                    if(com.skin.ayada.jstl.core.ExitTag.getTrue()){
                        return;
                    }
                    /* jsp.jstl.core.ExitTag END */
                    /* NODE END: lineNumber: 77, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_75 */

                    /* TEXT: lineNumber: 77 */
                    out.write("\r\n");
                    _jsp_flag_69 = _jsp_ConnectTag_69.doAfterBody();
                }
                while(_jsp_flag_69 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_ConnectTag_69.doEndTag();
            _jsp_ConnectTag_69.release();
        }
        catch(Throwable throwable){
            _jsp_ConnectTag_69.doCatch(throwable);
        }
        finally{
            _jsp_ConnectTag_69.doFinally();
        }
        /* NODE END: lineNumber: 72, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_69 */

        /* TEXT: lineNumber: 78 */
        out.write("\r\n");

        /* NODE START: lineNumber: 79, offset: 79, length: 56, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_80 */
        /* <sql:connect var="connection" url="${url}" driverClass="com.mysql.jdbc.Driver" userName="${userName}" password="${password}">...</sql:connect> */
        com.skin.ayada.jstl.sql.ConnectTag _jsp_ConnectTag_80 = new com.skin.ayada.jstl.sql.ConnectTag();
        try{
            _jsp_ConnectTag_80.setParent((Tag)null);
            _jsp_ConnectTag_80.setPageContext(pageContext);
            _jsp_ConnectTag_80.setVar("connection");
            _jsp_ConnectTag_80.setUrl(ExpressionUtil.getString(expressionContext, "${url}"));
            _jsp_ConnectTag_80.setDriverClass("com.mysql.jdbc.Driver");
            _jsp_ConnectTag_80.setUserName(ExpressionUtil.getString(expressionContext, "${userName}"));
            _jsp_ConnectTag_80.setPassword(ExpressionUtil.getString(expressionContext, "${password}"));
            int _jsp_start_flag_80 = _jsp_ConnectTag_80.doStartTag();

            if(_jsp_start_flag_80 == Tag.SKIP_PAGE){
                return;
            }
            if(_jsp_start_flag_80 != Tag.SKIP_BODY){
                int _jsp_flag_80 = 0;

                do{
                    /* TEXT: lineNumber: 79 */
                    out.write("\r\n    ");

                    /* NODE START: lineNumber: 80, offset: 81, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_82 */
                    /* <sql:execute home="${template.home}/database" file="create.sql" encoding="UTF-8" out="${pageContext}"/> */
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_82 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_82.setParent(_jsp_ConnectTag_80);
                    _jsp_SqlTag_82.setPageContext(pageContext);
                    _jsp_SqlTag_82.setHome(ExpressionUtil.getString(expressionContext, "${template.home}/database"));
                    _jsp_SqlTag_82.setFile("create.sql");
                    _jsp_SqlTag_82.setEncoding("UTF-8");
                    _jsp_SqlTag_82.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext}"));
                    int _jsp_start_flag_82 = _jsp_SqlTag_82.doStartTag();

                    if(_jsp_start_flag_82 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_82 != Tag.SKIP_BODY){
                        _jsp_SqlTag_82.doAfterBody();
                    }
                    _jsp_SqlTag_82.doEndTag();
                    _jsp_SqlTag_82.release();
                    /* NODE END: lineNumber: 80, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_82 */

                    /* TEXT: lineNumber: 80 */
                    out.write("\r\n    ");

                    /* NODE START: lineNumber: 81, offset: 84, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_85 */
                    /* <sql:execute sql="delete from my_test1;" out="${pageContext}"/> */
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_85 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_85.setParent(_jsp_ConnectTag_80);
                    _jsp_SqlTag_85.setPageContext(pageContext);
                    _jsp_SqlTag_85.setSql("delete from my_test1;");
                    _jsp_SqlTag_85.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext}"));
                    int _jsp_start_flag_85 = _jsp_SqlTag_85.doStartTag();

                    if(_jsp_start_flag_85 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_85 != Tag.SKIP_BODY){
                        _jsp_SqlTag_85.doAfterBody();
                    }
                    _jsp_SqlTag_85.doEndTag();
                    _jsp_SqlTag_85.release();
                    /* NODE END: lineNumber: 81, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_85 */

                    /* TEXT: lineNumber: 81 */
                    out.write("\r\n    ");

                    /* NODE START: lineNumber: 82, offset: 87, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_88 */
                    /* <sql:execute sql="delete from my_test2;" out="${pageContext}"/> */
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_88 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_88.setParent(_jsp_ConnectTag_80);
                    _jsp_SqlTag_88.setPageContext(pageContext);
                    _jsp_SqlTag_88.setSql("delete from my_test2;");
                    _jsp_SqlTag_88.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext}"));
                    int _jsp_start_flag_88 = _jsp_SqlTag_88.doStartTag();

                    if(_jsp_start_flag_88 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_88 != Tag.SKIP_BODY){
                        _jsp_SqlTag_88.doAfterBody();
                    }
                    _jsp_SqlTag_88.doEndTag();
                    _jsp_SqlTag_88.release();
                    /* NODE END: lineNumber: 82, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_88 */

                    /* TEXT: lineNumber: 82 */
                    out.write("\r\n    ");

                    /* NODE START: lineNumber: 83, offset: 90, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_91 */
                    /* <sql:execute sql="insert into my_test2(my_id, my_code, my_name) values (1, &#39;1&#39;, &#39;1&#39;);"/> */
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_91 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_91.setParent(_jsp_ConnectTag_80);
                    _jsp_SqlTag_91.setPageContext(pageContext);
                    _jsp_SqlTag_91.setSql("insert into my_test2(my_id, my_code, my_name) values (1, \'1\', \'1\');");
                    int _jsp_start_flag_91 = _jsp_SqlTag_91.doStartTag();

                    if(_jsp_start_flag_91 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_91 != Tag.SKIP_BODY){
                        _jsp_SqlTag_91.doAfterBody();
                    }
                    _jsp_SqlTag_91.doEndTag();
                    _jsp_SqlTag_91.release();
                    /* NODE END: lineNumber: 83, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_91 */

                    /* TEXT: lineNumber: 83 */
                    out.write("\r\n\r\n    ");

                    /* NODE START: lineNumber: 85, offset: 93, length: 23, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_94 */
                    /* <sql:execute out="${pageContext}">...</sql:execute> */
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_94 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_94.setParent(_jsp_ConnectTag_80);
                    _jsp_SqlTag_94.setPageContext(pageContext);
                    _jsp_SqlTag_94.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext}"));
                    int _jsp_start_flag_94 = _jsp_SqlTag_94.doStartTag();

                    if(_jsp_start_flag_94 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_94 != Tag.SKIP_BODY){
                        int _jsp_flag_94 = 0;
                        if(_jsp_start_flag_94 == BodyTag.EVAL_BODY_BUFFERED){
                            BodyContent _jsp_body_content_94 = (BodyContent)(pageContext.pushBody());
                            _jsp_SqlTag_94.setBodyContent(_jsp_body_content_94);
                            _jsp_SqlTag_94.doInitBody();
                            out = _jsp_body_content_94;
                        }

                        do{
                            /* TEXT: lineNumber: 85 */
                            out.write("\r\n        ");

                            /* NODE START: lineNumber: 86, offset: 95, length: 9, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_96 */
                            /* <c:forEach items="1, 2, 3, 4, 5" var="id">...</c:forEach> */
                            Object _jsp_old_var_96 = pageContext.getAttribute("id");
                            com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_96 = new com.skin.ayada.jstl.core.ForEachTag();
                            _jsp_ForEachTag_96.setParent(_jsp_SqlTag_94);
                            _jsp_ForEachTag_96.setPageContext(pageContext);
                            _jsp_ForEachTag_96.setVar("id");
                            _jsp_ForEachTag_96.setItems("1, 2, 3, 4, 5");
                            _jsp_ForEachTag_96.init();
                            while(_jsp_ForEachTag_96.hasNext()){
                                pageContext.setAttribute("id", _jsp_ForEachTag_96.next());
                                /* TEXT: lineNumber: 86 */
                                out.write("\r\n            insert into my_test1(my_id, my_code, my_name) values (");
                                /* VARIABLE: lineNumber: 87 */
                                out.print(pageContext.getAttribute("id"), false);
                                /* TEXT: lineNumber: 87 */
                                out.write(", \'");
                                /* VARIABLE: lineNumber: 87 */
                                out.print(pageContext.getAttribute("id"), false);
                                /* TEXT: lineNumber: 87 */
                                out.write("\', \'");
                                /* VARIABLE: lineNumber: 87 */
                                out.print(pageContext.getAttribute("id"), false);
                                /* TEXT: lineNumber: 87 */
                                out.write("\');\r\n        ");
                            }
                            _jsp_ForEachTag_96.release();
                            pageContext.setAttribute("id", _jsp_old_var_96);
                            /* jsp.jstl.core.ForEachTag END */
                            /* NODE END: lineNumber: 86, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_96 */

                            /* TEXT: lineNumber: 88 */
                            out.write("\r\n        ");

                            /* NODE START: lineNumber: 89, offset: 105, length: 9, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_106 */
                            /* <c:forEach items="1, 2, 3, 4, 5" var="id">...</c:forEach> */
                            Object _jsp_old_var_106 = pageContext.getAttribute("id");
                            com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_106 = new com.skin.ayada.jstl.core.ForEachTag();
                            _jsp_ForEachTag_106.setParent(_jsp_SqlTag_94);
                            _jsp_ForEachTag_106.setPageContext(pageContext);
                            _jsp_ForEachTag_106.setVar("id");
                            _jsp_ForEachTag_106.setItems("1, 2, 3, 4, 5");
                            _jsp_ForEachTag_106.init();
                            while(_jsp_ForEachTag_106.hasNext()){
                                pageContext.setAttribute("id", _jsp_ForEachTag_106.next());
                                /* TEXT: lineNumber: 89 */
                                out.write("\r\n            insert into my_test2(my_id, my_code, my_name) values (");
                                /* VARIABLE: lineNumber: 90 */
                                out.print(pageContext.getAttribute("id"), false);
                                /* TEXT: lineNumber: 90 */
                                out.write(", \'");
                                /* VARIABLE: lineNumber: 90 */
                                out.print(pageContext.getAttribute("id"), false);
                                /* TEXT: lineNumber: 90 */
                                out.write("\', \'");
                                /* VARIABLE: lineNumber: 90 */
                                out.print(pageContext.getAttribute("id"), false);
                                /* TEXT: lineNumber: 90 */
                                out.write("\');\r\n        ");
                            }
                            _jsp_ForEachTag_106.release();
                            pageContext.setAttribute("id", _jsp_old_var_106);
                            /* jsp.jstl.core.ForEachTag END */
                            /* NODE END: lineNumber: 89, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_106 */

                            /* TEXT: lineNumber: 91 */
                            out.write("\r\n    ");
                            _jsp_flag_94 = _jsp_SqlTag_94.doAfterBody();
                        }
                        while(_jsp_flag_94 == IterationTag.EVAL_BODY_AGAIN);
                        if(_jsp_start_flag_94 == BodyTag.EVAL_BODY_BUFFERED){
                            out = pageContext.popBody();
                        }
                    }
                    _jsp_SqlTag_94.doEndTag();
                    _jsp_SqlTag_94.release();
                    /* NODE END: lineNumber: 85, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_94 */

                    /* TEXT: lineNumber: 92 */
                    out.write("\r\n\r\n    ");

                    /* NODE START: lineNumber: 94, offset: 117, length: 3, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_118 */
                    /* <sql:execute out="${pageContext.getOut()}">...</sql:execute> */
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_118 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_118.setParent(_jsp_ConnectTag_80);
                    _jsp_SqlTag_118.setPageContext(pageContext);
                    _jsp_SqlTag_118.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext.getOut()}"));
                    int _jsp_start_flag_118 = _jsp_SqlTag_118.doStartTag();

                    if(_jsp_start_flag_118 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_118 != Tag.SKIP_BODY){
                        int _jsp_flag_118 = 0;
                        if(_jsp_start_flag_118 == BodyTag.EVAL_BODY_BUFFERED){
                            BodyContent _jsp_body_content_118 = (BodyContent)(pageContext.pushBody());
                            _jsp_SqlTag_118.setBodyContent(_jsp_body_content_118);
                            _jsp_SqlTag_118.doInitBody();
                            out = _jsp_body_content_118;
                        }

                        do{
                            /* TEXT: lineNumber: 94 */
                            out.write("\r\n        delete from my_test2;\r\n        insert into my_test2(my_id, my_code, my_name) values (1001, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1002, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1003, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1004, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1005, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1006, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1007, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1008, \'1001\', \'1001\');\r\n    ");
                            _jsp_flag_118 = _jsp_SqlTag_118.doAfterBody();
                        }
                        while(_jsp_flag_118 == IterationTag.EVAL_BODY_AGAIN);
                        if(_jsp_start_flag_118 == BodyTag.EVAL_BODY_BUFFERED){
                            out = pageContext.popBody();
                        }
                    }
                    _jsp_SqlTag_118.doEndTag();
                    _jsp_SqlTag_118.release();
                    /* NODE END: lineNumber: 94, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_118 */

                    /* TEXT: lineNumber: 104 */
                    out.write("\r\n\r\n    ");

                    /* NODE START: lineNumber: 106, offset: 121, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_122 */
                    /* <sql:execute connection="${connection}" sql="insert into my_test2(my_id, my_code, my_name) values (1009, &#39;1001&#39;, &#39;1001&#39;);"/> */
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_122 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_122.setParent(_jsp_ConnectTag_80);
                    _jsp_SqlTag_122.setPageContext(pageContext);
                    _jsp_SqlTag_122.setConnection((java.sql.Connection)(ExpressionUtil.evaluate(expressionContext, "${connection}", java.sql.Connection.class)));
                    _jsp_SqlTag_122.setSql("insert into my_test2(my_id, my_code, my_name) values (1009, \'1001\', \'1001\');");
                    int _jsp_start_flag_122 = _jsp_SqlTag_122.doStartTag();

                    if(_jsp_start_flag_122 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_122 != Tag.SKIP_BODY){
                        _jsp_SqlTag_122.doAfterBody();
                    }
                    _jsp_SqlTag_122.doEndTag();
                    _jsp_SqlTag_122.release();
                    /* NODE END: lineNumber: 106, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_122 */

                    /* TEXT: lineNumber: 106 */
                    out.write("\r\n    <table>\r\n        <tr>\r\n            <td>id</td>\r\n            <td>userName</td>\r\n            <td>nickName</td>\r\n        </tr>\r\n        ");

                    /* NODE START: lineNumber: 113, offset: 124, length: 9, tagClassName: com.skin.ayada.jstl.sql.QueryTag, tagInstanceName: _jsp_QueryTag_125 */
                    /* <sql:query var="resultSet" sql="select * from my_test2 where my_id &gt; 1001" offset="2" length="3">...</sql:query> */
                    com.skin.ayada.jstl.sql.QueryTag _jsp_QueryTag_125 = new com.skin.ayada.jstl.sql.QueryTag();
                    try{
                        _jsp_QueryTag_125.setParent(_jsp_ConnectTag_80);
                        _jsp_QueryTag_125.setPageContext(pageContext);
                        _jsp_QueryTag_125.setVar("resultSet");
                        _jsp_QueryTag_125.setSql("select * from my_test2 where my_id > 1001");
                        _jsp_QueryTag_125.setOffset(2);
                        _jsp_QueryTag_125.setLength(3);
                        int _jsp_start_flag_125 = _jsp_QueryTag_125.doStartTag();

                        if(_jsp_start_flag_125 == Tag.SKIP_PAGE){
                            return;
                        }
                        if(_jsp_start_flag_125 != Tag.SKIP_BODY){
                            int _jsp_flag_125 = 0;

                            do{
                                /* TEXT: lineNumber: 113 */
                                out.write("\r\n        <tr>\r\n            <td>");
                                /* EXPRESSION: lineNumber: 115 */
                                out.write(expressionContext.getString("resultSet.getLong(\"my_id\")"));
                                /* TEXT: lineNumber: 115 */
                                out.write("</td>\r\n            <td>");
                                /* EXPRESSION: lineNumber: 116 */
                                out.write(expressionContext.getString("resultSet.getString(\"my_code\")"));
                                /* TEXT: lineNumber: 116 */
                                out.write("</td>\r\n            <td>");
                                /* EXPRESSION: lineNumber: 117 */
                                out.write(expressionContext.getString("resultSet.getString(\"my_name\")"));
                                /* TEXT: lineNumber: 117 */
                                out.write("</td>\r\n        </tr>\r\n        ");
                                _jsp_flag_125 = _jsp_QueryTag_125.doAfterBody();
                            }
                            while(_jsp_flag_125 == IterationTag.EVAL_BODY_AGAIN);
                        }
                        _jsp_QueryTag_125.doEndTag();
                        _jsp_QueryTag_125.release();
                    }
                    catch(Throwable throwable){
                        _jsp_QueryTag_125.doCatch(throwable);
                    }
                    finally{
                        _jsp_QueryTag_125.doFinally();
                    }
                    /* NODE END: lineNumber: 113, tagClassName: com.skin.ayada.jstl.sql.QueryTag, tagInstanceName: _jsp_QueryTag_125 */

                    /* TEXT: lineNumber: 119 */
                    out.write("\r\n    </table>\r\n");
                    _jsp_flag_80 = _jsp_ConnectTag_80.doAfterBody();
                }
                while(_jsp_flag_80 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_ConnectTag_80.doEndTag();
            _jsp_ConnectTag_80.release();
        }
        catch(Throwable throwable){
            _jsp_ConnectTag_80.doCatch(throwable);
        }
        finally{
            _jsp_ConnectTag_80.doFinally();
        }
        /* NODE END: lineNumber: 79, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_80 */

        out.flush();
        jspWriter.flush();
    }
}
