/*
 * $RCSfile: ExtTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2013-11-29 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * LastModified: 2013-11-29 17:15:34 859
 * JSP generated by JspCompiler-0.1.1 (built 2013-11-29 17:16:44 390)
 *
 */
package _jsp.webapp;

import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;

/**
 * <p>Title: ExtTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
public class ExtTestTemplate extends JspTemplate
{
    /**
     * @param pageContext
     * @throws Exception
     */
    @Override
    public void _execute(final PageContext pageContext) throws Exception
    {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /* NODE START: lineNumber: 1, offset: 0, length: 8, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_1 */
        /* <c:bean name="testTag1" className="com.skin.ayada.jstl.core.TestTag">...</c:bean> */
        com.skin.ayada.jstl.core.BeanTag _jsp_BeanTag_1 = new com.skin.ayada.jstl.core.BeanTag();
        _jsp_BeanTag_1.setParent((Tag)null);
        _jsp_BeanTag_1.setPageContext(pageContext);
        _jsp_BeanTag_1.setName("testTag1");
        _jsp_BeanTag_1.setClassName("com.skin.ayada.jstl.core.TestTag");
        int _jsp_start_flag_1 = _jsp_BeanTag_1.doStartTag();

        if(_jsp_start_flag_1 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_1 != Tag.SKIP_BODY){
            int _jsp_flag_1 = 0;

            do{
                /* NODE START: lineNumber: 2, offset: 1, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_2 */
                /* <c:constructor type="char" value="c"/> */
                com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_1, "char", "c");
                /* jsp.jstl.core.ConstructorTag END */
                /* NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_2 */

                /* NODE START: lineNumber: 3, offset: 3, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_4 */
                /* <c:constructor type="byte" value="2"/> */
                com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_1, "byte", 2);
                /* jsp.jstl.core.ConstructorTag END */
                /* NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_4 */

                /* NODE START: lineNumber: 4, offset: 5, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_6 */
                /* <c:property name="pageContext" value="${pageContext}"/> */
                _jsp_BeanTag_1.setProperty("pageContext", pageContext.getAttribute("pageContext"));
                /* jsp.jstl.core.PropertyTag END */
                /* NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_6 */

                _jsp_flag_1 = _jsp_BeanTag_1.doAfterBody();
            }
            while(_jsp_flag_1 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_BeanTag_1.doEndTag();
        _jsp_BeanTag_1.release();
        /* NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_1 */

        /* TEXT: lineNumber: 5 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 7, offset: 9, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_10 */
        /* <c:set var="a1" value="1"/> */
        pageContext.setAttribute("a1", 1);
        /* jsp.jstl.core.SetTag END */
        /* NODE END: lineNumber: 7, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_10 */

        /* TEXT: lineNumber: 7 */
        out.write("<p>a1: ");
        /* VARIABLE: lineNumber: 7 */
        out.print(pageContext.getAttribute("a1"), false);
        /* TEXT: lineNumber: 7 */
        out.write("</p>\r\n");

        /* NODE START: lineNumber: 8, offset: 14, length: 3, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_15 */
        /* <c:set var="a1">...</c:set> */
        out = pageContext.pushBody();
        /* TEXT: lineNumber: 8 */
        out.write("0 - Hello World!");
        pageContext.setAttribute("a1", ((BodyContent)out).getString().trim());
        out = pageContext.popBody();
        /* jsp.jstl.core.SetTag END */
        /* NODE END: lineNumber: 8, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_15 */

        /* TEXT: lineNumber: 8 */
        out.write("<p>a1: ");
        /* VARIABLE: lineNumber: 8 */
        out.print(pageContext.getAttribute("a1"), false);
        /* TEXT: lineNumber: 8 */
        out.write("</p>\r\n\r\n");

        /* NODE START: lineNumber: 10, offset: 20, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_21 */
        /* <c:set target="${testTag1}" property="myString" value="00 - Hello World !"/> */
        com.skin.ayada.util.ClassUtil.setProperty(pageContext.getAttribute("testTag1"), "myString", "00 - Hello World !");
        /* jsp.jstl.core.SetTag END */
        /* NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_21 */

        /* TEXT: lineNumber: 10 */
        out.write("\r\n");

        /* NODE START: lineNumber: 11, offset: 23, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_24 */
        /* <c:execute value="${testTag1.print()}"/> */
        pageContext.setAttribute((String)null, ExpressionUtil.evaluate(expressionContext, "${testTag1.print()}"));
        /* jsp.jstl.core.ExecuteTag END */
        /* NODE END: lineNumber: 11, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_24 */

        /* TEXT: lineNumber: 11 */
        out.write("\r\n");

        /* NODE START: lineNumber: 12, offset: 26, length: 3, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_27 */
        /* <c:set target="${testTag1}" property="myString">...</c:set> */
        out = pageContext.pushBody();
        /* TEXT: lineNumber: 12 */
        out.write("00 - Hello World !");
        com.skin.ayada.util.ClassUtil.setProperty(pageContext.getAttribute("testTag1"), "myString", ((BodyContent)out).getString().trim());
        out = pageContext.popBody();
        /* jsp.jstl.core.SetTag END */
        /* NODE END: lineNumber: 12, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_27 */

        /* TEXT: lineNumber: 12 */
        out.write("\r\n");

        /* NODE START: lineNumber: 13, offset: 30, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_31 */
        /* <c:execute value="${testTag1.print()}"/> */
        pageContext.setAttribute((String)null, ExpressionUtil.evaluate(expressionContext, "${testTag1.print()}"));
        /* jsp.jstl.core.ExecuteTag END */
        /* NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_31 */

        /* TEXT: lineNumber: 13 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 15, offset: 33, length: 13, tagClassName: com.skin.ayada.jstl.core.OutputTag, tagInstanceName: _jsp_OutputTag_34 */
        /* <c:output out="true" trim="false" file="webapp\extTest.log">...</c:output> */
        com.skin.ayada.jstl.core.OutputTag _jsp_OutputTag_34 = new com.skin.ayada.jstl.core.OutputTag();
        _jsp_OutputTag_34.setParent((Tag)null);
        _jsp_OutputTag_34.setPageContext(pageContext);
        _jsp_OutputTag_34.setOut(true);
        _jsp_OutputTag_34.setTrim(false);
        _jsp_OutputTag_34.setFile("webapp\\extTest.log");
        int _jsp_start_flag_34 = _jsp_OutputTag_34.doStartTag();

        if(_jsp_start_flag_34 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_34 != Tag.SKIP_BODY){
            int _jsp_flag_34 = 0;
            if(_jsp_start_flag_34 == BodyTag.EVAL_BODY_BUFFERED){
                BodyContent _jsp_body_content_34 = (BodyContent)(pageContext.pushBody());
                _jsp_OutputTag_34.setBodyContent(_jsp_body_content_34);
                _jsp_OutputTag_34.doInitBody();
                out = _jsp_body_content_34;
            }

            do{
                /* TEXT: lineNumber: 15 */
                out.write("\r\n    <p>1 - Hello World!</p>\r\n    ");

                /* NODE START: lineNumber: 17, offset: 35, length: 6, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_36 */
                /* <c:out>...</c:out> */
                out = pageContext.pushBody();
                /* TEXT: lineNumber: 17 */
                out.write("\r\n    <p>2 - Hello World!</p>\r\n    ");

                /* NODE START: lineNumber: 19, offset: 37, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_38 */
                /* <c:execute value="${pageContext.clear()}"/> */
                pageContext.setAttribute((String)null, ExpressionUtil.evaluate(expressionContext, "${pageContext.clear()}"));
                /* jsp.jstl.core.ExecuteTag END */
                /* NODE END: lineNumber: 19, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_38 */

                /* TEXT: lineNumber: 19 */
                out.write("\r\n    <p>3 - Hello World!</p>\r\n    ");
                pageContext.printBodyContent((BodyContent)out, false);
                out = pageContext.popBody();
                /* jsp.jstl.core.OutTag END */
                /* NODE END: lineNumber: 17, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_36 */

                /* TEXT: lineNumber: 21 */
                out.write("\r\n    ");

                /* NODE START: lineNumber: 22, offset: 42, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_43 */
                /* <c:set var="a1" value="a1"/> */
                pageContext.setAttribute("a1", "a1");
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 22, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_43 */

                /* TEXT: lineNumber: 22 */
                out.write("\r\n");
                _jsp_flag_34 = _jsp_OutputTag_34.doAfterBody();
            }
            while(_jsp_flag_34 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_34 == BodyTag.EVAL_BODY_BUFFERED){
                out = pageContext.popBody();
            }
        }
        _jsp_OutputTag_34.doEndTag();
        _jsp_OutputTag_34.release();
        /* NODE END: lineNumber: 15, tagClassName: com.skin.ayada.jstl.core.OutputTag, tagInstanceName: _jsp_OutputTag_34 */

        /* TEXT: lineNumber: 23 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 25, offset: 47, length: 96, tagClassName: com.skin.ayada.jstl.core.OutputTag, tagInstanceName: _jsp_OutputTag_48 */
        /* <c:xml out="true" trim="false" file="webapp\extTest.log">...</c:xml> */
        com.skin.ayada.jstl.core.OutputTag _jsp_OutputTag_48 = new com.skin.ayada.jstl.core.OutputTag();
        _jsp_OutputTag_48.setParent((Tag)null);
        _jsp_OutputTag_48.setPageContext(pageContext);
        _jsp_OutputTag_48.setOut(true);
        _jsp_OutputTag_48.setTrim(false);
        _jsp_OutputTag_48.setFile("webapp\\extTest.log");
        int _jsp_start_flag_48 = _jsp_OutputTag_48.doStartTag();

        if(_jsp_start_flag_48 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_48 != Tag.SKIP_BODY){
            int _jsp_flag_48 = 0;
            if(_jsp_start_flag_48 == BodyTag.EVAL_BODY_BUFFERED){
                BodyContent _jsp_body_content_48 = (BodyContent)(pageContext.pushBody());
                _jsp_OutputTag_48.setBodyContent(_jsp_body_content_48);
                _jsp_OutputTag_48.doInitBody();
                out = _jsp_body_content_48;
            }

            do{
                /* NODE START: lineNumber: 27, offset: 48, length: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_49 */
                /* <c:out>...</c:out> */
                out = pageContext.pushBody();
                /* TEXT: lineNumber: 27 */
                out.write("<p>3 - Hello World!</p>");
                pageContext.printBodyContent((BodyContent)out, false);
                out = pageContext.popBody();
                /* jsp.jstl.core.OutTag END */
                /* NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_49 */

                /* NODE START: lineNumber: 29, offset: 51, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_52 */
                /* <c:set var="a1" value="a1"/> */
                pageContext.setAttribute("a1", "a1");
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 29, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_52 */

                /* NODE START: lineNumber: 30, offset: 53, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_54 */
                /* <c:set var="a2" value="${a1}"/> */
                pageContext.setAttribute("a2", pageContext.getAttribute("a1"));
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 30, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_54 */

                /* NODE START: lineNumber: 31, offset: 55, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_56 */
                /* <c:set var="a3" value="${a2}"/> */
                pageContext.setAttribute("a3", pageContext.getAttribute("a2"));
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 31, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_56 */

                /* NODE START: lineNumber: 32, offset: 57, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_58 */
                /* <c:set var="a4" value="${a3}"/> */
                pageContext.setAttribute("a4", pageContext.getAttribute("a3"));
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 32, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_58 */

                /* NODE START: lineNumber: 34, offset: 59, length: 8, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_60 */
                /* <c:bean name="testTag1" className="com.skin.ayada.jstl.core.TestTag">...</c:bean> */
                com.skin.ayada.jstl.core.BeanTag _jsp_BeanTag_60 = new com.skin.ayada.jstl.core.BeanTag();
                _jsp_BeanTag_60.setParent(_jsp_OutputTag_48);
                _jsp_BeanTag_60.setPageContext(pageContext);
                _jsp_BeanTag_60.setName("testTag1");
                _jsp_BeanTag_60.setClassName("com.skin.ayada.jstl.core.TestTag");
                int _jsp_start_flag_60 = _jsp_BeanTag_60.doStartTag();

                if(_jsp_start_flag_60 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_60 != Tag.SKIP_BODY){
                    int _jsp_flag_60 = 0;

                    do{
                        /* NODE START: lineNumber: 35, offset: 60, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_61 */
                        /* <c:constructor type="char" value="c"/> */
                        com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_60, "char", "c");
                        /* jsp.jstl.core.ConstructorTag END */
                        /* NODE END: lineNumber: 35, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_61 */

                        /* NODE START: lineNumber: 36, offset: 62, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_63 */
                        /* <c:constructor type="byte" value="2"/> */
                        com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_60, "byte", 2);
                        /* jsp.jstl.core.ConstructorTag END */
                        /* NODE END: lineNumber: 36, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_63 */

                        /* NODE START: lineNumber: 37, offset: 64, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_65 */
                        /* <c:property name="pageContext" value="${pageContext}"/> */
                        _jsp_BeanTag_60.setProperty("pageContext", pageContext.getAttribute("pageContext"));
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 37, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_65 */

                        _jsp_flag_60 = _jsp_BeanTag_60.doAfterBody();
                    }
                    while(_jsp_flag_60 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_BeanTag_60.doEndTag();
                _jsp_BeanTag_60.release();
                /* NODE END: lineNumber: 34, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_60 */

                /* NODE START: lineNumber: 40, offset: 67, length: 8, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_68 */
                /* <c:bean name="testTag2" className="com.skin.ayada.jstl.core.TestTag">...</c:bean> */
                com.skin.ayada.jstl.core.BeanTag _jsp_BeanTag_68 = new com.skin.ayada.jstl.core.BeanTag();
                _jsp_BeanTag_68.setParent(_jsp_OutputTag_48);
                _jsp_BeanTag_68.setPageContext(pageContext);
                _jsp_BeanTag_68.setName("testTag2");
                _jsp_BeanTag_68.setClassName("com.skin.ayada.jstl.core.TestTag");
                int _jsp_start_flag_68 = _jsp_BeanTag_68.doStartTag();

                if(_jsp_start_flag_68 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_68 != Tag.SKIP_BODY){
                    int _jsp_flag_68 = 0;

                    do{
                        /* NODE START: lineNumber: 41, offset: 68, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_69 */
                        /* <c:constructor type="long" value="1.2e3"/> */
                        com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_68, "long", 1200.0d);
                        /* jsp.jstl.core.ConstructorTag END */
                        /* NODE END: lineNumber: 41, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_69 */

                        /* NODE START: lineNumber: 42, offset: 70, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_71 */
                        /* <c:constructor type="java.lang.String" value="Hello"/> */
                        com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_68, "java.lang.String", "Hello");
                        /* jsp.jstl.core.ConstructorTag END */
                        /* NODE END: lineNumber: 42, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_71 */

                        /* NODE START: lineNumber: 43, offset: 72, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_73 */
                        /* <c:property name="pageContext" value="${pageContext}"/> */
                        _jsp_BeanTag_68.setProperty("pageContext", pageContext.getAttribute("pageContext"));
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 43, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_73 */

                        _jsp_flag_68 = _jsp_BeanTag_68.doAfterBody();
                    }
                    while(_jsp_flag_68 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_BeanTag_68.doEndTag();
                _jsp_BeanTag_68.release();
                /* NODE END: lineNumber: 40, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_68 */

                /* NODE START: lineNumber: 46, offset: 75, length: 20, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_76 */
                /* <c:bean name="testTag3" className="com.skin.ayada.jstl.core.TestTag">...</c:bean> */
                com.skin.ayada.jstl.core.BeanTag _jsp_BeanTag_76 = new com.skin.ayada.jstl.core.BeanTag();
                _jsp_BeanTag_76.setParent(_jsp_OutputTag_48);
                _jsp_BeanTag_76.setPageContext(pageContext);
                _jsp_BeanTag_76.setName("testTag3");
                _jsp_BeanTag_76.setClassName("com.skin.ayada.jstl.core.TestTag");
                int _jsp_start_flag_76 = _jsp_BeanTag_76.doStartTag();

                if(_jsp_start_flag_76 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_76 != Tag.SKIP_BODY){
                    int _jsp_flag_76 = 0;

                    do{
                        /* NODE START: lineNumber: 47, offset: 76, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_77 */
                        /* <c:property name="myBoolean" value="true"/> */
                        _jsp_BeanTag_76.setProperty("myBoolean", true);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 47, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_77 */

                        /* NODE START: lineNumber: 48, offset: 78, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_79 */
                        /* <c:property name="myChar" value="cc"/> */
                        _jsp_BeanTag_76.setProperty("myChar", "cc");
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 48, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_79 */

                        /* NODE START: lineNumber: 49, offset: 80, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_81 */
                        /* <c:property name="myByte" value="1"/> */
                        _jsp_BeanTag_76.setProperty("myByte", 1);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 49, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_81 */

                        /* NODE START: lineNumber: 50, offset: 82, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_83 */
                        /* <c:property name="myInt" value="-1.0"/> */
                        _jsp_BeanTag_76.setProperty("myInt", -1.0d);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 50, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_83 */

                        /* NODE START: lineNumber: 51, offset: 84, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_85 */
                        /* <c:property name="myFloat" value="1.2f"/> */
                        _jsp_BeanTag_76.setProperty("myFloat", 1.2f);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 51, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_85 */

                        /* NODE START: lineNumber: 52, offset: 86, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_87 */
                        /* <c:property name="myDouble" value="2.3d"/> */
                        _jsp_BeanTag_76.setProperty("myDouble", 2.3d);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 52, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_87 */

                        /* NODE START: lineNumber: 53, offset: 88, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_89 */
                        /* <c:property name="myLong" value="5L"/> */
                        _jsp_BeanTag_76.setProperty("myLong", 5L);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 53, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_89 */

                        /* NODE START: lineNumber: 54, offset: 90, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_91 */
                        /* <c:property name="myString" value="Hello"/> */
                        _jsp_BeanTag_76.setProperty("myString", "Hello");
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 54, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_91 */

                        /* NODE START: lineNumber: 55, offset: 92, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_93 */
                        /* <c:property name="pageContext" value="${pageContext}"/> */
                        _jsp_BeanTag_76.setProperty("pageContext", pageContext.getAttribute("pageContext"));
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 55, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_93 */

                        _jsp_flag_76 = _jsp_BeanTag_76.doAfterBody();
                    }
                    while(_jsp_flag_76 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_BeanTag_76.doEndTag();
                _jsp_BeanTag_76.release();
                /* NODE END: lineNumber: 46, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_76 */

                /* NODE START: lineNumber: 58, offset: 95, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_96 */
                /* <c:execute value="${testTag1.print()}"/> */
                pageContext.setAttribute((String)null, ExpressionUtil.evaluate(expressionContext, "${testTag1.print()}"));
                /* jsp.jstl.core.ExecuteTag END */
                /* NODE END: lineNumber: 58, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_96 */

                /* NODE START: lineNumber: 59, offset: 97, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_98 */
                /* <c:execute value="${testTag2.print()}"/> */
                pageContext.setAttribute((String)null, ExpressionUtil.evaluate(expressionContext, "${testTag2.print()}"));
                /* jsp.jstl.core.ExecuteTag END */
                /* NODE END: lineNumber: 59, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_98 */

                /* NODE START: lineNumber: 60, offset: 99, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_100 */
                /* <c:execute value="${testTag3.print()}"/> */
                pageContext.setAttribute((String)null, ExpressionUtil.evaluate(expressionContext, "${testTag3.print()}"));
                /* jsp.jstl.core.ExecuteTag END */
                /* NODE END: lineNumber: 60, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_100 */

                /* NODE START: lineNumber: 62, offset: 101, length: 10, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_102 */
                /* <c:list name="list">...</c:list> */
                com.skin.ayada.jstl.core.ListTag _jsp_ListTag_102 = new com.skin.ayada.jstl.core.ListTag();
                _jsp_ListTag_102.setParent(_jsp_OutputTag_48);
                _jsp_ListTag_102.setPageContext(pageContext);
                _jsp_ListTag_102.setName("list");
                int _jsp_start_flag_102 = _jsp_ListTag_102.doStartTag();

                if(_jsp_start_flag_102 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_102 != Tag.SKIP_BODY){
                    int _jsp_flag_102 = 0;

                    do{
                        /* NODE START: lineNumber: 63, offset: 102, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_103 */
                        /* <c:element value="1"/> */
                        _jsp_ListTag_102.setAttribute((String)null, 1);
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 63, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_103 */

                        /* NODE START: lineNumber: 64, offset: 104, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_105 */
                        /* <c:element value="2"/> */
                        _jsp_ListTag_102.setAttribute((String)null, 2);
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 64, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_105 */

                        /* NODE START: lineNumber: 65, offset: 106, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_107 */
                        /* <c:element value="3"/> */
                        _jsp_ListTag_102.setAttribute((String)null, 3);
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 65, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_107 */

                        /* NODE START: lineNumber: 66, offset: 108, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_109 */
                        /* <c:element value="4"/> */
                        _jsp_ListTag_102.setAttribute((String)null, 4);
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 66, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_109 */

                        _jsp_flag_102 = _jsp_ListTag_102.doAfterBody();
                    }
                    while(_jsp_flag_102 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_ListTag_102.doEndTag();
                _jsp_ListTag_102.release();
                /* NODE END: lineNumber: 62, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_102 */

                /* NODE START: lineNumber: 69, offset: 111, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_112 */
                /* <c:print value="${list}"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, pageContext.getAttribute("list"));
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 69, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_112 */

                /* NODE START: lineNumber: 71, offset: 113, length: 8, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_114 */
                /* <c:map name="map">...</c:map> */
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_114 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_114.setParent(_jsp_OutputTag_48);
                _jsp_MapTag_114.setPageContext(pageContext);
                _jsp_MapTag_114.setName("map");
                int _jsp_start_flag_114 = _jsp_MapTag_114.doStartTag();

                if(_jsp_start_flag_114 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_114 != Tag.SKIP_BODY){
                    int _jsp_flag_114 = 0;

                    do{
                        /* NODE START: lineNumber: 72, offset: 114, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_115 */
                        /* <c:entry name="1" value="test1"/> */
                        _jsp_MapTag_114.setAttribute("1", "test1");
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 72, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_115 */

                        /* NODE START: lineNumber: 73, offset: 116, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_117 */
                        /* <c:entry name="2" value="test2"/> */
                        _jsp_MapTag_114.setAttribute("2", "test2");
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 73, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_117 */

                        /* NODE START: lineNumber: 74, offset: 118, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_119 */
                        /* <c:entry name="3" value="test3"/> */
                        _jsp_MapTag_114.setAttribute("3", "test3");
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 74, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_119 */

                        _jsp_flag_114 = _jsp_MapTag_114.doAfterBody();
                    }
                    while(_jsp_flag_114 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_MapTag_114.doEndTag();
                _jsp_MapTag_114.release();
                /* NODE END: lineNumber: 71, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_114 */

                /* NODE START: lineNumber: 77, offset: 121, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_122 */
                /* <c:print value="${map}"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, pageContext.getAttribute("map"));
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 77, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_122 */

                /* NODE START: lineNumber: 78, offset: 123, length: 2, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_124 */
                /* <c:test/> */
                com.skin.ayada.jstl.core.TestTag _jsp_TestTag_124 = new com.skin.ayada.jstl.core.TestTag();
                _jsp_TestTag_124.setParent(_jsp_OutputTag_48);
                _jsp_TestTag_124.setPageContext(pageContext);
                int _jsp_start_flag_124 = _jsp_TestTag_124.doStartTag();

                if(_jsp_start_flag_124 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_124 != Tag.SKIP_BODY){
                    _jsp_TestTag_124.doAfterBody();
                }
                _jsp_TestTag_124.doEndTag();
                _jsp_TestTag_124.release();
                /* NODE END: lineNumber: 78, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_124 */

                /* NODE START: lineNumber: 80, offset: 125, length: 2, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_126 */
                /* <c:list name="userList"/> */
                com.skin.ayada.jstl.core.ListTag _jsp_ListTag_126 = new com.skin.ayada.jstl.core.ListTag();
                _jsp_ListTag_126.setParent(_jsp_OutputTag_48);
                _jsp_ListTag_126.setPageContext(pageContext);
                _jsp_ListTag_126.setName("userList");
                int _jsp_start_flag_126 = _jsp_ListTag_126.doStartTag();

                if(_jsp_start_flag_126 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_126 != Tag.SKIP_BODY){
                    _jsp_ListTag_126.doAfterBody();
                }
                _jsp_ListTag_126.doEndTag();
                _jsp_ListTag_126.release();
                /* NODE END: lineNumber: 80, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_126 */

                /* NODE START: lineNumber: 82, offset: 127, length: 13, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_128 */
                /* <c:forEach items="1, 2, 3, 4, 5" var="num">...</c:forEach> */
                Object _jsp_old_var_128 = pageContext.getAttribute("num");
                com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_128 = new com.skin.ayada.jstl.core.ForEachTag();
                _jsp_ForEachTag_128.setParent(_jsp_OutputTag_48);
                _jsp_ForEachTag_128.setPageContext(pageContext);
                _jsp_ForEachTag_128.setVar("num");
                _jsp_ForEachTag_128.setItems("1, 2, 3, 4, 5");
                _jsp_ForEachTag_128.init();
                while(_jsp_ForEachTag_128.hasNext()){
                    pageContext.setAttribute("num", _jsp_ForEachTag_128.next());
                    /* TEXT: lineNumber: 82 */
                    out.write("\r\n        ");

                    /* NODE START: lineNumber: 83, offset: 129, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_130 */
                    /* <c:map name="user">...</c:map> */
                    com.skin.ayada.jstl.core.MapTag _jsp_MapTag_130 = new com.skin.ayada.jstl.core.MapTag();
                    _jsp_MapTag_130.setParent((Tag)null);
                    _jsp_MapTag_130.setPageContext(pageContext);
                    _jsp_MapTag_130.setName("user");
                    int _jsp_start_flag_130 = _jsp_MapTag_130.doStartTag();

                    if(_jsp_start_flag_130 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_130 != Tag.SKIP_BODY){
                        int _jsp_flag_130 = 0;

                        do{
                            /* NODE START: lineNumber: 84, offset: 130, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_131 */
                            /* <c:entry name="userName" value="test_${num}"/> */
                            _jsp_MapTag_130.setAttribute("userName", ExpressionUtil.evaluate(expressionContext, "test_${num}"));
                            /* jsp.jstl.core.AttributeTag END */
                            /* NODE END: lineNumber: 84, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_131 */

                            /* NODE START: lineNumber: 85, offset: 132, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_133 */
                            /* <c:entry name="nickName" value="test_${num}"/> */
                            _jsp_MapTag_130.setAttribute("nickName", ExpressionUtil.evaluate(expressionContext, "test_${num}"));
                            /* jsp.jstl.core.AttributeTag END */
                            /* NODE END: lineNumber: 85, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_133 */

                            _jsp_flag_130 = _jsp_MapTag_130.doAfterBody();
                        }
                        while(_jsp_flag_130 == IterationTag.EVAL_BODY_AGAIN);
                    }
                    _jsp_MapTag_130.doEndTag();
                    _jsp_MapTag_130.release();
                    /* NODE END: lineNumber: 83, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_130 */

                    /* TEXT: lineNumber: 86 */
                    out.write("\r\n        ");

                    /* NODE START: lineNumber: 87, offset: 136, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_137 */
                    /* <c:execute value="${userList.add(user)}"/> */
                    pageContext.setAttribute((String)null, ExpressionUtil.evaluate(expressionContext, "${userList.add(user)}"));
                    /* jsp.jstl.core.ExecuteTag END */
                    /* NODE END: lineNumber: 87, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_137 */

                    /* TEXT: lineNumber: 87 */
                    out.write("\r\n    ");
                }
                _jsp_ForEachTag_128.release();
                pageContext.setAttribute("num", _jsp_old_var_128);
                /* jsp.jstl.core.ForEachTag END */
                /* NODE END: lineNumber: 82, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_128 */

                /* NODE START: lineNumber: 90, offset: 140, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_141 */
                /* <c:print value="${userList}"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, pageContext.getAttribute("userList"));
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 90, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_141 */

                _jsp_flag_48 = _jsp_OutputTag_48.doAfterBody();
            }
            while(_jsp_flag_48 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_48 == BodyTag.EVAL_BODY_BUFFERED){
                out = pageContext.popBody();
            }
        }
        _jsp_OutputTag_48.doEndTag();
        _jsp_OutputTag_48.release();
        /* NODE END: lineNumber: 25, tagClassName: com.skin.ayada.jstl.core.OutputTag, tagInstanceName: _jsp_OutputTag_48 */

        /* TEXT: lineNumber: 91 */
        out.write("\r\n");

        /* NODE START: lineNumber: 92, offset: 144, length: 2, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_145 */
        /* <c:exit/> */
        if(com.skin.ayada.jstl.core.ExitTag.getTrue()){
            return;
        }
        /* jsp.jstl.core.ExitTag END */
        /* NODE END: lineNumber: 92, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_145 */

        out.flush();
        jspWriter.flush();
    }
}
