/*
 * $RCSfile: AllTagTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2013-11-28 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: C:\WorkSpace\ayada\webapp
 * path: allTagTest.jsp
 * lastModified: 2013-11-28 15:44:00 000
 * options: -fastJstl false
 * JSP generated by JspCompiler-1.0.0.8 (built 2014-06-28 11:55:52 296)
 */
package _tpl._jsp;

import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;
import java.io.IOException; /* jsp:directive.import: lineNumber: 4 */

/**
 * <p>Title: AllTagTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
public class AllTagTestTemplate extends JspTemplate
{
    public static void main(String[] args)
    {
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getDefaultPageContext(writer);
        AllTagTestTemplate template = new AllTagTestTemplate();

        try{
            template._execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable)
        {
            throwable.printStackTrace();
        }
    }

    /* JSP_DECLARATION: lineNumber: 9 */
    public void hello1(JspWriter out) throws IOException{
        out.println("Hello, World !");
    }
    /* jsp:declaration END */

    /* JSP_DECLARATION: lineNumber: 14 */
    public void hello2(JspWriter out) throws IOException{
        out.println("Hello, World !");
    }
    /* jsp:declaration END */

    /* JSP_DECLARATION: lineNumber: 20 */
    public void hello3(JspWriter out) throws IOException{
        out.println("Hello, World !");
    }
    /* jsp:declaration END */

    /* JSP_DECLARATION: lineNumber: 26 */
    public void hello4(JspWriter out) throws IOException{
        out.println("Hello, World !");
    }
    /* jsp:declaration END */

    /* JSP_DECLARATION: lineNumber: 46 */
    public int myInt = 0;
    /* jsp:declaration END */

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    public void _execute(final PageContext pageContext) throws Throwable
    {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /* jsp:directive.page: lineNumber: 1 */
        /* <jsp:directive.page contentType="text/html;charset=UTF-8"/> */
        /* jsp:directive.page END */

        /* jsp:directive.taglib: lineNumber: 2 */
        /* <jsp:directive.taglib taglib="" prefix="c" uri="http://java.sun.com/jsp/jstl/core"/> */
        /* jsp:directive.taglib END */

        /* jsp:directive.taglib: lineNumber: 3 */
        /* <jsp:directive.taglib taglib="" prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"/> */
        /* jsp:directive.taglib END */

        /* jsp:directive.page: lineNumber: 4 */
        /* <jsp:directive.page import="java.io.IOException"/> */
        /* jsp:directive.page END */

        /* jsp:declaration: lineNumber: 9 */
        /* <jsp:declaration>...</jsp:declaration> */
        /* jsp:declaration END */

        /* jsp:declaration: lineNumber: 14 */
        /* <jsp:declaration>...</jsp:declaration> */
        /* jsp:declaration END */

        /* jsp:declaration: lineNumber: 20 */
        /* <jsp:declaration>...</jsp:declaration> */
        /* jsp:declaration END */

        /* jsp:declaration: lineNumber: 26 */
        /* <jsp:declaration>...</jsp:declaration> */
        /* jsp:declaration END */

        /* TEXT: lineNumber: 31 */
        out.write("<html>\r\n<head>\r\n<title>test</title>\r\n</head>\r\n<body jsp=\"");

        /* jsp:expression: lineNumber: 35 */
        out.print(1 + 2);
        /* jsp:expression END */

        /* TEXT: lineNumber: 35 */
        out.write("\" version=\"1.0\">\r\n============================================\r\n");

        /* jsp:scriptlet: lineNumber: 38 */
    out.println("Hello, World !");

        /* jsp:scriptlet END */

        /* TEXT: lineNumber: 41 */
        out.write("============================================\r\n");

        /* jsp:scriptlet: lineNumber: 42 */
    out.println("Hello, World !");

        /* jsp:scriptlet END */

        /* jsp:declaration: lineNumber: 46 */
        /* <jsp:declaration>...</jsp:declaration> */
        /* jsp:declaration END */

        /* jsp:scriptlet: lineNumber: 50 */
    // out.println("Hello, World1 !");

        /* jsp:scriptlet END */

        /* jsp:scriptlet: lineNumber: 54 */
    // out.println("Hello, World2 ! </test");
    // out.println("Hello, World2 ! </jsp:scriptlet2>");

        /* jsp:scriptlet END */

        /* jsp:scriptlet: lineNumber: 60 */
    int mytest = 0;

        /* jsp:scriptlet END */

        /* TEXT: lineNumber: 63 */
        out.write("<p>\r\n    myInt: ");

        /* jsp:expression: lineNumber: 64 */
        out.print( this.myInt );
        /* jsp:expression END */

        /* TEXT: lineNumber: 64 */
        out.write("\r\n</p>\r\n\r\n<p>\r\n    mytest: ");

        /* jsp:expression: lineNumber: 68 */
        out.print(mytest);
        /* jsp:expression END */

        /* TEXT: lineNumber: 68 */
        out.write("\r\n</p>\r\n");

        /* jsp:scriptlet: lineNumber: 70 */
    out.println("Hello, World4 !");

        /* jsp:scriptlet END */

        /* jsp:expression: lineNumber: 74 */
        out.print(("Hello" + " " + "World !"));
        /* jsp:expression END */

        /* TEXT: lineNumber: 74 */
        out.write("\r\n============================================\r\n");

        /* NODE START: lineNumber: 76, offset: 45, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_46 */
        /* <c:set var="myString" value="${StringUtil.replace(&#39;abc&#39;, &#39;b&#39;, &#39;\n&#39;)}"/> */
        com.skin.ayada.jstl.core.SetTag _jsp_SetTag_46 = new com.skin.ayada.jstl.core.SetTag();
        _jsp_SetTag_46.setParent((Tag)null);
        _jsp_SetTag_46.setPageContext(pageContext);
        _jsp_SetTag_46.setVar("myString");
        _jsp_SetTag_46.setValue(ExpressionUtil.evaluate(expressionContext, "${StringUtil.replace(\'abc\', \'b\', \'\\n\')}", null));
        int _jsp_start_flag_46 = _jsp_SetTag_46.doStartTag();

        if(_jsp_start_flag_46 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_46 != Tag.SKIP_BODY){
            _jsp_SetTag_46.doAfterBody();
        }
        _jsp_SetTag_46.doEndTag();
        _jsp_SetTag_46.release();
        /* NODE END: lineNumber: 76, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_46 */

        /* TEXT: lineNumber: 77 */
        out.write("<p>myString: [");

        /* NODE START: lineNumber: 77, offset: 48, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_49 */
        /* <c:out value="${myString}"/> */
        com.skin.ayada.jstl.core.OutTag _jsp_OutTag_49 = new com.skin.ayada.jstl.core.OutTag();
        _jsp_OutTag_49.setParent((Tag)null);
        _jsp_OutTag_49.setPageContext(pageContext);
        _jsp_OutTag_49.setValue(ExpressionUtil.evaluate(expressionContext, "${myString}", null));
        int _jsp_start_flag_49 = _jsp_OutTag_49.doStartTag();

        if(_jsp_start_flag_49 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_49 != Tag.SKIP_BODY){
            _jsp_OutTag_49.doAfterBody();
        }
        _jsp_OutTag_49.doEndTag();
        _jsp_OutTag_49.release();
        /* NODE END: lineNumber: 77, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_49 */

        /* TEXT: lineNumber: 77 */
        out.write("]</p>\r\n\r\n");

        /* NODE START: lineNumber: 79, offset: 51, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_52 */
        /* <c:set var="myString" value="&quot;a + 1&quot;"/> */
        com.skin.ayada.jstl.core.SetTag _jsp_SetTag_52 = new com.skin.ayada.jstl.core.SetTag();
        _jsp_SetTag_52.setParent((Tag)null);
        _jsp_SetTag_52.setPageContext(pageContext);
        _jsp_SetTag_52.setVar("myString");
        _jsp_SetTag_52.setValue("\"a + 1\"");
        int _jsp_start_flag_52 = _jsp_SetTag_52.doStartTag();

        if(_jsp_start_flag_52 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_52 != Tag.SKIP_BODY){
            _jsp_SetTag_52.doAfterBody();
        }
        _jsp_SetTag_52.doEndTag();
        _jsp_SetTag_52.release();
        /* NODE END: lineNumber: 79, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_52 */

        /* TEXT: lineNumber: 80 */
        out.write("<p>myString: [");

        /* NODE START: lineNumber: 80, offset: 54, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_55 */
        /* <c:out value="${myString}"/> */
        com.skin.ayada.jstl.core.OutTag _jsp_OutTag_55 = new com.skin.ayada.jstl.core.OutTag();
        _jsp_OutTag_55.setParent((Tag)null);
        _jsp_OutTag_55.setPageContext(pageContext);
        _jsp_OutTag_55.setValue(ExpressionUtil.evaluate(expressionContext, "${myString}", null));
        int _jsp_start_flag_55 = _jsp_OutTag_55.doStartTag();

        if(_jsp_start_flag_55 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_55 != Tag.SKIP_BODY){
            _jsp_OutTag_55.doAfterBody();
        }
        _jsp_OutTag_55.doEndTag();
        _jsp_OutTag_55.release();
        /* NODE END: lineNumber: 80, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_55 */

        /* TEXT: lineNumber: 80 */
        out.write("]</p>\r\n\r\n");

        /* NODE START: lineNumber: 82, offset: 57, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_58 */
        /* <c:set var="myVar" value="Hello, World!"/> */
        com.skin.ayada.jstl.core.SetTag _jsp_SetTag_58 = new com.skin.ayada.jstl.core.SetTag();
        _jsp_SetTag_58.setParent((Tag)null);
        _jsp_SetTag_58.setPageContext(pageContext);
        _jsp_SetTag_58.setVar("myVar");
        _jsp_SetTag_58.setValue("Hello, World!");
        int _jsp_start_flag_58 = _jsp_SetTag_58.doStartTag();

        if(_jsp_start_flag_58 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_58 != Tag.SKIP_BODY){
            _jsp_SetTag_58.doAfterBody();
        }
        _jsp_SetTag_58.doEndTag();
        _jsp_SetTag_58.release();
        /* NODE END: lineNumber: 82, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_58 */

        /* TEXT: lineNumber: 83 */
        out.write("<h1>############## ");
        /* VARIABLE: lineNumber: 83 */
        out.print(pageContext.getAttribute("myVar"), false);
        /* TEXT: lineNumber: 83 */
        out.write(" ##############</h1>\r\n\r\n");

        /* NODE START: lineNumber: 85, offset: 62, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_63 */
        /* <c:out value="c:out: Hello, World!"/> */
        com.skin.ayada.jstl.core.OutTag _jsp_OutTag_63 = new com.skin.ayada.jstl.core.OutTag();
        _jsp_OutTag_63.setParent((Tag)null);
        _jsp_OutTag_63.setPageContext(pageContext);
        _jsp_OutTag_63.setValue("c:out: Hello, World!");
        int _jsp_start_flag_63 = _jsp_OutTag_63.doStartTag();

        if(_jsp_start_flag_63 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_63 != Tag.SKIP_BODY){
            _jsp_OutTag_63.doAfterBody();
        }
        _jsp_OutTag_63.doEndTag();
        _jsp_OutTag_63.release();
        /* NODE END: lineNumber: 85, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_63 */

        /* TEXT: lineNumber: 85 */
        out.write("\r\n<div style=\"background-color: #c0c0c0;\"></div>\r\n");

        /* NODE START: lineNumber: 87, offset: 65, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_66 */
        /* <c:out value="&quot;&lt;div&gt;Hello World!&lt;/div&gt;&quot;" escapeXml="false"/> */
        com.skin.ayada.jstl.core.OutTag _jsp_OutTag_66 = new com.skin.ayada.jstl.core.OutTag();
        _jsp_OutTag_66.setParent((Tag)null);
        _jsp_OutTag_66.setPageContext(pageContext);
        _jsp_OutTag_66.setValue("\"<div>Hello World!</div>\"");
        _jsp_OutTag_66.setEscapeXml(false);
        int _jsp_start_flag_66 = _jsp_OutTag_66.doStartTag();

        if(_jsp_start_flag_66 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_66 != Tag.SKIP_BODY){
            _jsp_OutTag_66.doAfterBody();
        }
        _jsp_OutTag_66.doEndTag();
        _jsp_OutTag_66.release();
        /* NODE END: lineNumber: 87, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_66 */

        /* TEXT: lineNumber: 87 */
        out.write("\r\n");

        /* NODE START: lineNumber: 88, offset: 68, length: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_69 */
        /* <c:out escapeXml="true">...</c:out> */
        com.skin.ayada.jstl.core.OutTag _jsp_OutTag_69 = new com.skin.ayada.jstl.core.OutTag();
        _jsp_OutTag_69.setParent((Tag)null);
        _jsp_OutTag_69.setPageContext(pageContext);
        _jsp_OutTag_69.setEscapeXml(true);
        int _jsp_start_flag_69 = _jsp_OutTag_69.doStartTag();

        if(_jsp_start_flag_69 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_69 != Tag.SKIP_BODY){
            int _jsp_flag_69 = 0;
            if(_jsp_start_flag_69 == BodyTag.EVAL_BODY_BUFFERED){
                BodyContent _jsp_body_content_69 = (BodyContent)(pageContext.pushBody());
                _jsp_OutTag_69.setBodyContent(_jsp_body_content_69);
                _jsp_OutTag_69.doInitBody();
                out = _jsp_body_content_69;
            }

            do{
                /* TEXT: lineNumber: 88 */
                out.write("<h1>Hello World!</h1>");
                _jsp_flag_69 = _jsp_OutTag_69.doAfterBody();
            }
            while(_jsp_flag_69 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_69 == BodyTag.EVAL_BODY_BUFFERED){
                out = pageContext.popBody();
            }
        }
        _jsp_OutTag_69.doEndTag();
        _jsp_OutTag_69.release();
        /* NODE END: lineNumber: 88, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_69 */

        /* TEXT: lineNumber: 88 */
        out.write("\r\n");

        /* NODE START: lineNumber: 89, offset: 72, length: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_73 */
        /* <c:out value="&lt;div&gt;Hello World!&lt;/div&gt;" escapeXml="true">...</c:out> */
        com.skin.ayada.jstl.core.OutTag _jsp_OutTag_73 = new com.skin.ayada.jstl.core.OutTag();
        _jsp_OutTag_73.setParent((Tag)null);
        _jsp_OutTag_73.setPageContext(pageContext);
        _jsp_OutTag_73.setValue("<div>Hello World!</div>");
        _jsp_OutTag_73.setEscapeXml(true);
        int _jsp_start_flag_73 = _jsp_OutTag_73.doStartTag();

        if(_jsp_start_flag_73 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_73 != Tag.SKIP_BODY){
            int _jsp_flag_73 = 0;
            if(_jsp_start_flag_73 == BodyTag.EVAL_BODY_BUFFERED){
                BodyContent _jsp_body_content_73 = (BodyContent)(pageContext.pushBody());
                _jsp_OutTag_73.setBodyContent(_jsp_body_content_73);
                _jsp_OutTag_73.doInitBody();
                out = _jsp_body_content_73;
            }

            do{
                /* TEXT: lineNumber: 89 */
                out.write("<h1>Hello World!</h1>");
                _jsp_flag_73 = _jsp_OutTag_73.doAfterBody();
            }
            while(_jsp_flag_73 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_73 == BodyTag.EVAL_BODY_BUFFERED){
                out = pageContext.popBody();
            }
        }
        _jsp_OutTag_73.doEndTag();
        _jsp_OutTag_73.release();
        /* NODE END: lineNumber: 89, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_73 */

        /* TEXT: lineNumber: 89 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 91, offset: 76, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_77 */
        /* <c:set var="myName" value="xuesong.net"/> */
        com.skin.ayada.jstl.core.SetTag _jsp_SetTag_77 = new com.skin.ayada.jstl.core.SetTag();
        _jsp_SetTag_77.setParent((Tag)null);
        _jsp_SetTag_77.setPageContext(pageContext);
        _jsp_SetTag_77.setVar("myName");
        _jsp_SetTag_77.setValue("xuesong.net");
        int _jsp_start_flag_77 = _jsp_SetTag_77.doStartTag();

        if(_jsp_start_flag_77 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_77 != Tag.SKIP_BODY){
            _jsp_SetTag_77.doAfterBody();
        }
        _jsp_SetTag_77.doEndTag();
        _jsp_SetTag_77.release();
        /* NODE END: lineNumber: 91, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_77 */

        /* NODE START: lineNumber: 92, offset: 78, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_79 */
        /* <c:out value="Hello, ${myName}!" escapeXml="true"/> */
        com.skin.ayada.jstl.core.OutTag _jsp_OutTag_79 = new com.skin.ayada.jstl.core.OutTag();
        _jsp_OutTag_79.setParent((Tag)null);
        _jsp_OutTag_79.setPageContext(pageContext);
        _jsp_OutTag_79.setValue(ExpressionUtil.evaluate(expressionContext, "Hello, ${myName}!", null));
        _jsp_OutTag_79.setEscapeXml(true);
        int _jsp_start_flag_79 = _jsp_OutTag_79.doStartTag();

        if(_jsp_start_flag_79 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_79 != Tag.SKIP_BODY){
            _jsp_OutTag_79.doAfterBody();
        }
        _jsp_OutTag_79.doEndTag();
        _jsp_OutTag_79.release();
        /* NODE END: lineNumber: 92, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_79 */

        /* TEXT: lineNumber: 92 */
        out.write("\r\n");

        /* NODE START: lineNumber: 93, offset: 81, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_82 */
        /* <c:out value="Hello, ${myName}!" escapeXml="false"/> */
        com.skin.ayada.jstl.core.OutTag _jsp_OutTag_82 = new com.skin.ayada.jstl.core.OutTag();
        _jsp_OutTag_82.setParent((Tag)null);
        _jsp_OutTag_82.setPageContext(pageContext);
        _jsp_OutTag_82.setValue(ExpressionUtil.evaluate(expressionContext, "Hello, ${myName}!", null));
        _jsp_OutTag_82.setEscapeXml(false);
        int _jsp_start_flag_82 = _jsp_OutTag_82.doStartTag();

        if(_jsp_start_flag_82 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_82 != Tag.SKIP_BODY){
            _jsp_OutTag_82.doAfterBody();
        }
        _jsp_OutTag_82.doEndTag();
        _jsp_OutTag_82.release();
        /* NODE END: lineNumber: 93, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_82 */

        /* TEXT: lineNumber: 93 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 95, offset: 84, length: 3, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_85 */
        /* <c:if test="${1 == 1}">...</c:if> */
        com.skin.ayada.jstl.core.IfTag _jsp_IfTag_85 = new com.skin.ayada.jstl.core.IfTag();
        _jsp_IfTag_85.setParent((Tag)null);
        _jsp_IfTag_85.setPageContext(pageContext);
        _jsp_IfTag_85.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
        int _jsp_start_flag_85 = _jsp_IfTag_85.doStartTag();

        if(_jsp_start_flag_85 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_85 != Tag.SKIP_BODY){
            int _jsp_flag_85 = 0;

            do{
                /* TEXT: lineNumber: 95 */
                out.write("c:if test");
                _jsp_flag_85 = _jsp_IfTag_85.doAfterBody();
            }
            while(_jsp_flag_85 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_IfTag_85.doEndTag();
        _jsp_IfTag_85.release();
        /* NODE END: lineNumber: 95, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_85 */

        /* TEXT: lineNumber: 95 */
        out.write("\r\n\r\n<h1>c:forEach test1</h1>\r\n");

        /* NODE START: lineNumber: 98, offset: 88, length: 3, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_89 */
        /* <c:each items="1,2,3,4,5" var="mynum">...</c:each> */
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_89 = new com.skin.ayada.jstl.core.ForEachTag();
        try{
            _jsp_ForEachTag_89.setParent((Tag)null);
            _jsp_ForEachTag_89.setPageContext(pageContext);
            _jsp_ForEachTag_89.setItems("1,2,3,4,5");
            _jsp_ForEachTag_89.setVar("mynum");
            int _jsp_start_flag_89 = _jsp_ForEachTag_89.doStartTag();

            if(_jsp_start_flag_89 == Tag.SKIP_PAGE){
                return;
            }
            if(_jsp_start_flag_89 != Tag.SKIP_BODY){
                int _jsp_flag_89 = 0;

                do{
                    /* VARIABLE: lineNumber: 100 */
                    out.print(pageContext.getAttribute("mynum"), false);
                    _jsp_flag_89 = _jsp_ForEachTag_89.doAfterBody();
                }
                while(_jsp_flag_89 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_ForEachTag_89.doEndTag();
            _jsp_ForEachTag_89.release();
        }
        catch(Throwable throwable){
            _jsp_ForEachTag_89.doCatch(throwable);
        }
        finally{
            _jsp_ForEachTag_89.doFinally();
        }
        /* NODE END: lineNumber: 98, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_89 */

        /* TEXT: lineNumber: 100 */
        out.write("\r\n\r\n<h1>c:forEach test2</h1>\r\n");

        /* NODE START: lineNumber: 103, offset: 92, length: 20, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_93 */
        /* <c:forEach items="${userList}" var="user" varStatus="status">...</c:forEach> */
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_93 = new com.skin.ayada.jstl.core.ForEachTag();
        try{
            _jsp_ForEachTag_93.setParent((Tag)null);
            _jsp_ForEachTag_93.setPageContext(pageContext);
            _jsp_ForEachTag_93.setItems(ExpressionUtil.evaluate(expressionContext, "${userList}", null));
            _jsp_ForEachTag_93.setVar("user");
            _jsp_ForEachTag_93.setVarStatus("status");
            int _jsp_start_flag_93 = _jsp_ForEachTag_93.doStartTag();

            if(_jsp_start_flag_93 == Tag.SKIP_PAGE){
                return;
            }
            if(_jsp_start_flag_93 != Tag.SKIP_BODY){
                int _jsp_flag_93 = 0;

                do{
                    /* TEXT: lineNumber: 103 */
                    out.write("\r\n    <p>user: ");
                    /* EXPRESSION: lineNumber: 104 */
                    out.write(expressionContext.getString("user.userName"));
                    /* TEXT: lineNumber: 104 */
                    out.write("</p>\r\n    ");

                    /* NODE START: lineNumber: 105, offset: 96, length: 14, tagClassName: com.skin.ayada.jstl.core.ChooseTag, tagInstanceName: _jsp_ChooseTag_97 */
                    /* <c:choose>...</c:choose> */
                    com.skin.ayada.jstl.core.ChooseTag _jsp_ChooseTag_97 = new com.skin.ayada.jstl.core.ChooseTag();
                    _jsp_ChooseTag_97.setParent(_jsp_ForEachTag_93);
                    _jsp_ChooseTag_97.setPageContext(pageContext);
                    int _jsp_start_flag_97 = _jsp_ChooseTag_97.doStartTag();

                    if(_jsp_start_flag_97 == Tag.SKIP_PAGE){
                        return;
                    }
                    if(_jsp_start_flag_97 != Tag.SKIP_BODY){
                        int _jsp_flag_97 = 0;

                        do{
                            /* NODE START: lineNumber: 106, offset: 97, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_98 */
                            /* <c:when test="${user.userName == &#39;test1&#39;}">...</c:when> */
                            com.skin.ayada.jstl.core.WhenTag _jsp_WhenTag_98 = new com.skin.ayada.jstl.core.WhenTag();
                            _jsp_WhenTag_98.setParent(_jsp_ChooseTag_97);
                            _jsp_WhenTag_98.setPageContext(pageContext);
                            _jsp_WhenTag_98.setTest(ExpressionUtil.getBoolean(expressionContext, "${user.userName == \'test1\'}"));
                            int _jsp_start_flag_98 = _jsp_WhenTag_98.doStartTag();

                            if(_jsp_start_flag_98 == Tag.SKIP_PAGE){
                                return;
                            }
                            if(_jsp_start_flag_98 != Tag.SKIP_BODY){
                                int _jsp_flag_98 = 0;

                                do{
                                    /* TEXT: lineNumber: 106 */
                                    out.write("<p>test1, good man !</p>");
                                    _jsp_flag_98 = _jsp_WhenTag_98.doAfterBody();
                                }
                                while(_jsp_flag_98 == IterationTag.EVAL_BODY_AGAIN);
                            }
                            _jsp_WhenTag_98.doEndTag();
                            _jsp_WhenTag_98.release();
                            /* NODE END: lineNumber: 106, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_98 */

                            /* NODE START: lineNumber: 107, offset: 100, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_101 */
                            /* <c:when test="${user.userName == &#39;test2&#39;}">...</c:when> */
                            com.skin.ayada.jstl.core.WhenTag _jsp_WhenTag_101 = new com.skin.ayada.jstl.core.WhenTag();
                            _jsp_WhenTag_101.setParent(_jsp_ChooseTag_97);
                            _jsp_WhenTag_101.setPageContext(pageContext);
                            _jsp_WhenTag_101.setTest(ExpressionUtil.getBoolean(expressionContext, "${user.userName == \'test2\'}"));
                            int _jsp_start_flag_101 = _jsp_WhenTag_101.doStartTag();

                            if(_jsp_start_flag_101 == Tag.SKIP_PAGE){
                                return;
                            }
                            if(_jsp_start_flag_101 != Tag.SKIP_BODY){
                                int _jsp_flag_101 = 0;

                                do{
                                    /* TEXT: lineNumber: 107 */
                                    out.write("<p>test2, good man !</p>");
                                    _jsp_flag_101 = _jsp_WhenTag_101.doAfterBody();
                                }
                                while(_jsp_flag_101 == IterationTag.EVAL_BODY_AGAIN);
                            }
                            _jsp_WhenTag_101.doEndTag();
                            _jsp_WhenTag_101.release();
                            /* NODE END: lineNumber: 107, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_101 */

                            /* NODE START: lineNumber: 108, offset: 103, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_104 */
                            /* <c:when test="${user.userName == &#39;test3&#39;}">...</c:when> */
                            com.skin.ayada.jstl.core.WhenTag _jsp_WhenTag_104 = new com.skin.ayada.jstl.core.WhenTag();
                            _jsp_WhenTag_104.setParent(_jsp_ChooseTag_97);
                            _jsp_WhenTag_104.setPageContext(pageContext);
                            _jsp_WhenTag_104.setTest(ExpressionUtil.getBoolean(expressionContext, "${user.userName == \'test3\'}"));
                            int _jsp_start_flag_104 = _jsp_WhenTag_104.doStartTag();

                            if(_jsp_start_flag_104 == Tag.SKIP_PAGE){
                                return;
                            }
                            if(_jsp_start_flag_104 != Tag.SKIP_BODY){
                                int _jsp_flag_104 = 0;

                                do{
                                    /* TEXT: lineNumber: 108 */
                                    out.write("<p>test3, good man !</p>");
                                    _jsp_flag_104 = _jsp_WhenTag_104.doAfterBody();
                                }
                                while(_jsp_flag_104 == IterationTag.EVAL_BODY_AGAIN);
                            }
                            _jsp_WhenTag_104.doEndTag();
                            _jsp_WhenTag_104.release();
                            /* NODE END: lineNumber: 108, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_104 */

                            /* NODE START: lineNumber: 109, offset: 106, length: 3, tagClassName: com.skin.ayada.jstl.core.OtherwiseTag, tagInstanceName: _jsp_OtherwiseTag_107 */
                            /* <c:otherwise>...</c:otherwise> */
                            com.skin.ayada.jstl.core.OtherwiseTag _jsp_OtherwiseTag_107 = new com.skin.ayada.jstl.core.OtherwiseTag();
                            _jsp_OtherwiseTag_107.setParent(_jsp_ChooseTag_97);
                            _jsp_OtherwiseTag_107.setPageContext(pageContext);
                            int _jsp_start_flag_107 = _jsp_OtherwiseTag_107.doStartTag();

                            if(_jsp_start_flag_107 == Tag.SKIP_PAGE){
                                return;
                            }
                            if(_jsp_start_flag_107 != Tag.SKIP_BODY){
                                int _jsp_flag_107 = 0;

                                do{
                                    /* TEXT: lineNumber: 109 */
                                    out.write("<p>unknown user! Do you known \'bad egg\'? You! Are!</p>");
                                    _jsp_flag_107 = _jsp_OtherwiseTag_107.doAfterBody();
                                }
                                while(_jsp_flag_107 == IterationTag.EVAL_BODY_AGAIN);
                            }
                            _jsp_OtherwiseTag_107.doEndTag();
                            _jsp_OtherwiseTag_107.release();
                            /* NODE END: lineNumber: 109, tagClassName: com.skin.ayada.jstl.core.OtherwiseTag, tagInstanceName: _jsp_OtherwiseTag_107 */

                            _jsp_flag_97 = _jsp_ChooseTag_97.doAfterBody();
                        }
                        while(_jsp_flag_97 == IterationTag.EVAL_BODY_AGAIN);
                    }
                    _jsp_ChooseTag_97.doEndTag();
                    _jsp_ChooseTag_97.release();
                    /* NODE END: lineNumber: 105, tagClassName: com.skin.ayada.jstl.core.ChooseTag, tagInstanceName: _jsp_ChooseTag_97 */

                    /* TEXT: lineNumber: 110 */
                    out.write("\r\n");
                    _jsp_flag_93 = _jsp_ForEachTag_93.doAfterBody();
                }
                while(_jsp_flag_93 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_ForEachTag_93.doEndTag();
            _jsp_ForEachTag_93.release();
        }
        catch(Throwable throwable){
            _jsp_ForEachTag_93.doCatch(throwable);
        }
        finally{
            _jsp_ForEachTag_93.doFinally();
        }
        /* NODE END: lineNumber: 103, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_93 */

        /* TEXT: lineNumber: 111 */
        out.write("\r\n\r\n<h1>c:choose test1</h1>\r\n");

        /* NODE START: lineNumber: 114, offset: 113, length: 14, tagClassName: com.skin.ayada.jstl.core.ChooseTag, tagInstanceName: _jsp_ChooseTag_114 */
        /* <c:choose>...</c:choose> */
        com.skin.ayada.jstl.core.ChooseTag _jsp_ChooseTag_114 = new com.skin.ayada.jstl.core.ChooseTag();
        _jsp_ChooseTag_114.setParent((Tag)null);
        _jsp_ChooseTag_114.setPageContext(pageContext);
        int _jsp_start_flag_114 = _jsp_ChooseTag_114.doStartTag();

        if(_jsp_start_flag_114 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_114 != Tag.SKIP_BODY){
            int _jsp_flag_114 = 0;

            do{
                /* NODE START: lineNumber: 115, offset: 114, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_115 */
                /* <c:when test="${1 == 1}">...</c:when> */
                com.skin.ayada.jstl.core.WhenTag _jsp_WhenTag_115 = new com.skin.ayada.jstl.core.WhenTag();
                _jsp_WhenTag_115.setParent(_jsp_ChooseTag_114);
                _jsp_WhenTag_115.setPageContext(pageContext);
                _jsp_WhenTag_115.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                int _jsp_start_flag_115 = _jsp_WhenTag_115.doStartTag();

                if(_jsp_start_flag_115 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_115 != Tag.SKIP_BODY){
                    int _jsp_flag_115 = 0;

                    do{
                        /* TEXT: lineNumber: 115 */
                        out.write("c:when test=\"{1 == 1}\"");
                        _jsp_flag_115 = _jsp_WhenTag_115.doAfterBody();
                    }
                    while(_jsp_flag_115 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_WhenTag_115.doEndTag();
                _jsp_WhenTag_115.release();
                /* NODE END: lineNumber: 115, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_115 */

                /* NODE START: lineNumber: 116, offset: 117, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_118 */
                /* <c:when test="${2 == 2}">...</c:when> */
                com.skin.ayada.jstl.core.WhenTag _jsp_WhenTag_118 = new com.skin.ayada.jstl.core.WhenTag();
                _jsp_WhenTag_118.setParent(_jsp_ChooseTag_114);
                _jsp_WhenTag_118.setPageContext(pageContext);
                _jsp_WhenTag_118.setTest(ExpressionUtil.getBoolean(expressionContext, "${2 == 2}"));
                int _jsp_start_flag_118 = _jsp_WhenTag_118.doStartTag();

                if(_jsp_start_flag_118 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_118 != Tag.SKIP_BODY){
                    int _jsp_flag_118 = 0;

                    do{
                        /* TEXT: lineNumber: 116 */
                        out.write("c:when test=\"{2 == 2}\"");
                        _jsp_flag_118 = _jsp_WhenTag_118.doAfterBody();
                    }
                    while(_jsp_flag_118 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_WhenTag_118.doEndTag();
                _jsp_WhenTag_118.release();
                /* NODE END: lineNumber: 116, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_118 */

                /* NODE START: lineNumber: 117, offset: 120, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_121 */
                /* <c:when test="${3 == 3}">...</c:when> */
                com.skin.ayada.jstl.core.WhenTag _jsp_WhenTag_121 = new com.skin.ayada.jstl.core.WhenTag();
                _jsp_WhenTag_121.setParent(_jsp_ChooseTag_114);
                _jsp_WhenTag_121.setPageContext(pageContext);
                _jsp_WhenTag_121.setTest(ExpressionUtil.getBoolean(expressionContext, "${3 == 3}"));
                int _jsp_start_flag_121 = _jsp_WhenTag_121.doStartTag();

                if(_jsp_start_flag_121 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_121 != Tag.SKIP_BODY){
                    int _jsp_flag_121 = 0;

                    do{
                        /* TEXT: lineNumber: 117 */
                        out.write("c:when test=\"{3 == 3}\"");
                        _jsp_flag_121 = _jsp_WhenTag_121.doAfterBody();
                    }
                    while(_jsp_flag_121 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_WhenTag_121.doEndTag();
                _jsp_WhenTag_121.release();
                /* NODE END: lineNumber: 117, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_121 */

                /* NODE START: lineNumber: 118, offset: 123, length: 3, tagClassName: com.skin.ayada.jstl.core.OtherwiseTag, tagInstanceName: _jsp_OtherwiseTag_124 */
                /* <c:otherwise>...</c:otherwise> */
                com.skin.ayada.jstl.core.OtherwiseTag _jsp_OtherwiseTag_124 = new com.skin.ayada.jstl.core.OtherwiseTag();
                _jsp_OtherwiseTag_124.setParent(_jsp_ChooseTag_114);
                _jsp_OtherwiseTag_124.setPageContext(pageContext);
                int _jsp_start_flag_124 = _jsp_OtherwiseTag_124.doStartTag();

                if(_jsp_start_flag_124 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_124 != Tag.SKIP_BODY){
                    int _jsp_flag_124 = 0;

                    do{
                        /* TEXT: lineNumber: 118 */
                        out.write("c:otherwise");
                        _jsp_flag_124 = _jsp_OtherwiseTag_124.doAfterBody();
                    }
                    while(_jsp_flag_124 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_OtherwiseTag_124.doEndTag();
                _jsp_OtherwiseTag_124.release();
                /* NODE END: lineNumber: 118, tagClassName: com.skin.ayada.jstl.core.OtherwiseTag, tagInstanceName: _jsp_OtherwiseTag_124 */

                _jsp_flag_114 = _jsp_ChooseTag_114.doAfterBody();
            }
            while(_jsp_flag_114 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_ChooseTag_114.doEndTag();
        _jsp_ChooseTag_114.release();
        /* NODE END: lineNumber: 114, tagClassName: com.skin.ayada.jstl.core.ChooseTag, tagInstanceName: _jsp_ChooseTag_114 */

        /* TEXT: lineNumber: 119 */
        out.write("\r\n\r\n<h1>app:test test1</h1>\r\n");

        /* NODE START: lineNumber: 122, offset: 128, length: 2, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_129 */
        /* <app:test myBoolean="true" myChar="c" myByte="1" myInt="-1.0" myFloat="1.0f" myDouble="1.0d" myLong="1L" myString="Hello"/> */
        com.skin.ayada.jstl.core.TestTag _jsp_TestTag_129 = new com.skin.ayada.jstl.core.TestTag();
        _jsp_TestTag_129.setParent((Tag)null);
        _jsp_TestTag_129.setPageContext(pageContext);
        _jsp_TestTag_129.setMyBoolean(true);
        _jsp_TestTag_129.setMyChar('c');
        _jsp_TestTag_129.setMyByte((byte)1);
        _jsp_TestTag_129.setMyInt(-1);
        _jsp_TestTag_129.setMyFloat(1.0f);
        _jsp_TestTag_129.setMyDouble(1.0d);
        _jsp_TestTag_129.setMyLong(1L);
        _jsp_TestTag_129.setMyString("Hello");
        int _jsp_start_flag_129 = _jsp_TestTag_129.doStartTag();

        if(_jsp_start_flag_129 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_129 != Tag.SKIP_BODY){
            _jsp_TestTag_129.doAfterBody();
        }
        _jsp_TestTag_129.doEndTag();
        _jsp_TestTag_129.release();
        /* NODE END: lineNumber: 122, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_129 */

        /* TEXT: lineNumber: 122 */
        out.write("\r\n");

        /* NODE START: lineNumber: 123, offset: 131, length: 2, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_132 */
        /* <app:test myBoolean="false" myChar="c" myByte="243" myInt="-1.0" myFloat="1.0F" myDouble="1.0D" myLong="1L" myString="Hello"/> */
        com.skin.ayada.jstl.core.TestTag _jsp_TestTag_132 = new com.skin.ayada.jstl.core.TestTag();
        _jsp_TestTag_132.setParent((Tag)null);
        _jsp_TestTag_132.setPageContext(pageContext);
        _jsp_TestTag_132.setMyBoolean(false);
        _jsp_TestTag_132.setMyChar('c');
        _jsp_TestTag_132.setMyByte((byte)243);
        _jsp_TestTag_132.setMyInt(-1);
        _jsp_TestTag_132.setMyFloat(1.0f);
        _jsp_TestTag_132.setMyDouble(1.0d);
        _jsp_TestTag_132.setMyLong(1L);
        _jsp_TestTag_132.setMyString("Hello");
        int _jsp_start_flag_132 = _jsp_TestTag_132.doStartTag();

        if(_jsp_start_flag_132 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_132 != Tag.SKIP_BODY){
            _jsp_TestTag_132.doAfterBody();
        }
        _jsp_TestTag_132.doEndTag();
        _jsp_TestTag_132.release();
        /* NODE END: lineNumber: 123, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_132 */

        /* TEXT: lineNumber: 123 */
        out.write("\r\n");

        /* NODE START: lineNumber: 124, offset: 134, length: 2, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_135 */
        /* <app:test myInt="-1.0" myFloat="1.0" myDouble="1e3" myLong="1e3" myString="Hello"/> */
        com.skin.ayada.jstl.core.TestTag _jsp_TestTag_135 = new com.skin.ayada.jstl.core.TestTag();
        _jsp_TestTag_135.setParent((Tag)null);
        _jsp_TestTag_135.setPageContext(pageContext);
        _jsp_TestTag_135.setMyInt(-1);
        _jsp_TestTag_135.setMyFloat(1.0f);
        _jsp_TestTag_135.setMyDouble(1000.0d);
        _jsp_TestTag_135.setMyLong(1000L);
        _jsp_TestTag_135.setMyString("Hello");
        int _jsp_start_flag_135 = _jsp_TestTag_135.doStartTag();

        if(_jsp_start_flag_135 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_135 != Tag.SKIP_BODY){
            _jsp_TestTag_135.doAfterBody();
        }
        _jsp_TestTag_135.doEndTag();
        _jsp_TestTag_135.release();
        /* NODE END: lineNumber: 124, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_135 */

        /* TEXT: lineNumber: 124 */
        out.write("\r\n");

        /* NODE START: lineNumber: 125, offset: 137, length: 2, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_138 */
        /* <app:test myInt="-1.0" myFloat="1.0" myDouble="1.2e3" myLong="1.2e3" myString="Hello"/> */
        com.skin.ayada.jstl.core.TestTag _jsp_TestTag_138 = new com.skin.ayada.jstl.core.TestTag();
        _jsp_TestTag_138.setParent((Tag)null);
        _jsp_TestTag_138.setPageContext(pageContext);
        _jsp_TestTag_138.setMyInt(-1);
        _jsp_TestTag_138.setMyFloat(1.0f);
        _jsp_TestTag_138.setMyDouble(1200.0d);
        _jsp_TestTag_138.setMyLong(1200L);
        _jsp_TestTag_138.setMyString("Hello");
        int _jsp_start_flag_138 = _jsp_TestTag_138.doStartTag();

        if(_jsp_start_flag_138 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_138 != Tag.SKIP_BODY){
            _jsp_TestTag_138.doAfterBody();
        }
        _jsp_TestTag_138.doEndTag();
        _jsp_TestTag_138.release();
        /* NODE END: lineNumber: 125, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_138 */

        /* TEXT: lineNumber: 125 */
        out.write("\r\n\r\n<h1>app:scrollpage test1</h1>\r\n");

        /* NODE START: lineNumber: 128, offset: 140, length: 2, tagClassName: test.com.skin.ayada.taglib.ScrollPage, tagInstanceName: _jsp_ScrollPage_141 */
        /* <app:scrollpage count="254" pageNum="2" pageSize="10"/> */
        test.com.skin.ayada.taglib.ScrollPage _jsp_ScrollPage_141 = new test.com.skin.ayada.taglib.ScrollPage();
        _jsp_ScrollPage_141.setParent((Tag)null);
        _jsp_ScrollPage_141.setPageContext(pageContext);
        _jsp_ScrollPage_141.setCount(254);
        _jsp_ScrollPage_141.setPageNum(2);
        _jsp_ScrollPage_141.setPageSize(10);
        int _jsp_start_flag_141 = _jsp_ScrollPage_141.doStartTag();

        if(_jsp_start_flag_141 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_141 != Tag.SKIP_BODY){
            _jsp_ScrollPage_141.doAfterBody();
        }
        _jsp_ScrollPage_141.doEndTag();
        _jsp_ScrollPage_141.release();
        /* NODE END: lineNumber: 128, tagClassName: test.com.skin.ayada.taglib.ScrollPage, tagInstanceName: _jsp_ScrollPage_141 */

        /* TEXT: lineNumber: 128 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 130, offset: 143, length: 2, tagClassName: test.com.skin.ayada.taglib.TestBodyTag, tagInstanceName: _jsp_TestBodyTag_144 */
        /* <app:bodytest/> */
        test.com.skin.ayada.taglib.TestBodyTag _jsp_TestBodyTag_144 = new test.com.skin.ayada.taglib.TestBodyTag();
        _jsp_TestBodyTag_144.setParent((Tag)null);
        _jsp_TestBodyTag_144.setPageContext(pageContext);
        int _jsp_start_flag_144 = _jsp_TestBodyTag_144.doStartTag();

        if(_jsp_start_flag_144 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_144 != Tag.SKIP_BODY){
            _jsp_TestBodyTag_144.doAfterBody();
        }
        _jsp_TestBodyTag_144.doEndTag();
        _jsp_TestBodyTag_144.release();
        /* NODE END: lineNumber: 130, tagClassName: test.com.skin.ayada.taglib.TestBodyTag, tagInstanceName: _jsp_TestBodyTag_144 */

        /* TEXT: lineNumber: 130 */
        out.write("\r\n");

        /* NODE START: lineNumber: 131, offset: 146, length: 3, tagClassName: test.com.skin.ayada.taglib.TestBodyTag, tagInstanceName: _jsp_TestBodyTag_147 */
        /* <app:bodytest>...</app:bodytest> */
        test.com.skin.ayada.taglib.TestBodyTag _jsp_TestBodyTag_147 = new test.com.skin.ayada.taglib.TestBodyTag();
        _jsp_TestBodyTag_147.setParent((Tag)null);
        _jsp_TestBodyTag_147.setPageContext(pageContext);
        int _jsp_start_flag_147 = _jsp_TestBodyTag_147.doStartTag();

        if(_jsp_start_flag_147 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_147 != Tag.SKIP_BODY){
            int _jsp_flag_147 = 0;
            if(_jsp_start_flag_147 == BodyTag.EVAL_BODY_BUFFERED){
                BodyContent _jsp_body_content_147 = (BodyContent)(pageContext.pushBody());
                _jsp_TestBodyTag_147.setBodyContent(_jsp_body_content_147);
                _jsp_TestBodyTag_147.doInitBody();
                out = _jsp_body_content_147;
            }

            do{
                /* TEXT: lineNumber: 131 */
                out.write("Hello World !");
                _jsp_flag_147 = _jsp_TestBodyTag_147.doAfterBody();
            }
            while(_jsp_flag_147 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_147 == BodyTag.EVAL_BODY_BUFFERED){
                out = pageContext.popBody();
            }
        }
        _jsp_TestBodyTag_147.doEndTag();
        _jsp_TestBodyTag_147.release();
        /* NODE END: lineNumber: 131, tagClassName: test.com.skin.ayada.taglib.TestBodyTag, tagInstanceName: _jsp_TestBodyTag_147 */

        /* TEXT: lineNumber: 131 */
        out.write("\r\n");

        /* NODE START: lineNumber: 132, offset: 150, length: 2, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_151 */
        /* <c:test/> */
        com.skin.ayada.jstl.core.TestTag _jsp_TestTag_151 = new com.skin.ayada.jstl.core.TestTag();
        _jsp_TestTag_151.setParent((Tag)null);
        _jsp_TestTag_151.setPageContext(pageContext);
        int _jsp_start_flag_151 = _jsp_TestTag_151.doStartTag();

        if(_jsp_start_flag_151 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_151 != Tag.SKIP_BODY){
            _jsp_TestTag_151.doAfterBody();
        }
        _jsp_TestTag_151.doEndTag();
        _jsp_TestTag_151.release();
        /* NODE END: lineNumber: 132, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_151 */

        /* TEXT: lineNumber: 132 */
        out.write("\r\n</body>\r\n</html>");
        out.flush();
        jspWriter.flush();
    }
}
