/*
 * $RCSfile: BookListTemplate.java,v $
 * $Revision: 1.1 $
 * $Date: 2017-03-03 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp/benchmark
 * path: bookList.jsp
 * lastModified: 2017-02-25 23:42:36 000
 * options: -fastJstl true
 * template.dependencies
 * -- /bookList.jsp
 *
 * JSP generated by JspCompiler-1.0.1.6 (built 2017-03-03 23:16:44 956)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.ExpressionContext;
import com.skin.ayada.JspWriter;
import com.skin.ayada.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.JspTemplate;
import com.skin.ayada.util.ELUtil;


/**
 * <p>Title: BookListTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class BookListTemplate extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args) {
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        BookListTemplate template = new BookListTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /**
         * 自定义隐含变量, 允许不同的运行环境定义不同的隐含变量
         * 如果需要定义隐含变量请配置编译模板: ayada.properties
         * ayada.compile.java-template=com/skin/ayada/compile/class.jsp
         * 重新指定一个新的模板文件即可
         * 例如在web环境可定义如下的隐含变量:
         * 
         * ServletContext servletContext = (ServletContext)(pageContext.getAttribute("servletContext"));
         * HttpServletRequest request = (HttpServletRequest)(pageContext.getAttribute("request"));
         * HttpServletResponse response = (HttpServletResponse)(pageContext.getAttribute("response"));
         * 注: 隐含变量必须在模板运行之前由应用方注入到pageContext中.
         */

        // [1] out.write("<html>\r\n<head>\r\n<title>");
        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        // [3] engineName
        expressionContext.print(out, pageContext.getAttribute("engineName"));
        // [3] out.write("</title>\r\n</head>\r\n<body>\r\n<h1>");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        // [6] user.userId
        expressionContext.print(out, expressionContext.getValue("user.userId"));
        // [6] out.write(" / ");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        // [6] user.userName
        expressionContext.print(out, expressionContext.getValue("user.userName"));
        // [6] out.write("</h1>\r\n\r\n");
        out.write(_jsp_string_7, 0, _jsp_string_7.length);

        // [8] offset: 7, length: 33, name: _jsp_ChooseTag_8, tag: com.skin.ayada.jstl.core.ChooseTag
        // <c:choose>...</c:choose>
        // boolean _jsp_ChooseTag_8 = true;

        // [9] offset: 8, length: 25, name: _jsp_WhenTag_9, tag: com.skin.ayada.jstl.core.WhenTag
        // <c:when test=\"user.userName == &#39;admin&#39;\">...</c:when>
        if(expressionContext.getBoolean("user.userName == 'admin'")) {
            // [9] out.write("<table>\r\n    <tr>\r\n        <th>NO.</th>\r\n        <th>Title</th>\r\n        <th>Author</th>\r\n        <th>Publisher</th>\r\n        <th>PublicationDate</th>\r\n        <th>Price</th>\r\n        <th>DiscountPercent</th>\r\n        <th>DiscountPrice</th>\r\n    </tr>\r\n");
            out.write(_jsp_string_10, 0, _jsp_string_10.length);

            // [21] offset: 10, length: 21, name: _jsp_ForEachTag_11, tag: com.skin.ayada.jstl.core.ForEachTag
            // <c:forEach var=\"book\" items=\"books\" varStatus=\"status\">...</c:forEach>
            Object _jsp_old_var_11 = pageContext.getAttribute("book");
            Object _jsp_old_var_status_11 = pageContext.getAttribute("status");
            com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_11 = new com.skin.ayada.jstl.core.ForEachTag();
            _jsp_ForEachTag_11.setParent((Tag)null);
            _jsp_ForEachTag_11.setPageContext(pageContext);
            _jsp_ForEachTag_11.setVar("book");
            _jsp_ForEachTag_11.setItems(pageContext.getAttribute("books"));
            _jsp_ForEachTag_11.setVarStatus("status");
            if(_jsp_ForEachTag_11.doStartTag() != Tag.SKIP_BODY) {
                while(true) {
                    // [22] offset: 11, length: 19, name: _jsp_IfTag_12, tag: com.skin.ayada.jstl.core.IfTag
                    // <c:if test=\"book.price &gt; 0\">...</c:if>
                    if(expressionContext.getBoolean("book.price > 0")) {
                        // [22] out.write("    <tr>\r\n        <td>");
                        out.write(_jsp_string_13, 0, _jsp_string_13.length);
                        // [24] status.index + 1
                        expressionContext.print(out, expressionContext.getValue("status.index + 1"));
                        // [24] out.write("</td>\r\n        <td>");
                        out.write(_jsp_string_15, 0, _jsp_string_15.length);
                        // [25] book.title
                        expressionContext.print(out, expressionContext.getValue("book.title"));
                        // [25] out.write("</td>\r\n        <td>");
                        out.write(_jsp_string_17, 0, _jsp_string_17.length);
                        // [26] book.author
                        expressionContext.print(out, expressionContext.getValue("book.author"));
                        // [26] out.write("</td>\r\n        <td>");
                        out.write(_jsp_string_19, 0, _jsp_string_19.length);
                        // [27] book.publisher
                        expressionContext.print(out, expressionContext.getValue("book.publisher"));
                        // [27] out.write("</td>\r\n        <td>");
                        out.write(_jsp_string_21, 0, _jsp_string_21.length);
                        // [28] DateUtil.format(book.publication, \"yyyy-MM-dd HH:mm:ss\")
                        expressionContext.print(out, expressionContext.getValue("DateUtil.format(book.publication, \"yyyy-MM-dd HH:mm:ss\")"));
                        // [28] out.write("</td>\r\n        <td>");
                        out.write(_jsp_string_23, 0, _jsp_string_23.length);
                        // [29] book.price
                        expressionContext.print(out, expressionContext.getValue("book.price"));
                        // [29] out.write("</td>\r\n        <td>");
                        out.write(_jsp_string_25, 0, _jsp_string_25.length);
                        // [30] book.discount
                        expressionContext.print(out, expressionContext.getValue("book.discount"));
                        // [30] out.write("%</td>\r\n        <td>");
                        out.write(_jsp_string_27, 0, _jsp_string_27.length);
                        // [31] book.price * book.discount / 100
                        expressionContext.print(out, expressionContext.getValue("book.price * book.discount / 100"));
                        // [31] out.write("</td>\r\n    </tr>\r\n");
                        out.write(_jsp_string_29, 0, _jsp_string_29.length);
                    }
                    // [22] name: _jsp_IfTag_12, tag: com.skin.ayada.jstl.core.IfTag

                    if(_jsp_ForEachTag_11.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                        break;
                    }
                }
            }
            _jsp_ForEachTag_11.release();
            pageContext.setAttribute("book", _jsp_old_var_11);
            pageContext.setAttribute("status", _jsp_old_var_status_11);
            // [21] name: _jsp_ForEachTag_11, tag: com.skin.ayada.jstl.core.ForEachTag

            // [44] out.write("</table>\r\n");
            out.write(_jsp_string_32, 0, _jsp_string_32.length);
        }
        // [9] name: _jsp_WhenTag_9, tag: com.skin.ayada.jstl.core.WhenTag

        // [47] offset: 33, length: 3, name: _jsp_WhenTag_34, tag: com.skin.ayada.jstl.core.WhenTag
        // <c:when test=\"user != null\">...</c:when>
        else if(expressionContext.getBoolean("user != null")) {
            // [47] out.write("<table>\r\n    <tr>\r\n        <td>No privilege.</td>\r\n    </tr>\r\n</table>\r\n");
            out.write(_jsp_string_35, 0, _jsp_string_35.length);
        }
        // [47] name: _jsp_WhenTag_34, tag: com.skin.ayada.jstl.core.WhenTag

        // [54] offset: 36, length: 3, name: _jsp_OtherwiseTag_37, tag: com.skin.ayada.jstl.core.OtherwiseTag
        // <c:otherwise>...</c:otherwise>
        else {
            // [54] out.write("<table>\r\n    <tr>\r\n        <td>No login.</td>\r\n    </tr>\r\n</table>\r\n");
            out.write(_jsp_string_38, 0, _jsp_string_38.length);
        }
        // [54] name: _jsp_OtherwiseTag_37, tag: com.skin.ayada.jstl.core.OtherwiseTag

        // [8] name: _jsp_ChooseTag_8, tag: com.skin.ayada.jstl.core.ChooseTag

        // [61] out.write("</body>\r\n</html>\r\n");
        out.write(_jsp_string_41, 0, _jsp_string_41.length);

        out.flush();
        jspWriter.flush();
    }

    protected static final char[] _jsp_string_1 = "<html>\r\n<head>\r\n<title>".toCharArray();
    protected static final char[] _jsp_string_3 = "</title>\r\n</head>\r\n<body>\r\n<h1>".toCharArray();
    protected static final char[] _jsp_string_5 = " / ".toCharArray();
    protected static final char[] _jsp_string_7 = "</h1>\r\n\r\n".toCharArray();
    protected static final char[] _jsp_string_10 = "<table>\r\n    <tr>\r\n        <th>NO.</th>\r\n        <th>Title</th>\r\n        <th>Author</th>\r\n        <th>Publisher</th>\r\n        <th>PublicationDate</th>\r\n        <th>Price</th>\r\n        <th>DiscountPercent</th>\r\n        <th>DiscountPrice</th>\r\n    </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_13 = "    <tr>\r\n        <td>".toCharArray();
    protected static final char[] _jsp_string_15 = "</td>\r\n        <td>".toCharArray();
    protected static final char[] _jsp_string_17 = "</td>\r\n        <td>".toCharArray();
    protected static final char[] _jsp_string_19 = "</td>\r\n        <td>".toCharArray();
    protected static final char[] _jsp_string_21 = "</td>\r\n        <td>".toCharArray();
    protected static final char[] _jsp_string_23 = "</td>\r\n        <td>".toCharArray();
    protected static final char[] _jsp_string_25 = "</td>\r\n        <td>".toCharArray();
    protected static final char[] _jsp_string_27 = "%</td>\r\n        <td>".toCharArray();
    protected static final char[] _jsp_string_29 = "</td>\r\n    </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_32 = "</table>\r\n".toCharArray();
    protected static final char[] _jsp_string_35 = "<table>\r\n    <tr>\r\n        <td>No privilege.</td>\r\n    </tr>\r\n</table>\r\n".toCharArray();
    protected static final char[] _jsp_string_38 = "<table>\r\n    <tr>\r\n        <td>No login.</td>\r\n    </tr>\r\n</table>\r\n".toCharArray();
    protected static final char[] _jsp_string_41 = "</body>\r\n</html>\r\n".toCharArray();

}
