/*
 * $RCSfile: BufferTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2017-02-09 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /buffer.jsp
 * lastModified: 2014-05-27 14:13:32 000
 * options: -fastJstl true
 * template.dependencies
 * -- /buffer.jsp
 *
 * JSP generated by JspCompiler-1.0.1.4 (built 2017-02-09 00:51:26 841)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: BufferTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class BufferTemplate extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        BufferTemplate template = new BufferTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 3, tagClassName: com.skin.ayada.jstl.core.BufferTag, tagInstanceName: _jsp_BufferTag_1
        // <c:buffer var=\"mybuffer\">...</c:buffer>
        com.skin.ayada.jstl.core.BufferTag _jsp_BufferTag_1 = new com.skin.ayada.jstl.core.BufferTag();
        try {
            _jsp_BufferTag_1.setPageContext(pageContext);
            _jsp_BufferTag_1.setParent((Tag)null);
            _jsp_BufferTag_1.setVar("mybuffer");
            int _jsp_start_flag_1 = _jsp_BufferTag_1.doStartTag();

            if(_jsp_start_flag_1 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_1 != Tag.SKIP_BODY) {
                int _jsp_flag_1 = 0;
                if(_jsp_start_flag_1 == BodyTag.EVAL_BODY_BUFFERED) {
                    BodyContent _jsp_body_content_1 = pageContext.pushBody();
                    _jsp_BufferTag_1.setBodyContent(_jsp_body_content_1);
                    _jsp_BufferTag_1.doInitBody();
                    out = _jsp_body_content_1;
                }

                do {
                // TEXT: lineNumber: 1
                // out.write("    <h1>Hello World !</h1>\r\n");
                out.write(_jsp_string_2, 0, _jsp_string_2.length);
                    _jsp_flag_1 = _jsp_BufferTag_1.doAfterBody();
                }
                while(_jsp_flag_1 == IterationTag.EVAL_BODY_AGAIN);
                if(_jsp_start_flag_1 == BodyTag.EVAL_BODY_BUFFERED) {
                    out = pageContext.popBody();
                }
            }
            _jsp_BufferTag_1.doEndTag();
        }
        finally {
            this.doFinally(_jsp_BufferTag_1);
        }
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.BufferTag, tagInstanceName: _jsp_BufferTag_1

        // TEXT: lineNumber: 3
        // out.write("\r\n<div>");
        out.write(_jsp_string_4, 0, _jsp_string_4.length);

        // NODE START: lineNumber: 5, offset: 4, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_5
        // <c:out value=\"${mybuffer}\"/>
        com.skin.ayada.jstl.core.OutTag.write(out, pageContext.getAttribute("mybuffer"), false);
        // out.print(ExpressionUtil.getString(expressionContext, "${mybuffer}"));
        // jsp.jstl.core.OutTag END
        // NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_5

        // TEXT: lineNumber: 5
        // out.write("</div>\r\n<div>");
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        // VARIABLE: lineNumber: 6
        expressionContext.print(out, pageContext.getAttribute("mybuffer"));
        // TEXT: lineNumber: 6
        // out.write("</div>");
        out.write(_jsp_string_9, 0, _jsp_string_9.length);

        out.flush();
        jspWriter.flush();
    }

    protected static final char[] _jsp_string_2 = "    <h1>Hello World !</h1>\r\n".toCharArray();
    protected static final char[] _jsp_string_4 = "\r\n<div>".toCharArray();
    protected static final char[] _jsp_string_7 = "</div>\r\n<div>".toCharArray();
    protected static final char[] _jsp_string_9 = "</div>".toCharArray();

}
