/*
 * $RCSfile: ChooseWhenTest2Template.java,v $$
 * $Revision: 1.1 $
 * $Date: 2017-02-09 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /chooseWhenTest2.jsp
 * lastModified: 2017-02-07 22:39:54 637
 * options: -fastJstl true
 * template.dependencies
 * -- /chooseWhenTest2.jsp
 *
 * JSP generated by JspCompiler-1.0.1.4 (built 2017-02-09 00:51:27 406)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ChooseWhenTest2Template</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ChooseWhenTest2Template extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ChooseWhenTest2Template template = new ChooseWhenTest2Template();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_1
        // <c:set var=\"mystring\" value=\"a\"/>
        pageContext.setAttribute("mystring", "a");
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_1

        // NODE START: lineNumber: 2, offset: 2, length: 14, tagClassName: com.skin.ayada.jstl.core.ChooseTag, tagInstanceName: _jsp_ChooseTag_3
        // <c:choose>...</c:choose>
        boolean _jsp_ChooseTag_3 = true;

        // NODE START: lineNumber: 3, offset: 3, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_4
        // <c:when test=\"${mystring == &#39;a&#39;}\">...</c:when>
        if(_jsp_ChooseTag_3 && ExpressionUtil.getBoolean(expressionContext, "${mystring == 'a'}")) {
            _jsp_ChooseTag_3 = false;
            // TEXT: lineNumber: 3
            // out.write("        a\r\n");
            out.write(_jsp_string_5, 0, _jsp_string_5.length);
        } // jsp.jstl.core.WhenTag END
        // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_4

        // NODE START: lineNumber: 6, offset: 6, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_7
        // <c:when test=\"${mystring == &#39;b&#39;}\">...</c:when>
        if(_jsp_ChooseTag_3 && ExpressionUtil.getBoolean(expressionContext, "${mystring == 'b'}")) {
            _jsp_ChooseTag_3 = false;
            // TEXT: lineNumber: 6
            // out.write("        b\r\n");
            out.write(_jsp_string_8, 0, _jsp_string_8.length);
        } // jsp.jstl.core.WhenTag END
        // NODE END: lineNumber: 6, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_7

        // NODE START: lineNumber: 9, offset: 9, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_10
        // <c:when test=\"${mystring == &#39;c&#39;}\">...</c:when>
        if(_jsp_ChooseTag_3 && ExpressionUtil.getBoolean(expressionContext, "${mystring == 'c'}")) {
            _jsp_ChooseTag_3 = false;
            // TEXT: lineNumber: 9
            // out.write("        c\r\n");
            out.write(_jsp_string_11, 0, _jsp_string_11.length);
        } // jsp.jstl.core.WhenTag END
        // NODE END: lineNumber: 9, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_10

        // NODE START: lineNumber: 12, offset: 12, length: 3, tagClassName: com.skin.ayada.jstl.core.OtherwiseTag, tagInstanceName: _jsp_OtherwiseTag_13
        // <c:otherwise>...</c:otherwise>
        if(_jsp_ChooseTag_3) {
            _jsp_ChooseTag_3 = false;
            // TEXT: lineNumber: 12
            // out.write("        x\r\n");
            out.write(_jsp_string_14, 0, _jsp_string_14.length);
        } // jsp.jstl.core.OtherwiseTag END
        // NODE END: lineNumber: 12, tagClassName: com.skin.ayada.jstl.core.OtherwiseTag, tagInstanceName: _jsp_OtherwiseTag_13

        // jsp.jstl.core.ChooseTag END
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.ChooseTag, tagInstanceName: _jsp_ChooseTag_3


        out.flush();
        jspWriter.flush();
    }

    protected static final char[] _jsp_string_5 = "        a\r\n".toCharArray();
    protected static final char[] _jsp_string_8 = "        b\r\n".toCharArray();
    protected static final char[] _jsp_string_11 = "        c\r\n".toCharArray();
    protected static final char[] _jsp_string_14 = "        x\r\n".toCharArray();

}
