/*
 * $RCSfile: ClipTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /clipTest.jsp
 * lastModified: 2016-01-12 16:30:40 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-12 23:29:58 333)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ClipTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ClipTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ClipTestTemplate template = new ClipTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // TEXT: lineNumber: 2
        // out.write("<h1>header</h1>\r\n<p>Clip Test</p>\r\n");
        out.write(_jsp_string_1, 0, _jsp_string_1.length);

        // NODE START: lineNumber: 4, offset: 1, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_2
        // <c:set var=\"myVar1\" value=\"123\"/>
        pageContext.setAttribute("myVar1", 123);
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_2

        // TEXT: lineNumber: 4
        // out.write("   ####\r\n");
        out.write(_jsp_string_4, 0, _jsp_string_4.length);

        // NODE START: lineNumber: 6, offset: 4, length: 5, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_5
        // <c:forEach var=\"myVar\" items=\"1,2,3\">...</c:forEach>
        Object _jsp_old_var_5 = pageContext.getAttribute("myVar");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_5 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_5.setParent((Tag)null);
        _jsp_ForEachTag_5.setPageContext(pageContext);
        _jsp_ForEachTag_5.setVar("myVar");
        _jsp_ForEachTag_5.setItems("1,2,3");
        if(_jsp_ForEachTag_5.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // TEXT: lineNumber: 6
                // out.write("    <p>");
                out.write(_jsp_string_6, 0, _jsp_string_6.length);
                // VARIABLE: lineNumber: 7
                expressionContext.print(out, pageContext.getAttribute("myVar"));
                // TEXT: lineNumber: 7
                // out.write("</p>\r\n");
                out.write(_jsp_string_8, 0, _jsp_string_8.length);
                if(_jsp_ForEachTag_5.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_5.release();
        pageContext.setAttribute("myVar", _jsp_old_var_5);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 6, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_5

        // TEXT: lineNumber: 8
        // out.write("###\r\n");
        out.write(_jsp_string_10, 0, _jsp_string_10.length);

        // NODE START: lineNumber: 13, offset: 10, length: 8, tagClassName: com.skin.ayada.jstl.core.ChooseTag, tagInstanceName: _jsp_ChooseTag_11
        // <c:choose>...</c:choose>
        boolean _jsp_ChooseTag_11 = true;

        // NODE START: lineNumber: 14, offset: 11, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_12
        // <c:when test=\"${1 == 1}\">...</c:when>
        if(_jsp_ChooseTag_11 && ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")) {
            _jsp_ChooseTag_11 = false;
            // TEXT: lineNumber: 14
            // out.write("        Hello !\r\n");
            out.write(_jsp_string_13, 0, _jsp_string_13.length);
        } // jsp.jstl.core.WhenTag END
        // NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_12

        // NODE START: lineNumber: 17, offset: 14, length: 3, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_15
        // <c:when test=\"${1 == 1}\">...</c:when>
        if(_jsp_ChooseTag_11 && ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")) {
            _jsp_ChooseTag_11 = false;
            // TEXT: lineNumber: 17
            // out.write("        Hi !\r\n");
            out.write(_jsp_string_16, 0, _jsp_string_16.length);
        } // jsp.jstl.core.WhenTag END
        // NODE END: lineNumber: 17, tagClassName: com.skin.ayada.jstl.core.WhenTag, tagInstanceName: _jsp_WhenTag_15

        // jsp.jstl.core.ChooseTag END
        // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.ChooseTag, tagInstanceName: _jsp_ChooseTag_11

        // TEXT: lineNumber: 20
        // out.write("###\r\n\r\n<p>test</p>\r\n<p>test</p>\r\n\r\n\r\n###\r\n\r\n");
        out.write(_jsp_string_19, 0, _jsp_string_19.length);

        // jsp:scriptlet: lineNumber: 35
    for(int i = 0; i < 3; i++) {
    
        // jsp:scriptlet END

        // TEXT: lineNumber: 37
        // out.write("<p>");
        out.write(_jsp_string_22, 0, _jsp_string_22.length);

        // jsp:expression: lineNumber: 37
        expressionContext.print(out, (i));
        // jsp:expression END

        // TEXT: lineNumber: 37
        // out.write("</p>\r\n");
        out.write(_jsp_string_25, 0, _jsp_string_25.length);

        // jsp:scriptlet: lineNumber: 39
     }

        // jsp:scriptlet END

        // TEXT: lineNumber: 42
        // out.write("###\r\n");
        out.write(_jsp_string_28, 0, _jsp_string_28.length);

        // jsp:scriptlet: lineNumber: 44
    for(int i = 0; i < 3; i++) {
    
        // jsp:scriptlet END

        // TEXT: lineNumber: 46
        // out.write("<p>");
        out.write(_jsp_string_31, 0, _jsp_string_31.length);

        // jsp:expression: lineNumber: 46
        expressionContext.print(out, (i));
        // jsp:expression END

        // TEXT: lineNumber: 46
        // out.write("</p>\r\n");
        out.write(_jsp_string_34, 0, _jsp_string_34.length);

        // jsp:scriptlet: lineNumber: 48
     }

        // jsp:scriptlet END


        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_1 = "<h1>header</h1>\r\n<p>Clip Test</p>\r\n".toCharArray();
    public static final char[] _jsp_string_4 = "   ####\r\n".toCharArray();
    public static final char[] _jsp_string_6 = "    <p>".toCharArray();
    public static final char[] _jsp_string_8 = "</p>\r\n".toCharArray();
    public static final char[] _jsp_string_10 = "###\r\n".toCharArray();
    public static final char[] _jsp_string_13 = "        Hello !\r\n".toCharArray();
    public static final char[] _jsp_string_16 = "        Hi !\r\n".toCharArray();
    public static final char[] _jsp_string_19 = "###\r\n\r\n<p>test</p>\r\n<p>test</p>\r\n\r\n\r\n###\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_22 = "<p>".toCharArray();
    public static final char[] _jsp_string_25 = "</p>\r\n".toCharArray();
    public static final char[] _jsp_string_28 = "###\r\n".toCharArray();
    public static final char[] _jsp_string_31 = "<p>".toCharArray();
    public static final char[] _jsp_string_34 = "</p>\r\n".toCharArray();

}
