/*
 * $RCSfile: CommandTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /command.jsp
 * lastModified: 2014-05-27 11:37:50 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-12 23:29:58 643)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: CommandTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class CommandTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        CommandTemplate template = new CommandTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html; charset=UTF-8"/>

        // TEXT: lineNumber: 2
        // out.write("<!--\r\nt:import: 编译指令\r\n1. 可以放在任何位置, 但必须在使用之前引入\r\n2. 如果多次引入同一个tag, tag的bodyContent以最后一次引入的为准, 引擎在编译结束之后才会根据bodyContent的类型做一次紧缩处理\r\n   bodyContent: jsp|tagdependent|empty\r\n   如果是tagdependent, 那么该tag内部的所有文本节点和表达式节点都会被清除, 其子节点的内容不会清除(但是会根据子节点的bodyContent决定是否清除)\r\n   如果是empty, 那么内部的任何节点都会被清除\r\n   如果是jsp, 则保持现有内容不变\r\n   因此所有的引入操作最好放在文件头, 并且对同一个tag只引入一次\r\n\r\n3. className不是必选项, 可以为空, 如果为空则使用ayada-taglib-default.xml或者ayada-taglib.xml文件中配置的className, 因此下面的两种写法都是合法的\r\n4. bodyContent和description都不是必选项, 可以为空, bodyContent默认为jsp\r\n-->\r\n<h1>tag.bodyContent</h1>\r\n<p>1. jsp: any content</p>\r\n<p>2. tagdependent: tag only</p>\r\n<p>3. empty: ignore any content</p>\r\n\r\n<!-- 使用重新定义的c:if标签, 该标签内部的所有文本内容在编译期都会被清除, 但是自标签的文本仍然可以输出 -->\r\n");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);

        // NODE START: lineNumber: 27, offset: 3, length: 5, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_4
        // <c:if test=\"${1 == 1}\">...</c:if>
        if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")) {
            // NODE START: lineNumber: 29, offset: 4, length: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_5
            // <c:out escapeXml=\"true\">...</c:out>
            out = pageContext.pushBody();
            // TEXT: lineNumber: 29
            // out.write("\"I\'m here !\"");
            out.write(_jsp_string_6, 0, _jsp_string_6.length);
            pageContext.print((BodyContent)out, true);
            out = pageContext.popBody();
            // jsp.jstl.core.OutTag END
            // NODE END: lineNumber: 29, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_5

        } // jsp.jstl.core.IfTag END
        // NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_4

        // TEXT: lineNumber: 30
        // out.write("<!-- c:command的bodyContent被定义为tagdependent，因此内部的文本内容都会被忽略。-->\r\n");
        out.write(_jsp_string_9, 0, _jsp_string_9.length);

        // NODE START: lineNumber: 33, offset: 9, length: 16, tagClassName: com.skin.ayada.jstl.core.DependentTag, tagInstanceName: _jsp_DependentTag_10
        // <c:command>...</c:command>
        com.skin.ayada.jstl.core.DependentTag _jsp_DependentTag_10 = new com.skin.ayada.jstl.core.DependentTag();
        _jsp_DependentTag_10.setPageContext(pageContext);
        _jsp_DependentTag_10.setParent((Tag)null);
        int _jsp_start_flag_10 = _jsp_DependentTag_10.doStartTag();

        if(_jsp_start_flag_10 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_10 != Tag.SKIP_BODY) {
            int _jsp_flag_10 = 0;

            do {
                // NODE START: lineNumber: 35, offset: 10, length: 14, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_11
                // <c:if test=\"${1 == 2}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${1 == 2}")) {
                    // NODE START: lineNumber: 36, offset: 11, length: 2, tagClassName: com.skin.ayada.jstl.io.CopyTag, tagInstanceName: _jsp_CopyTag_12
                    // <io:copy file=\"E:/WorkSpace/ayada/webapp/test1\" todir=\"E:/WorkSpace/ayada/webapp/test2\"/>
                    com.skin.ayada.jstl.io.CopyTag _jsp_CopyTag_12 = new com.skin.ayada.jstl.io.CopyTag();
                    _jsp_CopyTag_12.setPageContext(pageContext);
                    _jsp_CopyTag_12.setParent((Tag)null);
                    _jsp_CopyTag_12.setFile("E:/WorkSpace/ayada/webapp/test1");
                    _jsp_CopyTag_12.setTodir("E:/WorkSpace/ayada/webapp/test2");
                    int _jsp_start_flag_12 = _jsp_CopyTag_12.doStartTag();

                    if(_jsp_start_flag_12 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_12 != Tag.SKIP_BODY) {
                        _jsp_CopyTag_12.doAfterBody();
                    }
                    _jsp_CopyTag_12.doEndTag();
                    _jsp_CopyTag_12.release();
                    // NODE END: lineNumber: 36, tagClassName: com.skin.ayada.jstl.io.CopyTag, tagInstanceName: _jsp_CopyTag_12

                    // NODE START: lineNumber: 37, offset: 13, length: 2, tagClassName: com.skin.ayada.jstl.io.DeleteTag, tagInstanceName: _jsp_DeleteTag_14
                    // <io:delete file=\"E:/WorkSpace/ayada/webapp/test2/style.css\"/>
                    com.skin.ayada.jstl.io.DeleteTag _jsp_DeleteTag_14 = new com.skin.ayada.jstl.io.DeleteTag();
                    _jsp_DeleteTag_14.setPageContext(pageContext);
                    _jsp_DeleteTag_14.setParent((Tag)null);
                    _jsp_DeleteTag_14.setFile("E:/WorkSpace/ayada/webapp/test2/style.css");
                    int _jsp_start_flag_14 = _jsp_DeleteTag_14.doStartTag();

                    if(_jsp_start_flag_14 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_14 != Tag.SKIP_BODY) {
                        _jsp_DeleteTag_14.doAfterBody();
                    }
                    _jsp_DeleteTag_14.doEndTag();
                    _jsp_DeleteTag_14.release();
                    // NODE END: lineNumber: 37, tagClassName: com.skin.ayada.jstl.io.DeleteTag, tagInstanceName: _jsp_DeleteTag_14

                    // NODE START: lineNumber: 38, offset: 15, length: 2, tagClassName: com.skin.ayada.jstl.io.MakeDirTag, tagInstanceName: _jsp_MakeDirTag_16
                    // <io:mkdir file=\"E:/WorkSpace/ayada/webapp/test2/empty1\"/>
                    com.skin.ayada.jstl.io.MakeDirTag _jsp_MakeDirTag_16 = new com.skin.ayada.jstl.io.MakeDirTag();
                    _jsp_MakeDirTag_16.setPageContext(pageContext);
                    _jsp_MakeDirTag_16.setParent((Tag)null);
                    _jsp_MakeDirTag_16.setFile("E:/WorkSpace/ayada/webapp/test2/empty1");
                    int _jsp_start_flag_16 = _jsp_MakeDirTag_16.doStartTag();

                    if(_jsp_start_flag_16 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_16 != Tag.SKIP_BODY) {
                        _jsp_MakeDirTag_16.doAfterBody();
                    }
                    _jsp_MakeDirTag_16.doEndTag();
                    _jsp_MakeDirTag_16.release();
                    // NODE END: lineNumber: 38, tagClassName: com.skin.ayada.jstl.io.MakeDirTag, tagInstanceName: _jsp_MakeDirTag_16

                    // NODE START: lineNumber: 39, offset: 17, length: 2, tagClassName: com.skin.ayada.jstl.io.MakeDirTag, tagInstanceName: _jsp_MakeDirTag_18
                    // <io:mkdir file=\"E:/WorkSpace/ayada/webapp/test2/empty2\"/>
                    com.skin.ayada.jstl.io.MakeDirTag _jsp_MakeDirTag_18 = new com.skin.ayada.jstl.io.MakeDirTag();
                    _jsp_MakeDirTag_18.setPageContext(pageContext);
                    _jsp_MakeDirTag_18.setParent((Tag)null);
                    _jsp_MakeDirTag_18.setFile("E:/WorkSpace/ayada/webapp/test2/empty2");
                    int _jsp_start_flag_18 = _jsp_MakeDirTag_18.doStartTag();

                    if(_jsp_start_flag_18 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_18 != Tag.SKIP_BODY) {
                        _jsp_MakeDirTag_18.doAfterBody();
                    }
                    _jsp_MakeDirTag_18.doEndTag();
                    _jsp_MakeDirTag_18.release();
                    // NODE END: lineNumber: 39, tagClassName: com.skin.ayada.jstl.io.MakeDirTag, tagInstanceName: _jsp_MakeDirTag_18

                    // NODE START: lineNumber: 40, offset: 19, length: 2, tagClassName: com.skin.ayada.jstl.io.DeleteTag, tagInstanceName: _jsp_DeleteTag_20
                    // <io:delete file=\"E:/WorkSpace/ayada/webapp/test2/empty2\"/>
                    com.skin.ayada.jstl.io.DeleteTag _jsp_DeleteTag_20 = new com.skin.ayada.jstl.io.DeleteTag();
                    _jsp_DeleteTag_20.setPageContext(pageContext);
                    _jsp_DeleteTag_20.setParent((Tag)null);
                    _jsp_DeleteTag_20.setFile("E:/WorkSpace/ayada/webapp/test2/empty2");
                    int _jsp_start_flag_20 = _jsp_DeleteTag_20.doStartTag();

                    if(_jsp_start_flag_20 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_20 != Tag.SKIP_BODY) {
                        _jsp_DeleteTag_20.doAfterBody();
                    }
                    _jsp_DeleteTag_20.doEndTag();
                    _jsp_DeleteTag_20.release();
                    // NODE END: lineNumber: 40, tagClassName: com.skin.ayada.jstl.io.DeleteTag, tagInstanceName: _jsp_DeleteTag_20

                    // NODE START: lineNumber: 41, offset: 21, length: 2, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_22
                    // <c:exit test=\"${1 == 1}\"/>
                    if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")) {
                        return;
                    }
                    // jsp.jstl.core.ExitTag END
                    // NODE END: lineNumber: 41, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_22

                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 35, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_11

                _jsp_flag_10 = _jsp_DependentTag_10.doAfterBody();
            }
            while(_jsp_flag_10 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_DependentTag_10.doEndTag();
        _jsp_DependentTag_10.release();
        // NODE END: lineNumber: 33, tagClassName: com.skin.ayada.jstl.core.DependentTag, tagInstanceName: _jsp_DependentTag_10

        // TEXT: lineNumber: 43
        // out.write("<h1>sql:execute</h1>\r\n<h2>connection</h2>\r\n<p>1. get from attribute, example: connection=\"${expression}\"</p>\r\n<p>2. get from pageContext by name: connection</p>\r\n<p>3. get from parent tag</p>\r\n<p>4. throws exception</p>\r\n<p>template.home: ");
        out.write(_jsp_string_26, 0, _jsp_string_26.length);
        // EXPRESSION: lineNumber: 51
        expressionContext.print(out, expressionContext.getString("template.home"));
        // TEXT: lineNumber: 51
        // out.write("</p>\r\n\r\n<!-- use external connection -->\r\n");
        out.write(_jsp_string_28, 0, _jsp_string_28.length);

        // NODE START: lineNumber: 54, offset: 28, length: 2, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_29
        // <sql:connect var=\"connection2\" connection=\"${myConnection}\">...</sql:connect>
        com.skin.ayada.jstl.sql.ConnectTag _jsp_ConnectTag_29 = new com.skin.ayada.jstl.sql.ConnectTag();
        try {
            _jsp_ConnectTag_29.setPageContext(pageContext);
            _jsp_ConnectTag_29.setParent((Tag)null);
            _jsp_ConnectTag_29.setVar("connection2");
            _jsp_ConnectTag_29.setConnection(pageContext.getValue("myConnection", java.sql.Connection.class));
            int _jsp_start_flag_29 = _jsp_ConnectTag_29.doStartTag();

            if(_jsp_start_flag_29 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_29 != Tag.SKIP_BODY) {
                _jsp_ConnectTag_29.doAfterBody();
            }
            _jsp_ConnectTag_29.doEndTag();
            _jsp_ConnectTag_29.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_ConnectTag_29.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_ConnectTag_29.doFinally();
        }
        // NODE END: lineNumber: 54, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_29

        // NODE START: lineNumber: 56, offset: 30, length: 12, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_31
        // <c:if test=\"${1 == 1}\">...</c:if>
        if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")) {
            // NODE START: lineNumber: 57, offset: 31, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_32
            // <c:set var=\"createDatabaseUrl\" value=\"jdbc:mysql://localhost:3306?user=root&amp;password=1234&amp;characterEncoding=utf8\"/>
            pageContext.setAttribute("createDatabaseUrl", "jdbc:mysql://localhost:3306?user=root&password=1234&characterEncoding=utf8");
            // jsp.jstl.core.SetTag END
            // NODE END: lineNumber: 57, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_32

            // NODE START: lineNumber: 58, offset: 33, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_34
            // <c:set var=\"url\" value=\"jdbc:mysql://localhost:3306/mytest2?user=root&amp;password=1234&amp;characterEncoding=utf8\"/>
            pageContext.setAttribute("url", "jdbc:mysql://localhost:3306/mytest2?user=root&password=1234&characterEncoding=utf8");
            // jsp.jstl.core.SetTag END
            // NODE END: lineNumber: 58, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_34

            // NODE START: lineNumber: 59, offset: 35, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_36
            // <c:set var=\"driverClass\" value=\"com.mysql.jdbc.Driver\"/>
            pageContext.setAttribute("driverClass", "com.mysql.jdbc.Driver");
            // jsp.jstl.core.SetTag END
            // NODE END: lineNumber: 59, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_36

            // NODE START: lineNumber: 60, offset: 37, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_38
            // <c:set var=\"userName\" value=\"root\"/>
            pageContext.setAttribute("userName", "root");
            // jsp.jstl.core.SetTag END
            // NODE END: lineNumber: 60, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_38

            // NODE START: lineNumber: 61, offset: 39, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_40
            // <c:set var=\"password\" value=\"1234\"/>
            pageContext.setAttribute("password", 1234);
            // jsp.jstl.core.SetTag END
            // NODE END: lineNumber: 61, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_40

        } // jsp.jstl.core.IfTag END
        // NODE END: lineNumber: 56, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_31

        // NODE START: lineNumber: 64, offset: 42, length: 5, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_43
        // <sql:connect var=\"connection\" url=\"${createDatabaseUrl}\" driverClass=\"com.mysql.jdbc.Driver\" userName=\"${userName}\" password=\"${password}\">...</sql:connect>
        com.skin.ayada.jstl.sql.ConnectTag _jsp_ConnectTag_43 = new com.skin.ayada.jstl.sql.ConnectTag();
        try {
            _jsp_ConnectTag_43.setPageContext(pageContext);
            _jsp_ConnectTag_43.setParent((Tag)null);
            _jsp_ConnectTag_43.setVar("connection");
            _jsp_ConnectTag_43.setUrl(pageContext.getString("createDatabaseUrl"));
            _jsp_ConnectTag_43.setDriverClass("com.mysql.jdbc.Driver");
            _jsp_ConnectTag_43.setUserName(pageContext.getString("userName"));
            _jsp_ConnectTag_43.setPassword(pageContext.getString("password"));
            int _jsp_start_flag_43 = _jsp_ConnectTag_43.doStartTag();

            if(_jsp_start_flag_43 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_43 != Tag.SKIP_BODY) {
                int _jsp_flag_43 = 0;

                do {
                    // NODE START: lineNumber: 65, offset: 43, length: 3, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_44
                    // <sql:execute out=\"${pageContext}\">...</sql:execute>
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_44 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_44.setPageContext(pageContext);
                    _jsp_SqlTag_44.setParent(_jsp_ConnectTag_43);
                    _jsp_SqlTag_44.setOut(pageContext.getAttribute("pageContext"));
                    int _jsp_start_flag_44 = _jsp_SqlTag_44.doStartTag();

                    if(_jsp_start_flag_44 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_44 != Tag.SKIP_BODY) {
                        int _jsp_flag_44 = 0;
                        if(_jsp_start_flag_44 == BodyTag.EVAL_BODY_BUFFERED) {
                            BodyContent _jsp_body_content_44 = pageContext.pushBody();
                            _jsp_SqlTag_44.setBodyContent(_jsp_body_content_44);
                            _jsp_SqlTag_44.doInitBody();
                            out = _jsp_body_content_44;
                        }

                        do {
                            // TEXT: lineNumber: 65
                            // out.write("        drop database if exists mytest2;\r\n        create database mytest2 character set utf8;\r\n");
                            out.write(_jsp_string_45, 0, _jsp_string_45.length);
                            _jsp_flag_44 = _jsp_SqlTag_44.doAfterBody();
                        }
                        while(_jsp_flag_44 == IterationTag.EVAL_BODY_AGAIN);
                        if(_jsp_start_flag_44 == BodyTag.EVAL_BODY_BUFFERED) {
                            out = pageContext.popBody();
                        }
                    }
                    _jsp_SqlTag_44.doEndTag();
                    _jsp_SqlTag_44.release();
                    // NODE END: lineNumber: 65, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_44

                    _jsp_flag_43 = _jsp_ConnectTag_43.doAfterBody();
                }
                while(_jsp_flag_43 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_ConnectTag_43.doEndTag();
            _jsp_ConnectTag_43.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_ConnectTag_43.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_ConnectTag_43.doFinally();
        }
        // NODE END: lineNumber: 64, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_43

        // NODE START: lineNumber: 71, offset: 47, length: 46, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_48
        // <sql:connect var=\"connection\" url=\"${url}\" driverClass=\"com.mysql.jdbc.Driver\" userName=\"${userName}\" password=\"${password}\">...</sql:connect>
        com.skin.ayada.jstl.sql.ConnectTag _jsp_ConnectTag_48 = new com.skin.ayada.jstl.sql.ConnectTag();
        try {
            _jsp_ConnectTag_48.setPageContext(pageContext);
            _jsp_ConnectTag_48.setParent((Tag)null);
            _jsp_ConnectTag_48.setVar("connection");
            _jsp_ConnectTag_48.setUrl(pageContext.getString("url"));
            _jsp_ConnectTag_48.setDriverClass("com.mysql.jdbc.Driver");
            _jsp_ConnectTag_48.setUserName(pageContext.getString("userName"));
            _jsp_ConnectTag_48.setPassword(pageContext.getString("password"));
            int _jsp_start_flag_48 = _jsp_ConnectTag_48.doStartTag();

            if(_jsp_start_flag_48 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_48 != Tag.SKIP_BODY) {
                int _jsp_flag_48 = 0;

                do {
                    // NODE START: lineNumber: 72, offset: 48, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_49
                    // <sql:execute home=\"${template.home}/database\" file=\"create.sql\" encoding=\"UTF-8\" out=\"${pageContext}\"/>
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_49 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_49.setPageContext(pageContext);
                    _jsp_SqlTag_49.setParent(_jsp_ConnectTag_48);
                    _jsp_SqlTag_49.setHome(ExpressionUtil.getString(expressionContext, "${template.home}/database"));
                    _jsp_SqlTag_49.setFile("create.sql");
                    _jsp_SqlTag_49.setEncoding("UTF-8");
                    _jsp_SqlTag_49.setOut(pageContext.getAttribute("pageContext"));
                    int _jsp_start_flag_49 = _jsp_SqlTag_49.doStartTag();

                    if(_jsp_start_flag_49 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_49 != Tag.SKIP_BODY) {
                        _jsp_SqlTag_49.doAfterBody();
                    }
                    _jsp_SqlTag_49.doEndTag();
                    _jsp_SqlTag_49.release();
                    // NODE END: lineNumber: 72, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_49

                    // NODE START: lineNumber: 73, offset: 50, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_51
                    // <sql:execute sql=\"delete from my_test1;\" out=\"${pageContext}\"/>
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_51 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_51.setPageContext(pageContext);
                    _jsp_SqlTag_51.setParent(_jsp_ConnectTag_48);
                    _jsp_SqlTag_51.setSql("delete from my_test1;");
                    _jsp_SqlTag_51.setOut(pageContext.getAttribute("pageContext"));
                    int _jsp_start_flag_51 = _jsp_SqlTag_51.doStartTag();

                    if(_jsp_start_flag_51 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_51 != Tag.SKIP_BODY) {
                        _jsp_SqlTag_51.doAfterBody();
                    }
                    _jsp_SqlTag_51.doEndTag();
                    _jsp_SqlTag_51.release();
                    // NODE END: lineNumber: 73, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_51

                    // NODE START: lineNumber: 74, offset: 52, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_53
                    // <sql:execute sql=\"delete from my_test2;\" out=\"${pageContext}\"/>
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_53 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_53.setPageContext(pageContext);
                    _jsp_SqlTag_53.setParent(_jsp_ConnectTag_48);
                    _jsp_SqlTag_53.setSql("delete from my_test2;");
                    _jsp_SqlTag_53.setOut(pageContext.getAttribute("pageContext"));
                    int _jsp_start_flag_53 = _jsp_SqlTag_53.doStartTag();

                    if(_jsp_start_flag_53 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_53 != Tag.SKIP_BODY) {
                        _jsp_SqlTag_53.doAfterBody();
                    }
                    _jsp_SqlTag_53.doEndTag();
                    _jsp_SqlTag_53.release();
                    // NODE END: lineNumber: 74, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_53

                    // NODE START: lineNumber: 75, offset: 54, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_55
                    // <sql:execute sql=\"insert into my_test2(my_id, my_code, my_name) values (1, &#39;1&#39;, &#39;1&#39;);\"/>
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_55 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_55.setPageContext(pageContext);
                    _jsp_SqlTag_55.setParent(_jsp_ConnectTag_48);
                    _jsp_SqlTag_55.setSql("insert into my_test2(my_id, my_code, my_name) values (1, \'1\', \'1\');");
                    int _jsp_start_flag_55 = _jsp_SqlTag_55.doStartTag();

                    if(_jsp_start_flag_55 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_55 != Tag.SKIP_BODY) {
                        _jsp_SqlTag_55.doAfterBody();
                    }
                    _jsp_SqlTag_55.doEndTag();
                    _jsp_SqlTag_55.release();
                    // NODE END: lineNumber: 75, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_55

                    // NODE START: lineNumber: 77, offset: 56, length: 20, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_57
                    // <sql:execute out=\"${pageContext}\">...</sql:execute>
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_57 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_57.setPageContext(pageContext);
                    _jsp_SqlTag_57.setParent(_jsp_ConnectTag_48);
                    _jsp_SqlTag_57.setOut(pageContext.getAttribute("pageContext"));
                    int _jsp_start_flag_57 = _jsp_SqlTag_57.doStartTag();

                    if(_jsp_start_flag_57 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_57 != Tag.SKIP_BODY) {
                        int _jsp_flag_57 = 0;
                        if(_jsp_start_flag_57 == BodyTag.EVAL_BODY_BUFFERED) {
                            BodyContent _jsp_body_content_57 = pageContext.pushBody();
                            _jsp_SqlTag_57.setBodyContent(_jsp_body_content_57);
                            _jsp_SqlTag_57.doInitBody();
                            out = _jsp_body_content_57;
                        }

                        do {
                            // NODE START: lineNumber: 78, offset: 57, length: 9, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_58
                            // <c:forEach items=\"1, 2, 3, 4, 5\" var=\"id\">...</c:forEach>
                            Object _jsp_old_var_58 = pageContext.getAttribute("id");
                            com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_58 = new com.skin.ayada.jstl.core.ForEachTag();
                            _jsp_ForEachTag_58.setParent(_jsp_SqlTag_57);
                            _jsp_ForEachTag_58.setPageContext(pageContext);
                            _jsp_ForEachTag_58.setVar("id");
                            _jsp_ForEachTag_58.setItems("1, 2, 3, 4, 5");
                            if(_jsp_ForEachTag_58.doStartTag() != Tag.SKIP_BODY) {
                                while(true) {
                                    // TEXT: lineNumber: 78
                                    // out.write("            insert into my_test1(my_id, my_code, my_name) values (");
                                    out.write(_jsp_string_59, 0, _jsp_string_59.length);
                                    // VARIABLE: lineNumber: 79
                                    expressionContext.print(out, pageContext.getAttribute("id"));
                                    // TEXT: lineNumber: 79
                                    // out.write(", \'");
                                    out.write(_jsp_string_61, 0, _jsp_string_61.length);
                                    // VARIABLE: lineNumber: 79
                                    expressionContext.print(out, pageContext.getAttribute("id"));
                                    // TEXT: lineNumber: 79
                                    // out.write("\', \'");
                                    out.write(_jsp_string_63, 0, _jsp_string_63.length);
                                    // VARIABLE: lineNumber: 79
                                    expressionContext.print(out, pageContext.getAttribute("id"));
                                    // TEXT: lineNumber: 79
                                    // out.write("\');\r\n");
                                    out.write(_jsp_string_65, 0, _jsp_string_65.length);
                                    if(_jsp_ForEachTag_58.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                                        break;
                                    }
                                }
                            }
                            _jsp_ForEachTag_58.release();
                            pageContext.setAttribute("id", _jsp_old_var_58);
                            // jsp.jstl.core.ForEachTag END
                            // NODE END: lineNumber: 78, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_58

                            // NODE START: lineNumber: 81, offset: 66, length: 9, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_67
                            // <c:forEach items=\"1, 2, 3, 4, 5\" var=\"id\">...</c:forEach>
                            Object _jsp_old_var_67 = pageContext.getAttribute("id");
                            com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_67 = new com.skin.ayada.jstl.core.ForEachTag();
                            _jsp_ForEachTag_67.setParent(_jsp_SqlTag_57);
                            _jsp_ForEachTag_67.setPageContext(pageContext);
                            _jsp_ForEachTag_67.setVar("id");
                            _jsp_ForEachTag_67.setItems("1, 2, 3, 4, 5");
                            if(_jsp_ForEachTag_67.doStartTag() != Tag.SKIP_BODY) {
                                while(true) {
                                    // TEXT: lineNumber: 81
                                    // out.write("            insert into my_test2(my_id, my_code, my_name) values (");
                                    out.write(_jsp_string_68, 0, _jsp_string_68.length);
                                    // VARIABLE: lineNumber: 82
                                    expressionContext.print(out, pageContext.getAttribute("id"));
                                    // TEXT: lineNumber: 82
                                    // out.write(", \'");
                                    out.write(_jsp_string_70, 0, _jsp_string_70.length);
                                    // VARIABLE: lineNumber: 82
                                    expressionContext.print(out, pageContext.getAttribute("id"));
                                    // TEXT: lineNumber: 82
                                    // out.write("\', \'");
                                    out.write(_jsp_string_72, 0, _jsp_string_72.length);
                                    // VARIABLE: lineNumber: 82
                                    expressionContext.print(out, pageContext.getAttribute("id"));
                                    // TEXT: lineNumber: 82
                                    // out.write("\');\r\n");
                                    out.write(_jsp_string_74, 0, _jsp_string_74.length);
                                    if(_jsp_ForEachTag_67.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                                        break;
                                    }
                                }
                            }
                            _jsp_ForEachTag_67.release();
                            pageContext.setAttribute("id", _jsp_old_var_67);
                            // jsp.jstl.core.ForEachTag END
                            // NODE END: lineNumber: 81, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_67

                            _jsp_flag_57 = _jsp_SqlTag_57.doAfterBody();
                        }
                        while(_jsp_flag_57 == IterationTag.EVAL_BODY_AGAIN);
                        if(_jsp_start_flag_57 == BodyTag.EVAL_BODY_BUFFERED) {
                            out = pageContext.popBody();
                        }
                    }
                    _jsp_SqlTag_57.doEndTag();
                    _jsp_SqlTag_57.release();
                    // NODE END: lineNumber: 77, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_57

                    // NODE START: lineNumber: 86, offset: 76, length: 3, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_77
                    // <sql:execute out=\"${pageContext.getOut()}\">...</sql:execute>
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_77 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_77.setPageContext(pageContext);
                    _jsp_SqlTag_77.setParent(_jsp_ConnectTag_48);
                    _jsp_SqlTag_77.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext.getOut()}", java.lang.Object.class));
                    int _jsp_start_flag_77 = _jsp_SqlTag_77.doStartTag();

                    if(_jsp_start_flag_77 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_77 != Tag.SKIP_BODY) {
                        int _jsp_flag_77 = 0;
                        if(_jsp_start_flag_77 == BodyTag.EVAL_BODY_BUFFERED) {
                            BodyContent _jsp_body_content_77 = pageContext.pushBody();
                            _jsp_SqlTag_77.setBodyContent(_jsp_body_content_77);
                            _jsp_SqlTag_77.doInitBody();
                            out = _jsp_body_content_77;
                        }

                        do {
                            // TEXT: lineNumber: 86
                            // out.write("        delete from my_test2;\r\n        insert into my_test2(my_id, my_code, my_name) values (1001, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1002, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1003, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1004, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1005, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1006, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1007, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1008, \'1001\', \'1001\');\r\n");
                            out.write(_jsp_string_78, 0, _jsp_string_78.length);
                            _jsp_flag_77 = _jsp_SqlTag_77.doAfterBody();
                        }
                        while(_jsp_flag_77 == IterationTag.EVAL_BODY_AGAIN);
                        if(_jsp_start_flag_77 == BodyTag.EVAL_BODY_BUFFERED) {
                            out = pageContext.popBody();
                        }
                    }
                    _jsp_SqlTag_77.doEndTag();
                    _jsp_SqlTag_77.release();
                    // NODE END: lineNumber: 86, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_77

                    // NODE START: lineNumber: 98, offset: 79, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_80
                    // <sql:execute connection=\"${connection}\" sql=\"insert into my_test2(my_id, my_code, my_name) values (1009, &#39;1001&#39;, &#39;1001&#39;);\"/>
                    com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_80 = new com.skin.ayada.jstl.sql.SqlTag();
                    _jsp_SqlTag_80.setPageContext(pageContext);
                    _jsp_SqlTag_80.setParent(_jsp_ConnectTag_48);
                    _jsp_SqlTag_80.setConnection(pageContext.getValue("connection", java.sql.Connection.class));
                    _jsp_SqlTag_80.setSql("insert into my_test2(my_id, my_code, my_name) values (1009, \'1001\', \'1001\');");
                    int _jsp_start_flag_80 = _jsp_SqlTag_80.doStartTag();

                    if(_jsp_start_flag_80 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_80 != Tag.SKIP_BODY) {
                        _jsp_SqlTag_80.doAfterBody();
                    }
                    _jsp_SqlTag_80.doEndTag();
                    _jsp_SqlTag_80.release();
                    // NODE END: lineNumber: 98, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_80

                    // TEXT: lineNumber: 98
                    // out.write("    <table>\r\n        <tr>\r\n            <td>id</td>\r\n            <td>userName</td>\r\n            <td>nickName</td>\r\n        </tr>\r\n");
                    out.write(_jsp_string_82, 0, _jsp_string_82.length);

                    // NODE START: lineNumber: 105, offset: 82, length: 9, tagClassName: com.skin.ayada.jstl.sql.QueryTag, tagInstanceName: _jsp_QueryTag_83
                    // <sql:query var=\"resultSet\" sql=\"select * from my_test2 where my_id &gt; 1001\" offset=\"2\" length=\"3\">...</sql:query>
                    com.skin.ayada.jstl.sql.QueryTag _jsp_QueryTag_83 = new com.skin.ayada.jstl.sql.QueryTag();
                    try {
                        _jsp_QueryTag_83.setPageContext(pageContext);
                        _jsp_QueryTag_83.setParent(_jsp_ConnectTag_48);
                        _jsp_QueryTag_83.setVar("resultSet");
                        _jsp_QueryTag_83.setSql("select * from my_test2 where my_id > 1001");
                        _jsp_QueryTag_83.setOffset(2);
                        _jsp_QueryTag_83.setLength(3);
                        int _jsp_start_flag_83 = _jsp_QueryTag_83.doStartTag();

                        if(_jsp_start_flag_83 == Tag.SKIP_PAGE) {
                            return;
                        }
                        if(_jsp_start_flag_83 != Tag.SKIP_BODY) {
                            int _jsp_flag_83 = 0;

                            do {
                                // TEXT: lineNumber: 105
                                // out.write("        <tr>\r\n            <td>");
                                out.write(_jsp_string_84, 0, _jsp_string_84.length);
                                // EXPRESSION: lineNumber: 107
                                expressionContext.print(out, expressionContext.getString("resultSet.getLong(\"my_id\")"));
                                // TEXT: lineNumber: 107
                                // out.write("</td>\r\n            <td>");
                                out.write(_jsp_string_86, 0, _jsp_string_86.length);
                                // EXPRESSION: lineNumber: 108
                                expressionContext.print(out, expressionContext.getString("resultSet.getString(\"my_code\")"));
                                // TEXT: lineNumber: 108
                                // out.write("</td>\r\n            <td>");
                                out.write(_jsp_string_88, 0, _jsp_string_88.length);
                                // EXPRESSION: lineNumber: 109
                                expressionContext.print(out, expressionContext.getString("resultSet.getString(\"my_name\")"));
                                // TEXT: lineNumber: 109
                                // out.write("</td>\r\n        </tr>\r\n");
                                out.write(_jsp_string_90, 0, _jsp_string_90.length);
                                _jsp_flag_83 = _jsp_QueryTag_83.doAfterBody();
                            }
                            while(_jsp_flag_83 == IterationTag.EVAL_BODY_AGAIN);
                        }
                        _jsp_QueryTag_83.doEndTag();
                        _jsp_QueryTag_83.release();
                    }
                    catch(Throwable throwable) {
                        try {
                            _jsp_QueryTag_83.doCatch(throwable);
                        } catch (Throwable t) {
                            throw new Exception(t);
                        }
                    }
                    finally {
                        _jsp_QueryTag_83.doFinally();
                    }
                    // NODE END: lineNumber: 105, tagClassName: com.skin.ayada.jstl.sql.QueryTag, tagInstanceName: _jsp_QueryTag_83

                    // TEXT: lineNumber: 111
                    // out.write("    </table>\r\n");
                    out.write(_jsp_string_92, 0, _jsp_string_92.length);
                    _jsp_flag_48 = _jsp_ConnectTag_48.doAfterBody();
                }
                while(_jsp_flag_48 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_ConnectTag_48.doEndTag();
            _jsp_ConnectTag_48.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_ConnectTag_48.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_ConnectTag_48.doFinally();
        }
        // NODE END: lineNumber: 71, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_48


        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_3 = "<!--\r\nt:import: 编译指令\r\n1. 可以放在任何位置, 但必须在使用之前引入\r\n2. 如果多次引入同一个tag, tag的bodyContent以最后一次引入的为准, 引擎在编译结束之后才会根据bodyContent的类型做一次紧缩处理\r\n   bodyContent: jsp|tagdependent|empty\r\n   如果是tagdependent, 那么该tag内部的所有文本节点和表达式节点都会被清除, 其子节点的内容不会清除(但是会根据子节点的bodyContent决定是否清除)\r\n   如果是empty, 那么内部的任何节点都会被清除\r\n   如果是jsp, 则保持现有内容不变\r\n   因此所有的引入操作最好放在文件头, 并且对同一个tag只引入一次\r\n\r\n3. className不是必选项, 可以为空, 如果为空则使用ayada-taglib-default.xml或者ayada-taglib.xml文件中配置的className, 因此下面的两种写法都是合法的\r\n4. bodyContent和description都不是必选项, 可以为空, bodyContent默认为jsp\r\n-->\r\n<h1>tag.bodyContent</h1>\r\n<p>1. jsp: any content</p>\r\n<p>2. tagdependent: tag only</p>\r\n<p>3. empty: ignore any content</p>\r\n\r\n<!-- 使用重新定义的c:if标签, 该标签内部的所有文本内容在编译期都会被清除, 但是自标签的文本仍然可以输出 -->\r\n".toCharArray();
    public static final char[] _jsp_string_6 = "\"I\'m here !\"".toCharArray();
    public static final char[] _jsp_string_9 = "<!-- c:command的bodyContent被定义为tagdependent，因此内部的文本内容都会被忽略。-->\r\n".toCharArray();
    public static final char[] _jsp_string_26 = "<h1>sql:execute</h1>\r\n<h2>connection</h2>\r\n<p>1. get from attribute, example: connection=\"${expression}\"</p>\r\n<p>2. get from pageContext by name: connection</p>\r\n<p>3. get from parent tag</p>\r\n<p>4. throws exception</p>\r\n<p>template.home: ".toCharArray();
    public static final char[] _jsp_string_28 = "</p>\r\n\r\n<!-- use external connection -->\r\n".toCharArray();
    public static final char[] _jsp_string_45 = "        drop database if exists mytest2;\r\n        create database mytest2 character set utf8;\r\n".toCharArray();
    public static final char[] _jsp_string_59 = "            insert into my_test1(my_id, my_code, my_name) values (".toCharArray();
    public static final char[] _jsp_string_61 = ", \'".toCharArray();
    public static final char[] _jsp_string_63 = "\', \'".toCharArray();
    public static final char[] _jsp_string_65 = "\');\r\n".toCharArray();
    public static final char[] _jsp_string_68 = "            insert into my_test2(my_id, my_code, my_name) values (".toCharArray();
    public static final char[] _jsp_string_70 = ", \'".toCharArray();
    public static final char[] _jsp_string_72 = "\', \'".toCharArray();
    public static final char[] _jsp_string_74 = "\');\r\n".toCharArray();
    public static final char[] _jsp_string_78 = "        delete from my_test2;\r\n        insert into my_test2(my_id, my_code, my_name) values (1001, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1002, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1003, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1004, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1005, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1006, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1007, \'1001\', \'1001\');\r\n        insert into my_test2(my_id, my_code, my_name) values (1008, \'1001\', \'1001\');\r\n".toCharArray();
    public static final char[] _jsp_string_82 = "    <table>\r\n        <tr>\r\n            <td>id</td>\r\n            <td>userName</td>\r\n            <td>nickName</td>\r\n        </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_84 = "        <tr>\r\n            <td>".toCharArray();
    public static final char[] _jsp_string_86 = "</td>\r\n            <td>".toCharArray();
    public static final char[] _jsp_string_88 = "</td>\r\n            <td>".toCharArray();
    public static final char[] _jsp_string_90 = "</td>\r\n        </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_92 = "    </table>\r\n".toCharArray();

}
