/*
 * $RCSfile: CsvTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-02-01 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: csvTest.jsp
 * lastModified: 2016-02-01 22:59:16 129
 * options: -fastJstl true
 * template.dependencies
 * -- /csvTest.jsp
 *
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-02-01 22:59:23 995)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: CsvTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class CsvTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        CsvTestTemplate template = new CsvTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 3, tagClassName: com.skin.ayada.jstl.core.BufferTag, tagInstanceName: _jsp_BufferTag_1
        // <c:buffer var=\"csvContent\">...</c:buffer>
        com.skin.ayada.jstl.core.BufferTag _jsp_BufferTag_1 = new com.skin.ayada.jstl.core.BufferTag();
        _jsp_BufferTag_1.setPageContext(pageContext);
        _jsp_BufferTag_1.setParent((Tag)null);
        _jsp_BufferTag_1.setVar("csvContent");
        int _jsp_start_flag_1 = _jsp_BufferTag_1.doStartTag();

        if(_jsp_start_flag_1 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_1 != Tag.SKIP_BODY) {
            int _jsp_flag_1 = 0;
            if(_jsp_start_flag_1 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_1 = pageContext.pushBody();
                _jsp_BufferTag_1.setBodyContent(_jsp_body_content_1);
                _jsp_BufferTag_1.doInitBody();
                out = _jsp_body_content_1;
            }

            do {
                // TEXT: lineNumber: 1
                // out.write("id, userName, password, sex, birthday\r\n1,\"test1\", \"1234\", 1, \"2000-01-01\"\r\n2,\"test2\", \"1234\", 1, \"2000-01-01\"\r\n");
                out.write(_jsp_string_2, 0, _jsp_string_2.length);
                _jsp_flag_1 = _jsp_BufferTag_1.doAfterBody();
            }
            while(_jsp_flag_1 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_1 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_BufferTag_1.doEndTag();
        _jsp_BufferTag_1.release();
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.BufferTag, tagInstanceName: _jsp_BufferTag_1

        // TEXT: lineNumber: 5
        // out.write("\r\n# 1\r\n");
        out.write(_jsp_string_4, 0, _jsp_string_4.length);

        // NODE START: lineNumber: 8, offset: 4, length: 5, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_5
        // <csv:each content=\"${csvContent}\" var=\"dataSet\">...</csv:each>
        com.skin.ayada.jstl.csv.CSVTag _jsp_CSVTag_5 = new com.skin.ayada.jstl.csv.CSVTag();
        try {
            _jsp_CSVTag_5.setPageContext(pageContext);
            _jsp_CSVTag_5.setParent((Tag)null);
            _jsp_CSVTag_5.setContent(pageContext.getString("csvContent"));
            _jsp_CSVTag_5.setVar("dataSet");
            int _jsp_start_flag_5 = _jsp_CSVTag_5.doStartTag();

            if(_jsp_start_flag_5 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_5 != Tag.SKIP_BODY) {
                int _jsp_flag_5 = 0;

                do {
                    // TEXT: lineNumber: 8
                    // out.write("    ");
                    out.write(_jsp_string_6, 0, _jsp_string_6.length);
                    // EXPRESSION: lineNumber: 9
                    out.write(expressionContext.getString("dataSet.getInsert(\"user\")"));
                    // TEXT: lineNumber: 9
                    // out.write("\r\n");
                    out.write(_jsp_string_8, 0, _jsp_string_8.length);
                    _jsp_flag_5 = _jsp_CSVTag_5.doAfterBody();
                }
                while(_jsp_flag_5 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_CSVTag_5.doEndTag();
            _jsp_CSVTag_5.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_CSVTag_5.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_CSVTag_5.doFinally();
        }
        // NODE END: lineNumber: 8, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_5

        // TEXT: lineNumber: 10
        // out.write("\r\n# 2\r\n");
        out.write(_jsp_string_10, 0, _jsp_string_10.length);

        // NODE START: lineNumber: 13, offset: 10, length: 6, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_11
        // <csv:each content=\"${csvContent}\" var=\"dataSet\">...</csv:each>
        com.skin.ayada.jstl.csv.CSVTag _jsp_CSVTag_11 = new com.skin.ayada.jstl.csv.CSVTag();
        try {
            _jsp_CSVTag_11.setPageContext(pageContext);
            _jsp_CSVTag_11.setParent((Tag)null);
            _jsp_CSVTag_11.setContent(pageContext.getString("csvContent"));
            _jsp_CSVTag_11.setVar("dataSet");
            int _jsp_start_flag_11 = _jsp_CSVTag_11.doStartTag();

            if(_jsp_start_flag_11 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_11 != Tag.SKIP_BODY) {
                int _jsp_flag_11 = 0;

                do {
                    // TEXT: lineNumber: 13
                    // out.write("    ");
                    out.write(_jsp_string_12, 0, _jsp_string_12.length);

                    // NODE START: lineNumber: 14, offset: 12, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_13
                    // <c:out value=\"${dataSet.getInsert(&#39;user&#39;)}\"/>
                    com.skin.ayada.jstl.core.OutTag.write(out, ExpressionUtil.evaluate(expressionContext, "${dataSet.getInsert(\'user\')}", null), false);
                    // out.print(ExpressionUtil.getString(expressionContext, "${dataSet.getInsert(\'user\')}"));
                    // jsp.jstl.core.OutTag END
                    // NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_13

                    // TEXT: lineNumber: 14
                    // out.write("\r\n");
                    out.write(_jsp_string_15, 0, _jsp_string_15.length);
                    _jsp_flag_11 = _jsp_CSVTag_11.doAfterBody();
                }
                while(_jsp_flag_11 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_CSVTag_11.doEndTag();
            _jsp_CSVTag_11.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_CSVTag_11.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_CSVTag_11.doFinally();
        }
        // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_11

        // TEXT: lineNumber: 15
        // out.write("\r\n# 3\r\n");
        out.write(_jsp_string_17, 0, _jsp_string_17.length);

        // NODE START: lineNumber: 18, offset: 17, length: 6, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_18
        // <csv:each content=\"${csvContent}\" var=\"dataSet\">...</csv:each>
        com.skin.ayada.jstl.csv.CSVTag _jsp_CSVTag_18 = new com.skin.ayada.jstl.csv.CSVTag();
        try {
            _jsp_CSVTag_18.setPageContext(pageContext);
            _jsp_CSVTag_18.setParent((Tag)null);
            _jsp_CSVTag_18.setContent(pageContext.getString("csvContent"));
            _jsp_CSVTag_18.setVar("dataSet");
            int _jsp_start_flag_18 = _jsp_CSVTag_18.doStartTag();

            if(_jsp_start_flag_18 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_18 != Tag.SKIP_BODY) {
                int _jsp_flag_18 = 0;

                do {
                    // TEXT: lineNumber: 18
                    // out.write("    ");
                    out.write(_jsp_string_19, 0, _jsp_string_19.length);

                    // NODE START: lineNumber: 19, offset: 19, length: 2, tagClassName: com.skin.ayada.jstl.csv.DataSetTag, tagInstanceName: _jsp_DataSetTag_20
                    // <csv:dataSet value=\"${dataSet}\" tableName=\"user\"/>
                    com.skin.ayada.jstl.csv.DataSetTag _jsp_DataSetTag_20 = new com.skin.ayada.jstl.csv.DataSetTag();
                    _jsp_DataSetTag_20.setPageContext(pageContext);
                    _jsp_DataSetTag_20.setParent(_jsp_CSVTag_18);
                    _jsp_DataSetTag_20.setValue(pageContext.getAttribute("dataSet"));
                    _jsp_DataSetTag_20.setTableName("user");
                    int _jsp_start_flag_20 = _jsp_DataSetTag_20.doStartTag();

                    if(_jsp_start_flag_20 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_20 != Tag.SKIP_BODY) {
                        _jsp_DataSetTag_20.doAfterBody();
                    }
                    _jsp_DataSetTag_20.doEndTag();
                    _jsp_DataSetTag_20.release();
                    // NODE END: lineNumber: 19, tagClassName: com.skin.ayada.jstl.csv.DataSetTag, tagInstanceName: _jsp_DataSetTag_20

                    // TEXT: lineNumber: 19
                    // out.write("\r\n");
                    out.write(_jsp_string_22, 0, _jsp_string_22.length);
                    _jsp_flag_18 = _jsp_CSVTag_18.doAfterBody();
                }
                while(_jsp_flag_18 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_CSVTag_18.doEndTag();
            _jsp_CSVTag_18.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_CSVTag_18.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_CSVTag_18.doFinally();
        }
        // NODE END: lineNumber: 18, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_18

        // TEXT: lineNumber: 20
        // out.write("\r\n# 4\r\n");
        out.write(_jsp_string_24, 0, _jsp_string_24.length);

        // NODE START: lineNumber: 23, offset: 24, length: 5, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_25
        // <csv:each content=\"${csvContent}\" var=\"dataSet\">...</csv:each>
        com.skin.ayada.jstl.csv.CSVTag _jsp_CSVTag_25 = new com.skin.ayada.jstl.csv.CSVTag();
        try {
            _jsp_CSVTag_25.setPageContext(pageContext);
            _jsp_CSVTag_25.setParent((Tag)null);
            _jsp_CSVTag_25.setContent(pageContext.getString("csvContent"));
            _jsp_CSVTag_25.setVar("dataSet");
            int _jsp_start_flag_25 = _jsp_CSVTag_25.doStartTag();

            if(_jsp_start_flag_25 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_25 != Tag.SKIP_BODY) {
                int _jsp_flag_25 = 0;

                do {
                    // NODE START: lineNumber: 24, offset: 25, length: 3, tagClassName: com.skin.ayada.jstl.csv.DataSetTag, tagInstanceName: _jsp_DataSetTag_26
                    // <csv:dataSet value=\"${dataSet}\">...</csv:dataSet>
                    com.skin.ayada.jstl.csv.DataSetTag _jsp_DataSetTag_26 = new com.skin.ayada.jstl.csv.DataSetTag();
                    _jsp_DataSetTag_26.setPageContext(pageContext);
                    _jsp_DataSetTag_26.setParent(_jsp_CSVTag_25);
                    _jsp_DataSetTag_26.setValue(pageContext.getAttribute("dataSet"));
                    int _jsp_start_flag_26 = _jsp_DataSetTag_26.doStartTag();

                    if(_jsp_start_flag_26 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_26 != Tag.SKIP_BODY) {
                        int _jsp_flag_26 = 0;
                        if(_jsp_start_flag_26 == BodyTag.EVAL_BODY_BUFFERED) {
                            BodyContent _jsp_body_content_26 = pageContext.pushBody();
                            _jsp_DataSetTag_26.setBodyContent(_jsp_body_content_26);
                            _jsp_DataSetTag_26.doInitBody();
                            out = _jsp_body_content_26;
                        }

                        do {
                            // TEXT: lineNumber: 24
                            // out.write("    insert into user(id, userName, password, sex, birthday) values (${id}, \'${userName}\', \'${password}\', ${sex}, \'${birthday}\');\r\n");
                            out.write(_jsp_string_27, 0, _jsp_string_27.length);
                            _jsp_flag_26 = _jsp_DataSetTag_26.doAfterBody();
                        }
                        while(_jsp_flag_26 == IterationTag.EVAL_BODY_AGAIN);
                        if(_jsp_start_flag_26 == BodyTag.EVAL_BODY_BUFFERED) {
                            out = pageContext.popBody();
                        }
                    }
                    _jsp_DataSetTag_26.doEndTag();
                    _jsp_DataSetTag_26.release();
                    // NODE END: lineNumber: 24, tagClassName: com.skin.ayada.jstl.csv.DataSetTag, tagInstanceName: _jsp_DataSetTag_26

                    _jsp_flag_25 = _jsp_CSVTag_25.doAfterBody();
                }
                while(_jsp_flag_25 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_CSVTag_25.doEndTag();
            _jsp_CSVTag_25.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_CSVTag_25.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_CSVTag_25.doFinally();
        }
        // NODE END: lineNumber: 23, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_25

        // TEXT: lineNumber: 27
        // out.write("\r\n# 5\r\n");
        out.write(_jsp_string_30, 0, _jsp_string_30.length);

        // NODE START: lineNumber: 30, offset: 30, length: 5, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_31
        // <csv:each file=\"webapp/test.csv\" var=\"dataSet\">...</csv:each>
        com.skin.ayada.jstl.csv.CSVTag _jsp_CSVTag_31 = new com.skin.ayada.jstl.csv.CSVTag();
        try {
            _jsp_CSVTag_31.setPageContext(pageContext);
            _jsp_CSVTag_31.setParent((Tag)null);
            _jsp_CSVTag_31.setFile("webapp/test.csv");
            _jsp_CSVTag_31.setVar("dataSet");
            int _jsp_start_flag_31 = _jsp_CSVTag_31.doStartTag();

            if(_jsp_start_flag_31 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_31 != Tag.SKIP_BODY) {
                int _jsp_flag_31 = 0;

                do {
                    // NODE START: lineNumber: 31, offset: 31, length: 3, tagClassName: com.skin.ayada.jstl.csv.DataSetTag, tagInstanceName: _jsp_DataSetTag_32
                    // <csv:dataSet value=\"${dataSet}\">...</csv:dataSet>
                    com.skin.ayada.jstl.csv.DataSetTag _jsp_DataSetTag_32 = new com.skin.ayada.jstl.csv.DataSetTag();
                    _jsp_DataSetTag_32.setPageContext(pageContext);
                    _jsp_DataSetTag_32.setParent(_jsp_CSVTag_31);
                    _jsp_DataSetTag_32.setValue(pageContext.getAttribute("dataSet"));
                    int _jsp_start_flag_32 = _jsp_DataSetTag_32.doStartTag();

                    if(_jsp_start_flag_32 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_32 != Tag.SKIP_BODY) {
                        int _jsp_flag_32 = 0;
                        if(_jsp_start_flag_32 == BodyTag.EVAL_BODY_BUFFERED) {
                            BodyContent _jsp_body_content_32 = pageContext.pushBody();
                            _jsp_DataSetTag_32.setBodyContent(_jsp_body_content_32);
                            _jsp_DataSetTag_32.doInitBody();
                            out = _jsp_body_content_32;
                        }

                        do {
                            // TEXT: lineNumber: 31
                            // out.write("    insert into user(id, userName, password, sex, birthday) values (${id}, \'${userName}\', \'${password}\', ${sex}, \'${birthday}\');\r\n");
                            out.write(_jsp_string_33, 0, _jsp_string_33.length);
                            _jsp_flag_32 = _jsp_DataSetTag_32.doAfterBody();
                        }
                        while(_jsp_flag_32 == IterationTag.EVAL_BODY_AGAIN);
                        if(_jsp_start_flag_32 == BodyTag.EVAL_BODY_BUFFERED) {
                            out = pageContext.popBody();
                        }
                    }
                    _jsp_DataSetTag_32.doEndTag();
                    _jsp_DataSetTag_32.release();
                    // NODE END: lineNumber: 31, tagClassName: com.skin.ayada.jstl.csv.DataSetTag, tagInstanceName: _jsp_DataSetTag_32

                    _jsp_flag_31 = _jsp_CSVTag_31.doAfterBody();
                }
                while(_jsp_flag_31 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_CSVTag_31.doEndTag();
            _jsp_CSVTag_31.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_CSVTag_31.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_CSVTag_31.doFinally();
        }
        // NODE END: lineNumber: 30, tagClassName: com.skin.ayada.jstl.csv.CSVTag, tagInstanceName: _jsp_CSVTag_31

        // TEXT: lineNumber: 34
        // out.write("\r\n# 6\r\n<--\r\n可以配合 sql:execute标签直接执行导入到数据库, 关于sql:execute请参考commandTest.jsp\r\n数据导入导出请参考另一个开源项目: exchange, 支持从任意数据库导出任意格式的文件, 或者从已经导出的数据文件导入到任意数据库。\r\n-->\r\n<!-- sql:execute sql=\"${dataSet.getInsert(\"user\")}\"/ -->");
        out.write(_jsp_string_36, 0, _jsp_string_36.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_2 = "id, userName, password, sex, birthday\r\n1,\"test1\", \"1234\", 1, \"2000-01-01\"\r\n2,\"test2\", \"1234\", 1, \"2000-01-01\"\r\n".toCharArray();
    public static final char[] _jsp_string_4 = "\r\n# 1\r\n".toCharArray();
    public static final char[] _jsp_string_6 = "    ".toCharArray();
    public static final char[] _jsp_string_8 = "\r\n".toCharArray();
    public static final char[] _jsp_string_10 = "\r\n# 2\r\n".toCharArray();
    public static final char[] _jsp_string_12 = "    ".toCharArray();
    public static final char[] _jsp_string_15 = "\r\n".toCharArray();
    public static final char[] _jsp_string_17 = "\r\n# 3\r\n".toCharArray();
    public static final char[] _jsp_string_19 = "    ".toCharArray();
    public static final char[] _jsp_string_22 = "\r\n".toCharArray();
    public static final char[] _jsp_string_24 = "\r\n# 4\r\n".toCharArray();
    public static final char[] _jsp_string_27 = "    insert into user(id, userName, password, sex, birthday) values (${id}, \'${userName}\', \'${password}\', ${sex}, \'${birthday}\');\r\n".toCharArray();
    public static final char[] _jsp_string_30 = "\r\n# 5\r\n".toCharArray();
    public static final char[] _jsp_string_33 = "    insert into user(id, userName, password, sex, birthday) values (${id}, \'${userName}\', \'${password}\', ${sex}, \'${birthday}\');\r\n".toCharArray();
    public static final char[] _jsp_string_36 = "\r\n# 6\r\n<--\r\n可以配合 sql:execute标签直接执行导入到数据库, 关于sql:execute请参考commandTest.jsp\r\n数据导入导出请参考另一个开源项目: exchange, 支持从任意数据库导出任意格式的文件, 或者从已经导出的数据文件导入到任意数据库。\r\n-->\r\n<!-- sql:execute sql=\"${dataSet.getInsert(\"user\")}\"/ -->".toCharArray();

}
