/*
 * $RCSfile: EachTest1Template.java,v $$
 * $Revision: 1.1 $
 * $Date: 2017-02-09 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /eachTest1.jsp
 * lastModified: 2013-11-29 14:18:06 000
 * options: -fastJstl true
 * template.dependencies
 * -- /eachTest1.jsp
 *
 * JSP generated by JspCompiler-1.0.1.4 (built 2017-02-09 00:51:29 899)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: EachTest1Template</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class EachTest1Template extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        EachTest1Template template = new EachTest1Template();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html;charset=UTF-8"/>

        // NODE START: lineNumber: 2, offset: 2, length: 2, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_3
        // <c:list name=\"userList\"/>
        com.skin.ayada.jstl.core.ListTag _jsp_ListTag_3 = new com.skin.ayada.jstl.core.ListTag();
        try {
            _jsp_ListTag_3.setPageContext(pageContext);
            _jsp_ListTag_3.setParent((Tag)null);
            _jsp_ListTag_3.setName("userList");
            int _jsp_start_flag_3 = _jsp_ListTag_3.doStartTag();

            if(_jsp_start_flag_3 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_3 != Tag.SKIP_BODY) {
                _jsp_ListTag_3.doAfterBody();
            }
            _jsp_ListTag_3.doEndTag();
        }
        finally {
            this.doFinally(_jsp_ListTag_3);
        }
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_3

        // TEXT: lineNumber: 2
        // out.write("\r\n");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);

        // NODE START: lineNumber: 4, offset: 5, length: 11, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_6
        // <c:forEach begin=\"1\" end=\"5\" step=\"1\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_status_6 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_6 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_6.setParent((Tag)null);
        _jsp_ForEachTag_6.setPageContext(pageContext);
        _jsp_ForEachTag_6.setBegin(1);
        _jsp_ForEachTag_6.setEnd(5);
        _jsp_ForEachTag_6.setStep(1);
        _jsp_ForEachTag_6.setVarStatus("status");
        if(_jsp_ForEachTag_6.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // NODE START: lineNumber: 5, offset: 6, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_7
                // <c:map name=\"user\">...</c:map>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_7 = new com.skin.ayada.jstl.core.MapTag();
                try {
                    _jsp_MapTag_7.setPageContext(pageContext);
                    _jsp_MapTag_7.setParent((Tag)null);
                    _jsp_MapTag_7.setDynamicAttribute("name", "user");
                    int _jsp_start_flag_7 = _jsp_MapTag_7.doStartTag();

                    if(_jsp_start_flag_7 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_7 != Tag.SKIP_BODY) {
                        int _jsp_flag_7 = 0;

                        do {
                        // NODE START: lineNumber: 6, offset: 7, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_8
                        // <c:entry name=\"userName\" value=\"ayada${status.index}\"/>
                        _jsp_MapTag_7.setAttribute("userName", ExpressionUtil.evaluate(expressionContext, "ayada${status.index}", null));
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 6, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_8

                        // NODE START: lineNumber: 7, offset: 9, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_10
                        // <c:entry name=\"nickName\" value=\"ayada${status.index}\"/>
                        _jsp_MapTag_7.setAttribute("nickName", ExpressionUtil.evaluate(expressionContext, "ayada${status.index}", null));
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 7, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_10

                            _jsp_flag_7 = _jsp_MapTag_7.doAfterBody();
                        }
                        while(_jsp_flag_7 == IterationTag.EVAL_BODY_AGAIN);
                    }
                    _jsp_MapTag_7.doEndTag();
                }
                finally {
                    this.doFinally(_jsp_MapTag_7);
                }
                // NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_7

                // TEXT: lineNumber: 8
                // out.write("\r\n");
                out.write(_jsp_string_13, 0, _jsp_string_13.length);

                // NODE START: lineNumber: 10, offset: 13, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_14
                // <c:execute value=\"${userList.add(user)}\"/>
                ExpressionUtil.evaluate(expressionContext, "${userList.add(user)}", null);
                // jsp.jstl.core.ExecuteTag END
                // NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_14

                if(_jsp_ForEachTag_6.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_6.release();
        pageContext.setAttribute("status", _jsp_old_var_status_6);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_6

        // TEXT: lineNumber: 11
        // out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n<title>test</title>\r\n<meta http-equiv=\"Pragma\" content=\"no-cache\"/> \r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/> \r\n<meta http-equiv=\"Expires\" content=\"0\"/>\r\n</head>\r\n<body version=\"1.0\">\r\n");
        out.write(_jsp_string_17, 0, _jsp_string_17.length);

        // NODE START: lineNumber: 22, offset: 17, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_18
        // <c:set var=\"rows\" value=\"${((userList.size() + 1) / 2).intValue()}\"/>
        pageContext.setAttribute("rows", ExpressionUtil.evaluate(expressionContext, "${((userList.size() + 1) / 2).intValue()}", null));
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 22, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_18

        // TEXT: lineNumber: 22
        // out.write("<table>\r\n");
        out.write(_jsp_string_20, 0, _jsp_string_20.length);

        // NODE START: lineNumber: 24, offset: 20, length: 21, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_21
        // <c:forEach items=\"${userList}\" var=\"user\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_21 = pageContext.getAttribute("user");
        Object _jsp_old_var_status_21 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_21 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_21.setParent((Tag)null);
        _jsp_ForEachTag_21.setPageContext(pageContext);
        _jsp_ForEachTag_21.setVar("user");
        _jsp_ForEachTag_21.setItems(pageContext.getAttribute("userList"));
        _jsp_ForEachTag_21.setVarStatus("status");
        if(_jsp_ForEachTag_21.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // NODE START: lineNumber: 25, offset: 21, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_22
                // <c:set var=\"rowNum\" value=\"${((status.index + 2) / 2).intValue()}\"/>
                pageContext.setAttribute("rowNum", ExpressionUtil.evaluate(expressionContext, "${((status.index + 2) / 2).intValue()}", null));
                // jsp.jstl.core.SetTag END
                // NODE END: lineNumber: 25, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_22

                // NODE START: lineNumber: 26, offset: 23, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_24
                // <c:if test=\"${(status.index) % 2 == 0}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${(status.index) % 2 == 0}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 26, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_24

                // NODE START: lineNumber: 27, offset: 25, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_26
                // <c:if test=\"${rowNum &lt; rows}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${rowNum < rows}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_26

                // NODE START: lineNumber: 27, offset: 27, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_28
                // <c:if test=\"${rowNum &gt;= rows}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${rowNum >= rows}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_28

                // TEXT: lineNumber: 27
                // out.write("            <div>status:</div>\r\n            <div>rows: ");
                out.write(_jsp_string_30, 0, _jsp_string_30.length);
                // VARIABLE: lineNumber: 29
                expressionContext.print(out, pageContext.getAttribute("rows"));
                // TEXT: lineNumber: 29
                // out.write(", rowNum: ");
                out.write(_jsp_string_32, 0, _jsp_string_32.length);
                // VARIABLE: lineNumber: 29
                expressionContext.print(out, pageContext.getAttribute("rowNum"));
                // TEXT: lineNumber: 29
                // out.write(", status.index: ");
                out.write(_jsp_string_34, 0, _jsp_string_34.length);
                // EXPRESSION: lineNumber: 29
                expressionContext.print(out, expressionContext.getString("status.index"));
                // TEXT: lineNumber: 29
                // out.write(": user.userName: ");
                out.write(_jsp_string_36, 0, _jsp_string_36.length);
                // EXPRESSION: lineNumber: 29
                expressionContext.print(out, expressionContext.getString("user.userName"));
                // TEXT: lineNumber: 29
                // out.write("</div>\r\n        </td>\r\n        <td align=\"center\">test</td>\r\n");
                out.write(_jsp_string_38, 0, _jsp_string_38.length);

                // NODE START: lineNumber: 32, offset: 38, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_39
                // <c:if test=\"${(status.index + 1) % 2 == 0}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${(status.index + 1) % 2 == 0}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 32, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_39

                if(_jsp_ForEachTag_21.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_21.release();
        pageContext.setAttribute("user", _jsp_old_var_21);
        pageContext.setAttribute("status", _jsp_old_var_status_21);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 24, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_21

        // TEXT: lineNumber: 33
        // out.write("</table>\r\n</body>\r\n</html>");
        out.write(_jsp_string_42, 0, _jsp_string_42.length);

        out.flush();
        jspWriter.flush();
    }

    protected static final char[] _jsp_string_5 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_13 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_17 = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n<title>test</title>\r\n<meta http-equiv=\"Pragma\" content=\"no-cache\"/> \r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/> \r\n<meta http-equiv=\"Expires\" content=\"0\"/>\r\n</head>\r\n<body version=\"1.0\">\r\n".toCharArray();
    protected static final char[] _jsp_string_20 = "<table>\r\n".toCharArray();
    protected static final char[] _jsp_string_30 = "            <div>status:</div>\r\n            <div>rows: ".toCharArray();
    protected static final char[] _jsp_string_32 = ", rowNum: ".toCharArray();
    protected static final char[] _jsp_string_34 = ", status.index: ".toCharArray();
    protected static final char[] _jsp_string_36 = ": user.userName: ".toCharArray();
    protected static final char[] _jsp_string_38 = "</div>\r\n        </td>\r\n        <td align=\"center\">test</td>\r\n".toCharArray();
    protected static final char[] _jsp_string_42 = "</table>\r\n</body>\r\n</html>".toCharArray();

}
