/*
 * $RCSfile: EachTest2Template.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-14 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /eachTest2.jsp
 * lastModified: 2014-06-12 10:55:06 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-14 23:17:01 467)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: EachTest2Template</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class EachTest2Template extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        EachTest2Template template = new EachTest2Template();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html;charset=UTF-8"/>

        // NODE START: lineNumber: 2, offset: 2, length: 2, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_3
        // <c:list name=\"userList\"/>
        com.skin.ayada.jstl.core.ListTag _jsp_ListTag_3 = new com.skin.ayada.jstl.core.ListTag();
        _jsp_ListTag_3.setPageContext(pageContext);
        _jsp_ListTag_3.setParent((Tag)null);
        _jsp_ListTag_3.setName("userList");
        int _jsp_start_flag_3 = _jsp_ListTag_3.doStartTag();

        if(_jsp_start_flag_3 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_3 != Tag.SKIP_BODY) {
            _jsp_ListTag_3.doAfterBody();
        }
        _jsp_ListTag_3.doEndTag();
        _jsp_ListTag_3.release();
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_3

        // TEXT: lineNumber: 2
        // out.write("\r\n");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);

        // NODE START: lineNumber: 4, offset: 5, length: 11, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_6
        // <c:forEach begin=\"1\" end=\"5\" step=\"1\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_status_6 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_6 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_6.setParent((Tag)null);
        _jsp_ForEachTag_6.setPageContext(pageContext);
        _jsp_ForEachTag_6.setBegin(1);
        _jsp_ForEachTag_6.setEnd(5);
        _jsp_ForEachTag_6.setStep(1);
        _jsp_ForEachTag_6.setVarStatus("status");
        if(_jsp_ForEachTag_6.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // NODE START: lineNumber: 5, offset: 6, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_7
                // <c:map name=\"user\">...</c:map>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_7 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_7.setPageContext(pageContext);
                _jsp_MapTag_7.setParent((Tag)null);
                _jsp_MapTag_7.setDynamicAttribute("name", "user");
                int _jsp_start_flag_7 = _jsp_MapTag_7.doStartTag();

                if(_jsp_start_flag_7 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_7 != Tag.SKIP_BODY) {
                    int _jsp_flag_7 = 0;

                    do {
                        // NODE START: lineNumber: 6, offset: 7, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_8
                        // <c:entry name=\"userName\" value=\"ayada${status.index}\"/>
                        _jsp_MapTag_7.setAttribute("userName", ExpressionUtil.evaluate(expressionContext, "ayada${status.index}", null));
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 6, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_8

                        // NODE START: lineNumber: 7, offset: 9, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_10
                        // <c:entry name=\"nickName\" value=\"ayada${status.index}\"/>
                        _jsp_MapTag_7.setAttribute("nickName", ExpressionUtil.evaluate(expressionContext, "ayada${status.index}", null));
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 7, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_10

                        _jsp_flag_7 = _jsp_MapTag_7.doAfterBody();
                    }
                    while(_jsp_flag_7 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_MapTag_7.doEndTag();
                _jsp_MapTag_7.release();
                // NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_7

                // TEXT: lineNumber: 8
                // out.write("\r\n");
                out.write(_jsp_string_13, 0, _jsp_string_13.length);

                // NODE START: lineNumber: 10, offset: 13, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_14
                // <c:execute value=\"${userList.add(user)}\"/>
                ExpressionUtil.evaluate(expressionContext, "${userList.add(user)}", null);
                // jsp.jstl.core.ExecuteTag END
                // NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_14

                if(_jsp_ForEachTag_6.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_6.release();
        pageContext.setAttribute("status", _jsp_old_var_status_6);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_6

        // TEXT: lineNumber: 11
        // out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html message=\"hello\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head><title>test</title></head>\r\n<body version=\"1.0\">\r\n<table>\r\n");
        out.write(_jsp_string_17, 0, _jsp_string_17.length);

        // NODE START: lineNumber: 17, offset: 17, length: 23, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_18
        // <c:forEach items=\"${userList}\" var=\"user\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_18 = pageContext.getAttribute("user");
        Object _jsp_old_var_status_18 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_18 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_18.setParent((Tag)null);
        _jsp_ForEachTag_18.setPageContext(pageContext);
        _jsp_ForEachTag_18.setVar("user");
        _jsp_ForEachTag_18.setItems(pageContext.getAttribute("userList"));
        _jsp_ForEachTag_18.setVarStatus("status");
        if(_jsp_ForEachTag_18.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // NODE START: lineNumber: 18, offset: 18, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_19
                // <c:set var=\"rowNum\" value=\"${((status.index + 2) / 2).intValue()}\"/>
                pageContext.setAttribute("rowNum", ExpressionUtil.evaluate(expressionContext, "${((status.index + 2) / 2).intValue()}", null));
                // jsp.jstl.core.SetTag END
                // NODE END: lineNumber: 18, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_19

                // NODE START: lineNumber: 19, offset: 20, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_21
                // <c:if test=\"${(status.index) % 2 == 0}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${(status.index) % 2 == 0}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 19, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_21

                // NODE START: lineNumber: 20, offset: 22, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_23
                // <c:if test=\"${rowNum &lt; rows}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${rowNum < rows}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 20, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_23

                // NODE START: lineNumber: 21, offset: 24, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_25
                // <c:if test=\"${rowNum &gt;= rows}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${rowNum >= rows}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 21, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_25

                // TEXT: lineNumber: 23
                // out.write("        <div>status: ");
                out.write(_jsp_string_27, 0, _jsp_string_27.length);
                // VARIABLE: lineNumber: 24
                expressionContext.print(out, pageContext.getAttribute("status"));
                // TEXT: lineNumber: 24
                // out.write("</div>\r\n        <div>rows: ");
                out.write(_jsp_string_29, 0, _jsp_string_29.length);
                // VARIABLE: lineNumber: 25
                expressionContext.print(out, pageContext.getAttribute("rows"));
                // TEXT: lineNumber: 25
                // out.write(", rowNum: ");
                out.write(_jsp_string_31, 0, _jsp_string_31.length);
                // VARIABLE: lineNumber: 25
                expressionContext.print(out, pageContext.getAttribute("rowNum"));
                // TEXT: lineNumber: 25
                // out.write(", status.index: ");
                out.write(_jsp_string_33, 0, _jsp_string_33.length);
                // EXPRESSION: lineNumber: 25
                expressionContext.print(out, expressionContext.getString("status.index"));
                // TEXT: lineNumber: 25
                // out.write(": user.userName: ");
                out.write(_jsp_string_35, 0, _jsp_string_35.length);
                // EXPRESSION: lineNumber: 25
                expressionContext.print(out, expressionContext.getString("user.userName"));
                // TEXT: lineNumber: 25
                // out.write("</div>\r\n        </td>\r\n");
                out.write(_jsp_string_37, 0, _jsp_string_37.length);

                // NODE START: lineNumber: 27, offset: 37, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_38
                // <c:if test=\"${(status.index + 1) % 2 == 0}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${(status.index + 1) % 2 == 0}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_38

                if(_jsp_ForEachTag_18.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_18.release();
        pageContext.setAttribute("user", _jsp_old_var_18);
        pageContext.setAttribute("status", _jsp_old_var_status_18);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 17, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_18

        // TEXT: lineNumber: 28
        // out.write("</table>\r\n</body>\r\n</html>");
        out.write(_jsp_string_41, 0, _jsp_string_41.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_5 = "\r\n".toCharArray();
    public static final char[] _jsp_string_13 = "\r\n".toCharArray();
    public static final char[] _jsp_string_17 = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html message=\"hello\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head><title>test</title></head>\r\n<body version=\"1.0\">\r\n<table>\r\n".toCharArray();
    public static final char[] _jsp_string_27 = "        <div>status: ".toCharArray();
    public static final char[] _jsp_string_29 = "</div>\r\n        <div>rows: ".toCharArray();
    public static final char[] _jsp_string_31 = ", rowNum: ".toCharArray();
    public static final char[] _jsp_string_33 = ", status.index: ".toCharArray();
    public static final char[] _jsp_string_35 = ": user.userName: ".toCharArray();
    public static final char[] _jsp_string_37 = "</div>\r\n        </td>\r\n".toCharArray();
    public static final char[] _jsp_string_41 = "</table>\r\n</body>\r\n</html>".toCharArray();

}
