/*
 * $RCSfile: ExprTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2014-10-06 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:\WorkSpace\ayada\webapp
 * path: exprTest.jsp
 * lastModified: 2014-10-06 15:51:39 958
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.0 (built 2014-10-06 15:51:44 008)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ExprTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ExprTestTemplate extends JspTemplate{
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getDefaultPageContext(writer);
        ExprTestTemplate template = new ExprTestTemplate();

        try{
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable)
        {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    public void _execute(final PageContext pageContext) throws Throwable{
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 2, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_1
        // <c:escape encoder="xml"/>
        com.skin.ayada.jstl.core.EscapeTag _jsp_EscapeTag_1 = new com.skin.ayada.jstl.core.EscapeTag();
        _jsp_EscapeTag_1.setPageContext(pageContext);
        _jsp_EscapeTag_1.setParent((Tag)null);
        _jsp_EscapeTag_1.setEncoder("xml");
        int _jsp_start_flag_1 = _jsp_EscapeTag_1.doStartTag();

        if(_jsp_start_flag_1 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_1 != Tag.SKIP_BODY){
            _jsp_EscapeTag_1.doAfterBody();
        }
        _jsp_EscapeTag_1.doEndTag();
        _jsp_EscapeTag_1.release();
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_1

        // TEXT: lineNumber: 1
        // out.write("\r\n");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);

        // NODE START: lineNumber: 2, offset: 3, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_4
        // <c:set var="myString" value="&lt;h1&gt;test&lt;/h1&gt;"/>
        pageContext.setAttribute("myString", "<h1>test</h1>");
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_4

        // VARIABLE: lineNumber: 3
        expressionContext.print(out, pageContext.getAttribute("myString"));
        // TEXT: lineNumber: 3
        // out.write("\r\n");
        out.write(_jsp_string_7, 0, _jsp_string_7.length);

        // NODE START: lineNumber: 4, offset: 7, length: 2, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_8
        // <c:escape encoder="null"/>
        com.skin.ayada.jstl.core.EscapeTag _jsp_EscapeTag_8 = new com.skin.ayada.jstl.core.EscapeTag();
        _jsp_EscapeTag_8.setPageContext(pageContext);
        _jsp_EscapeTag_8.setParent((Tag)null);
        _jsp_EscapeTag_8.setEncoder("null");
        int _jsp_start_flag_8 = _jsp_EscapeTag_8.doStartTag();

        if(_jsp_start_flag_8 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_8 != Tag.SKIP_BODY){
            _jsp_EscapeTag_8.doAfterBody();
        }
        _jsp_EscapeTag_8.doEndTag();
        _jsp_EscapeTag_8.release();
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_8

        // TEXT: lineNumber: 4
        // out.write("\r\n");
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        // VARIABLE: lineNumber: 5
        expressionContext.print(out, pageContext.getAttribute("myString"));
        // TEXT: lineNumber: 5
        // out.write("\r\n");
        out.write(_jsp_string_12, 0, _jsp_string_12.length);

        out.flush();
        jspWriter.flush();
    }

    private static final char[] _jsp_string_3 = "\r\n".toCharArray();
    private static final char[] _jsp_string_7 = "\r\n".toCharArray();
    private static final char[] _jsp_string_10 = "\r\n".toCharArray();
    private static final char[] _jsp_string_12 = "\r\n".toCharArray();

}
