/*
 * $RCSfile: ExprTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-08 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /exprTest.jsp
 * lastModified: 2014-10-06 15:51:39 958
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-08 22:06:49 256)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ExprTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ExprTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ExprTestTemplate template = new ExprTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 2, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_1
        // <c:escape encoder=\"xml\"/>
        com.skin.ayada.jstl.core.EscapeTag _jsp_EscapeTag_1 = new com.skin.ayada.jstl.core.EscapeTag();
        _jsp_EscapeTag_1.setPageContext(pageContext);
        _jsp_EscapeTag_1.setParent((Tag)null);
        _jsp_EscapeTag_1.setEncoder("xml");
        int _jsp_start_flag_1 = _jsp_EscapeTag_1.doStartTag();

        if(_jsp_start_flag_1 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_1 != Tag.SKIP_BODY) {
            _jsp_EscapeTag_1.doAfterBody();
        }
        _jsp_EscapeTag_1.doEndTag();
        _jsp_EscapeTag_1.release();
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_1

        // TEXT: lineNumber: 1
        // out.write("\r\n");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);

        // NODE START: lineNumber: 2, offset: 3, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_4
        // <c:set var=\"myString\" value=\"&lt;h1&gt;test&lt;/h1&gt;\"/>
        pageContext.setAttribute("myString", "<h1>test</h1>");
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_4

        // TEXT: lineNumber: 2
        // out.write("\r\n");
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        // VARIABLE: lineNumber: 3
        expressionContext.print(out, pageContext.getAttribute("myString"));
        // TEXT: lineNumber: 3
        // out.write("\r\n");
        out.write(_jsp_string_8, 0, _jsp_string_8.length);

        // NODE START: lineNumber: 4, offset: 8, length: 2, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_9
        // <c:escape encoder=\"null\"/>
        com.skin.ayada.jstl.core.EscapeTag _jsp_EscapeTag_9 = new com.skin.ayada.jstl.core.EscapeTag();
        _jsp_EscapeTag_9.setPageContext(pageContext);
        _jsp_EscapeTag_9.setParent((Tag)null);
        _jsp_EscapeTag_9.setEncoder("null");
        int _jsp_start_flag_9 = _jsp_EscapeTag_9.doStartTag();

        if(_jsp_start_flag_9 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_9 != Tag.SKIP_BODY) {
            _jsp_EscapeTag_9.doAfterBody();
        }
        _jsp_EscapeTag_9.doEndTag();
        _jsp_EscapeTag_9.release();
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_9

        // TEXT: lineNumber: 4
        // out.write("\r\n");
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        // VARIABLE: lineNumber: 5
        expressionContext.print(out, pageContext.getAttribute("myString"));
        // TEXT: lineNumber: 5
        // out.write("\r\n");
        out.write(_jsp_string_13, 0, _jsp_string_13.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_3 = "\r\n".toCharArray();
    public static final char[] _jsp_string_6 = "\r\n".toCharArray();
    public static final char[] _jsp_string_8 = "\r\n".toCharArray();
    public static final char[] _jsp_string_11 = "\r\n".toCharArray();
    public static final char[] _jsp_string_13 = "\r\n".toCharArray();

}
