/*
 * $RCSfile: ExprTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-14 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /exprTest.jsp
 * lastModified: 2016-01-14 23:00:56 173
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-14 23:17:01 831)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ExprTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ExprTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ExprTestTemplate template = new ExprTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 2, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_1
        // <c:escape encoder=\"xml\"/>
        com.skin.ayada.jstl.core.EscapeTag _jsp_EscapeTag_1 = new com.skin.ayada.jstl.core.EscapeTag();
        _jsp_EscapeTag_1.setPageContext(pageContext);
        _jsp_EscapeTag_1.setParent((Tag)null);
        _jsp_EscapeTag_1.setEncoder("xml");
        int _jsp_start_flag_1 = _jsp_EscapeTag_1.doStartTag();

        if(_jsp_start_flag_1 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_1 != Tag.SKIP_BODY) {
            _jsp_EscapeTag_1.doAfterBody();
        }
        _jsp_EscapeTag_1.doEndTag();
        _jsp_EscapeTag_1.release();
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_1

        // NODE START: lineNumber: 2, offset: 2, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_3
        // <c:set var=\"myString\" value=\"&lt;h1&gt;test&lt;/h1&gt;\"/>
        pageContext.setAttribute("myString", "<h1>test</h1>");
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_3

        // TEXT: lineNumber: 2
        // out.write("expr: ${myString}\r\ntext: ");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        // VARIABLE: lineNumber: 4
        out.print(pageContext.getAttribute("myString"));
        // TEXT: lineNumber: 4
        // out.write("\r\nhtml: ");
        out.write(_jsp_string_7, 0, _jsp_string_7.length);
        // VARIABLE: lineNumber: 5
        expressionContext.print(out, pageContext.getAttribute("myString"));
        // TEXT: lineNumber: 5
        // out.write("\r\nhtml: ");
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        // VARIABLE: lineNumber: 6
        expressionContext.print(out, pageContext.getAttribute("myString"));
        // TEXT: lineNumber: 6
        // out.write("\r\n");
        out.write(_jsp_string_11, 0, _jsp_string_11.length);

        // NODE START: lineNumber: 7, offset: 11, length: 2, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_12
        // <c:escape encoder=\"null\"/>
        com.skin.ayada.jstl.core.EscapeTag _jsp_EscapeTag_12 = new com.skin.ayada.jstl.core.EscapeTag();
        _jsp_EscapeTag_12.setPageContext(pageContext);
        _jsp_EscapeTag_12.setParent((Tag)null);
        _jsp_EscapeTag_12.setEncoder("null");
        int _jsp_start_flag_12 = _jsp_EscapeTag_12.doStartTag();

        if(_jsp_start_flag_12 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_12 != Tag.SKIP_BODY) {
            _jsp_EscapeTag_12.doAfterBody();
        }
        _jsp_EscapeTag_12.doEndTag();
        _jsp_EscapeTag_12.release();
        // NODE END: lineNumber: 7, tagClassName: com.skin.ayada.jstl.core.EscapeTag, tagInstanceName: _jsp_EscapeTag_12

        // TEXT: lineNumber: 7
        // out.write("text: ");
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        // VARIABLE: lineNumber: 8
        expressionContext.print(out, pageContext.getAttribute("myString"));
        // TEXT: lineNumber: 8
        // out.write("\r\n\r\n${}\r\n\r\n\r\n");
        out.write(_jsp_string_16, 0, _jsp_string_16.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_5 = "expr: ${myString}\r\ntext: ".toCharArray();
    public static final char[] _jsp_string_7 = "\r\nhtml: ".toCharArray();
    public static final char[] _jsp_string_9 = "\r\nhtml: ".toCharArray();
    public static final char[] _jsp_string_11 = "\r\n".toCharArray();
    public static final char[] _jsp_string_14 = "text: ".toCharArray();
    public static final char[] _jsp_string_16 = "\r\n\r\n${}\r\n\r\n\r\n".toCharArray();

}
