/*
 * $RCSfile: ExtTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2014-06-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * LastModified: 2014-06-12 13:39:55 864
 * JSP generated by JspCompiler-0.1.1 (built 2014-06-12 14:10:02 694)
 *
 */
package _tpl._jsp;

import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;

/**
 * <p>Title: ExtTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
public class ExtTestTemplate extends JspTemplate
{
    public static void main(String[] args)
    {
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getDefaultPageContext(writer);
        ExtTestTemplate template = new ExtTestTemplate();

        try{
            template._execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable)
        {
            throwable.printStackTrace();
        }
     }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    public void _execute(final PageContext pageContext) throws Throwable
    {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /* NODE START: lineNumber: 1, offset: 0, length: 12, tagClassName: com.skin.ayada.jstl.core.OutputTag, tagInstanceName: _jsp_OutputTag_1 */
        /* <c:output out="true" trim="false" file="webapp\extTest.log">...</c:output> */
        com.skin.ayada.jstl.core.OutputTag _jsp_OutputTag_1 = new com.skin.ayada.jstl.core.OutputTag();
        _jsp_OutputTag_1.setParent((Tag)null);
        _jsp_OutputTag_1.setPageContext(pageContext);
        _jsp_OutputTag_1.setOut(true);
        _jsp_OutputTag_1.setTrim(false);
        _jsp_OutputTag_1.setFile("webapp\\extTest.log");
        int _jsp_start_flag_1 = _jsp_OutputTag_1.doStartTag();

        if(_jsp_start_flag_1 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_1 != Tag.SKIP_BODY){
            int _jsp_flag_1 = 0;
            if(_jsp_start_flag_1 == BodyTag.EVAL_BODY_BUFFERED){
                BodyContent _jsp_body_content_1 = (BodyContent)(pageContext.pushBody());
                _jsp_OutputTag_1.setBodyContent(_jsp_body_content_1);
                _jsp_OutputTag_1.doInitBody();
                out = _jsp_body_content_1;
            }

            do{
                /* TEXT: lineNumber: 1 */
                out.write("\r\n    <p>1 - Hello World!</p>\r\n    ");

                /* NODE START: lineNumber: 3, offset: 2, length: 6, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_3 */
                /* <c:out>...</c:out> */
                out = pageContext.pushBody();
                /* TEXT: lineNumber: 3 */
                out.write("\r\n        <p>2 - Hello World!</p>\r\n        ");

                /* NODE START: lineNumber: 5, offset: 4, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_5 */
                /* <c:execute value="${pageContext.clear()}"/> */
                ExpressionUtil.evaluate(expressionContext, "${pageContext.clear()}", null);
                /* jsp.jstl.core.ExecuteTag END */
                /* NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_5 */

                /* TEXT: lineNumber: 6 */
                out.write("        <p>3 - Hello World!</p>\r\n    ");
                pageContext.print((BodyContent)out, false);
                out = pageContext.popBody();
                /* jsp.jstl.core.OutTag END */
                /* NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_3 */

                /* TEXT: lineNumber: 7 */
                out.write("\r\n    ");

                /* NODE START: lineNumber: 8, offset: 9, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_10 */
                /* <c:set var="a1" value="a1"/> */
                pageContext.setAttribute("a1", "a1");
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 8, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_10 */

                _jsp_flag_1 = _jsp_OutputTag_1.doAfterBody();
            }
            while(_jsp_flag_1 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_1 == BodyTag.EVAL_BODY_BUFFERED){
                out = pageContext.popBody();
            }
        }
        _jsp_OutputTag_1.doEndTag();
        _jsp_OutputTag_1.release();
        /* NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.OutputTag, tagInstanceName: _jsp_OutputTag_1 */

        /* TEXT: lineNumber: 9 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 11, offset: 13, length: 121, tagClassName: com.skin.ayada.jstl.core.OutputTag, tagInstanceName: _jsp_OutputTag_14 */
        /* <c:xml out="true" trim="false" file="webapp\extTest.log">...</c:xml> */
        com.skin.ayada.jstl.core.OutputTag _jsp_OutputTag_14 = new com.skin.ayada.jstl.core.OutputTag();
        _jsp_OutputTag_14.setParent((Tag)null);
        _jsp_OutputTag_14.setPageContext(pageContext);
        _jsp_OutputTag_14.setOut(true);
        _jsp_OutputTag_14.setTrim(false);
        _jsp_OutputTag_14.setFile("webapp\\extTest.log");
        int _jsp_start_flag_14 = _jsp_OutputTag_14.doStartTag();

        if(_jsp_start_flag_14 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_14 != Tag.SKIP_BODY){
            int _jsp_flag_14 = 0;
            if(_jsp_start_flag_14 == BodyTag.EVAL_BODY_BUFFERED){
                BodyContent _jsp_body_content_14 = pageContext.pushBody();
                _jsp_OutputTag_14.setBodyContent(_jsp_body_content_14);
                _jsp_OutputTag_14.doInitBody();
                out = _jsp_body_content_14;
            }

            do{
                /* NODE START: lineNumber: 13, offset: 14, length: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_15 */
                /* <c:out>...</c:out> */
                out = pageContext.pushBody();
                /* TEXT: lineNumber: 13 */
                out.write("<p>3 - Hello World!</p>");
                pageContext.print((BodyContent)out, false);
                out = pageContext.popBody();
                /* jsp.jstl.core.OutTag END */
                /* NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_15 */

                /* NODE START: lineNumber: 15, offset: 17, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_18 */
                /* <c:set var="a1" value="a1"/> */
                pageContext.setAttribute("a1", "a1");
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 15, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_18 */

                /* NODE START: lineNumber: 16, offset: 19, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_20 */
                /* <c:set var="a2" value="${a1}"/> */
                pageContext.setAttribute("a2", pageContext.getAttribute("a1"));
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 16, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_20 */

                /* NODE START: lineNumber: 17, offset: 21, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_22 */
                /* <c:set var="a3" value="${a2}"/> */
                pageContext.setAttribute("a3", pageContext.getAttribute("a2"));
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 17, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_22 */

                /* NODE START: lineNumber: 18, offset: 23, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_24 */
                /* <c:set var="a4" value="${a3}"/> */
                pageContext.setAttribute("a4", pageContext.getAttribute("a3"));
                /* jsp.jstl.core.SetTag END */
                /* NODE END: lineNumber: 18, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_24 */

                /* NODE START: lineNumber: 20, offset: 25, length: 8, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_26 */
                /* <c:bean name="testTag1" className="com.skin.ayada.jstl.core.TestTag">...</c:bean> */
                com.skin.ayada.jstl.core.BeanTag _jsp_BeanTag_26 = new com.skin.ayada.jstl.core.BeanTag();
                _jsp_BeanTag_26.setParent(_jsp_OutputTag_14);
                _jsp_BeanTag_26.setPageContext(pageContext);
                _jsp_BeanTag_26.setName("testTag1");
                _jsp_BeanTag_26.setClassName("com.skin.ayada.jstl.core.TestTag");
                int _jsp_start_flag_26 = _jsp_BeanTag_26.doStartTag();

                if(_jsp_start_flag_26 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_26 != Tag.SKIP_BODY){
                    int _jsp_flag_26 = 0;

                    do{
                        /* NODE START: lineNumber: 21, offset: 26, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_27 */
                        /* <c:constructor type="char" value="c"/> */
                        com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_26, "char", "c");
                        /* jsp.jstl.core.ConstructorTag END */
                        /* NODE END: lineNumber: 21, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_27 */

                        /* NODE START: lineNumber: 22, offset: 28, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_29 */
                        /* <c:constructor type="byte" value="2"/> */
                        com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_26, "byte", 2);
                        /* jsp.jstl.core.ConstructorTag END */
                        /* NODE END: lineNumber: 22, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_29 */

                        /* NODE START: lineNumber: 23, offset: 30, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_31 */
                        /* <c:property name="pageContext" value="${pageContext}"/> */
                        _jsp_BeanTag_26.setProperty("pageContext", pageContext.getAttribute("pageContext"));
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 23, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_31 */

                        _jsp_flag_26 = _jsp_BeanTag_26.doAfterBody();
                    }
                    while(_jsp_flag_26 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_BeanTag_26.doEndTag();
                _jsp_BeanTag_26.release();
                /* NODE END: lineNumber: 20, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_26 */

                /* NODE START: lineNumber: 26, offset: 33, length: 8, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_34 */
                /* <c:bean name="testTag2" className="com.skin.ayada.jstl.core.TestTag">...</c:bean> */
                com.skin.ayada.jstl.core.BeanTag _jsp_BeanTag_34 = new com.skin.ayada.jstl.core.BeanTag();
                _jsp_BeanTag_34.setParent(_jsp_OutputTag_14);
                _jsp_BeanTag_34.setPageContext(pageContext);
                _jsp_BeanTag_34.setName("testTag2");
                _jsp_BeanTag_34.setClassName("com.skin.ayada.jstl.core.TestTag");
                int _jsp_start_flag_34 = _jsp_BeanTag_34.doStartTag();

                if(_jsp_start_flag_34 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_34 != Tag.SKIP_BODY){
                    int _jsp_flag_34 = 0;

                    do{
                        /* NODE START: lineNumber: 27, offset: 34, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_35 */
                        /* <c:constructor type="long" value="1.2e3"/> */
                        com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_34, "long", 1200.0d);
                        /* jsp.jstl.core.ConstructorTag END */
                        /* NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_35 */

                        /* NODE START: lineNumber: 28, offset: 36, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_37 */
                        /* <c:constructor type="java.lang.String" value="Hello"/> */
                        com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_34, "java.lang.String", "Hello");
                        /* jsp.jstl.core.ConstructorTag END */
                        /* NODE END: lineNumber: 28, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_37 */

                        /* NODE START: lineNumber: 29, offset: 38, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_39 */
                        /* <c:property name="pageContext" value="${pageContext}"/> */
                        _jsp_BeanTag_34.setProperty("pageContext", pageContext.getAttribute("pageContext"));
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 29, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_39 */

                        _jsp_flag_34 = _jsp_BeanTag_34.doAfterBody();
                    }
                    while(_jsp_flag_34 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_BeanTag_34.doEndTag();
                _jsp_BeanTag_34.release();
                /* NODE END: lineNumber: 26, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_34 */

                /* NODE START: lineNumber: 32, offset: 41, length: 20, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_42 */
                /* <c:bean name="testTag3" className="com.skin.ayada.jstl.core.TestTag">...</c:bean> */
                com.skin.ayada.jstl.core.BeanTag _jsp_BeanTag_42 = new com.skin.ayada.jstl.core.BeanTag();
                _jsp_BeanTag_42.setParent(_jsp_OutputTag_14);
                _jsp_BeanTag_42.setPageContext(pageContext);
                _jsp_BeanTag_42.setName("testTag3");
                _jsp_BeanTag_42.setClassName("com.skin.ayada.jstl.core.TestTag");
                int _jsp_start_flag_42 = _jsp_BeanTag_42.doStartTag();

                if(_jsp_start_flag_42 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_42 != Tag.SKIP_BODY){
                    int _jsp_flag_42 = 0;

                    do{
                        /* NODE START: lineNumber: 33, offset: 42, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_43 */
                        /* <c:property name="myBoolean" value="true"/> */
                        _jsp_BeanTag_42.setProperty("myBoolean", true);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 33, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_43 */

                        /* NODE START: lineNumber: 34, offset: 44, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_45 */
                        /* <c:property name="myChar" value="cc"/> */
                        _jsp_BeanTag_42.setProperty("myChar", "cc");
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 34, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_45 */

                        /* NODE START: lineNumber: 35, offset: 46, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_47 */
                        /* <c:property name="myByte" value="1"/> */
                        _jsp_BeanTag_42.setProperty("myByte", 1);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 35, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_47 */

                        /* NODE START: lineNumber: 36, offset: 48, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_49 */
                        /* <c:property name="myInt" value="-1.0"/> */
                        _jsp_BeanTag_42.setProperty("myInt", -1.0d);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 36, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_49 */

                        /* NODE START: lineNumber: 37, offset: 50, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_51 */
                        /* <c:property name="myFloat" value="1.2f"/> */
                        _jsp_BeanTag_42.setProperty("myFloat", 1.2f);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 37, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_51 */

                        /* NODE START: lineNumber: 38, offset: 52, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_53 */
                        /* <c:property name="myDouble" value="2.3d"/> */
                        _jsp_BeanTag_42.setProperty("myDouble", 2.3d);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 38, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_53 */

                        /* NODE START: lineNumber: 39, offset: 54, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_55 */
                        /* <c:property name="myLong" value="5L"/> */
                        _jsp_BeanTag_42.setProperty("myLong", 5L);
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 39, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_55 */

                        /* NODE START: lineNumber: 40, offset: 56, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_57 */
                        /* <c:property name="myString" value="Hello"/> */
                        _jsp_BeanTag_42.setProperty("myString", "Hello");
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 40, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_57 */

                        /* NODE START: lineNumber: 41, offset: 58, length: 2, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_59 */
                        /* <c:property name="pageContext" value="${pageContext}"/> */
                        _jsp_BeanTag_42.setProperty("pageContext", pageContext.getAttribute("pageContext"));
                        /* jsp.jstl.core.PropertyTag END */
                        /* NODE END: lineNumber: 41, tagClassName: com.skin.ayada.jstl.core.PropertyTag, tagInstanceName: _jsp_PropertyTag_59 */

                        _jsp_flag_42 = _jsp_BeanTag_42.doAfterBody();
                    }
                    while(_jsp_flag_42 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_BeanTag_42.doEndTag();
                _jsp_BeanTag_42.release();
                /* NODE END: lineNumber: 32, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_42 */

                /* NODE START: lineNumber: 44, offset: 61, length: 4, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_62 */
                /* <c:out>...</c:out> */
                out = pageContext.pushBody();
                /* TEXT: lineNumber: 44 */
                out.write("<p>#########################</p>");
                /* EXPRESSION: lineNumber: 44 */
                out.write(expressionContext.getString("\"\\r\\n\""));
                pageContext.print((BodyContent)out, false);
                out = pageContext.popBody();
                /* jsp.jstl.core.OutTag END */
                /* NODE END: lineNumber: 44, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_62 */

                /* NODE START: lineNumber: 46, offset: 65, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_66 */
                /* <c:execute value="${testTag1.print()}"/> */
                ExpressionUtil.evaluate(expressionContext, "${testTag1.print()}", null);
                /* jsp.jstl.core.ExecuteTag END */
                /* NODE END: lineNumber: 46, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_66 */

                /* NODE START: lineNumber: 47, offset: 67, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_68 */
                /* <c:execute value="${testTag2.print()}"/> */
                ExpressionUtil.evaluate(expressionContext, "${testTag2.print()}", null);
                /* jsp.jstl.core.ExecuteTag END */
                /* NODE END: lineNumber: 47, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_68 */

                /* NODE START: lineNumber: 48, offset: 69, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_70 */
                /* <c:execute value="${testTag3.print()}"/> */
                ExpressionUtil.evaluate(expressionContext, "${testTag3.print()}", null);
                /* jsp.jstl.core.ExecuteTag END */
                /* NODE END: lineNumber: 48, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_70 */

                /* NODE START: lineNumber: 50, offset: 71, length: 10, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_72 */
                /* <c:list name="list">...</c:list> */
                com.skin.ayada.jstl.core.ListTag _jsp_ListTag_72 = new com.skin.ayada.jstl.core.ListTag();
                _jsp_ListTag_72.setParent(_jsp_OutputTag_14);
                _jsp_ListTag_72.setPageContext(pageContext);
                _jsp_ListTag_72.setName("list");
                int _jsp_start_flag_72 = _jsp_ListTag_72.doStartTag();

                if(_jsp_start_flag_72 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_72 != Tag.SKIP_BODY){
                    int _jsp_flag_72 = 0;

                    do{
                        /* NODE START: lineNumber: 51, offset: 72, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_73 */
                        /* <c:element value="1"/> */
                        _jsp_ListTag_72.addElement(1);
                        /* jsp.jstl.core.ElementTag END */
                        /* NODE END: lineNumber: 51, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_73 */

                        /* NODE START: lineNumber: 52, offset: 74, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_75 */
                        /* <c:element value="2"/> */
                        _jsp_ListTag_72.addElement(2);
                        /* jsp.jstl.core.ElementTag END */
                        /* NODE END: lineNumber: 52, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_75 */

                        /* NODE START: lineNumber: 53, offset: 76, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_77 */
                        /* <c:element value="3"/> */
                        _jsp_ListTag_72.addElement(3);
                        /* jsp.jstl.core.ElementTag END */
                        /* NODE END: lineNumber: 53, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_77 */

                        /* NODE START: lineNumber: 54, offset: 78, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_79 */
                        /* <c:element value="4"/> */
                        _jsp_ListTag_72.addElement(4);
                        /* jsp.jstl.core.ElementTag END */
                        /* NODE END: lineNumber: 54, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_79 */

                        _jsp_flag_72 = _jsp_ListTag_72.doAfterBody();
                    }
                    while(_jsp_flag_72 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_ListTag_72.doEndTag();
                _jsp_ListTag_72.release();
                /* NODE END: lineNumber: 50, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_72 */

                /* NODE START: lineNumber: 57, offset: 81, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_82 */
                /* <c:print value="${list}"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, pageContext.getAttribute("list"));
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 57, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_82 */

                /* NODE START: lineNumber: 59, offset: 83, length: 8, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_84 */
                /* <c:map name="map">...</c:map> */
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_84 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_84.setParent(_jsp_OutputTag_14);
                _jsp_MapTag_84.setPageContext(pageContext);
                _jsp_MapTag_84.setDynamicAttribute("name", "map");
                int _jsp_start_flag_84 = _jsp_MapTag_84.doStartTag();

                if(_jsp_start_flag_84 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_84 != Tag.SKIP_BODY){
                    int _jsp_flag_84 = 0;

                    do{
                        /* NODE START: lineNumber: 60, offset: 84, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_85 */
                        /* <c:entry name="1" value="test1"/> */
                        _jsp_MapTag_84.setAttribute("1", "test1");
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 60, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_85 */

                        /* NODE START: lineNumber: 61, offset: 86, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_87 */
                        /* <c:entry name="2" value="test2"/> */
                        _jsp_MapTag_84.setAttribute("2", "test2");
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 61, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_87 */

                        /* NODE START: lineNumber: 62, offset: 88, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_89 */
                        /* <c:entry name="3" value="test3"/> */
                        _jsp_MapTag_84.setAttribute("3", "test3");
                        /* jsp.jstl.core.AttributeTag END */
                        /* NODE END: lineNumber: 62, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_89 */

                        _jsp_flag_84 = _jsp_MapTag_84.doAfterBody();
                    }
                    while(_jsp_flag_84 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_MapTag_84.doEndTag();
                _jsp_MapTag_84.release();
                /* NODE END: lineNumber: 59, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_84 */

                /* NODE START: lineNumber: 65, offset: 91, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_92 */
                /* <c:print value="&lt;p&gt;"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, "<p>");
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 65, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_92 */

                /* NODE START: lineNumber: 65, offset: 93, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_94 */
                /* <c:print value="${map}"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, pageContext.getAttribute("map"));
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 65, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_94 */

                /* NODE START: lineNumber: 65, offset: 95, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_96 */
                /* <c:print value="&lt;/p&gt;"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, "</p>");
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 65, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_96 */

                /* NODE START: lineNumber: 66, offset: 97, length: 2, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_98 */
                /* <c:test/> */
                com.skin.ayada.jstl.core.TestTag _jsp_TestTag_98 = new com.skin.ayada.jstl.core.TestTag();
                _jsp_TestTag_98.setParent(_jsp_OutputTag_14);
                _jsp_TestTag_98.setPageContext(pageContext);
                int _jsp_start_flag_98 = _jsp_TestTag_98.doStartTag();

                if(_jsp_start_flag_98 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_98 != Tag.SKIP_BODY){
                    _jsp_TestTag_98.doAfterBody();
                }
                _jsp_TestTag_98.doEndTag();
                _jsp_TestTag_98.release();
                /* NODE END: lineNumber: 66, tagClassName: com.skin.ayada.jstl.core.TestTag, tagInstanceName: _jsp_TestTag_98 */

                /* NODE START: lineNumber: 68, offset: 99, length: 2, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_100 */
                /* <c:list name="userList"/> */
                com.skin.ayada.jstl.core.ListTag _jsp_ListTag_100 = new com.skin.ayada.jstl.core.ListTag();
                _jsp_ListTag_100.setParent(_jsp_OutputTag_14);
                _jsp_ListTag_100.setPageContext(pageContext);
                _jsp_ListTag_100.setName("userList");
                int _jsp_start_flag_100 = _jsp_ListTag_100.doStartTag();

                if(_jsp_start_flag_100 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_100 != Tag.SKIP_BODY){
                    _jsp_ListTag_100.doAfterBody();
                }
                _jsp_ListTag_100.doEndTag();
                _jsp_ListTag_100.release();
                /* NODE END: lineNumber: 68, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_100 */

                /* NODE START: lineNumber: 70, offset: 101, length: 13, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_102 */
                /* <c:forEach items="1, 2, 3, 4, 5" var="num">...</c:forEach> */
                Object _jsp_old_var_102 = pageContext.getAttribute("num");
                com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_102 = new com.skin.ayada.jstl.core.ForEachTag();
                _jsp_ForEachTag_102.setParent(_jsp_OutputTag_14);
                _jsp_ForEachTag_102.setPageContext(pageContext);
                _jsp_ForEachTag_102.setVar("num");
                _jsp_ForEachTag_102.setItems("1, 2, 3, 4, 5");
                if(_jsp_ForEachTag_102.doStartTag() != Tag.SKIP_BODY){
                    while(true){
                        /* TEXT: lineNumber: 70 */
                        out.write("\r\n        ");

                        /* NODE START: lineNumber: 71, offset: 103, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_104 */
                        /* <c:map name="user">...</c:map> */
                        com.skin.ayada.jstl.core.MapTag _jsp_MapTag_104 = new com.skin.ayada.jstl.core.MapTag();
                        _jsp_MapTag_104.setParent((Tag)null);
                        _jsp_MapTag_104.setPageContext(pageContext);
                        _jsp_MapTag_104.setDynamicAttribute("name", "user");
                        int _jsp_start_flag_104 = _jsp_MapTag_104.doStartTag();

                        if(_jsp_start_flag_104 == Tag.SKIP_PAGE){
                            return;
                        }
                        if(_jsp_start_flag_104 != Tag.SKIP_BODY){
                            int _jsp_flag_104 = 0;

                            do{
                                /* NODE START: lineNumber: 72, offset: 104, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_105 */
                                /* <c:entry name="userName" value="test_${num}"/> */
                                _jsp_MapTag_104.setAttribute("userName", ExpressionUtil.evaluate(expressionContext, "test_${num}", null));
                                /* jsp.jstl.core.AttributeTag END */
                                /* NODE END: lineNumber: 72, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_105 */

                                /* NODE START: lineNumber: 73, offset: 106, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_107 */
                                /* <c:entry name="nickName" value="test_${num}"/> */
                                _jsp_MapTag_104.setAttribute("nickName", ExpressionUtil.evaluate(expressionContext, "test_${num}", null));
                                /* jsp.jstl.core.AttributeTag END */
                                /* NODE END: lineNumber: 73, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_107 */

                                _jsp_flag_104 = _jsp_MapTag_104.doAfterBody();
                            }
                            while(_jsp_flag_104 == IterationTag.EVAL_BODY_AGAIN);
                        }
                        _jsp_MapTag_104.doEndTag();
                        _jsp_MapTag_104.release();
                        /* NODE END: lineNumber: 71, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_104 */

                        /* TEXT: lineNumber: 74 */
                        out.write("\r\n        ");

                        /* NODE START: lineNumber: 75, offset: 110, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_111 */
                        /* <c:execute value="${userList.add(user)}"/> */
                        ExpressionUtil.evaluate(expressionContext, "${userList.add(user)}", null);
                        /* jsp.jstl.core.ExecuteTag END */
                        /* NODE END: lineNumber: 75, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_111 */

                        /* TEXT: lineNumber: 76 */
                        out.write("    ");
                        if(_jsp_ForEachTag_102.doAfterBody() != IterationTag.EVAL_BODY_AGAIN){
                            break;
                        }
                    }
                }
                _jsp_ForEachTag_102.release();
                pageContext.setAttribute("num", _jsp_old_var_102);
                /* jsp.jstl.core.ForEachTag END */
                /* NODE END: lineNumber: 70, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_102 */

                /* NODE START: lineNumber: 77, offset: 114, length: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_115 */
                /* <c:out>...</c:out> */
                out = pageContext.pushBody();
                /* TEXT: lineNumber: 77 */
                out.write("userList: ");
                pageContext.print((BodyContent)out, false);
                out = pageContext.popBody();
                /* jsp.jstl.core.OutTag END */
                /* NODE END: lineNumber: 77, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_115 */

                /* NODE START: lineNumber: 77, offset: 117, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_118 */
                /* <c:print value="${userList}"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, pageContext.getAttribute("userList"));
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 77, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_118 */

                /* NODE START: lineNumber: 79, offset: 119, length: 9, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_120 */
                /* <c:forEach items="1, 2, 3, 4, 5" var="num">...</c:forEach> */
                Object _jsp_old_var_120 = pageContext.getAttribute("num");
                com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_120 = new com.skin.ayada.jstl.core.ForEachTag();
                _jsp_ForEachTag_120.setParent(_jsp_OutputTag_14);
                _jsp_ForEachTag_120.setPageContext(pageContext);
                _jsp_ForEachTag_120.setVar("num");
                _jsp_ForEachTag_120.setItems("1, 2, 3, 4, 5");
                if(_jsp_ForEachTag_120.doStartTag() != Tag.SKIP_BODY){
                    while(true){
                        /* TEXT: lineNumber: 79 */
                        out.write("\r\n        ");

                        /* NODE START: lineNumber: 80, offset: 121, length: 2, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_122 */
                        /* <c:map name="user" userName="${num}_test_${num}"/> */
                        com.skin.ayada.jstl.core.MapTag _jsp_MapTag_122 = new com.skin.ayada.jstl.core.MapTag();
                        _jsp_MapTag_122.setParent((Tag)null);
                        _jsp_MapTag_122.setPageContext(pageContext);
                        _jsp_MapTag_122.setDynamicAttribute("name", "user");
                        _jsp_MapTag_122.setDynamicAttribute("userName", ExpressionUtil.evaluate(expressionContext, "${num}_test_${num}", null));
                        int _jsp_start_flag_122 = _jsp_MapTag_122.doStartTag();

                        if(_jsp_start_flag_122 == Tag.SKIP_PAGE){
                            return;
                        }
                        if(_jsp_start_flag_122 != Tag.SKIP_BODY){
                            _jsp_MapTag_122.doAfterBody();
                        }
                        _jsp_MapTag_122.doEndTag();
                        _jsp_MapTag_122.release();
                        /* NODE END: lineNumber: 80, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_122 */

                        /* TEXT: lineNumber: 80 */
                        out.write("\r\n        ");

                        /* NODE START: lineNumber: 81, offset: 124, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_125 */
                        /* <c:execute value="${userList.add(user)}"/> */
                        ExpressionUtil.evaluate(expressionContext, "${userList.add(user)}", null);
                        /* jsp.jstl.core.ExecuteTag END */
                        /* NODE END: lineNumber: 81, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_125 */

                        /* TEXT: lineNumber: 82 */
                        out.write("    ");
                        if(_jsp_ForEachTag_120.doAfterBody() != IterationTag.EVAL_BODY_AGAIN){
                            break;
                        }
                    }
                }
                _jsp_ForEachTag_120.release();
                pageContext.setAttribute("num", _jsp_old_var_120);
                /* jsp.jstl.core.ForEachTag END */
                /* NODE END: lineNumber: 79, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_120 */

                /* NODE START: lineNumber: 83, offset: 128, length: 3, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_129 */
                /* <c:out>...</c:out> */
                out = pageContext.pushBody();
                /* TEXT: lineNumber: 83 */
                out.write("userList: ");
                pageContext.print((BodyContent)out, false);
                out = pageContext.popBody();
                /* jsp.jstl.core.OutTag END */
                /* NODE END: lineNumber: 83, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_129 */

                /* NODE START: lineNumber: 83, offset: 131, length: 2, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_132 */
                /* <c:print value="${userList}"/> */
                com.skin.ayada.jstl.core.PrintTag.print(pageContext, null, pageContext.getAttribute("userList"));
                /* jsp.jstl.core.PrintTag END */
                /* NODE END: lineNumber: 83, tagClassName: com.skin.ayada.jstl.core.PrintTag, tagInstanceName: _jsp_PrintTag_132 */

                _jsp_flag_14 = _jsp_OutputTag_14.doAfterBody();
            }
            while(_jsp_flag_14 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_14 == BodyTag.EVAL_BODY_BUFFERED){
                out = pageContext.popBody();
            }
        }
        _jsp_OutputTag_14.doEndTag();
        _jsp_OutputTag_14.release();
        /* NODE END: lineNumber: 11, tagClassName: com.skin.ayada.jstl.core.OutputTag, tagInstanceName: _jsp_OutputTag_14 */

        /* TEXT: lineNumber: 84 */
        out.write("\r\n");

        /* NODE START: lineNumber: 85, offset: 135, length: 2, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_136 */
        /* <c:exit/> */
        if(com.skin.ayada.jstl.core.ExitTag.getTrue()){
            return;
        }
        /* jsp.jstl.core.ExitTag END */
        /* NODE END: lineNumber: 85, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_136 */

        out.flush();
        jspWriter.flush();
    }
}
