/*
 * $RCSfile: FmtTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-14 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /fmtTest.jsp
 * lastModified: 2014-06-13 09:58:06 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-14 23:17:02 308)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: FmtTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class FmtTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        FmtTestTemplate template = new FmtTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_1
        // <c:set var=\"i18n\" value=\"${I18n.getBundle(&#39;ayada_i18n&#39;, &#39;zh_cn&#39;)}\"/>
        pageContext.setAttribute("i18n", ExpressionUtil.evaluate(expressionContext, "${I18n.getBundle(\'ayada_i18n\', \'zh_cn\')}", null));
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_1

        // TEXT: lineNumber: 1
        // out.write("message1: ");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        // EXPRESSION: lineNumber: 2
        expressionContext.print(out, expressionContext.getString("i18n.format(\"test.common.test4\", \"000\", \"111\", \"222\", \"333\")"));
        // TEXT: lineNumber: 2
        // out.write("\r\nmessage2: ");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        // EXPRESSION: lineNumber: 3
        expressionContext.print(out, expressionContext.getString("i18n.message(\"test.common.test4\")"));
        // TEXT: lineNumber: 3
        // out.write("\r\n\r\n");
        out.write(_jsp_string_7, 0, _jsp_string_7.length);

        // NODE START: lineNumber: 5, offset: 7, length: 2, tagClassName: com.skin.ayada.jstl.fmt.SetBundleTag, tagInstanceName: _jsp_SetBundleTag_8
        // <fmt:setBundle var=\"myI18n\" basename=\"ayada_i18n\"/>
        com.skin.ayada.jstl.fmt.SetBundleTag _jsp_SetBundleTag_8 = new com.skin.ayada.jstl.fmt.SetBundleTag();
        _jsp_SetBundleTag_8.setPageContext(pageContext);
        _jsp_SetBundleTag_8.setParent((Tag)null);
        _jsp_SetBundleTag_8.setVar("myI18n");
        _jsp_SetBundleTag_8.setBasename("ayada_i18n");
        int _jsp_start_flag_8 = _jsp_SetBundleTag_8.doStartTag();

        if(_jsp_start_flag_8 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_8 != Tag.SKIP_BODY) {
            _jsp_SetBundleTag_8.doAfterBody();
        }
        _jsp_SetBundleTag_8.doEndTag();
        _jsp_SetBundleTag_8.release();
        // NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.fmt.SetBundleTag, tagInstanceName: _jsp_SetBundleTag_8

        // TEXT: lineNumber: 5
        // out.write("message3: ");
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        // EXPRESSION: lineNumber: 6
        expressionContext.print(out, expressionContext.getString("myI18n.format(\"test.common.test4\", \"000\", \"111\", \"222\", \"333\")"));
        // TEXT: lineNumber: 6
        // out.write("\r\n\r\n");
        out.write(_jsp_string_12, 0, _jsp_string_12.length);

        // NODE START: lineNumber: 8, offset: 12, length: 4, tagClassName: com.skin.ayada.jstl.fmt.BundleTag, tagInstanceName: _jsp_BundleTag_13
        // <fmt:bundle basename=\"ayada_i18n\">...</fmt:bundle>
        com.skin.ayada.jstl.fmt.BundleTag _jsp_BundleTag_13 = new com.skin.ayada.jstl.fmt.BundleTag();
        try {
            _jsp_BundleTag_13.setPageContext(pageContext);
            _jsp_BundleTag_13.setParent((Tag)null);
            _jsp_BundleTag_13.setBasename("ayada_i18n");
            int _jsp_start_flag_13 = _jsp_BundleTag_13.doStartTag();

            if(_jsp_start_flag_13 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_13 != Tag.SKIP_BODY) {
                int _jsp_flag_13 = 0;

                do {
                    // NODE START: lineNumber: 9, offset: 13, length: 2, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_14
                    // <fmt:message key=\"test.common.test1\"/>
                    com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_14 = new com.skin.ayada.jstl.fmt.MessageTag();
                    _jsp_MessageTag_14.setPageContext(pageContext);
                    _jsp_MessageTag_14.setParent(_jsp_BundleTag_13);
                    _jsp_MessageTag_14.setKey("test.common.test1");
                    int _jsp_start_flag_14 = _jsp_MessageTag_14.doStartTag();

                    if(_jsp_start_flag_14 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_14 != Tag.SKIP_BODY) {
                        _jsp_MessageTag_14.doAfterBody();
                    }
                    _jsp_MessageTag_14.doEndTag();
                    _jsp_MessageTag_14.release();
                    // NODE END: lineNumber: 9, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_14

                    _jsp_flag_13 = _jsp_BundleTag_13.doAfterBody();
                }
                while(_jsp_flag_13 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_BundleTag_13.doEndTag();
            _jsp_BundleTag_13.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_BundleTag_13.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_BundleTag_13.doFinally();
        }
        // NODE END: lineNumber: 8, tagClassName: com.skin.ayada.jstl.fmt.BundleTag, tagInstanceName: _jsp_BundleTag_13

        // NODE START: lineNumber: 11, offset: 16, length: 2, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_17
        // <fmt:message key=\"test.common.test2\" bundle=\"ayada_i18n\"/>
        com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_17 = new com.skin.ayada.jstl.fmt.MessageTag();
        _jsp_MessageTag_17.setPageContext(pageContext);
        _jsp_MessageTag_17.setParent((Tag)null);
        _jsp_MessageTag_17.setKey("test.common.test2");
        _jsp_MessageTag_17.setBundle("ayada_i18n");
        int _jsp_start_flag_17 = _jsp_MessageTag_17.doStartTag();

        if(_jsp_start_flag_17 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_17 != Tag.SKIP_BODY) {
            _jsp_MessageTag_17.doAfterBody();
        }
        _jsp_MessageTag_17.doEndTag();
        _jsp_MessageTag_17.release();
        // NODE END: lineNumber: 11, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_17

        // TEXT: lineNumber: 11
        // out.write("\r\n");
        out.write(_jsp_string_19, 0, _jsp_string_19.length);

        // NODE START: lineNumber: 13, offset: 19, length: 10, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_20
        // <fmt:message key=\"test.common.test4\" bundle=\"ayada_i18n\">...</fmt:message>
        com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_20 = new com.skin.ayada.jstl.fmt.MessageTag();
        _jsp_MessageTag_20.setPageContext(pageContext);
        _jsp_MessageTag_20.setParent((Tag)null);
        _jsp_MessageTag_20.setKey("test.common.test4");
        _jsp_MessageTag_20.setBundle("ayada_i18n");
        int _jsp_start_flag_20 = _jsp_MessageTag_20.doStartTag();

        if(_jsp_start_flag_20 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_20 != Tag.SKIP_BODY) {
            int _jsp_flag_20 = 0;
            if(_jsp_start_flag_20 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_20 = pageContext.pushBody();
                _jsp_MessageTag_20.setBodyContent(_jsp_body_content_20);
                _jsp_MessageTag_20.doInitBody();
                out = _jsp_body_content_20;
            }

            do {
                // NODE START: lineNumber: 14, offset: 20, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_21
                // <fmt:param value=\"000\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_21 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_21.setPageContext(pageContext);
                _jsp_FmtParamTag_21.setParent(_jsp_MessageTag_20);
                _jsp_FmtParamTag_21.setValue(0);
                int _jsp_start_flag_21 = _jsp_FmtParamTag_21.doStartTag();

                if(_jsp_start_flag_21 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_21 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_21.doAfterBody();
                }
                _jsp_FmtParamTag_21.doEndTag();
                _jsp_FmtParamTag_21.release();
                // NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_21

                // NODE START: lineNumber: 15, offset: 22, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_23
                // <fmt:param value=\"111\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_23 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_23.setPageContext(pageContext);
                _jsp_FmtParamTag_23.setParent(_jsp_MessageTag_20);
                _jsp_FmtParamTag_23.setValue(111);
                int _jsp_start_flag_23 = _jsp_FmtParamTag_23.doStartTag();

                if(_jsp_start_flag_23 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_23 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_23.doAfterBody();
                }
                _jsp_FmtParamTag_23.doEndTag();
                _jsp_FmtParamTag_23.release();
                // NODE END: lineNumber: 15, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_23

                // NODE START: lineNumber: 16, offset: 24, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_25
                // <fmt:param value=\"222\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_25 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_25.setPageContext(pageContext);
                _jsp_FmtParamTag_25.setParent(_jsp_MessageTag_20);
                _jsp_FmtParamTag_25.setValue(222);
                int _jsp_start_flag_25 = _jsp_FmtParamTag_25.doStartTag();

                if(_jsp_start_flag_25 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_25 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_25.doAfterBody();
                }
                _jsp_FmtParamTag_25.doEndTag();
                _jsp_FmtParamTag_25.release();
                // NODE END: lineNumber: 16, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_25

                // NODE START: lineNumber: 17, offset: 26, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_27
                // <fmt:param value=\"333\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_27 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_27.setPageContext(pageContext);
                _jsp_FmtParamTag_27.setParent(_jsp_MessageTag_20);
                _jsp_FmtParamTag_27.setValue(333);
                int _jsp_start_flag_27 = _jsp_FmtParamTag_27.doStartTag();

                if(_jsp_start_flag_27 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_27 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_27.doAfterBody();
                }
                _jsp_FmtParamTag_27.doEndTag();
                _jsp_FmtParamTag_27.release();
                // NODE END: lineNumber: 17, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_27

                _jsp_flag_20 = _jsp_MessageTag_20.doAfterBody();
            }
            while(_jsp_flag_20 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_20 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_MessageTag_20.doEndTag();
        _jsp_MessageTag_20.release();
        // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_20

        // TEXT: lineNumber: 18
        // out.write("\r\n");
        out.write(_jsp_string_30, 0, _jsp_string_30.length);

        // NODE START: lineNumber: 20, offset: 30, length: 14, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_31
        // <fmt:message key=\"test.common.test4\" bundle=\"ayada_i18n\">...</fmt:message>
        com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_31 = new com.skin.ayada.jstl.fmt.MessageTag();
        _jsp_MessageTag_31.setPageContext(pageContext);
        _jsp_MessageTag_31.setParent((Tag)null);
        _jsp_MessageTag_31.setKey("test.common.test4");
        _jsp_MessageTag_31.setBundle("ayada_i18n");
        int _jsp_start_flag_31 = _jsp_MessageTag_31.doStartTag();

        if(_jsp_start_flag_31 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_31 != Tag.SKIP_BODY) {
            int _jsp_flag_31 = 0;
            if(_jsp_start_flag_31 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_31 = pageContext.pushBody();
                _jsp_MessageTag_31.setBodyContent(_jsp_body_content_31);
                _jsp_MessageTag_31.doInitBody();
                out = _jsp_body_content_31;
            }

            do {
                // NODE START: lineNumber: 21, offset: 31, length: 3, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_32
                // <fmt:param>...</fmt:param>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_32 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_32.setPageContext(pageContext);
                _jsp_FmtParamTag_32.setParent(_jsp_MessageTag_31);
                int _jsp_start_flag_32 = _jsp_FmtParamTag_32.doStartTag();

                if(_jsp_start_flag_32 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_32 != Tag.SKIP_BODY) {
                    int _jsp_flag_32 = 0;
                    if(_jsp_start_flag_32 == BodyTag.EVAL_BODY_BUFFERED) {
                        BodyContent _jsp_body_content_32 = pageContext.pushBody();
                        _jsp_FmtParamTag_32.setBodyContent(_jsp_body_content_32);
                        _jsp_FmtParamTag_32.doInitBody();
                        out = _jsp_body_content_32;
                    }

                    do {
                        // TEXT: lineNumber: 21
                        // out.write("000");
                        out.write(_jsp_string_33, 0, _jsp_string_33.length);
                        _jsp_flag_32 = _jsp_FmtParamTag_32.doAfterBody();
                    }
                    while(_jsp_flag_32 == IterationTag.EVAL_BODY_AGAIN);
                    if(_jsp_start_flag_32 == BodyTag.EVAL_BODY_BUFFERED) {
                        out = pageContext.popBody();
                    }
                }
                _jsp_FmtParamTag_32.doEndTag();
                _jsp_FmtParamTag_32.release();
                // NODE END: lineNumber: 21, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_32

                // NODE START: lineNumber: 22, offset: 34, length: 3, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_35
                // <fmt:param>...</fmt:param>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_35 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_35.setPageContext(pageContext);
                _jsp_FmtParamTag_35.setParent(_jsp_MessageTag_31);
                int _jsp_start_flag_35 = _jsp_FmtParamTag_35.doStartTag();

                if(_jsp_start_flag_35 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_35 != Tag.SKIP_BODY) {
                    int _jsp_flag_35 = 0;
                    if(_jsp_start_flag_35 == BodyTag.EVAL_BODY_BUFFERED) {
                        BodyContent _jsp_body_content_35 = pageContext.pushBody();
                        _jsp_FmtParamTag_35.setBodyContent(_jsp_body_content_35);
                        _jsp_FmtParamTag_35.doInitBody();
                        out = _jsp_body_content_35;
                    }

                    do {
                        // TEXT: lineNumber: 22
                        // out.write("111");
                        out.write(_jsp_string_36, 0, _jsp_string_36.length);
                        _jsp_flag_35 = _jsp_FmtParamTag_35.doAfterBody();
                    }
                    while(_jsp_flag_35 == IterationTag.EVAL_BODY_AGAIN);
                    if(_jsp_start_flag_35 == BodyTag.EVAL_BODY_BUFFERED) {
                        out = pageContext.popBody();
                    }
                }
                _jsp_FmtParamTag_35.doEndTag();
                _jsp_FmtParamTag_35.release();
                // NODE END: lineNumber: 22, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_35

                // NODE START: lineNumber: 23, offset: 37, length: 3, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_38
                // <fmt:param>...</fmt:param>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_38 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_38.setPageContext(pageContext);
                _jsp_FmtParamTag_38.setParent(_jsp_MessageTag_31);
                int _jsp_start_flag_38 = _jsp_FmtParamTag_38.doStartTag();

                if(_jsp_start_flag_38 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_38 != Tag.SKIP_BODY) {
                    int _jsp_flag_38 = 0;
                    if(_jsp_start_flag_38 == BodyTag.EVAL_BODY_BUFFERED) {
                        BodyContent _jsp_body_content_38 = pageContext.pushBody();
                        _jsp_FmtParamTag_38.setBodyContent(_jsp_body_content_38);
                        _jsp_FmtParamTag_38.doInitBody();
                        out = _jsp_body_content_38;
                    }

                    do {
                        // TEXT: lineNumber: 23
                        // out.write("222");
                        out.write(_jsp_string_39, 0, _jsp_string_39.length);
                        _jsp_flag_38 = _jsp_FmtParamTag_38.doAfterBody();
                    }
                    while(_jsp_flag_38 == IterationTag.EVAL_BODY_AGAIN);
                    if(_jsp_start_flag_38 == BodyTag.EVAL_BODY_BUFFERED) {
                        out = pageContext.popBody();
                    }
                }
                _jsp_FmtParamTag_38.doEndTag();
                _jsp_FmtParamTag_38.release();
                // NODE END: lineNumber: 23, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_38

                // NODE START: lineNumber: 24, offset: 40, length: 3, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_41
                // <fmt:param>...</fmt:param>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_41 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_41.setPageContext(pageContext);
                _jsp_FmtParamTag_41.setParent(_jsp_MessageTag_31);
                int _jsp_start_flag_41 = _jsp_FmtParamTag_41.doStartTag();

                if(_jsp_start_flag_41 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_41 != Tag.SKIP_BODY) {
                    int _jsp_flag_41 = 0;
                    if(_jsp_start_flag_41 == BodyTag.EVAL_BODY_BUFFERED) {
                        BodyContent _jsp_body_content_41 = pageContext.pushBody();
                        _jsp_FmtParamTag_41.setBodyContent(_jsp_body_content_41);
                        _jsp_FmtParamTag_41.doInitBody();
                        out = _jsp_body_content_41;
                    }

                    do {
                        // TEXT: lineNumber: 24
                        // out.write("333");
                        out.write(_jsp_string_42, 0, _jsp_string_42.length);
                        _jsp_flag_41 = _jsp_FmtParamTag_41.doAfterBody();
                    }
                    while(_jsp_flag_41 == IterationTag.EVAL_BODY_AGAIN);
                    if(_jsp_start_flag_41 == BodyTag.EVAL_BODY_BUFFERED) {
                        out = pageContext.popBody();
                    }
                }
                _jsp_FmtParamTag_41.doEndTag();
                _jsp_FmtParamTag_41.release();
                // NODE END: lineNumber: 24, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_41

                _jsp_flag_31 = _jsp_MessageTag_31.doAfterBody();
            }
            while(_jsp_flag_31 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_31 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_MessageTag_31.doEndTag();
        _jsp_MessageTag_31.release();
        // NODE END: lineNumber: 20, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_31

        // TEXT: lineNumber: 25
        // out.write("\r\n");
        out.write(_jsp_string_45, 0, _jsp_string_45.length);

        // NODE START: lineNumber: 27, offset: 45, length: 10, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_46
        // <fmt:message key=\"test.common.test4\" bundle=\"ayada_i18n\">...</fmt:message>
        com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_46 = new com.skin.ayada.jstl.fmt.MessageTag();
        _jsp_MessageTag_46.setPageContext(pageContext);
        _jsp_MessageTag_46.setParent((Tag)null);
        _jsp_MessageTag_46.setKey("test.common.test4");
        _jsp_MessageTag_46.setBundle("ayada_i18n");
        int _jsp_start_flag_46 = _jsp_MessageTag_46.doStartTag();

        if(_jsp_start_flag_46 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_46 != Tag.SKIP_BODY) {
            int _jsp_flag_46 = 0;
            if(_jsp_start_flag_46 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_46 = pageContext.pushBody();
                _jsp_MessageTag_46.setBodyContent(_jsp_body_content_46);
                _jsp_MessageTag_46.doInitBody();
                out = _jsp_body_content_46;
            }

            do {
                // NODE START: lineNumber: 28, offset: 46, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_47
                // <fmt:param value=\"aaa\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_47 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_47.setPageContext(pageContext);
                _jsp_FmtParamTag_47.setParent(_jsp_MessageTag_46);
                _jsp_FmtParamTag_47.setValue("aaa");
                int _jsp_start_flag_47 = _jsp_FmtParamTag_47.doStartTag();

                if(_jsp_start_flag_47 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_47 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_47.doAfterBody();
                }
                _jsp_FmtParamTag_47.doEndTag();
                _jsp_FmtParamTag_47.release();
                // NODE END: lineNumber: 28, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_47

                // NODE START: lineNumber: 29, offset: 48, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_49
                // <fmt:param value=\"bbb\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_49 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_49.setPageContext(pageContext);
                _jsp_FmtParamTag_49.setParent(_jsp_MessageTag_46);
                _jsp_FmtParamTag_49.setValue("bbb");
                int _jsp_start_flag_49 = _jsp_FmtParamTag_49.doStartTag();

                if(_jsp_start_flag_49 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_49 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_49.doAfterBody();
                }
                _jsp_FmtParamTag_49.doEndTag();
                _jsp_FmtParamTag_49.release();
                // NODE END: lineNumber: 29, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_49

                // NODE START: lineNumber: 30, offset: 50, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_51
                // <fmt:param value=\"ccc\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_51 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_51.setPageContext(pageContext);
                _jsp_FmtParamTag_51.setParent(_jsp_MessageTag_46);
                _jsp_FmtParamTag_51.setValue("ccc");
                int _jsp_start_flag_51 = _jsp_FmtParamTag_51.doStartTag();

                if(_jsp_start_flag_51 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_51 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_51.doAfterBody();
                }
                _jsp_FmtParamTag_51.doEndTag();
                _jsp_FmtParamTag_51.release();
                // NODE END: lineNumber: 30, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_51

                // NODE START: lineNumber: 31, offset: 52, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_53
                // <fmt:param value=\"ddd\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_53 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_53.setPageContext(pageContext);
                _jsp_FmtParamTag_53.setParent(_jsp_MessageTag_46);
                _jsp_FmtParamTag_53.setValue("ddd");
                int _jsp_start_flag_53 = _jsp_FmtParamTag_53.doStartTag();

                if(_jsp_start_flag_53 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_53 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_53.doAfterBody();
                }
                _jsp_FmtParamTag_53.doEndTag();
                _jsp_FmtParamTag_53.release();
                // NODE END: lineNumber: 31, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_53

                _jsp_flag_46 = _jsp_MessageTag_46.doAfterBody();
            }
            while(_jsp_flag_46 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_46 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_MessageTag_46.doEndTag();
        _jsp_MessageTag_46.release();
        // NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_46

        // TEXT: lineNumber: 32
        // out.write("\r\n");
        out.write(_jsp_string_56, 0, _jsp_string_56.length);

        // NODE START: lineNumber: 34, offset: 56, length: 2, tagClassName: com.skin.ayada.jstl.fmt.SetLocaleTag, tagInstanceName: _jsp_SetLocaleTag_57
        // <fmt:setLocale value=\"fr_fr\"/>
        com.skin.ayada.jstl.fmt.SetLocaleTag _jsp_SetLocaleTag_57 = new com.skin.ayada.jstl.fmt.SetLocaleTag();
        _jsp_SetLocaleTag_57.setPageContext(pageContext);
        _jsp_SetLocaleTag_57.setParent((Tag)null);
        _jsp_SetLocaleTag_57.setValue("fr_fr");
        int _jsp_start_flag_57 = _jsp_SetLocaleTag_57.doStartTag();

        if(_jsp_start_flag_57 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_57 != Tag.SKIP_BODY) {
            _jsp_SetLocaleTag_57.doAfterBody();
        }
        _jsp_SetLocaleTag_57.doEndTag();
        _jsp_SetLocaleTag_57.release();
        // NODE END: lineNumber: 34, tagClassName: com.skin.ayada.jstl.fmt.SetLocaleTag, tagInstanceName: _jsp_SetLocaleTag_57

        // NODE START: lineNumber: 35, offset: 58, length: 2, tagClassName: com.skin.ayada.jstl.fmt.NumberFormatTag, tagInstanceName: _jsp_NumberFormatTag_59
        // <fmt:formatNumber value=\"123456789.012\"/>
        com.skin.ayada.jstl.fmt.NumberFormatTag _jsp_NumberFormatTag_59 = new com.skin.ayada.jstl.fmt.NumberFormatTag();
        _jsp_NumberFormatTag_59.setPageContext(pageContext);
        _jsp_NumberFormatTag_59.setParent((Tag)null);
        _jsp_NumberFormatTag_59.setValue(1.23456789012E8d);
        int _jsp_start_flag_59 = _jsp_NumberFormatTag_59.doStartTag();

        if(_jsp_start_flag_59 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_59 != Tag.SKIP_BODY) {
            _jsp_NumberFormatTag_59.doAfterBody();
        }
        _jsp_NumberFormatTag_59.doEndTag();
        _jsp_NumberFormatTag_59.release();
        // NODE END: lineNumber: 35, tagClassName: com.skin.ayada.jstl.fmt.NumberFormatTag, tagInstanceName: _jsp_NumberFormatTag_59

        // TEXT: lineNumber: 35
        // out.write("\r\n");
        out.write(_jsp_string_61, 0, _jsp_string_61.length);

        // NODE START: lineNumber: 37, offset: 61, length: 2, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_62
        // <c:list name=\"userList\"/>
        com.skin.ayada.jstl.core.ListTag _jsp_ListTag_62 = new com.skin.ayada.jstl.core.ListTag();
        _jsp_ListTag_62.setPageContext(pageContext);
        _jsp_ListTag_62.setParent((Tag)null);
        _jsp_ListTag_62.setName("userList");
        int _jsp_start_flag_62 = _jsp_ListTag_62.doStartTag();

        if(_jsp_start_flag_62 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_62 != Tag.SKIP_BODY) {
            _jsp_ListTag_62.doAfterBody();
        }
        _jsp_ListTag_62.doEndTag();
        _jsp_ListTag_62.release();
        // NODE END: lineNumber: 37, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_62

        // NODE START: lineNumber: 38, offset: 63, length: 17, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_64
        // <c:forEach begin=\"1\" end=\"5\" var=\"myInt\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_64 = pageContext.getAttribute("myInt");
        Object _jsp_old_var_status_64 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_64 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_64.setParent((Tag)null);
        _jsp_ForEachTag_64.setPageContext(pageContext);
        _jsp_ForEachTag_64.setVar("myInt");
        _jsp_ForEachTag_64.setBegin(1);
        _jsp_ForEachTag_64.setEnd(5);
        _jsp_ForEachTag_64.setVarStatus("status");
        if(_jsp_ForEachTag_64.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // NODE START: lineNumber: 39, offset: 64, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_65
                // <c:map name=\"user\">...</c:map>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_65 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_65.setPageContext(pageContext);
                _jsp_MapTag_65.setParent((Tag)null);
                _jsp_MapTag_65.setDynamicAttribute("name", "user");
                int _jsp_start_flag_65 = _jsp_MapTag_65.doStartTag();

                if(_jsp_start_flag_65 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_65 != Tag.SKIP_BODY) {
                    int _jsp_flag_65 = 0;

                    do {
                        // NODE START: lineNumber: 40, offset: 65, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_66
                        // <c:entry name=\"userName\" value=\"ayada${status.index}\"/>
                        _jsp_MapTag_65.setAttribute("userName", ExpressionUtil.evaluate(expressionContext, "ayada${status.index}", null));
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 40, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_66

                        // NODE START: lineNumber: 41, offset: 67, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_68
                        // <c:entry name=\"nickName\" value=\"ayada${status.index}\"/>
                        _jsp_MapTag_65.setAttribute("nickName", ExpressionUtil.evaluate(expressionContext, "ayada${status.index}", null));
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 41, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_68

                        _jsp_flag_65 = _jsp_MapTag_65.doAfterBody();
                    }
                    while(_jsp_flag_65 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_MapTag_65.doEndTag();
                _jsp_MapTag_65.release();
                // NODE END: lineNumber: 39, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_65

                // NODE START: lineNumber: 43, offset: 70, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_71
                // <c:execute value=\"${userList.add(user)}\"/>
                ExpressionUtil.evaluate(expressionContext, "${userList.add(user)}", null);
                // jsp.jstl.core.ExecuteTag END
                // NODE END: lineNumber: 43, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_71

                // TEXT: lineNumber: 43
                // out.write("    <div>1 index: ");
                out.write(_jsp_string_73, 0, _jsp_string_73.length);
                // EXPRESSION: lineNumber: 44
                expressionContext.print(out, expressionContext.getString("status.index"));
                // TEXT: lineNumber: 44
                // out.write(", myInt: ");
                out.write(_jsp_string_75, 0, _jsp_string_75.length);
                // VARIABLE: lineNumber: 44
                expressionContext.print(out, pageContext.getAttribute("myInt"));
                // TEXT: lineNumber: 44
                // out.write(", user.userName: ");
                out.write(_jsp_string_77, 0, _jsp_string_77.length);
                // EXPRESSION: lineNumber: 44
                expressionContext.print(out, expressionContext.getString("user.userName"));
                // TEXT: lineNumber: 44
                // out.write("</div>\r\n");
                out.write(_jsp_string_79, 0, _jsp_string_79.length);
                if(_jsp_ForEachTag_64.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_64.release();
        pageContext.setAttribute("myInt", _jsp_old_var_64);
        pageContext.setAttribute("status", _jsp_old_var_status_64);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 38, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_64

        // TEXT: lineNumber: 45
        // out.write("\r\n");
        out.write(_jsp_string_81, 0, _jsp_string_81.length);

        // NODE START: lineNumber: 47, offset: 81, length: 2, tagClassName: com.skin.ayada.jstl.core.CommentTag, tagInstanceName: _jsp_CommentTag_82
        // <c:comment>...</c:comment>
        if(com.skin.ayada.jstl.core.ContinueTag.getTrue()) {
        } // jsp.jstl.core.CommentTag END
        // NODE END: lineNumber: 47, tagClassName: com.skin.ayada.jstl.core.CommentTag, tagInstanceName: _jsp_CommentTag_82


        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_3 = "message1: ".toCharArray();
    public static final char[] _jsp_string_5 = "\r\nmessage2: ".toCharArray();
    public static final char[] _jsp_string_7 = "\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_10 = "message3: ".toCharArray();
    public static final char[] _jsp_string_12 = "\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_19 = "\r\n".toCharArray();
    public static final char[] _jsp_string_30 = "\r\n".toCharArray();
    public static final char[] _jsp_string_33 = "000".toCharArray();
    public static final char[] _jsp_string_36 = "111".toCharArray();
    public static final char[] _jsp_string_39 = "222".toCharArray();
    public static final char[] _jsp_string_42 = "333".toCharArray();
    public static final char[] _jsp_string_45 = "\r\n".toCharArray();
    public static final char[] _jsp_string_56 = "\r\n".toCharArray();
    public static final char[] _jsp_string_61 = "\r\n".toCharArray();
    public static final char[] _jsp_string_73 = "    <div>1 index: ".toCharArray();
    public static final char[] _jsp_string_75 = ", myInt: ".toCharArray();
    public static final char[] _jsp_string_77 = ", user.userName: ".toCharArray();
    public static final char[] _jsp_string_79 = "</div>\r\n".toCharArray();
    public static final char[] _jsp_string_81 = "\r\n".toCharArray();

}
