/*
 * $RCSfile: FmtTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /fmtTest.jsp
 * lastModified: 2014-06-13 09:58:06 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-12 23:30:02 399)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: FmtTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class FmtTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        FmtTestTemplate template = new FmtTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_1
        // <c:set var=\"i18n\" value=\"${I18n.getBundle(&#39;ayada_i18n&#39;, &#39;zh_cn&#39;)}\"/>
        pageContext.setAttribute("i18n", ExpressionUtil.evaluate(expressionContext, "${I18n.getBundle(\'ayada_i18n\', \'zh_cn\')}", null));
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_1

        // TEXT: lineNumber: 1
        // out.write("message1: ");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        // EXPRESSION: lineNumber: 2
        expressionContext.print(out, expressionContext.getString("i18n.format(\"test.common.test4\", \"000\", \"111\", \"222\", \"333\")"));
        // TEXT: lineNumber: 2
        // out.write("\r\nmessage2: ");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);
        // EXPRESSION: lineNumber: 3
        expressionContext.print(out, expressionContext.getString("i18n.message(\"test.common.test4\")"));
        // TEXT: lineNumber: 3
        // out.write("\r\n\r\n");
        out.write(_jsp_string_7, 0, _jsp_string_7.length);

        // NODE START: lineNumber: 5, offset: 7, length: 2, tagClassName: com.skin.ayada.jstl.fmt.SetBundleTag, tagInstanceName: _jsp_SetBundleTag_8
        // <fmt:setBundle var=\"myI18n\" basename=\"ayada_i18n\"/>
        com.skin.ayada.jstl.fmt.SetBundleTag _jsp_SetBundleTag_8 = new com.skin.ayada.jstl.fmt.SetBundleTag();
        _jsp_SetBundleTag_8.setPageContext(pageContext);
        _jsp_SetBundleTag_8.setParent((Tag)null);
        _jsp_SetBundleTag_8.setVar("myI18n");
        _jsp_SetBundleTag_8.setBasename("ayada_i18n");
        int _jsp_start_flag_8 = _jsp_SetBundleTag_8.doStartTag();

        if(_jsp_start_flag_8 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_8 != Tag.SKIP_BODY) {
            _jsp_SetBundleTag_8.doAfterBody();
        }
        _jsp_SetBundleTag_8.doEndTag();
        _jsp_SetBundleTag_8.release();
        // NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.fmt.SetBundleTag, tagInstanceName: _jsp_SetBundleTag_8

        // TEXT: lineNumber: 5
        // out.write("message3: ");
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        // EXPRESSION: lineNumber: 6
        expressionContext.print(out, expressionContext.getString("myI18n.format(\"test.common.test4\", \"000\", \"111\", \"222\", \"333\")"));
        // TEXT: lineNumber: 6
        // out.write("\r\n\r\n");
        out.write(_jsp_string_12, 0, _jsp_string_12.length);

        // NODE START: lineNumber: 8, offset: 12, length: 4, tagClassName: com.skin.ayada.jstl.fmt.BundleTag, tagInstanceName: _jsp_BundleTag_13
        // <fmt:bundle basename=\"ayada_i18n\">...</fmt:bundle>
        com.skin.ayada.jstl.fmt.BundleTag _jsp_BundleTag_13 = new com.skin.ayada.jstl.fmt.BundleTag();
        try {
            _jsp_BundleTag_13.setPageContext(pageContext);
            _jsp_BundleTag_13.setParent((Tag)null);
            _jsp_BundleTag_13.setBasename("ayada_i18n");
            int _jsp_start_flag_13 = _jsp_BundleTag_13.doStartTag();

            if(_jsp_start_flag_13 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_13 != Tag.SKIP_BODY) {
                int _jsp_flag_13 = 0;

                do {
                    // NODE START: lineNumber: 9, offset: 13, length: 2, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_14
                    // <fmt:message key=\"test.common.test1\"/>
                    com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_14 = new com.skin.ayada.jstl.fmt.MessageTag();
                    _jsp_MessageTag_14.setPageContext(pageContext);
                    _jsp_MessageTag_14.setParent(_jsp_BundleTag_13);
                    _jsp_MessageTag_14.setKey("test.common.test1");
                    int _jsp_start_flag_14 = _jsp_MessageTag_14.doStartTag();

                    if(_jsp_start_flag_14 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_14 != Tag.SKIP_BODY) {
                        _jsp_MessageTag_14.doAfterBody();
                    }
                    _jsp_MessageTag_14.doEndTag();
                    _jsp_MessageTag_14.release();
                    // NODE END: lineNumber: 9, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_14

                    _jsp_flag_13 = _jsp_BundleTag_13.doAfterBody();
                }
                while(_jsp_flag_13 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_BundleTag_13.doEndTag();
            _jsp_BundleTag_13.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_BundleTag_13.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_BundleTag_13.doFinally();
        }
        // NODE END: lineNumber: 8, tagClassName: com.skin.ayada.jstl.fmt.BundleTag, tagInstanceName: _jsp_BundleTag_13

        // NODE START: lineNumber: 11, offset: 16, length: 2, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_17
        // <fmt:message key=\"test.common.test2\" bundle=\"ayada_i18n\"/>
        com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_17 = new com.skin.ayada.jstl.fmt.MessageTag();
        _jsp_MessageTag_17.setPageContext(pageContext);
        _jsp_MessageTag_17.setParent((Tag)null);
        _jsp_MessageTag_17.setKey("test.common.test2");
        _jsp_MessageTag_17.setBundle("ayada_i18n");
        int _jsp_start_flag_17 = _jsp_MessageTag_17.doStartTag();

        if(_jsp_start_flag_17 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_17 != Tag.SKIP_BODY) {
            _jsp_MessageTag_17.doAfterBody();
        }
        _jsp_MessageTag_17.doEndTag();
        _jsp_MessageTag_17.release();
        // NODE END: lineNumber: 11, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_17

        // NODE START: lineNumber: 13, offset: 18, length: 10, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_19
        // <fmt:message key=\"test.common.test4\" bundle=\"ayada_i18n\">...</fmt:message>
        com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_19 = new com.skin.ayada.jstl.fmt.MessageTag();
        _jsp_MessageTag_19.setPageContext(pageContext);
        _jsp_MessageTag_19.setParent((Tag)null);
        _jsp_MessageTag_19.setKey("test.common.test4");
        _jsp_MessageTag_19.setBundle("ayada_i18n");
        int _jsp_start_flag_19 = _jsp_MessageTag_19.doStartTag();

        if(_jsp_start_flag_19 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_19 != Tag.SKIP_BODY) {
            int _jsp_flag_19 = 0;
            if(_jsp_start_flag_19 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_19 = pageContext.pushBody();
                _jsp_MessageTag_19.setBodyContent(_jsp_body_content_19);
                _jsp_MessageTag_19.doInitBody();
                out = _jsp_body_content_19;
            }

            do {
                // NODE START: lineNumber: 14, offset: 19, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_20
                // <fmt:param value=\"000\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_20 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_20.setPageContext(pageContext);
                _jsp_FmtParamTag_20.setParent(_jsp_MessageTag_19);
                _jsp_FmtParamTag_20.setValue(0);
                int _jsp_start_flag_20 = _jsp_FmtParamTag_20.doStartTag();

                if(_jsp_start_flag_20 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_20 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_20.doAfterBody();
                }
                _jsp_FmtParamTag_20.doEndTag();
                _jsp_FmtParamTag_20.release();
                // NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_20

                // NODE START: lineNumber: 15, offset: 21, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_22
                // <fmt:param value=\"111\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_22 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_22.setPageContext(pageContext);
                _jsp_FmtParamTag_22.setParent(_jsp_MessageTag_19);
                _jsp_FmtParamTag_22.setValue(111);
                int _jsp_start_flag_22 = _jsp_FmtParamTag_22.doStartTag();

                if(_jsp_start_flag_22 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_22 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_22.doAfterBody();
                }
                _jsp_FmtParamTag_22.doEndTag();
                _jsp_FmtParamTag_22.release();
                // NODE END: lineNumber: 15, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_22

                // NODE START: lineNumber: 16, offset: 23, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_24
                // <fmt:param value=\"222\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_24 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_24.setPageContext(pageContext);
                _jsp_FmtParamTag_24.setParent(_jsp_MessageTag_19);
                _jsp_FmtParamTag_24.setValue(222);
                int _jsp_start_flag_24 = _jsp_FmtParamTag_24.doStartTag();

                if(_jsp_start_flag_24 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_24 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_24.doAfterBody();
                }
                _jsp_FmtParamTag_24.doEndTag();
                _jsp_FmtParamTag_24.release();
                // NODE END: lineNumber: 16, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_24

                // NODE START: lineNumber: 17, offset: 25, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_26
                // <fmt:param value=\"333\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_26 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_26.setPageContext(pageContext);
                _jsp_FmtParamTag_26.setParent(_jsp_MessageTag_19);
                _jsp_FmtParamTag_26.setValue(333);
                int _jsp_start_flag_26 = _jsp_FmtParamTag_26.doStartTag();

                if(_jsp_start_flag_26 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_26 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_26.doAfterBody();
                }
                _jsp_FmtParamTag_26.doEndTag();
                _jsp_FmtParamTag_26.release();
                // NODE END: lineNumber: 17, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_26

                _jsp_flag_19 = _jsp_MessageTag_19.doAfterBody();
            }
            while(_jsp_flag_19 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_19 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_MessageTag_19.doEndTag();
        _jsp_MessageTag_19.release();
        // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_19

        // NODE START: lineNumber: 20, offset: 28, length: 14, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_29
        // <fmt:message key=\"test.common.test4\" bundle=\"ayada_i18n\">...</fmt:message>
        com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_29 = new com.skin.ayada.jstl.fmt.MessageTag();
        _jsp_MessageTag_29.setPageContext(pageContext);
        _jsp_MessageTag_29.setParent((Tag)null);
        _jsp_MessageTag_29.setKey("test.common.test4");
        _jsp_MessageTag_29.setBundle("ayada_i18n");
        int _jsp_start_flag_29 = _jsp_MessageTag_29.doStartTag();

        if(_jsp_start_flag_29 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_29 != Tag.SKIP_BODY) {
            int _jsp_flag_29 = 0;
            if(_jsp_start_flag_29 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_29 = pageContext.pushBody();
                _jsp_MessageTag_29.setBodyContent(_jsp_body_content_29);
                _jsp_MessageTag_29.doInitBody();
                out = _jsp_body_content_29;
            }

            do {
                // NODE START: lineNumber: 21, offset: 29, length: 3, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_30
                // <fmt:param>...</fmt:param>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_30 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_30.setPageContext(pageContext);
                _jsp_FmtParamTag_30.setParent(_jsp_MessageTag_29);
                int _jsp_start_flag_30 = _jsp_FmtParamTag_30.doStartTag();

                if(_jsp_start_flag_30 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_30 != Tag.SKIP_BODY) {
                    int _jsp_flag_30 = 0;
                    if(_jsp_start_flag_30 == BodyTag.EVAL_BODY_BUFFERED) {
                        BodyContent _jsp_body_content_30 = pageContext.pushBody();
                        _jsp_FmtParamTag_30.setBodyContent(_jsp_body_content_30);
                        _jsp_FmtParamTag_30.doInitBody();
                        out = _jsp_body_content_30;
                    }

                    do {
                        // TEXT: lineNumber: 21
                        // out.write("000");
                        out.write(_jsp_string_31, 0, _jsp_string_31.length);
                        _jsp_flag_30 = _jsp_FmtParamTag_30.doAfterBody();
                    }
                    while(_jsp_flag_30 == IterationTag.EVAL_BODY_AGAIN);
                    if(_jsp_start_flag_30 == BodyTag.EVAL_BODY_BUFFERED) {
                        out = pageContext.popBody();
                    }
                }
                _jsp_FmtParamTag_30.doEndTag();
                _jsp_FmtParamTag_30.release();
                // NODE END: lineNumber: 21, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_30

                // NODE START: lineNumber: 22, offset: 32, length: 3, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_33
                // <fmt:param>...</fmt:param>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_33 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_33.setPageContext(pageContext);
                _jsp_FmtParamTag_33.setParent(_jsp_MessageTag_29);
                int _jsp_start_flag_33 = _jsp_FmtParamTag_33.doStartTag();

                if(_jsp_start_flag_33 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_33 != Tag.SKIP_BODY) {
                    int _jsp_flag_33 = 0;
                    if(_jsp_start_flag_33 == BodyTag.EVAL_BODY_BUFFERED) {
                        BodyContent _jsp_body_content_33 = pageContext.pushBody();
                        _jsp_FmtParamTag_33.setBodyContent(_jsp_body_content_33);
                        _jsp_FmtParamTag_33.doInitBody();
                        out = _jsp_body_content_33;
                    }

                    do {
                        // TEXT: lineNumber: 22
                        // out.write("111");
                        out.write(_jsp_string_34, 0, _jsp_string_34.length);
                        _jsp_flag_33 = _jsp_FmtParamTag_33.doAfterBody();
                    }
                    while(_jsp_flag_33 == IterationTag.EVAL_BODY_AGAIN);
                    if(_jsp_start_flag_33 == BodyTag.EVAL_BODY_BUFFERED) {
                        out = pageContext.popBody();
                    }
                }
                _jsp_FmtParamTag_33.doEndTag();
                _jsp_FmtParamTag_33.release();
                // NODE END: lineNumber: 22, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_33

                // NODE START: lineNumber: 23, offset: 35, length: 3, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_36
                // <fmt:param>...</fmt:param>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_36 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_36.setPageContext(pageContext);
                _jsp_FmtParamTag_36.setParent(_jsp_MessageTag_29);
                int _jsp_start_flag_36 = _jsp_FmtParamTag_36.doStartTag();

                if(_jsp_start_flag_36 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_36 != Tag.SKIP_BODY) {
                    int _jsp_flag_36 = 0;
                    if(_jsp_start_flag_36 == BodyTag.EVAL_BODY_BUFFERED) {
                        BodyContent _jsp_body_content_36 = pageContext.pushBody();
                        _jsp_FmtParamTag_36.setBodyContent(_jsp_body_content_36);
                        _jsp_FmtParamTag_36.doInitBody();
                        out = _jsp_body_content_36;
                    }

                    do {
                        // TEXT: lineNumber: 23
                        // out.write("222");
                        out.write(_jsp_string_37, 0, _jsp_string_37.length);
                        _jsp_flag_36 = _jsp_FmtParamTag_36.doAfterBody();
                    }
                    while(_jsp_flag_36 == IterationTag.EVAL_BODY_AGAIN);
                    if(_jsp_start_flag_36 == BodyTag.EVAL_BODY_BUFFERED) {
                        out = pageContext.popBody();
                    }
                }
                _jsp_FmtParamTag_36.doEndTag();
                _jsp_FmtParamTag_36.release();
                // NODE END: lineNumber: 23, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_36

                // NODE START: lineNumber: 24, offset: 38, length: 3, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_39
                // <fmt:param>...</fmt:param>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_39 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_39.setPageContext(pageContext);
                _jsp_FmtParamTag_39.setParent(_jsp_MessageTag_29);
                int _jsp_start_flag_39 = _jsp_FmtParamTag_39.doStartTag();

                if(_jsp_start_flag_39 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_39 != Tag.SKIP_BODY) {
                    int _jsp_flag_39 = 0;
                    if(_jsp_start_flag_39 == BodyTag.EVAL_BODY_BUFFERED) {
                        BodyContent _jsp_body_content_39 = pageContext.pushBody();
                        _jsp_FmtParamTag_39.setBodyContent(_jsp_body_content_39);
                        _jsp_FmtParamTag_39.doInitBody();
                        out = _jsp_body_content_39;
                    }

                    do {
                        // TEXT: lineNumber: 24
                        // out.write("333");
                        out.write(_jsp_string_40, 0, _jsp_string_40.length);
                        _jsp_flag_39 = _jsp_FmtParamTag_39.doAfterBody();
                    }
                    while(_jsp_flag_39 == IterationTag.EVAL_BODY_AGAIN);
                    if(_jsp_start_flag_39 == BodyTag.EVAL_BODY_BUFFERED) {
                        out = pageContext.popBody();
                    }
                }
                _jsp_FmtParamTag_39.doEndTag();
                _jsp_FmtParamTag_39.release();
                // NODE END: lineNumber: 24, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_39

                _jsp_flag_29 = _jsp_MessageTag_29.doAfterBody();
            }
            while(_jsp_flag_29 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_29 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_MessageTag_29.doEndTag();
        _jsp_MessageTag_29.release();
        // NODE END: lineNumber: 20, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_29

        // NODE START: lineNumber: 27, offset: 42, length: 10, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_43
        // <fmt:message key=\"test.common.test4\" bundle=\"ayada_i18n\">...</fmt:message>
        com.skin.ayada.jstl.fmt.MessageTag _jsp_MessageTag_43 = new com.skin.ayada.jstl.fmt.MessageTag();
        _jsp_MessageTag_43.setPageContext(pageContext);
        _jsp_MessageTag_43.setParent((Tag)null);
        _jsp_MessageTag_43.setKey("test.common.test4");
        _jsp_MessageTag_43.setBundle("ayada_i18n");
        int _jsp_start_flag_43 = _jsp_MessageTag_43.doStartTag();

        if(_jsp_start_flag_43 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_43 != Tag.SKIP_BODY) {
            int _jsp_flag_43 = 0;
            if(_jsp_start_flag_43 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_43 = pageContext.pushBody();
                _jsp_MessageTag_43.setBodyContent(_jsp_body_content_43);
                _jsp_MessageTag_43.doInitBody();
                out = _jsp_body_content_43;
            }

            do {
                // NODE START: lineNumber: 28, offset: 43, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_44
                // <fmt:param value=\"aaa\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_44 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_44.setPageContext(pageContext);
                _jsp_FmtParamTag_44.setParent(_jsp_MessageTag_43);
                _jsp_FmtParamTag_44.setValue("aaa");
                int _jsp_start_flag_44 = _jsp_FmtParamTag_44.doStartTag();

                if(_jsp_start_flag_44 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_44 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_44.doAfterBody();
                }
                _jsp_FmtParamTag_44.doEndTag();
                _jsp_FmtParamTag_44.release();
                // NODE END: lineNumber: 28, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_44

                // NODE START: lineNumber: 29, offset: 45, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_46
                // <fmt:param value=\"bbb\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_46 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_46.setPageContext(pageContext);
                _jsp_FmtParamTag_46.setParent(_jsp_MessageTag_43);
                _jsp_FmtParamTag_46.setValue("bbb");
                int _jsp_start_flag_46 = _jsp_FmtParamTag_46.doStartTag();

                if(_jsp_start_flag_46 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_46 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_46.doAfterBody();
                }
                _jsp_FmtParamTag_46.doEndTag();
                _jsp_FmtParamTag_46.release();
                // NODE END: lineNumber: 29, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_46

                // NODE START: lineNumber: 30, offset: 47, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_48
                // <fmt:param value=\"ccc\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_48 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_48.setPageContext(pageContext);
                _jsp_FmtParamTag_48.setParent(_jsp_MessageTag_43);
                _jsp_FmtParamTag_48.setValue("ccc");
                int _jsp_start_flag_48 = _jsp_FmtParamTag_48.doStartTag();

                if(_jsp_start_flag_48 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_48 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_48.doAfterBody();
                }
                _jsp_FmtParamTag_48.doEndTag();
                _jsp_FmtParamTag_48.release();
                // NODE END: lineNumber: 30, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_48

                // NODE START: lineNumber: 31, offset: 49, length: 2, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_50
                // <fmt:param value=\"ddd\"/>
                com.skin.ayada.jstl.fmt.FmtParamTag _jsp_FmtParamTag_50 = new com.skin.ayada.jstl.fmt.FmtParamTag();
                _jsp_FmtParamTag_50.setPageContext(pageContext);
                _jsp_FmtParamTag_50.setParent(_jsp_MessageTag_43);
                _jsp_FmtParamTag_50.setValue("ddd");
                int _jsp_start_flag_50 = _jsp_FmtParamTag_50.doStartTag();

                if(_jsp_start_flag_50 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_50 != Tag.SKIP_BODY) {
                    _jsp_FmtParamTag_50.doAfterBody();
                }
                _jsp_FmtParamTag_50.doEndTag();
                _jsp_FmtParamTag_50.release();
                // NODE END: lineNumber: 31, tagClassName: com.skin.ayada.jstl.fmt.FmtParamTag, tagInstanceName: _jsp_FmtParamTag_50

                _jsp_flag_43 = _jsp_MessageTag_43.doAfterBody();
            }
            while(_jsp_flag_43 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_43 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_MessageTag_43.doEndTag();
        _jsp_MessageTag_43.release();
        // NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.fmt.MessageTag, tagInstanceName: _jsp_MessageTag_43

        // NODE START: lineNumber: 34, offset: 52, length: 2, tagClassName: com.skin.ayada.jstl.fmt.SetLocaleTag, tagInstanceName: _jsp_SetLocaleTag_53
        // <fmt:setLocale value=\"fr_fr\"/>
        com.skin.ayada.jstl.fmt.SetLocaleTag _jsp_SetLocaleTag_53 = new com.skin.ayada.jstl.fmt.SetLocaleTag();
        _jsp_SetLocaleTag_53.setPageContext(pageContext);
        _jsp_SetLocaleTag_53.setParent((Tag)null);
        _jsp_SetLocaleTag_53.setValue("fr_fr");
        int _jsp_start_flag_53 = _jsp_SetLocaleTag_53.doStartTag();

        if(_jsp_start_flag_53 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_53 != Tag.SKIP_BODY) {
            _jsp_SetLocaleTag_53.doAfterBody();
        }
        _jsp_SetLocaleTag_53.doEndTag();
        _jsp_SetLocaleTag_53.release();
        // NODE END: lineNumber: 34, tagClassName: com.skin.ayada.jstl.fmt.SetLocaleTag, tagInstanceName: _jsp_SetLocaleTag_53

        // NODE START: lineNumber: 35, offset: 54, length: 2, tagClassName: com.skin.ayada.jstl.fmt.NumberFormatTag, tagInstanceName: _jsp_NumberFormatTag_55
        // <fmt:formatNumber value=\"123456789.012\"/>
        com.skin.ayada.jstl.fmt.NumberFormatTag _jsp_NumberFormatTag_55 = new com.skin.ayada.jstl.fmt.NumberFormatTag();
        _jsp_NumberFormatTag_55.setPageContext(pageContext);
        _jsp_NumberFormatTag_55.setParent((Tag)null);
        _jsp_NumberFormatTag_55.setValue(1.23456789012E8d);
        int _jsp_start_flag_55 = _jsp_NumberFormatTag_55.doStartTag();

        if(_jsp_start_flag_55 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_55 != Tag.SKIP_BODY) {
            _jsp_NumberFormatTag_55.doAfterBody();
        }
        _jsp_NumberFormatTag_55.doEndTag();
        _jsp_NumberFormatTag_55.release();
        // NODE END: lineNumber: 35, tagClassName: com.skin.ayada.jstl.fmt.NumberFormatTag, tagInstanceName: _jsp_NumberFormatTag_55

        // NODE START: lineNumber: 37, offset: 56, length: 2, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_57
        // <c:list name=\"userList\"/>
        com.skin.ayada.jstl.core.ListTag _jsp_ListTag_57 = new com.skin.ayada.jstl.core.ListTag();
        _jsp_ListTag_57.setPageContext(pageContext);
        _jsp_ListTag_57.setParent((Tag)null);
        _jsp_ListTag_57.setName("userList");
        int _jsp_start_flag_57 = _jsp_ListTag_57.doStartTag();

        if(_jsp_start_flag_57 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_57 != Tag.SKIP_BODY) {
            _jsp_ListTag_57.doAfterBody();
        }
        _jsp_ListTag_57.doEndTag();
        _jsp_ListTag_57.release();
        // NODE END: lineNumber: 37, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_57

        // NODE START: lineNumber: 38, offset: 58, length: 17, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_59
        // <c:forEach begin=\"1\" end=\"5\" var=\"myInt\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_59 = pageContext.getAttribute("myInt");
        Object _jsp_old_var_status_59 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_59 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_59.setParent((Tag)null);
        _jsp_ForEachTag_59.setPageContext(pageContext);
        _jsp_ForEachTag_59.setVar("myInt");
        _jsp_ForEachTag_59.setBegin(1);
        _jsp_ForEachTag_59.setEnd(5);
        _jsp_ForEachTag_59.setVarStatus("status");
        if(_jsp_ForEachTag_59.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // NODE START: lineNumber: 39, offset: 59, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_60
                // <c:map name=\"user\">...</c:map>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_60 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_60.setPageContext(pageContext);
                _jsp_MapTag_60.setParent((Tag)null);
                _jsp_MapTag_60.setDynamicAttribute("name", "user");
                int _jsp_start_flag_60 = _jsp_MapTag_60.doStartTag();

                if(_jsp_start_flag_60 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_60 != Tag.SKIP_BODY) {
                    int _jsp_flag_60 = 0;

                    do {
                        // NODE START: lineNumber: 40, offset: 60, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_61
                        // <c:entry name=\"userName\" value=\"ayada${status.index}\"/>
                        _jsp_MapTag_60.setAttribute("userName", ExpressionUtil.evaluate(expressionContext, "ayada${status.index}", null));
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 40, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_61

                        // NODE START: lineNumber: 41, offset: 62, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_63
                        // <c:entry name=\"nickName\" value=\"ayada${status.index}\"/>
                        _jsp_MapTag_60.setAttribute("nickName", ExpressionUtil.evaluate(expressionContext, "ayada${status.index}", null));
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 41, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_63

                        _jsp_flag_60 = _jsp_MapTag_60.doAfterBody();
                    }
                    while(_jsp_flag_60 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_MapTag_60.doEndTag();
                _jsp_MapTag_60.release();
                // NODE END: lineNumber: 39, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_60

                // NODE START: lineNumber: 43, offset: 65, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_66
                // <c:execute value=\"${userList.add(user)}\"/>
                ExpressionUtil.evaluate(expressionContext, "${userList.add(user)}", null);
                // jsp.jstl.core.ExecuteTag END
                // NODE END: lineNumber: 43, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_66

                // TEXT: lineNumber: 43
                // out.write("    <div>1 index: ");
                out.write(_jsp_string_68, 0, _jsp_string_68.length);
                // EXPRESSION: lineNumber: 44
                expressionContext.print(out, expressionContext.getString("status.index"));
                // TEXT: lineNumber: 44
                // out.write(", myInt: ");
                out.write(_jsp_string_70, 0, _jsp_string_70.length);
                // VARIABLE: lineNumber: 44
                expressionContext.print(out, pageContext.getAttribute("myInt"));
                // TEXT: lineNumber: 44
                // out.write(", user.userName: ");
                out.write(_jsp_string_72, 0, _jsp_string_72.length);
                // EXPRESSION: lineNumber: 44
                expressionContext.print(out, expressionContext.getString("user.userName"));
                // TEXT: lineNumber: 44
                // out.write("</div>\r\n");
                out.write(_jsp_string_74, 0, _jsp_string_74.length);
                if(_jsp_ForEachTag_59.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_59.release();
        pageContext.setAttribute("myInt", _jsp_old_var_59);
        pageContext.setAttribute("status", _jsp_old_var_status_59);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 38, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_59

        // NODE START: lineNumber: 47, offset: 75, length: 2, tagClassName: com.skin.ayada.jstl.core.CommentTag, tagInstanceName: _jsp_CommentTag_76
        // <c:comment>...</c:comment>
        if(com.skin.ayada.jstl.core.ContinueTag.getTrue()) {
        } // jsp.jstl.core.CommentTag END
        // NODE END: lineNumber: 47, tagClassName: com.skin.ayada.jstl.core.CommentTag, tagInstanceName: _jsp_CommentTag_76


        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_3 = "message1: ".toCharArray();
    public static final char[] _jsp_string_5 = "\r\nmessage2: ".toCharArray();
    public static final char[] _jsp_string_7 = "\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_10 = "message3: ".toCharArray();
    public static final char[] _jsp_string_12 = "\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_31 = "000".toCharArray();
    public static final char[] _jsp_string_34 = "111".toCharArray();
    public static final char[] _jsp_string_37 = "222".toCharArray();
    public static final char[] _jsp_string_40 = "333".toCharArray();
    public static final char[] _jsp_string_68 = "    <div>1 index: ".toCharArray();
    public static final char[] _jsp_string_70 = ", myInt: ".toCharArray();
    public static final char[] _jsp_string_72 = ", user.userName: ".toCharArray();
    public static final char[] _jsp_string_74 = "</div>\r\n".toCharArray();

}
