/*
 * $RCSfile: ImportTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-09-24 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/fmbak/db/data
 * path: import.jsp
 * lastModified: 2016-09-24 22:25:13 933
 * options: -fastJstl true
 * template.dependencies
 * -- /import.jsp
 *
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-09-24 22:27:40 035)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ImportTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ImportTemplate extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ImportTemplate template = new ImportTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html; charset=UTF-8"/>

        // NODE START: lineNumber: 2, offset: 2, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_3
        // <c:set var=\"createDatabase\" value=\"false\"/>
        pageContext.setAttribute("createDatabase", false);
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_3

        // NODE START: lineNumber: 3, offset: 4, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_5
        // <c:set var=\"databaseName\" value=\"test123\"/>
        pageContext.setAttribute("databaseName", "test123");
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_5

        // NODE START: lineNumber: 4, offset: 6, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_7
        // <c:set var=\"userName\" value=\"root\"/>
        pageContext.setAttribute("userName", "root");
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_7

        // NODE START: lineNumber: 5, offset: 8, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_9
        // <c:set var=\"password\" value=\"1234\"/>
        pageContext.setAttribute("password", 1234);
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_9

        // NODE START: lineNumber: 6, offset: 10, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_11
        // <c:set var=\"charset\" value=\"utf8\"/>
        pageContext.setAttribute("charset", "utf8");
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 6, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_11

        // TEXT: lineNumber: 6
        // out.write("\r\n");
        out.write(_jsp_string_13, 0, _jsp_string_13.length);

        // NODE START: lineNumber: 8, offset: 13, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_14
        // <c:set var=\"createDatabaseUrl\" value=\"jdbc:mysql://localhost:3306?user=${userName}&amp;password=${password}&amp;characterEncoding=${charset}\"/>
        pageContext.setAttribute("createDatabaseUrl", ExpressionUtil.evaluate(expressionContext, "jdbc:mysql://localhost:3306?user=${userName}&password=${password}&characterEncoding=${charset}", null));
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 8, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_14

        // NODE START: lineNumber: 9, offset: 15, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_16
        // <c:set var=\"url\" value=\"jdbc:mysql://localhost:3306/${databaseName}?user=${userName}&amp;password=${password}&amp;characterEncoding=${charset}\"/>
        pageContext.setAttribute("url", ExpressionUtil.evaluate(expressionContext, "jdbc:mysql://localhost:3306/${databaseName}?user=${userName}&password=${password}&characterEncoding=${charset}", null));
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 9, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_16

        // NODE START: lineNumber: 10, offset: 17, length: 2, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_18
        // <c:set var=\"driverClass\" value=\"com.mysql.jdbc.Driver\"/>
        pageContext.setAttribute("driverClass", "com.mysql.jdbc.Driver");
        // jsp.jstl.core.SetTag END
        // NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.SetTag, tagInstanceName: _jsp_SetTag_18

        // TEXT: lineNumber: 10
        // out.write("\r\n");
        out.write(_jsp_string_20, 0, _jsp_string_20.length);

        // NODE START: lineNumber: 12, offset: 20, length: 13, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_21
        // <c:if test=\"${createDatabase}\">...</c:if>
        if(ExpressionUtil.getBoolean(expressionContext, "${createDatabase}")) {
            // NODE START: lineNumber: 13, offset: 21, length: 11, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_22
            // <sql:connect var=\"connection\" url=\"${createDatabaseUrl}\" driverClass=\"${driverClass}\" userName=\"${userName}\" password=\"${password}\">...</sql:connect>
            com.skin.ayada.jstl.sql.ConnectTag _jsp_ConnectTag_22 = new com.skin.ayada.jstl.sql.ConnectTag();
            try {
                _jsp_ConnectTag_22.setPageContext(pageContext);
                _jsp_ConnectTag_22.setParent((Tag)null);
                _jsp_ConnectTag_22.setVar("connection");
                _jsp_ConnectTag_22.setUrl(pageContext.getString("createDatabaseUrl"));
                _jsp_ConnectTag_22.setDriverClass(pageContext.getString("driverClass"));
                _jsp_ConnectTag_22.setUserName(pageContext.getString("userName"));
                _jsp_ConnectTag_22.setPassword(pageContext.getString("password"));
                int _jsp_start_flag_22 = _jsp_ConnectTag_22.doStartTag();

                if(_jsp_start_flag_22 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_22 != Tag.SKIP_BODY) {
                    int _jsp_flag_22 = 0;

                    do {
                        // NODE START: lineNumber: 14, offset: 22, length: 9, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_23
                        // <sql:execute out=\"${pageContext}\">...</sql:execute>
                        com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_23 = new com.skin.ayada.jstl.sql.SqlTag();
                        _jsp_SqlTag_23.setPageContext(pageContext);
                        _jsp_SqlTag_23.setParent(_jsp_ConnectTag_22);
                        _jsp_SqlTag_23.setOut(pageContext.getAttribute("pageContext"));
                        int _jsp_start_flag_23 = _jsp_SqlTag_23.doStartTag();

                        if(_jsp_start_flag_23 == Tag.SKIP_PAGE) {
                            return;
                        }
                        if(_jsp_start_flag_23 != Tag.SKIP_BODY) {
                            int _jsp_flag_23 = 0;
                            if(_jsp_start_flag_23 == BodyTag.EVAL_BODY_BUFFERED) {
                                BodyContent _jsp_body_content_23 = pageContext.pushBody();
                                _jsp_SqlTag_23.setBodyContent(_jsp_body_content_23);
                                _jsp_SqlTag_23.doInitBody();
                                out = _jsp_body_content_23;
                            }

                            do {
                                // TEXT: lineNumber: 14
                                // out.write("            drop database if exists ");
                                out.write(_jsp_string_24, 0, _jsp_string_24.length);
                                // VARIABLE: lineNumber: 15
                                expressionContext.print(out, pageContext.getAttribute("databaseName"));
                                // TEXT: lineNumber: 15
                                // out.write(";\r\n            create database ");
                                out.write(_jsp_string_26, 0, _jsp_string_26.length);
                                // VARIABLE: lineNumber: 16
                                expressionContext.print(out, pageContext.getAttribute("databaseName"));
                                // TEXT: lineNumber: 16
                                // out.write(" character set ");
                                out.write(_jsp_string_28, 0, _jsp_string_28.length);
                                // VARIABLE: lineNumber: 16
                                expressionContext.print(out, pageContext.getAttribute("charset"));
                                // TEXT: lineNumber: 16
                                // out.write(";\r\n");
                                out.write(_jsp_string_30, 0, _jsp_string_30.length);
                                _jsp_flag_23 = _jsp_SqlTag_23.doAfterBody();
                            }
                            while(_jsp_flag_23 == IterationTag.EVAL_BODY_AGAIN);
                            if(_jsp_start_flag_23 == BodyTag.EVAL_BODY_BUFFERED) {
                                out = pageContext.popBody();
                            }
                        }
                        _jsp_SqlTag_23.doEndTag();
                        _jsp_SqlTag_23.release();
                        // NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_23

                        _jsp_flag_22 = _jsp_ConnectTag_22.doAfterBody();
                    }
                    while(_jsp_flag_22 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_ConnectTag_22.doEndTag();
                _jsp_ConnectTag_22.release();
            }
            catch(Throwable throwable) {
                try {
                    _jsp_ConnectTag_22.doCatch(throwable);
                } catch (Throwable t) {
                    throw new Exception(t);
                }
            }
            finally {
                _jsp_ConnectTag_22.doFinally();
            }
            // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_22

        } // jsp.jstl.core.IfTag END
        // NODE END: lineNumber: 12, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_21

        // TEXT: lineNumber: 19
        // out.write("\r\n");
        out.write(_jsp_string_34, 0, _jsp_string_34.length);

        // NODE START: lineNumber: 21, offset: 34, length: 15, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_35
        // <sql:connect var=\"connection\" url=\"${url}\" driverClass=\"${driverClass}\" userName=\"${userName}\" password=\"${password}\">...</sql:connect>
        com.skin.ayada.jstl.sql.ConnectTag _jsp_ConnectTag_35 = new com.skin.ayada.jstl.sql.ConnectTag();
        try {
            _jsp_ConnectTag_35.setPageContext(pageContext);
            _jsp_ConnectTag_35.setParent((Tag)null);
            _jsp_ConnectTag_35.setVar("connection");
            _jsp_ConnectTag_35.setUrl(pageContext.getString("url"));
            _jsp_ConnectTag_35.setDriverClass(pageContext.getString("driverClass"));
            _jsp_ConnectTag_35.setUserName(pageContext.getString("userName"));
            _jsp_ConnectTag_35.setPassword(pageContext.getString("password"));
            int _jsp_start_flag_35 = _jsp_ConnectTag_35.doStartTag();

            if(_jsp_start_flag_35 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_35 != Tag.SKIP_BODY) {
                int _jsp_flag_35 = 0;

                do {
                    // NODE START: lineNumber: 22, offset: 35, length: 4, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_36
                    // <c:bean name=\"dir\" className=\"java.io.File\">...</c:bean>
                    com.skin.ayada.jstl.core.BeanTag _jsp_BeanTag_36 = new com.skin.ayada.jstl.core.BeanTag();
                    _jsp_BeanTag_36.setPageContext(pageContext);
                    _jsp_BeanTag_36.setParent(_jsp_ConnectTag_35);
                    _jsp_BeanTag_36.setName("dir");
                    _jsp_BeanTag_36.setClassName("java.io.File");
                    int _jsp_start_flag_36 = _jsp_BeanTag_36.doStartTag();

                    if(_jsp_start_flag_36 == Tag.SKIP_PAGE) {
                        return;
                    }
                    if(_jsp_start_flag_36 != Tag.SKIP_BODY) {
                        int _jsp_flag_36 = 0;

                        do {
                            // NODE START: lineNumber: 23, offset: 36, length: 2, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_37
                            // <c:constructor type=\"java.lang.String\" value=\"fmbak\"/>
                            com.skin.ayada.jstl.core.ConstructorTag.setArgument(_jsp_BeanTag_36, "java.lang.String", "fmbak");
                            // jsp.jstl.core.ConstructorTag END
                            // NODE END: lineNumber: 23, tagClassName: com.skin.ayada.jstl.core.ConstructorTag, tagInstanceName: _jsp_ConstructorTag_37

                            _jsp_flag_36 = _jsp_BeanTag_36.doAfterBody();
                        }
                        while(_jsp_flag_36 == IterationTag.EVAL_BODY_AGAIN);
                    }
                    _jsp_BeanTag_36.doEndTag();
                    _jsp_BeanTag_36.release();
                    // NODE END: lineNumber: 22, tagClassName: com.skin.ayada.jstl.core.BeanTag, tagInstanceName: _jsp_BeanTag_36

                    // TEXT: lineNumber: 24
                    // out.write("\r\n");
                    out.write(_jsp_string_40, 0, _jsp_string_40.length);

                    // NODE START: lineNumber: 26, offset: 40, length: 8, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_41
                    // <c:forEach items=\"${dir.listFiles()}\" var=\"file\">...</c:forEach>
                    Object _jsp_old_var_41 = pageContext.getAttribute("file");
                    com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_41 = new com.skin.ayada.jstl.core.ForEachTag();
                    _jsp_ForEachTag_41.setParent(_jsp_ConnectTag_35);
                    _jsp_ForEachTag_41.setPageContext(pageContext);
                    _jsp_ForEachTag_41.setVar("file");
                    _jsp_ForEachTag_41.setItems(ExpressionUtil.evaluate(expressionContext, "${dir.listFiles()}", null));
                    if(_jsp_ForEachTag_41.doStartTag() != Tag.SKIP_BODY) {
                        while(true) {
                            // NODE START: lineNumber: 27, offset: 41, length: 4, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_42
                            // <sql:execute out=\"${pageContext}\">...</sql:execute>
                            com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_42 = new com.skin.ayada.jstl.sql.SqlTag();
                            _jsp_SqlTag_42.setPageContext(pageContext);
                            _jsp_SqlTag_42.setParent((Tag)null);
                            _jsp_SqlTag_42.setOut(pageContext.getAttribute("pageContext"));
                            int _jsp_start_flag_42 = _jsp_SqlTag_42.doStartTag();

                            if(_jsp_start_flag_42 == Tag.SKIP_PAGE) {
                                return;
                            }
                            if(_jsp_start_flag_42 != Tag.SKIP_BODY) {
                                int _jsp_flag_42 = 0;
                                if(_jsp_start_flag_42 == BodyTag.EVAL_BODY_BUFFERED) {
                                    BodyContent _jsp_body_content_42 = pageContext.pushBody();
                                    _jsp_SqlTag_42.setBodyContent(_jsp_body_content_42);
                                    _jsp_SqlTag_42.doInitBody();
                                    out = _jsp_body_content_42;
                                }

                                do {
                                    // TEXT: lineNumber: 27
                                    // out.write("delete from table ");
                                    out.write(_jsp_string_43, 0, _jsp_string_43.length);
                                    // EXPRESSION: lineNumber: 27
                                    expressionContext.print(out, expressionContext.getString("StringUtil.replace(file.getName(), \".txt\", \"\")"));
                                    _jsp_flag_42 = _jsp_SqlTag_42.doAfterBody();
                                }
                                while(_jsp_flag_42 == IterationTag.EVAL_BODY_AGAIN);
                                if(_jsp_start_flag_42 == BodyTag.EVAL_BODY_BUFFERED) {
                                    out = pageContext.popBody();
                                }
                            }
                            _jsp_SqlTag_42.doEndTag();
                            _jsp_SqlTag_42.release();
                            // NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_42

                            // NODE START: lineNumber: 28, offset: 45, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_46
                            // <sql:execute home=\"${template.home}\" file=\"fmbak/${file.getName()}\" encoding=\"UTF-8\" out=\"${pageContext}\"/>
                            com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_46 = new com.skin.ayada.jstl.sql.SqlTag();
                            _jsp_SqlTag_46.setPageContext(pageContext);
                            _jsp_SqlTag_46.setParent((Tag)null);
                            _jsp_SqlTag_46.setHome(ExpressionUtil.getString(expressionContext, "${template.home}"));
                            _jsp_SqlTag_46.setFile(ExpressionUtil.getString(expressionContext, "fmbak/${file.getName()}"));
                            _jsp_SqlTag_46.setEncoding("UTF-8");
                            _jsp_SqlTag_46.setOut(pageContext.getAttribute("pageContext"));
                            int _jsp_start_flag_46 = _jsp_SqlTag_46.doStartTag();

                            if(_jsp_start_flag_46 == Tag.SKIP_PAGE) {
                                return;
                            }
                            if(_jsp_start_flag_46 != Tag.SKIP_BODY) {
                                _jsp_SqlTag_46.doAfterBody();
                            }
                            _jsp_SqlTag_46.doEndTag();
                            _jsp_SqlTag_46.release();
                            // NODE END: lineNumber: 28, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_46

                            if(_jsp_ForEachTag_41.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                                break;
                            }
                        }
                    }
                    _jsp_ForEachTag_41.release();
                    pageContext.setAttribute("file", _jsp_old_var_41);
                    // jsp.jstl.core.ForEachTag END
                    // NODE END: lineNumber: 26, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_41

                    _jsp_flag_35 = _jsp_ConnectTag_35.doAfterBody();
                }
                while(_jsp_flag_35 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_ConnectTag_35.doEndTag();
            _jsp_ConnectTag_35.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_ConnectTag_35.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_ConnectTag_35.doFinally();
        }
        // NODE END: lineNumber: 21, tagClassName: com.skin.ayada.jstl.sql.ConnectTag, tagInstanceName: _jsp_ConnectTag_35


        out.flush();
        jspWriter.flush();
    }

    protected static final char[] _jsp_string_13 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_20 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_24 = "            drop database if exists ".toCharArray();
    protected static final char[] _jsp_string_26 = ";\r\n            create database ".toCharArray();
    protected static final char[] _jsp_string_28 = " character set ".toCharArray();
    protected static final char[] _jsp_string_30 = ";\r\n".toCharArray();
    protected static final char[] _jsp_string_34 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_40 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_43 = "delete from table ".toCharArray();

}
