/*
 * $RCSfile: ImportTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-14 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /importTest.jsp
 * lastModified: 2014-06-30 13:30:16 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-14 23:17:02 547)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ImportTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ImportTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ImportTestTemplate template = new ImportTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html;charset=UTF-8"/>

        // NODE START: lineNumber: 3, offset: 2, length: 3, tagClassName: test.com.skin.ayada.taglib.TestBodyTag, tagInstanceName: _jsp_TestBodyTag_3
        // <app:bodytest>...</app:bodytest>
        test.com.skin.ayada.taglib.TestBodyTag _jsp_TestBodyTag_3 = new test.com.skin.ayada.taglib.TestBodyTag();
        _jsp_TestBodyTag_3.setPageContext(pageContext);
        _jsp_TestBodyTag_3.setParent((Tag)null);
        int _jsp_start_flag_3 = _jsp_TestBodyTag_3.doStartTag();

        if(_jsp_start_flag_3 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_3 != Tag.SKIP_BODY) {
            int _jsp_flag_3 = 0;
            if(_jsp_start_flag_3 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_3 = pageContext.pushBody();
                _jsp_TestBodyTag_3.setBodyContent(_jsp_body_content_3);
                _jsp_TestBodyTag_3.doInitBody();
                out = _jsp_body_content_3;
            }

            do {
                // TEXT: lineNumber: 3
                // out.write("Hello World !");
                out.write(_jsp_string_4, 0, _jsp_string_4.length);
                _jsp_flag_3 = _jsp_TestBodyTag_3.doAfterBody();
            }
            while(_jsp_flag_3 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_3 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_TestBodyTag_3.doEndTag();
        _jsp_TestBodyTag_3.release();
        // NODE END: lineNumber: 3, tagClassName: test.com.skin.ayada.taglib.TestBodyTag, tagInstanceName: _jsp_TestBodyTag_3

        // NODE START: lineNumber: 4, offset: 5, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_6
        // <c:out value=\"a${1}c\"/>
        com.skin.ayada.jstl.core.OutTag.write(out, ExpressionUtil.evaluate(expressionContext, "a${1}c", null), false);
        // out.print(ExpressionUtil.getString(expressionContext, "a${1}c"));
        // jsp.jstl.core.OutTag END
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_6

        // TEXT: lineNumber: 4
        // out.write("\r\n");
        out.write(_jsp_string_8, 0, _jsp_string_8.length);

        // NODE START: lineNumber: 5, offset: 8, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_9
        // <c:out value=\"a${?1}c\"/>
        com.skin.ayada.jstl.core.OutTag.write(out, "a${?1}c", false);
        // out.print(ExpressionUtil.getString(expressionContext, "a${?1}c"));
        // jsp.jstl.core.OutTag END
        // NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_9

        // TEXT: lineNumber: 5
        // out.write("\r\n");
        out.write(_jsp_string_11, 0, _jsp_string_11.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_4 = "Hello World !".toCharArray();
    public static final char[] _jsp_string_8 = "\r\n".toCharArray();
    public static final char[] _jsp_string_11 = "\r\n".toCharArray();

}
