/*
 * $RCSfile: ImportTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2014-06-30 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: D:\workspace2\ayada\webapp
 * path: importTest.jsp
 * lastModified: 2014-06-30 13:30:14 833
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.0.8 (built 2014-06-30 13:30:20 961)
 */
package _tpl._jsp;

import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;

/**
 * <p>Title: ImportTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
public class ImportTestTemplate extends JspTemplate{
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getDefaultPageContext(writer);
        ImportTestTemplate template = new ImportTestTemplate();

        try{
            template._execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable)
        {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    public void _execute(final PageContext pageContext) throws Throwable{
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /* jsp:directive.page: lineNumber: 1 */
        /* <jsp:directive.page contentType="text/html;charset=UTF-8"/> */
        /* jsp:directive.page END */

        /* NODE START: lineNumber: 3, offset: 2, length: 3, tagClassName: test.com.skin.ayada.taglib.TestBodyTag, tagInstanceName: _jsp_TestBodyTag_3 */
        /* <app:bodytest>...</app:bodytest> */
        test.com.skin.ayada.taglib.TestBodyTag _jsp_TestBodyTag_3 = new test.com.skin.ayada.taglib.TestBodyTag();
        _jsp_TestBodyTag_3.setParent((Tag)null);
        _jsp_TestBodyTag_3.setPageContext(pageContext);
        int _jsp_start_flag_3 = _jsp_TestBodyTag_3.doStartTag();

        if(_jsp_start_flag_3 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_3 != Tag.SKIP_BODY){
            int _jsp_flag_3 = 0;
            if(_jsp_start_flag_3 == BodyTag.EVAL_BODY_BUFFERED){
                BodyContent _jsp_body_content_3 = pageContext.pushBody();
                _jsp_TestBodyTag_3.setBodyContent(_jsp_body_content_3);
                _jsp_TestBodyTag_3.doInitBody();
                out = _jsp_body_content_3;
            }

            do{
                /* TEXT: lineNumber: 3 */
                out.write("Hello World !");
                _jsp_flag_3 = _jsp_TestBodyTag_3.doAfterBody();
            }
            while(_jsp_flag_3 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_3 == BodyTag.EVAL_BODY_BUFFERED){
                out = pageContext.popBody();
            }
        }
        _jsp_TestBodyTag_3.doEndTag();
        _jsp_TestBodyTag_3.release();
        /* NODE END: lineNumber: 3, tagClassName: test.com.skin.ayada.taglib.TestBodyTag, tagInstanceName: _jsp_TestBodyTag_3 */

        /* TEXT: lineNumber: 3 */
        out.write("\r\n");

        /* NODE START: lineNumber: 4, offset: 6, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_7 */
        /* <c:out value="a${1}c"/> */
        /* out.write("a${1}c"); */
        out.write(ExpressionUtil.getString(expressionContext, "a${1}c"));
        /* jsp.jstl.core.OutTag END */
        /* NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_7 */

        /* TEXT: lineNumber: 4 */
        out.write("\r\n");

        /* NODE START: lineNumber: 5, offset: 9, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_10 */
        /* <c:out value="a${?1}c"/> */
        /* out.write("a${?1}c"); */
        out.write(ExpressionUtil.getString(expressionContext, "a${?1}c"));
        /* jsp.jstl.core.OutTag END */
        /* NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_10 */

        /* TEXT: lineNumber: 5 */
        out.write("\r\n");
        out.flush();
        jspWriter.flush();
    }
}
