/*
 * $RCSfile: IncludeTest1Template.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-08 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /includeTest1.jsp
 * lastModified: 2014-11-21 10:04:08 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-08 22:06:50 712)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: IncludeTest1Template</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class IncludeTest1Template extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        IncludeTest1Template template = new IncludeTest1Template();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // TEXT: lineNumber: 1
        // out.write("<html>\r\n<head>\r\n<title>test</title>\r\n</head>\r\n<body version=\"1.0\">\r\n");
        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        // TEXT: lineNumber: 1
        // out.write("<div>\r\n    <h3>");
        out.write(_jsp_string_2, 0, _jsp_string_2.length);
        // EXPRESSION: lineNumber: 2
        expressionContext.print(out, expressionContext.getString("template.home"));
        // TEXT: lineNumber: 2
        // out.write("/include/header.jsp</h3>\r\n    <div class=\"wrap\">header</div>\r\n</div>\r\n<div>\r\n    <p>template.home: ");
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        // EXPRESSION: lineNumber: 8
        expressionContext.print(out, expressionContext.getString("template.home"));
        // TEXT: lineNumber: 8
        // out.write("</p>\r\n    <p>template.path: ");
        out.write(_jsp_string_6, 0, _jsp_string_6.length);
        // EXPRESSION: lineNumber: 9
        expressionContext.print(out, expressionContext.getString("template.path"));
        // TEXT: lineNumber: 9
        // out.write("</p>\r\n    <p>template.lastModified: ");
        out.write(_jsp_string_8, 0, _jsp_string_8.length);
        // EXPRESSION: lineNumber: 10
        expressionContext.print(out, expressionContext.getString("DateUtil.format(template.lastModified, \"yyyy-MM-dd HH:mm:ss\")"));
        // TEXT: lineNumber: 10
        // out.write("</p>\r\n</div>\r\n");
        out.write(_jsp_string_10, 0, _jsp_string_10.length);

        // NODE START: lineNumber: 12, offset: 10, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_11
        // <c:if test=\"${1 == 1}\">...</c:if>
        if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")) {
        } // jsp.jstl.core.IfTag END
        // NODE END: lineNumber: 12, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_11

        // TEXT: lineNumber: 12
        // out.write("\r\n");
        out.write(_jsp_string_13, 0, _jsp_string_13.length);
        // TEXT: lineNumber: 1
        // out.write("<div>\r\n    <h3>");
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        // EXPRESSION: lineNumber: 2
        expressionContext.print(out, expressionContext.getString("template.home"));
        // TEXT: lineNumber: 2
        // out.write("/include/static.jsp</h3>\r\n    ");
        out.write(_jsp_string_16, 0, _jsp_string_16.length);

        // NODE START: lineNumber: 3, offset: 16, length: 4, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_17
        // <c:forEach items=\"1, 2, 3\" var=\"myi\">...</c:forEach>
        Object _jsp_old_var_17 = pageContext.getAttribute("myi");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_17 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_17.setParent((Tag)null);
        _jsp_ForEachTag_17.setPageContext(pageContext);
        _jsp_ForEachTag_17.setVar("myi");
        _jsp_ForEachTag_17.setItems("1, 2, 3");
        if(_jsp_ForEachTag_17.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // VARIABLE: lineNumber: 3
                expressionContext.print(out, pageContext.getAttribute("myi"));
                // TEXT: lineNumber: 3
                // out.write(",");
                out.write(_jsp_string_19, 0, _jsp_string_19.length);
                if(_jsp_ForEachTag_17.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_17.release();
        pageContext.setAttribute("myi", _jsp_old_var_17);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_17

        // TEXT: lineNumber: 3
        // out.write("\r\n</div>\r\n\r\n");
        out.write(_jsp_string_21, 0, _jsp_string_21.length);
        // TEXT: lineNumber: 14
        // out.write("<div>\r\n    <h3>${template.home}/include/static.jsp</h3>\r\n    <c:forEach items=\"1, 2, 3\" var=\"myi\">${myi},</c:forEach>\r\n</div>\r\n\r\n");
        out.write(_jsp_string_22, 0, _jsp_string_22.length);
        // TEXT: lineNumber: 1
        // out.write("<div>\r\n    <h3>");
        out.write(_jsp_string_23, 0, _jsp_string_23.length);
        // EXPRESSION: lineNumber: 2
        expressionContext.print(out, expressionContext.getString("template.home"));
        // TEXT: lineNumber: 2
        // out.write("/include/static.jsp</h3>\r\n    ");
        out.write(_jsp_string_25, 0, _jsp_string_25.length);

        // NODE START: lineNumber: 3, offset: 25, length: 4, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_26
        // <c:forEach items=\"1, 2, 3\" var=\"myi\">...</c:forEach>
        Object _jsp_old_var_26 = pageContext.getAttribute("myi");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_26 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_26.setParent((Tag)null);
        _jsp_ForEachTag_26.setPageContext(pageContext);
        _jsp_ForEachTag_26.setVar("myi");
        _jsp_ForEachTag_26.setItems("1, 2, 3");
        if(_jsp_ForEachTag_26.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // VARIABLE: lineNumber: 3
                expressionContext.print(out, pageContext.getAttribute("myi"));
                // TEXT: lineNumber: 3
                // out.write(",");
                out.write(_jsp_string_28, 0, _jsp_string_28.length);
                if(_jsp_ForEachTag_26.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_26.release();
        pageContext.setAttribute("myi", _jsp_old_var_26);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_26

        // TEXT: lineNumber: 3
        // out.write("\r\n</div>\r\n\r\n");
        out.write(_jsp_string_30, 0, _jsp_string_30.length);
        // TEXT: lineNumber: 16
        // out.write("<div>\r\n    <h3>${template.home}/include/static.jsp</h3>\r\n    <c:forEach items=\"1, 2, 3\" var=\"myi\">${myi},</c:forEach>\r\n</div>\r\n\r\n");
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        // TEXT: lineNumber: 1
        // out.write("<div>\r\n    <h3>");
        out.write(_jsp_string_32, 0, _jsp_string_32.length);
        // EXPRESSION: lineNumber: 2
        expressionContext.print(out, expressionContext.getString("template.home"));
        // TEXT: lineNumber: 2
        // out.write("/include/static.jsp</h3>\r\n    ");
        out.write(_jsp_string_34, 0, _jsp_string_34.length);

        // NODE START: lineNumber: 3, offset: 34, length: 4, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_35
        // <c:forEach items=\"1, 2, 3\" var=\"myi\">...</c:forEach>
        Object _jsp_old_var_35 = pageContext.getAttribute("myi");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_35 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_35.setParent((Tag)null);
        _jsp_ForEachTag_35.setPageContext(pageContext);
        _jsp_ForEachTag_35.setVar("myi");
        _jsp_ForEachTag_35.setItems("1, 2, 3");
        if(_jsp_ForEachTag_35.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // VARIABLE: lineNumber: 3
                expressionContext.print(out, pageContext.getAttribute("myi"));
                // TEXT: lineNumber: 3
                // out.write(",");
                out.write(_jsp_string_37, 0, _jsp_string_37.length);
                if(_jsp_ForEachTag_35.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_35.release();
        pageContext.setAttribute("myi", _jsp_old_var_35);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_35

        // TEXT: lineNumber: 3
        // out.write("\r\n</div>\r\n\r\n");
        out.write(_jsp_string_39, 0, _jsp_string_39.length);
        // TEXT: lineNumber: 1
        // out.write("<div class=\"wrap\">footer</div>\r\n\r\n<h2>jsp include</h2>\r\n");
        out.write(_jsp_string_40, 0, _jsp_string_40.length);
        // TEXT: lineNumber: 1
        // out.write("<div class=\"wrap\">footer</div>");
        out.write(_jsp_string_41, 0, _jsp_string_41.length);

        // jsp:directive.include: lineNumber: 21
        // <jsp:directive.include include="" file="/include/footer.jsp"/>

        // TEXT: lineNumber: 22
        // out.write("</body>\r\n</html>");
        out.write(_jsp_string_44, 0, _jsp_string_44.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_1 = "<html>\r\n<head>\r\n<title>test</title>\r\n</head>\r\n<body version=\"1.0\">\r\n".toCharArray();
    public static final char[] _jsp_string_2 = "<div>\r\n    <h3>".toCharArray();
    public static final char[] _jsp_string_4 = "/include/header.jsp</h3>\r\n    <div class=\"wrap\">header</div>\r\n</div>\r\n<div>\r\n    <p>template.home: ".toCharArray();
    public static final char[] _jsp_string_6 = "</p>\r\n    <p>template.path: ".toCharArray();
    public static final char[] _jsp_string_8 = "</p>\r\n    <p>template.lastModified: ".toCharArray();
    public static final char[] _jsp_string_10 = "</p>\r\n</div>\r\n".toCharArray();
    public static final char[] _jsp_string_13 = "\r\n".toCharArray();
    public static final char[] _jsp_string_14 = "<div>\r\n    <h3>".toCharArray();
    public static final char[] _jsp_string_16 = "/include/static.jsp</h3>\r\n    ".toCharArray();
    public static final char[] _jsp_string_19 = ",".toCharArray();
    public static final char[] _jsp_string_21 = "\r\n</div>\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_22 = "<div>\r\n    <h3>${template.home}/include/static.jsp</h3>\r\n    <c:forEach items=\"1, 2, 3\" var=\"myi\">${myi},</c:forEach>\r\n</div>\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_23 = "<div>\r\n    <h3>".toCharArray();
    public static final char[] _jsp_string_25 = "/include/static.jsp</h3>\r\n    ".toCharArray();
    public static final char[] _jsp_string_28 = ",".toCharArray();
    public static final char[] _jsp_string_30 = "\r\n</div>\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_31 = "<div>\r\n    <h3>${template.home}/include/static.jsp</h3>\r\n    <c:forEach items=\"1, 2, 3\" var=\"myi\">${myi},</c:forEach>\r\n</div>\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_32 = "<div>\r\n    <h3>".toCharArray();
    public static final char[] _jsp_string_34 = "/include/static.jsp</h3>\r\n    ".toCharArray();
    public static final char[] _jsp_string_37 = ",".toCharArray();
    public static final char[] _jsp_string_39 = "\r\n</div>\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_40 = "<div class=\"wrap\">footer</div>\r\n\r\n<h2>jsp include</h2>\r\n".toCharArray();
    public static final char[] _jsp_string_41 = "<div class=\"wrap\">footer</div>".toCharArray();
    public static final char[] _jsp_string_44 = "</body>\r\n</html>".toCharArray();

}
