/*
 * $RCSfile: JspTagTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2017-02-07 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /jspTagTest.jsp
 * lastModified: 2016-01-05 11:22:26 000
 * options: -fastJstl true
 * template.dependencies
 * -- /jspTagTest.jsp
 *
 * JSP generated by JspCompiler-1.0.1.2 (built 2017-02-07 20:41:24 882)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: JspTagTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class JspTagTestTemplate extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        JspTagTestTemplate template = new JspTagTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html; charset=UTF-8;"/>

        // jsp:directive.taglib: lineNumber: 2
        // <jsp:directive.taglib taglib="" prefix="c" uri="http://java.sun.com/jsp/jstl/core"/>

        // jsp:directive.taglib: lineNumber: 3
        // <jsp:directive.taglib taglib="" prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"/>

        // jsp:directive.taglib: lineNumber: 4
        // <jsp:directive.taglib taglib="" prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"/>

        // TEXT: lineNumber: 4
        // out.write("<html>\r\n<head>\r\n<title>test</title>\r\n</head>\r\n<body version=\"1.0\">\r\n\r\n");
        out.write(_jsp_string_9, 0, _jsp_string_9.length);

        // jsp:scriptlet: lineNumber: 11
 int abc = 1; 
        // jsp:scriptlet END

        // TEXT: lineNumber: 11
        // out.write("\r\nabc");
        out.write(_jsp_string_12, 0, _jsp_string_12.length);

        // jsp:expression: lineNumber: 13
        expressionContext.print(out, (abc));
        // jsp:expression END

        // TEXT: lineNumber: 13
        // out.write("123\r\n</body>\r\n</html>");
        out.write(_jsp_string_15, 0, _jsp_string_15.length);

        out.flush();
        jspWriter.flush();
    }

    protected static final char[] _jsp_string_9 = "<html>\r\n<head>\r\n<title>test</title>\r\n</head>\r\n<body version=\"1.0\">\r\n\r\n".toCharArray();
    protected static final char[] _jsp_string_12 = "\r\nabc".toCharArray();
    protected static final char[] _jsp_string_15 = "123\r\n</body>\r\n</html>".toCharArray();

}
