/*
 * $RCSfile: ListTest2Template.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /listTest2.jsp
 * lastModified: 2013-12-14 21:28:08 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-12 23:30:05 141)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ListTest2Template</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ListTest2Template extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ListTest2Template template = new ListTest2Template();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 6, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_1
        // <c:list name=\"myList\">...</c:list>
        com.skin.ayada.jstl.core.ListTag _jsp_ListTag_1 = new com.skin.ayada.jstl.core.ListTag();
        _jsp_ListTag_1.setPageContext(pageContext);
        _jsp_ListTag_1.setParent((Tag)null);
        _jsp_ListTag_1.setName("myList");
        int _jsp_start_flag_1 = _jsp_ListTag_1.doStartTag();

        if(_jsp_start_flag_1 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_1 != Tag.SKIP_BODY) {
            int _jsp_flag_1 = 0;

            do {
                // NODE START: lineNumber: 2, offset: 1, length: 2, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_2
                // <c:map test1=\"test1\" test2=\"test2\"/>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_2 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_2.setPageContext(pageContext);
                _jsp_MapTag_2.setParent(_jsp_ListTag_1);
                _jsp_MapTag_2.setDynamicAttribute("test1", "test1");
                _jsp_MapTag_2.setDynamicAttribute("test2", "test2");
                int _jsp_start_flag_2 = _jsp_MapTag_2.doStartTag();

                if(_jsp_start_flag_2 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_2 != Tag.SKIP_BODY) {
                    _jsp_MapTag_2.doAfterBody();
                }
                _jsp_MapTag_2.doEndTag();
                _jsp_MapTag_2.release();
                // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_2

                // NODE START: lineNumber: 3, offset: 3, length: 2, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_4
                // <c:map test1=\"test1\" test2=\"test2\"/>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_4 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_4.setPageContext(pageContext);
                _jsp_MapTag_4.setParent(_jsp_ListTag_1);
                _jsp_MapTag_4.setDynamicAttribute("test1", "test1");
                _jsp_MapTag_4.setDynamicAttribute("test2", "test2");
                int _jsp_start_flag_4 = _jsp_MapTag_4.doStartTag();

                if(_jsp_start_flag_4 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_4 != Tag.SKIP_BODY) {
                    _jsp_MapTag_4.doAfterBody();
                }
                _jsp_MapTag_4.doEndTag();
                _jsp_MapTag_4.release();
                // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_4

                _jsp_flag_1 = _jsp_ListTag_1.doAfterBody();
            }
            while(_jsp_flag_1 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_ListTag_1.doEndTag();
        _jsp_ListTag_1.release();
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_1

        // NODE START: lineNumber: 6, offset: 6, length: 7, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_7
        // <c:forEach items=\"${myList}\" var=\"myObj\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_7 = pageContext.getAttribute("myObj");
        Object _jsp_old_var_status_7 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_7 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_7.setParent((Tag)null);
        _jsp_ForEachTag_7.setPageContext(pageContext);
        _jsp_ForEachTag_7.setVar("myObj");
        _jsp_ForEachTag_7.setItems(pageContext.getAttribute("myList"));
        _jsp_ForEachTag_7.setVarStatus("status");
        if(_jsp_ForEachTag_7.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // TEXT: lineNumber: 6
                // out.write("<p>myObj=");
                out.write(_jsp_string_8, 0, _jsp_string_8.length);
                // EXPRESSION: lineNumber: 7
                expressionContext.print(out, expressionContext.getString("status.index"));
                // TEXT: lineNumber: 7
                // out.write(": ");
                out.write(_jsp_string_10, 0, _jsp_string_10.length);
                // EXPRESSION: lineNumber: 7
                expressionContext.print(out, expressionContext.getString("myObj.test1"));
                // TEXT: lineNumber: 7
                // out.write("</p>\r\n");
                out.write(_jsp_string_12, 0, _jsp_string_12.length);
                if(_jsp_ForEachTag_7.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_7.release();
        pageContext.setAttribute("myObj", _jsp_old_var_7);
        pageContext.setAttribute("status", _jsp_old_var_status_7);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 6, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_7

        // NODE START: lineNumber: 10, offset: 13, length: 7, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_14
        // <c:forEach items=\"${myList}\" var=\"myObj\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_14 = pageContext.getAttribute("myObj");
        Object _jsp_old_var_status_14 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_14 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_14.setParent((Tag)null);
        _jsp_ForEachTag_14.setPageContext(pageContext);
        _jsp_ForEachTag_14.setVar("myObj");
        _jsp_ForEachTag_14.setItems(pageContext.getAttribute("myList"));
        _jsp_ForEachTag_14.setVarStatus("status");
        if(_jsp_ForEachTag_14.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // TEXT: lineNumber: 10
                // out.write("<p>myObj=");
                out.write(_jsp_string_15, 0, _jsp_string_15.length);
                // EXPRESSION: lineNumber: 11
                expressionContext.print(out, expressionContext.getString("status.index"));
                // TEXT: lineNumber: 11
                // out.write(": ");
                out.write(_jsp_string_17, 0, _jsp_string_17.length);
                // EXPRESSION: lineNumber: 11
                expressionContext.print(out, expressionContext.getString("myObj.test1"));
                // TEXT: lineNumber: 11
                // out.write("</p>\r\n");
                out.write(_jsp_string_19, 0, _jsp_string_19.length);
                if(_jsp_ForEachTag_14.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_14.release();
        pageContext.setAttribute("myObj", _jsp_old_var_14);
        pageContext.setAttribute("status", _jsp_old_var_status_14);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_14


        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_8 = "<p>myObj=".toCharArray();
    public static final char[] _jsp_string_10 = ": ".toCharArray();
    public static final char[] _jsp_string_12 = "</p>\r\n".toCharArray();
    public static final char[] _jsp_string_15 = "<p>myObj=".toCharArray();
    public static final char[] _jsp_string_17 = ": ".toCharArray();
    public static final char[] _jsp_string_19 = "</p>\r\n".toCharArray();

}
