/*
 * $RCSfile: MapTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-14 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /mapTest.jsp
 * lastModified: 2014-05-27 19:31:32 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-14 23:17:03 827)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: MapTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class MapTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        MapTestTemplate template = new MapTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 2, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_1
        // <c:map name=\"myMap1\" test1=\"test1\" test2=\"test2\"/>
        com.skin.ayada.jstl.core.MapTag _jsp_MapTag_1 = new com.skin.ayada.jstl.core.MapTag();
        _jsp_MapTag_1.setPageContext(pageContext);
        _jsp_MapTag_1.setParent((Tag)null);
        _jsp_MapTag_1.setDynamicAttribute("name", "myMap1");
        _jsp_MapTag_1.setDynamicAttribute("test1", "test1");
        _jsp_MapTag_1.setDynamicAttribute("test2", "test2");
        int _jsp_start_flag_1 = _jsp_MapTag_1.doStartTag();

        if(_jsp_start_flag_1 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_1 != Tag.SKIP_BODY) {
            _jsp_MapTag_1.doAfterBody();
        }
        _jsp_MapTag_1.doEndTag();
        _jsp_MapTag_1.release();
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_1

        // TEXT: lineNumber: 1
        // out.write("<p>myMap1: ");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        // EXPRESSION: lineNumber: 2
        expressionContext.print(out, expressionContext.getString("myMap1.test1"));
        // TEXT: lineNumber: 2
        // out.write("</p>\r\n\r\n");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);

        // NODE START: lineNumber: 4, offset: 5, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_6
        // <c:map name=\"myMap2\">...</c:map>
        com.skin.ayada.jstl.core.MapTag _jsp_MapTag_6 = new com.skin.ayada.jstl.core.MapTag();
        _jsp_MapTag_6.setPageContext(pageContext);
        _jsp_MapTag_6.setParent((Tag)null);
        _jsp_MapTag_6.setDynamicAttribute("name", "myMap2");
        int _jsp_start_flag_6 = _jsp_MapTag_6.doStartTag();

        if(_jsp_start_flag_6 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_6 != Tag.SKIP_BODY) {
            int _jsp_flag_6 = 0;

            do {
                // NODE START: lineNumber: 5, offset: 6, length: 2, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_7
                // <c:map name=\"myMap3\" test1=\"test1\" test2=\"test2\"/>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_7 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_7.setPageContext(pageContext);
                _jsp_MapTag_7.setParent(_jsp_MapTag_6);
                _jsp_MapTag_7.setDynamicAttribute("name", "myMap3");
                _jsp_MapTag_7.setDynamicAttribute("test1", "test1");
                _jsp_MapTag_7.setDynamicAttribute("test2", "test2");
                int _jsp_start_flag_7 = _jsp_MapTag_7.doStartTag();

                if(_jsp_start_flag_7 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_7 != Tag.SKIP_BODY) {
                    _jsp_MapTag_7.doAfterBody();
                }
                _jsp_MapTag_7.doEndTag();
                _jsp_MapTag_7.release();
                // NODE END: lineNumber: 5, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_7

                // NODE START: lineNumber: 6, offset: 8, length: 2, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_9
                // <c:map name=\"myMap4\" test1=\"test1\" test2=\"test2\"/>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_9 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_9.setPageContext(pageContext);
                _jsp_MapTag_9.setParent(_jsp_MapTag_6);
                _jsp_MapTag_9.setDynamicAttribute("name", "myMap4");
                _jsp_MapTag_9.setDynamicAttribute("test1", "test1");
                _jsp_MapTag_9.setDynamicAttribute("test2", "test2");
                int _jsp_start_flag_9 = _jsp_MapTag_9.doStartTag();

                if(_jsp_start_flag_9 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_9 != Tag.SKIP_BODY) {
                    _jsp_MapTag_9.doAfterBody();
                }
                _jsp_MapTag_9.doEndTag();
                _jsp_MapTag_9.release();
                // NODE END: lineNumber: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_9

                _jsp_flag_6 = _jsp_MapTag_6.doAfterBody();
            }
            while(_jsp_flag_6 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_MapTag_6.doEndTag();
        _jsp_MapTag_6.release();
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_6

        // TEXT: lineNumber: 7
        // out.write("<p>myMap2.myMap3.test1: ");
        out.write(_jsp_string_12, 0, _jsp_string_12.length);
        // EXPRESSION: lineNumber: 8
        expressionContext.print(out, expressionContext.getString("myMap2.myMap3.test1"));
        // TEXT: lineNumber: 8
        // out.write("</p>\r\n<p>myMap2.myMap4.test1: ");
        out.write(_jsp_string_14, 0, _jsp_string_14.length);
        // EXPRESSION: lineNumber: 9
        expressionContext.print(out, expressionContext.getString("myMap2.myMap4.test2"));
        // TEXT: lineNumber: 9
        // out.write("</p>\r\n\r\n");
        out.write(_jsp_string_16, 0, _jsp_string_16.length);

        // NODE START: lineNumber: 11, offset: 16, length: 10, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_17
        // <c:list name=\"myList1\">...</c:list>
        com.skin.ayada.jstl.core.ListTag _jsp_ListTag_17 = new com.skin.ayada.jstl.core.ListTag();
        _jsp_ListTag_17.setPageContext(pageContext);
        _jsp_ListTag_17.setParent((Tag)null);
        _jsp_ListTag_17.setName("myList1");
        int _jsp_start_flag_17 = _jsp_ListTag_17.doStartTag();

        if(_jsp_start_flag_17 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_17 != Tag.SKIP_BODY) {
            int _jsp_flag_17 = 0;

            do {
                // NODE START: lineNumber: 12, offset: 17, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_18
                // <c:map>...</c:map>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_18 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_18.setPageContext(pageContext);
                _jsp_MapTag_18.setParent(_jsp_ListTag_17);
                int _jsp_start_flag_18 = _jsp_MapTag_18.doStartTag();

                if(_jsp_start_flag_18 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_18 != Tag.SKIP_BODY) {
                    int _jsp_flag_18 = 0;

                    do {
                        // NODE START: lineNumber: 13, offset: 18, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_19
                        // <c:entry name=\"test1\" value=\"test1\"/>
                        _jsp_MapTag_18.setAttribute("test1", "test1");
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_19

                        // NODE START: lineNumber: 14, offset: 20, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_21
                        // <c:entry name=\"test2\" value=\"test2\"/>
                        _jsp_MapTag_18.setAttribute("test2", "test2");
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_21

                        _jsp_flag_18 = _jsp_MapTag_18.doAfterBody();
                    }
                    while(_jsp_flag_18 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_MapTag_18.doEndTag();
                _jsp_MapTag_18.release();
                // NODE END: lineNumber: 12, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_18

                // NODE START: lineNumber: 16, offset: 23, length: 2, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_24
                // <c:map test1=\"test1\" test2=\"test2\"/>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_24 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_24.setPageContext(pageContext);
                _jsp_MapTag_24.setParent(_jsp_ListTag_17);
                _jsp_MapTag_24.setDynamicAttribute("test1", "test1");
                _jsp_MapTag_24.setDynamicAttribute("test2", "test2");
                int _jsp_start_flag_24 = _jsp_MapTag_24.doStartTag();

                if(_jsp_start_flag_24 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_24 != Tag.SKIP_BODY) {
                    _jsp_MapTag_24.doAfterBody();
                }
                _jsp_MapTag_24.doEndTag();
                _jsp_MapTag_24.release();
                // NODE END: lineNumber: 16, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_24

                _jsp_flag_17 = _jsp_ListTag_17.doAfterBody();
            }
            while(_jsp_flag_17 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_ListTag_17.doEndTag();
        _jsp_ListTag_17.release();
        // NODE END: lineNumber: 11, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_17

        // TEXT: lineNumber: 17
        // out.write("\r\n");
        out.write(_jsp_string_27, 0, _jsp_string_27.length);

        // NODE START: lineNumber: 19, offset: 27, length: 8, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_28
        // <c:map name=\"myMap1\">...</c:map>
        com.skin.ayada.jstl.core.MapTag _jsp_MapTag_28 = new com.skin.ayada.jstl.core.MapTag();
        _jsp_MapTag_28.setPageContext(pageContext);
        _jsp_MapTag_28.setParent((Tag)null);
        _jsp_MapTag_28.setDynamicAttribute("name", "myMap1");
        int _jsp_start_flag_28 = _jsp_MapTag_28.doStartTag();

        if(_jsp_start_flag_28 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_28 != Tag.SKIP_BODY) {
            int _jsp_flag_28 = 0;

            do {
                // NODE START: lineNumber: 20, offset: 28, length: 6, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_29
                // <c:map name=\"element1\">...</c:map>
                com.skin.ayada.jstl.core.MapTag _jsp_MapTag_29 = new com.skin.ayada.jstl.core.MapTag();
                _jsp_MapTag_29.setPageContext(pageContext);
                _jsp_MapTag_29.setParent(_jsp_MapTag_28);
                _jsp_MapTag_29.setDynamicAttribute("name", "element1");
                int _jsp_start_flag_29 = _jsp_MapTag_29.doStartTag();

                if(_jsp_start_flag_29 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_29 != Tag.SKIP_BODY) {
                    int _jsp_flag_29 = 0;

                    do {
                        // NODE START: lineNumber: 21, offset: 29, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_30
                        // <c:entry name=\"test1\" value=\"test1\"/>
                        _jsp_MapTag_29.setAttribute("test1", "test1");
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 21, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_30

                        // NODE START: lineNumber: 22, offset: 31, length: 2, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_32
                        // <c:entry name=\"test2\" value=\"test2\"/>
                        _jsp_MapTag_29.setAttribute("test2", "test2");
                        // jsp.jstl.core.AttributeTag END
                        // NODE END: lineNumber: 22, tagClassName: com.skin.ayada.jstl.core.AttributeTag, tagInstanceName: _jsp_AttributeTag_32

                        _jsp_flag_29 = _jsp_MapTag_29.doAfterBody();
                    }
                    while(_jsp_flag_29 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_MapTag_29.doEndTag();
                _jsp_MapTag_29.release();
                // NODE END: lineNumber: 20, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_29

                _jsp_flag_28 = _jsp_MapTag_28.doAfterBody();
            }
            while(_jsp_flag_28 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_MapTag_28.doEndTag();
        _jsp_MapTag_28.release();
        // NODE END: lineNumber: 19, tagClassName: com.skin.ayada.jstl.core.MapTag, tagInstanceName: _jsp_MapTag_28

        // TEXT: lineNumber: 24
        // out.write("\r\n");
        out.write(_jsp_string_36, 0, _jsp_string_36.length);
        // VARIABLE: lineNumber: 26
        expressionContext.print(out, pageContext.getAttribute("myMap1"));
        // TEXT: lineNumber: 26
        // out.write("\r\n\r\n");
        out.write(_jsp_string_38, 0, _jsp_string_38.length);

        // NODE START: lineNumber: 28, offset: 38, length: 18, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_39
        // <c:list name=\"myList2\">...</c:list>
        com.skin.ayada.jstl.core.ListTag _jsp_ListTag_39 = new com.skin.ayada.jstl.core.ListTag();
        _jsp_ListTag_39.setPageContext(pageContext);
        _jsp_ListTag_39.setParent((Tag)null);
        _jsp_ListTag_39.setName("myList2");
        int _jsp_start_flag_39 = _jsp_ListTag_39.doStartTag();

        if(_jsp_start_flag_39 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_39 != Tag.SKIP_BODY) {
            int _jsp_flag_39 = 0;

            do {
                // NODE START: lineNumber: 29, offset: 39, length: 8, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_40
                // <c:list>...</c:list>
                com.skin.ayada.jstl.core.ListTag _jsp_ListTag_40 = new com.skin.ayada.jstl.core.ListTag();
                _jsp_ListTag_40.setPageContext(pageContext);
                _jsp_ListTag_40.setParent(_jsp_ListTag_39);
                int _jsp_start_flag_40 = _jsp_ListTag_40.doStartTag();

                if(_jsp_start_flag_40 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_40 != Tag.SKIP_BODY) {
                    int _jsp_flag_40 = 0;

                    do {
                        // NODE START: lineNumber: 30, offset: 40, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_41
                        // <c:element value=\"123\"/>
                        _jsp_ListTag_40.addElement(123);
                        // jsp.jstl.core.ElementTag END
                        // NODE END: lineNumber: 30, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_41

                        // NODE START: lineNumber: 31, offset: 42, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_43
                        // <c:element value=\"234\"/>
                        _jsp_ListTag_40.addElement(234);
                        // jsp.jstl.core.ElementTag END
                        // NODE END: lineNumber: 31, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_43

                        // NODE START: lineNumber: 32, offset: 44, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_45
                        // <c:element value=\"456\"/>
                        _jsp_ListTag_40.addElement(456);
                        // jsp.jstl.core.ElementTag END
                        // NODE END: lineNumber: 32, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_45

                        _jsp_flag_40 = _jsp_ListTag_40.doAfterBody();
                    }
                    while(_jsp_flag_40 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_ListTag_40.doEndTag();
                _jsp_ListTag_40.release();
                // NODE END: lineNumber: 29, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_40

                // NODE START: lineNumber: 34, offset: 47, length: 8, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_48
                // <c:list>...</c:list>
                com.skin.ayada.jstl.core.ListTag _jsp_ListTag_48 = new com.skin.ayada.jstl.core.ListTag();
                _jsp_ListTag_48.setPageContext(pageContext);
                _jsp_ListTag_48.setParent(_jsp_ListTag_39);
                int _jsp_start_flag_48 = _jsp_ListTag_48.doStartTag();

                if(_jsp_start_flag_48 == Tag.SKIP_PAGE) {
                    return;
                }
                if(_jsp_start_flag_48 != Tag.SKIP_BODY) {
                    int _jsp_flag_48 = 0;

                    do {
                        // NODE START: lineNumber: 35, offset: 48, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_49
                        // <c:element value=\"456\"/>
                        _jsp_ListTag_48.addElement(456);
                        // jsp.jstl.core.ElementTag END
                        // NODE END: lineNumber: 35, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_49

                        // NODE START: lineNumber: 36, offset: 50, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_51
                        // <c:element value=\"234\"/>
                        _jsp_ListTag_48.addElement(234);
                        // jsp.jstl.core.ElementTag END
                        // NODE END: lineNumber: 36, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_51

                        // NODE START: lineNumber: 37, offset: 52, length: 2, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_53
                        // <c:element value=\"123\"/>
                        _jsp_ListTag_48.addElement(123);
                        // jsp.jstl.core.ElementTag END
                        // NODE END: lineNumber: 37, tagClassName: com.skin.ayada.jstl.core.ElementTag, tagInstanceName: _jsp_ElementTag_53

                        _jsp_flag_48 = _jsp_ListTag_48.doAfterBody();
                    }
                    while(_jsp_flag_48 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_ListTag_48.doEndTag();
                _jsp_ListTag_48.release();
                // NODE END: lineNumber: 34, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_48

                _jsp_flag_39 = _jsp_ListTag_39.doAfterBody();
            }
            while(_jsp_flag_39 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_ListTag_39.doEndTag();
        _jsp_ListTag_39.release();
        // NODE END: lineNumber: 28, tagClassName: com.skin.ayada.jstl.core.ListTag, tagInstanceName: _jsp_ListTag_39

        // TEXT: lineNumber: 39
        // out.write("myList2: ");
        out.write(_jsp_string_57, 0, _jsp_string_57.length);
        // VARIABLE: lineNumber: 40
        expressionContext.print(out, pageContext.getAttribute("myList2"));
        // TEXT: lineNumber: 40
        // out.write("\r\n\r\n<p>myList1: ");
        out.write(_jsp_string_59, 0, _jsp_string_59.length);
        // VARIABLE: lineNumber: 42
        expressionContext.print(out, pageContext.getAttribute("myList1"));
        // TEXT: lineNumber: 42
        // out.write("</p>\r\n");
        out.write(_jsp_string_61, 0, _jsp_string_61.length);

        // NODE START: lineNumber: 43, offset: 61, length: 5, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_62
        // <c:forEach items=\"${myList1}\" var=\"myObj\" varStatus=\"status\">...</c:forEach>
        Object _jsp_old_var_62 = pageContext.getAttribute("myObj");
        Object _jsp_old_var_status_62 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_62 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_62.setParent((Tag)null);
        _jsp_ForEachTag_62.setPageContext(pageContext);
        _jsp_ForEachTag_62.setVar("myObj");
        _jsp_ForEachTag_62.setItems(pageContext.getAttribute("myList1"));
        _jsp_ForEachTag_62.setVarStatus("status");
        if(_jsp_ForEachTag_62.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // TEXT: lineNumber: 43
                // out.write("<p>myObj: ");
                out.write(_jsp_string_63, 0, _jsp_string_63.length);
                // EXPRESSION: lineNumber: 44
                expressionContext.print(out, expressionContext.getString("myObj.test1"));
                // TEXT: lineNumber: 44
                // out.write("</p>\r\n");
                out.write(_jsp_string_65, 0, _jsp_string_65.length);
                if(_jsp_ForEachTag_62.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_62.release();
        pageContext.setAttribute("myObj", _jsp_old_var_62);
        pageContext.setAttribute("status", _jsp_old_var_status_62);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 43, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_62


        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_3 = "<p>myMap1: ".toCharArray();
    public static final char[] _jsp_string_5 = "</p>\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_12 = "<p>myMap2.myMap3.test1: ".toCharArray();
    public static final char[] _jsp_string_14 = "</p>\r\n<p>myMap2.myMap4.test1: ".toCharArray();
    public static final char[] _jsp_string_16 = "</p>\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_27 = "\r\n".toCharArray();
    public static final char[] _jsp_string_36 = "\r\n".toCharArray();
    public static final char[] _jsp_string_38 = "\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_57 = "myList2: ".toCharArray();
    public static final char[] _jsp_string_59 = "\r\n\r\n<p>myList1: ".toCharArray();
    public static final char[] _jsp_string_61 = "</p>\r\n".toCharArray();
    public static final char[] _jsp_string_63 = "<p>myObj: ".toCharArray();
    public static final char[] _jsp_string_65 = "</p>\r\n".toCharArray();

}
