/*
 * $RCSfile: ScriptletTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2017-02-07 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /scriptletTest.jsp
 * lastModified: 2016-01-14 11:47:20 000
 * options: -fastJstl true
 * template.dependencies
 * -- /scriptletTest.jsp
 * -- /include/header.jsp
 *
 * JSP generated by JspCompiler-1.0.1.2 (built 2017-02-07 20:41:28 896)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: ScriptletTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class ScriptletTestTemplate extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        ScriptletTestTemplate template = new ScriptletTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }
    // JSP_DECLARATION: lineNumber: 21
    // jsp:declaration END

    // JSP_DECLARATION: lineNumber: 23
int myVar1=1;    // jsp:declaration END


    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html; charset=utf-8" pageEncoding="utf-8"/>

        // TEXT: lineNumber: 1
        // out.write("\r\n");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        // TEXT: lineNumber: 1
        // out.write("<div>\r\n    <h3>");
        out.write(_jsp_string_4, 0, _jsp_string_4.length);
        // EXPRESSION: lineNumber: 2
        expressionContext.print(out, expressionContext.getString("template.home"));
        // TEXT: lineNumber: 2
        // out.write("/include/header.jsp</h3>\r\n    <div class=\"wrap\">header</div>\r\n</div>\r\n");
        out.write(_jsp_string_6, 0, _jsp_string_6.length);

        // jsp:directive.include: lineNumber: 3
        // <jsp:directive.include include="" file="/include/header.jsp"/>

        // TEXT: lineNumber: 3
        // out.write("\r\n\r\n");
        out.write(_jsp_string_9, 0, _jsp_string_9.length);

        // jsp:declaration: lineNumber: 21
        // <jsp:declaration>...</jsp:declaration>

        // jsp:scriptlet: lineNumber: 22

        // jsp:scriptlet END

        // jsp:declaration: lineNumber: 23
        // <jsp:declaration>...</jsp:declaration>

        // jsp:scriptlet: lineNumber: 24
int myVar2=1;
        // jsp:scriptlet END

        // TEXT: lineNumber: 24
        // out.write("\r\n");
        out.write(_jsp_string_18, 0, _jsp_string_18.length);

        // jsp:scriptlet: lineNumber: 26
int a=1;
        // jsp:scriptlet END

        // TEXT: lineNumber: 26
        // out.write("\r\n\r\n");
        out.write(_jsp_string_21, 0, _jsp_string_21.length);

        // jsp:scriptlet: lineNumber: 29
    int b = 2;

        // jsp:scriptlet END

        // TEXT: lineNumber: 31
        // out.write("\r\n");
        out.write(_jsp_string_24, 0, _jsp_string_24.length);

        // jsp:expression: lineNumber: 33
        expressionContext.print(out, ((a + 1)));
        // jsp:expression END

        // TEXT: lineNumber: 33
        // out.write("\r\n\r\n");
        out.write(_jsp_string_27, 0, _jsp_string_27.length);

        // jsp:scriptlet: lineNumber: 35
int sum = a + b;


        // jsp:scriptlet END

        // TEXT: lineNumber: 39
        // out.write("\r\n");
        out.write(_jsp_string_30, 0, _jsp_string_30.length);

        // jsp:expression: lineNumber: 41
        expressionContext.print(out, (1));
        // jsp:expression END

        // TEXT: lineNumber: 41
        // out.write("\r\n\r\n");
        out.write(_jsp_string_33, 0, _jsp_string_33.length);

        out.flush();
        jspWriter.flush();
    }

    protected static final char[] _jsp_string_3 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_4 = "<div>\r\n    <h3>".toCharArray();
    protected static final char[] _jsp_string_6 = "/include/header.jsp</h3>\r\n    <div class=\"wrap\">header</div>\r\n</div>\r\n".toCharArray();
    protected static final char[] _jsp_string_9 = "\r\n\r\n".toCharArray();
    protected static final char[] _jsp_string_18 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_21 = "\r\n\r\n".toCharArray();
    protected static final char[] _jsp_string_24 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_27 = "\r\n\r\n".toCharArray();
    protected static final char[] _jsp_string_30 = "\r\n".toCharArray();
    protected static final char[] _jsp_string_33 = "\r\n\r\n".toCharArray();

}
