/*
 * $RCSfile: SimpleTagTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2014-08-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: D:\workspace2\ayada\webapp
 * path: simpleTagTest.jsp
 * lastModified: 2014-07-13 22:03:04 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.0 (built 2014-08-12 14:49:24 450)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;
import java.io.IOException; // jsp:directive.import: lineNumber: 4


/**
 * <p>Title: SimpleTagTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class SimpleTagTestTemplate extends JspTemplate{
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getDefaultPageContext(writer);
        SimpleTagTestTemplate template = new SimpleTagTestTemplate();

        try{
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable)
        {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    public void _execute(final PageContext pageContext) throws Throwable{
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html;charset=UTF-8"/>

        // jsp:directive.taglib: lineNumber: 2
        // <jsp:directive.taglib taglib="" prefix="c" uri="http://java.sun.com/jsp/jstl/core"/>

        // jsp:directive.taglib: lineNumber: 3
        // <jsp:directive.taglib taglib="" prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"/>

        // jsp:directive.page: lineNumber: 4
        // <jsp:directive.page import="java.io.IOException"/>

        // TEXT: lineNumber: 6
        // out.write("<!-- t:import name=\"test:simpleTag\" className=\"test.com.skin.ayada.taglib.MySimpleTag\"/ -->\r\n");
        out.write(_jsp_string_9, 0, _jsp_string_9.length);

        // NODE START: lineNumber: 7, offset: 9, length: 3, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_10
        // <c:forEach items="1,1" var="myvar">...</c:forEach>
        Object _jsp_old_var_10 = pageContext.getAttribute("myvar");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_10 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_10.setParent((Tag)null);
        _jsp_ForEachTag_10.setPageContext(pageContext);
        _jsp_ForEachTag_10.setVar("myvar");
        _jsp_ForEachTag_10.setItems("1,1");
        if(_jsp_ForEachTag_10.doStartTag() != Tag.SKIP_BODY){
            while(true){
                // VARIABLE: lineNumber: 7
                out.print(pageContext.getAttribute("myvar"), expressionContext.getEscapeXml());
                if(_jsp_ForEachTag_10.doAfterBody() != IterationTag.EVAL_BODY_AGAIN){
                    break;
                }
            }
        }
        _jsp_ForEachTag_10.release();
        pageContext.setAttribute("myvar", _jsp_old_var_10);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 7, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_10

        // TEXT: lineNumber: 7
        // out.write("\r\n");
        out.write(_jsp_string_13, 0, _jsp_string_13.length);

        // NODE START: lineNumber: 8, offset: 13, length: 26, tagClassName: test.com.skin.ayada.taglib.MySimpleTag, tagInstanceName: _jsp_MySimpleTag_14
        // <test:simpleTag>...</test:simpleTag>
        test.com.skin.ayada.taglib.MySimpleTag _jsp_MySimpleTag_14 = new test.com.skin.ayada.taglib.MySimpleTag();
        _jsp_MySimpleTag_14.setPageContext(pageContext);
        _jsp_MySimpleTag_14.setParent((Tag)null);

        JspFragment_14 _jsp_fragment_14 = new JspFragment_14();
        _jsp_fragment_14.setPageContext(pageContext);
        _jsp_fragment_14.setParent(_jsp_MySimpleTag_14);

        _jsp_MySimpleTag_14.setJspBody(_jsp_fragment_14);
        _jsp_MySimpleTag_14.doTag();
        _jsp_MySimpleTag_14.release();
        // NODE END: lineNumber: 8, tagClassName: test.com.skin.ayada.taglib.MySimpleTag, tagInstanceName: _jsp_MySimpleTag_14

        // TEXT: lineNumber: 17
        // out.write("\r\nabc\r\n    <c:if test=\"${1 == 1}\">\r\n        <c:forEach items=\"1,1\" var=\"myvar\">${myvar}</c:forEach>\r\n    </c:if>\r\n1");
        out.write(_jsp_string_40, 0, _jsp_string_40.length);

        out.flush();
        jspWriter.flush();
    }

    // NODE START: lineNumber: 8, offset: 13, length: 26, tagClassName: test.com.skin.ayada.taglib.MySimpleTag, tagInstanceName: _jsp_MySimpleTag_14
    // <test:simpleTag>...</test:simpleTag>
    public class JspFragment_14 extends com.skin.ayada.tagext.AbstractJspFragment{
        @Override
        public void execute(final JspWriter writer) throws Exception{
            JspWriter out = writer;
            PageContext pageContext = this.getPageContext();
            ExpressionContext expressionContext = pageContext.getExpressionContext();
            Tag _jsp_MySimpleTag_14 = this.getParent();

            // offset: 14, length: 24
            // TEXT: lineNumber: 8
            // out.write("123");
            out.write(_jsp_string_15, 0, _jsp_string_15.length);
            // VARIABLE: lineNumber: 8
            out.print(pageContext.getAttribute("mytest"), expressionContext.getEscapeXml());
            // TEXT: lineNumber: 8
            // out.write("\r\n    ");
            out.write(_jsp_string_17, 0, _jsp_string_17.length);

            // NODE START: lineNumber: 9, offset: 17, length: 4, tagClassName: test.com.skin.ayada.taglib.MySimpleTag, tagInstanceName: _jsp_MySimpleTag_18
            // <test:simpleTag>...</test:simpleTag>
            test.com.skin.ayada.taglib.MySimpleTag _jsp_MySimpleTag_18 = new test.com.skin.ayada.taglib.MySimpleTag();
            _jsp_MySimpleTag_18.setPageContext(pageContext);
            _jsp_MySimpleTag_18.setParent(_jsp_MySimpleTag_14);

            JspFragment_18 _jsp_fragment_18 = new JspFragment_18();
            _jsp_fragment_18.setPageContext(pageContext);
            _jsp_fragment_18.setParent(_jsp_MySimpleTag_18);

            _jsp_MySimpleTag_18.setJspBody(_jsp_fragment_18);
            _jsp_MySimpleTag_18.doTag();
            _jsp_MySimpleTag_18.release();
            // NODE END: lineNumber: 9, tagClassName: test.com.skin.ayada.taglib.MySimpleTag, tagInstanceName: _jsp_MySimpleTag_18

            // TEXT: lineNumber: 9
            // out.write("\r\n    ");
            out.write(_jsp_string_22, 0, _jsp_string_22.length);

            // NODE START: lineNumber: 10, offset: 22, length: 7, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_23
            // <c:if test="${1 == 1}">...</c:if>
            if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")){
                // TEXT: lineNumber: 10
                // out.write("\r\n        ");
                out.write(_jsp_string_24, 0, _jsp_string_24.length);

                // NODE START: lineNumber: 11, offset: 24, length: 3, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_25
                // <c:forEach items="1,1" var="myvar">...</c:forEach>
                Object _jsp_old_var_25 = pageContext.getAttribute("myvar");
                com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_25 = new com.skin.ayada.jstl.core.ForEachTag();
                _jsp_ForEachTag_25.setParent((Tag)null);
                _jsp_ForEachTag_25.setPageContext(pageContext);
                _jsp_ForEachTag_25.setVar("myvar");
                _jsp_ForEachTag_25.setItems("1,1");
                if(_jsp_ForEachTag_25.doStartTag() != Tag.SKIP_BODY){
                    while(true){
                        // VARIABLE: lineNumber: 11
                        out.print(pageContext.getAttribute("myvar"), expressionContext.getEscapeXml());
                        if(_jsp_ForEachTag_25.doAfterBody() != IterationTag.EVAL_BODY_AGAIN){
                            break;
                        }
                    }
                }
                _jsp_ForEachTag_25.release();
                pageContext.setAttribute("myvar", _jsp_old_var_25);
                // jsp.jstl.core.ForEachTag END
                // NODE END: lineNumber: 11, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_25

                // TEXT: lineNumber: 11
                // out.write("\r\n    ");
                out.write(_jsp_string_28, 0, _jsp_string_28.length);
            } // jsp.jstl.core.IfTag END
            // NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_23

            // TEXT: lineNumber: 12
            // out.write("\r\n    ");
            out.write(_jsp_string_30, 0, _jsp_string_30.length);

            // NODE START: lineNumber: 13, offset: 30, length: 7, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_31
            // <c:forEach items="1,1">...</c:forEach>
            com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_31 = new com.skin.ayada.jstl.core.ForEachTag();
            _jsp_ForEachTag_31.setParent(_jsp_MySimpleTag_14);
            _jsp_ForEachTag_31.setPageContext(pageContext);
            _jsp_ForEachTag_31.setItems("1,1");
            if(_jsp_ForEachTag_31.doStartTag() != Tag.SKIP_BODY){
                while(true){
                    // TEXT: lineNumber: 13
                    // out.write("\r\n        ");
                    out.write(_jsp_string_32, 0, _jsp_string_32.length);

                    // NODE START: lineNumber: 14, offset: 32, length: 3, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_33
                    // <c:forEach items="a,a" var="myvar">...</c:forEach>
                    Object _jsp_old_var_33 = pageContext.getAttribute("myvar");
                    com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_33 = new com.skin.ayada.jstl.core.ForEachTag();
                    _jsp_ForEachTag_33.setParent((Tag)null);
                    _jsp_ForEachTag_33.setPageContext(pageContext);
                    _jsp_ForEachTag_33.setVar("myvar");
                    _jsp_ForEachTag_33.setItems("a,a");
                    if(_jsp_ForEachTag_33.doStartTag() != Tag.SKIP_BODY){
                        while(true){
                            // VARIABLE: lineNumber: 14
                            out.print(pageContext.getAttribute("myvar"), expressionContext.getEscapeXml());
                            if(_jsp_ForEachTag_33.doAfterBody() != IterationTag.EVAL_BODY_AGAIN){
                                break;
                            }
                        }
                    }
                    _jsp_ForEachTag_33.release();
                    pageContext.setAttribute("myvar", _jsp_old_var_33);
                    // jsp.jstl.core.ForEachTag END
                    // NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_33

                    // TEXT: lineNumber: 14
                    // out.write("\r\n    ");
                    out.write(_jsp_string_36, 0, _jsp_string_36.length);
                    if(_jsp_ForEachTag_31.doAfterBody() != IterationTag.EVAL_BODY_AGAIN){
                        break;
                    }
                }
            }
            _jsp_ForEachTag_31.release();
            // jsp.jstl.core.ForEachTag END
            // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_31

            // TEXT: lineNumber: 15
            // out.write("\r\nss\r\n");
            out.write(_jsp_string_38, 0, _jsp_string_38.length);
        }
    }
    // NODE END: lineNumber: 8, tagClassName: test.com.skin.ayada.taglib.MySimpleTag, tagInstanceName: _jsp_MySimpleTag_14

    // NODE START: lineNumber: 9, offset: 17, length: 4, tagClassName: test.com.skin.ayada.taglib.MySimpleTag, tagInstanceName: _jsp_MySimpleTag_18
    // <test:simpleTag>...</test:simpleTag>
    public class JspFragment_18 extends com.skin.ayada.tagext.AbstractJspFragment{
        @Override
        public void execute(final JspWriter writer) throws Exception{
            JspWriter out = writer;
            PageContext pageContext = this.getPageContext();
            ExpressionContext expressionContext = pageContext.getExpressionContext();
            Tag _jsp_MySimpleTag_18 = this.getParent();

            // offset: 18, length: 2
            // VARIABLE: lineNumber: 9
            out.print(pageContext.getAttribute("mytest"), expressionContext.getEscapeXml());
            // TEXT: lineNumber: 9
            // out.write("xyz");
            out.write(_jsp_string_20, 0, _jsp_string_20.length);
        }
    }
    // NODE END: lineNumber: 9, tagClassName: test.com.skin.ayada.taglib.MySimpleTag, tagInstanceName: _jsp_MySimpleTag_18

    private static final char[] _jsp_string_9 = "<!-- t:import name=\"test:simpleTag\" className=\"test.com.skin.ayada.taglib.MySimpleTag\"/ -->\r\n".toCharArray();
    private static final char[] _jsp_string_13 = "\r\n".toCharArray();
    private static final char[] _jsp_string_15 = "123".toCharArray();
    private static final char[] _jsp_string_17 = "\r\n    ".toCharArray();
    private static final char[] _jsp_string_20 = "xyz".toCharArray();
    private static final char[] _jsp_string_22 = "\r\n    ".toCharArray();
    private static final char[] _jsp_string_24 = "\r\n        ".toCharArray();
    private static final char[] _jsp_string_28 = "\r\n    ".toCharArray();
    private static final char[] _jsp_string_30 = "\r\n    ".toCharArray();
    private static final char[] _jsp_string_32 = "\r\n        ".toCharArray();
    private static final char[] _jsp_string_36 = "\r\n    ".toCharArray();
    private static final char[] _jsp_string_38 = "\r\nss\r\n".toCharArray();
    private static final char[] _jsp_string_40 = "\r\nabc\r\n    <c:if test=\"${1 == 1}\">\r\n        <c:forEach items=\"1,1\" var=\"myvar\">${myvar}</c:forEach>\r\n    </c:if>\r\n1".toCharArray();

}
