/*
 * $RCSfile: SqlTagTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-08 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /sqlTagTest.jsp
 * lastModified: 2014-03-31 17:18:38 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-08 22:06:53 342)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: SqlTagTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class SqlTagTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        SqlTagTestTemplate template = new SqlTagTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html;charset=UTF-8"/>

        // NODE START: lineNumber: 2, offset: 2, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_3
        // <sql:execute sql=\"delete from my_test2;\" out=\"${pageContext.getOut()}\"/>
        com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_3 = new com.skin.ayada.jstl.sql.SqlTag();
        _jsp_SqlTag_3.setPageContext(pageContext);
        _jsp_SqlTag_3.setParent((Tag)null);
        _jsp_SqlTag_3.setSql("delete from my_test2;");
        _jsp_SqlTag_3.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext.getOut()}", null));
        int _jsp_start_flag_3 = _jsp_SqlTag_3.doStartTag();

        if(_jsp_start_flag_3 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_3 != Tag.SKIP_BODY) {
            _jsp_SqlTag_3.doAfterBody();
        }
        _jsp_SqlTag_3.doEndTag();
        _jsp_SqlTag_3.release();
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_3

        // TEXT: lineNumber: 2
        // out.write("\r\n");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);

        // NODE START: lineNumber: 3, offset: 5, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_6
        // <sql:execute sql=\"insert into my_test2(my_id, my_code, my_name) values (1, &#39;1&#39;, &#39;1&#39;);\"/>
        com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_6 = new com.skin.ayada.jstl.sql.SqlTag();
        _jsp_SqlTag_6.setPageContext(pageContext);
        _jsp_SqlTag_6.setParent((Tag)null);
        _jsp_SqlTag_6.setSql("insert into my_test2(my_id, my_code, my_name) values (1, \'1\', \'1\');");
        int _jsp_start_flag_6 = _jsp_SqlTag_6.doStartTag();

        if(_jsp_start_flag_6 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_6 != Tag.SKIP_BODY) {
            _jsp_SqlTag_6.doAfterBody();
        }
        _jsp_SqlTag_6.doEndTag();
        _jsp_SqlTag_6.release();
        // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_6

        // TEXT: lineNumber: 3
        // out.write("\r\n");
        out.write(_jsp_string_8, 0, _jsp_string_8.length);

        // NODE START: lineNumber: 4, offset: 8, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_9
        // <sql:execute home=\"${template.home}/database\" file=\"create.sql\" encoding=\"UTF-8\" out=\"${pageContext.getOut()}\"/>
        com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_9 = new com.skin.ayada.jstl.sql.SqlTag();
        _jsp_SqlTag_9.setPageContext(pageContext);
        _jsp_SqlTag_9.setParent((Tag)null);
        _jsp_SqlTag_9.setHome(ExpressionUtil.getString(expressionContext, "${template.home}/database"));
        _jsp_SqlTag_9.setFile("create.sql");
        _jsp_SqlTag_9.setEncoding("UTF-8");
        _jsp_SqlTag_9.setOut(ExpressionUtil.evaluate(expressionContext, "${pageContext.getOut()}", null));
        int _jsp_start_flag_9 = _jsp_SqlTag_9.doStartTag();

        if(_jsp_start_flag_9 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_9 != Tag.SKIP_BODY) {
            _jsp_SqlTag_9.doAfterBody();
        }
        _jsp_SqlTag_9.doEndTag();
        _jsp_SqlTag_9.release();
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_9

        // TEXT: lineNumber: 4
        // out.write("\r\n\r\n");
        out.write(_jsp_string_11, 0, _jsp_string_11.length);

        // NODE START: lineNumber: 6, offset: 11, length: 23, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_12
        // <sql:execute>...</sql:execute>
        com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_12 = new com.skin.ayada.jstl.sql.SqlTag();
        _jsp_SqlTag_12.setPageContext(pageContext);
        _jsp_SqlTag_12.setParent((Tag)null);
        int _jsp_start_flag_12 = _jsp_SqlTag_12.doStartTag();

        if(_jsp_start_flag_12 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_12 != Tag.SKIP_BODY) {
            int _jsp_flag_12 = 0;
            if(_jsp_start_flag_12 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_12 = pageContext.pushBody();
                _jsp_SqlTag_12.setBodyContent(_jsp_body_content_12);
                _jsp_SqlTag_12.doInitBody();
                out = _jsp_body_content_12;
            }

            do {
                // TEXT: lineNumber: 6
                // out.write("\r\n    ");
                out.write(_jsp_string_13, 0, _jsp_string_13.length);

                // NODE START: lineNumber: 7, offset: 13, length: 9, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_14
                // <c:forEach items=\"1, 2, 3, 4, 5\" var=\"id\">...</c:forEach>
                Object _jsp_old_var_14 = pageContext.getAttribute("id");
                com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_14 = new com.skin.ayada.jstl.core.ForEachTag();
                _jsp_ForEachTag_14.setParent(_jsp_SqlTag_12);
                _jsp_ForEachTag_14.setPageContext(pageContext);
                _jsp_ForEachTag_14.setVar("id");
                _jsp_ForEachTag_14.setItems("1, 2, 3, 4, 5");
                if(_jsp_ForEachTag_14.doStartTag() != Tag.SKIP_BODY) {
                    while(true) {
                        // TEXT: lineNumber: 7
                        // out.write("\r\n        insert into my_test1(my_id, my_code, my_name) values (");
                        out.write(_jsp_string_15, 0, _jsp_string_15.length);
                        // VARIABLE: lineNumber: 8
                        expressionContext.print(out, pageContext.getAttribute("id"));
                        // TEXT: lineNumber: 8
                        // out.write(", \'");
                        out.write(_jsp_string_17, 0, _jsp_string_17.length);
                        // VARIABLE: lineNumber: 8
                        expressionContext.print(out, pageContext.getAttribute("id"));
                        // TEXT: lineNumber: 8
                        // out.write("\', \'");
                        out.write(_jsp_string_19, 0, _jsp_string_19.length);
                        // VARIABLE: lineNumber: 8
                        expressionContext.print(out, pageContext.getAttribute("id"));
                        // TEXT: lineNumber: 8
                        // out.write("\');\r\n    ");
                        out.write(_jsp_string_21, 0, _jsp_string_21.length);
                        if(_jsp_ForEachTag_14.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                            break;
                        }
                    }
                }
                _jsp_ForEachTag_14.release();
                pageContext.setAttribute("id", _jsp_old_var_14);
                // jsp.jstl.core.ForEachTag END
                // NODE END: lineNumber: 7, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_14

                // TEXT: lineNumber: 9
                // out.write("\r\n    ");
                out.write(_jsp_string_23, 0, _jsp_string_23.length);

                // NODE START: lineNumber: 10, offset: 23, length: 9, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_24
                // <c:forEach items=\"1, 2, 3, 4, 5\" var=\"id\">...</c:forEach>
                Object _jsp_old_var_24 = pageContext.getAttribute("id");
                com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_24 = new com.skin.ayada.jstl.core.ForEachTag();
                _jsp_ForEachTag_24.setParent(_jsp_SqlTag_12);
                _jsp_ForEachTag_24.setPageContext(pageContext);
                _jsp_ForEachTag_24.setVar("id");
                _jsp_ForEachTag_24.setItems("1, 2, 3, 4, 5");
                if(_jsp_ForEachTag_24.doStartTag() != Tag.SKIP_BODY) {
                    while(true) {
                        // TEXT: lineNumber: 10
                        // out.write("\r\n        insert into my_test2(my_id, my_code, my_name) values (");
                        out.write(_jsp_string_25, 0, _jsp_string_25.length);
                        // VARIABLE: lineNumber: 11
                        expressionContext.print(out, pageContext.getAttribute("id"));
                        // TEXT: lineNumber: 11
                        // out.write(", \'");
                        out.write(_jsp_string_27, 0, _jsp_string_27.length);
                        // VARIABLE: lineNumber: 11
                        expressionContext.print(out, pageContext.getAttribute("id"));
                        // TEXT: lineNumber: 11
                        // out.write("\', \'");
                        out.write(_jsp_string_29, 0, _jsp_string_29.length);
                        // VARIABLE: lineNumber: 11
                        expressionContext.print(out, pageContext.getAttribute("id"));
                        // TEXT: lineNumber: 11
                        // out.write("\');\r\n    ");
                        out.write(_jsp_string_31, 0, _jsp_string_31.length);
                        if(_jsp_ForEachTag_24.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                            break;
                        }
                    }
                }
                _jsp_ForEachTag_24.release();
                pageContext.setAttribute("id", _jsp_old_var_24);
                // jsp.jstl.core.ForEachTag END
                // NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_24

                // TEXT: lineNumber: 12
                // out.write("\r\n");
                out.write(_jsp_string_33, 0, _jsp_string_33.length);
                _jsp_flag_12 = _jsp_SqlTag_12.doAfterBody();
            }
            while(_jsp_flag_12 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_12 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_SqlTag_12.doEndTag();
        _jsp_SqlTag_12.release();
        // NODE END: lineNumber: 6, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_12

        // TEXT: lineNumber: 13
        // out.write("\r\n\r\n");
        out.write(_jsp_string_35, 0, _jsp_string_35.length);

        // NODE START: lineNumber: 15, offset: 35, length: 3, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_36
        // <sql:execute>...</sql:execute>
        com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_36 = new com.skin.ayada.jstl.sql.SqlTag();
        _jsp_SqlTag_36.setPageContext(pageContext);
        _jsp_SqlTag_36.setParent((Tag)null);
        int _jsp_start_flag_36 = _jsp_SqlTag_36.doStartTag();

        if(_jsp_start_flag_36 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_36 != Tag.SKIP_BODY) {
            int _jsp_flag_36 = 0;
            if(_jsp_start_flag_36 == BodyTag.EVAL_BODY_BUFFERED) {
                BodyContent _jsp_body_content_36 = pageContext.pushBody();
                _jsp_SqlTag_36.setBodyContent(_jsp_body_content_36);
                _jsp_SqlTag_36.doInitBody();
                out = _jsp_body_content_36;
            }

            do {
                // TEXT: lineNumber: 15
                // out.write("\r\ndelete from my_test2;\r\ninsert into my_test2(my_id, my_code, my_name) values (1001, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1002, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1003, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1004, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1005, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1006, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1007, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1008, \'1001\', \'1001\');\r\n");
                out.write(_jsp_string_37, 0, _jsp_string_37.length);
                _jsp_flag_36 = _jsp_SqlTag_36.doAfterBody();
            }
            while(_jsp_flag_36 == IterationTag.EVAL_BODY_AGAIN);
            if(_jsp_start_flag_36 == BodyTag.EVAL_BODY_BUFFERED) {
                out = pageContext.popBody();
            }
        }
        _jsp_SqlTag_36.doEndTag();
        _jsp_SqlTag_36.release();
        // NODE END: lineNumber: 15, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_36

        // TEXT: lineNumber: 25
        // out.write("\r\n\r\n");
        out.write(_jsp_string_39, 0, _jsp_string_39.length);

        // NODE START: lineNumber: 27, offset: 39, length: 2, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_40
        // <sql:execute connection=\"${connection}\" sql=\"insert into my_test2(my_id, my_code, my_name) values (1009, &#39;1001&#39;, &#39;1001&#39;);\"/>
        com.skin.ayada.jstl.sql.SqlTag _jsp_SqlTag_40 = new com.skin.ayada.jstl.sql.SqlTag();
        _jsp_SqlTag_40.setPageContext(pageContext);
        _jsp_SqlTag_40.setParent((Tag)null);
        _jsp_SqlTag_40.setConnection((java.sql.Connection)(ExpressionUtil.evaluate(expressionContext, "${connection}", java.sql.Connection.class)));
        _jsp_SqlTag_40.setSql("insert into my_test2(my_id, my_code, my_name) values (1009, \'1001\', \'1001\');");
        int _jsp_start_flag_40 = _jsp_SqlTag_40.doStartTag();

        if(_jsp_start_flag_40 == Tag.SKIP_PAGE) {
            return;
        }
        if(_jsp_start_flag_40 != Tag.SKIP_BODY) {
            _jsp_SqlTag_40.doAfterBody();
        }
        _jsp_SqlTag_40.doEndTag();
        _jsp_SqlTag_40.release();
        // NODE END: lineNumber: 27, tagClassName: com.skin.ayada.jstl.sql.SqlTag, tagInstanceName: _jsp_SqlTag_40

        // TEXT: lineNumber: 27
        // out.write("\r\n\r\n<table>\r\n    <tr>\r\n        <td>id</td>\r\n        <td>userName</td>\r\n        <td>nickName</td>\r\n    </tr>\r\n    ");
        out.write(_jsp_string_42, 0, _jsp_string_42.length);

        // NODE START: lineNumber: 35, offset: 42, length: 9, tagClassName: com.skin.ayada.jstl.sql.QueryTag, tagInstanceName: _jsp_QueryTag_43
        // <sql:query var=\"resultSet\" sql=\"select * from my_test2 where my_id &gt; 1001\" offset=\"2\">...</sql:query>
        com.skin.ayada.jstl.sql.QueryTag _jsp_QueryTag_43 = new com.skin.ayada.jstl.sql.QueryTag();
        try {
            _jsp_QueryTag_43.setPageContext(pageContext);
            _jsp_QueryTag_43.setParent((Tag)null);
            _jsp_QueryTag_43.setVar("resultSet");
            _jsp_QueryTag_43.setSql("select * from my_test2 where my_id > 1001");
            _jsp_QueryTag_43.setOffset(2);
            int _jsp_start_flag_43 = _jsp_QueryTag_43.doStartTag();

            if(_jsp_start_flag_43 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_43 != Tag.SKIP_BODY) {
                int _jsp_flag_43 = 0;

                do {
                    // TEXT: lineNumber: 35
                    // out.write("\r\n    <tr>\r\n        <td>");
                    out.write(_jsp_string_44, 0, _jsp_string_44.length);
                    // EXPRESSION: lineNumber: 37
                    expressionContext.print(out, expressionContext.getString("resultSet.getLong(\"my_id\")"));
                    // TEXT: lineNumber: 37
                    // out.write("</td>\r\n        <td>");
                    out.write(_jsp_string_46, 0, _jsp_string_46.length);
                    // EXPRESSION: lineNumber: 38
                    expressionContext.print(out, expressionContext.getString("resultSet.getString(\"my_code\")"));
                    // TEXT: lineNumber: 38
                    // out.write("</td>\r\n        <td>");
                    out.write(_jsp_string_48, 0, _jsp_string_48.length);
                    // EXPRESSION: lineNumber: 39
                    expressionContext.print(out, expressionContext.getString("resultSet.getString(\"my_name\")"));
                    // TEXT: lineNumber: 39
                    // out.write("</td>\r\n    </tr>\r\n    ");
                    out.write(_jsp_string_50, 0, _jsp_string_50.length);
                    _jsp_flag_43 = _jsp_QueryTag_43.doAfterBody();
                }
                while(_jsp_flag_43 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_QueryTag_43.doEndTag();
            _jsp_QueryTag_43.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_QueryTag_43.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_QueryTag_43.doFinally();
        }
        // NODE END: lineNumber: 35, tagClassName: com.skin.ayada.jstl.sql.QueryTag, tagInstanceName: _jsp_QueryTag_43

        // TEXT: lineNumber: 41
        // out.write("\r\n</table>\r\n");
        out.write(_jsp_string_52, 0, _jsp_string_52.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_5 = "\r\n".toCharArray();
    public static final char[] _jsp_string_8 = "\r\n".toCharArray();
    public static final char[] _jsp_string_11 = "\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_13 = "\r\n    ".toCharArray();
    public static final char[] _jsp_string_15 = "\r\n        insert into my_test1(my_id, my_code, my_name) values (".toCharArray();
    public static final char[] _jsp_string_17 = ", \'".toCharArray();
    public static final char[] _jsp_string_19 = "\', \'".toCharArray();
    public static final char[] _jsp_string_21 = "\');\r\n    ".toCharArray();
    public static final char[] _jsp_string_23 = "\r\n    ".toCharArray();
    public static final char[] _jsp_string_25 = "\r\n        insert into my_test2(my_id, my_code, my_name) values (".toCharArray();
    public static final char[] _jsp_string_27 = ", \'".toCharArray();
    public static final char[] _jsp_string_29 = "\', \'".toCharArray();
    public static final char[] _jsp_string_31 = "\');\r\n    ".toCharArray();
    public static final char[] _jsp_string_33 = "\r\n".toCharArray();
    public static final char[] _jsp_string_35 = "\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_37 = "\r\ndelete from my_test2;\r\ninsert into my_test2(my_id, my_code, my_name) values (1001, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1002, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1003, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1004, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1005, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1006, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1007, \'1001\', \'1001\');\r\ninsert into my_test2(my_id, my_code, my_name) values (1008, \'1001\', \'1001\');\r\n".toCharArray();
    public static final char[] _jsp_string_39 = "\r\n\r\n".toCharArray();
    public static final char[] _jsp_string_42 = "\r\n\r\n<table>\r\n    <tr>\r\n        <td>id</td>\r\n        <td>userName</td>\r\n        <td>nickName</td>\r\n    </tr>\r\n    ".toCharArray();
    public static final char[] _jsp_string_44 = "\r\n    <tr>\r\n        <td>".toCharArray();
    public static final char[] _jsp_string_46 = "</td>\r\n        <td>".toCharArray();
    public static final char[] _jsp_string_48 = "</td>\r\n        <td>".toCharArray();
    public static final char[] _jsp_string_50 = "</td>\r\n    </tr>\r\n    ".toCharArray();
    public static final char[] _jsp_string_52 = "\r\n</table>\r\n".toCharArray();

}
