/*
 * $RCSfile: StacktraceTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2013-11-28 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: C:\WorkSpace\ayada\webapp
 * path: stacktrace.jsp
 * lastModified: 2013-11-28 17:32:16 000
 * options: -fastJstl false
 * JSP generated by JspCompiler-1.0.0.8 (built 2014-06-28 11:49:14 943)
 */
package _tpl._jsp;

import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;

/**
 * <p>Title: StacktraceTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
public class StacktraceTemplate extends JspTemplate
{
    public static void main(String[] args)
    {
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getDefaultPageContext(writer);
        StacktraceTemplate template = new StacktraceTemplate();

        try{
            template._execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable)
        {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    public void _execute(final PageContext pageContext) throws Throwable
    {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /* TEXT: lineNumber: 2 */
        out.write("<html>\r\n<head>\r\n<title>test</title>\r\n<script type=\"text/javascript\" src=\"");
        /* VARIABLE: lineNumber: 5 */
        out.print(pageContext.getAttribute("resource"), false);
        /* TEXT: lineNumber: 5 */
        out.write("/js/jquery-1.4.2.min.js\"></script>\r\n</head>\r\n<body version=\"1.0\">\r\n");
        /* EXPRESSION: lineNumber: 8 */
        out.write(expressionContext.getString("user.userName"));
        /* TEXT: lineNumber: 8 */
        out.write("\r\n");

        /* NODE START: lineNumber: 9, offset: 5, length: 42, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_6 */
        /* <c:if test="${1 == 1}">...</c:if> */
        com.skin.ayada.jstl.core.IfTag _jsp_IfTag_6 = new com.skin.ayada.jstl.core.IfTag();
        _jsp_IfTag_6.setParent((Tag)null);
        _jsp_IfTag_6.setPageContext(pageContext);
        _jsp_IfTag_6.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
        int _jsp_start_flag_6 = _jsp_IfTag_6.doStartTag();

        if(_jsp_start_flag_6 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_6 != Tag.SKIP_BODY){
            int _jsp_flag_6 = 0;

            do{
                /* TEXT: lineNumber: 9 */
                out.write("\r\n    ");

                /* NODE START: lineNumber: 10, offset: 7, length: 38, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_8 */
                /* <c:if test="${1 == 1}">...</c:if> */
                com.skin.ayada.jstl.core.IfTag _jsp_IfTag_8 = new com.skin.ayada.jstl.core.IfTag();
                _jsp_IfTag_8.setParent(_jsp_IfTag_6);
                _jsp_IfTag_8.setPageContext(pageContext);
                _jsp_IfTag_8.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                int _jsp_start_flag_8 = _jsp_IfTag_8.doStartTag();

                if(_jsp_start_flag_8 == Tag.SKIP_PAGE){
                    return;
                }
                if(_jsp_start_flag_8 != Tag.SKIP_BODY){
                    int _jsp_flag_8 = 0;

                    do{
                        /* TEXT: lineNumber: 10 */
                        out.write("\r\n        ");

                        /* NODE START: lineNumber: 11, offset: 9, length: 34, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_10 */
                        /* <c:if test="${1 == 1}">...</c:if> */
                        com.skin.ayada.jstl.core.IfTag _jsp_IfTag_10 = new com.skin.ayada.jstl.core.IfTag();
                        _jsp_IfTag_10.setParent(_jsp_IfTag_8);
                        _jsp_IfTag_10.setPageContext(pageContext);
                        _jsp_IfTag_10.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                        int _jsp_start_flag_10 = _jsp_IfTag_10.doStartTag();

                        if(_jsp_start_flag_10 == Tag.SKIP_PAGE){
                            return;
                        }
                        if(_jsp_start_flag_10 != Tag.SKIP_BODY){
                            int _jsp_flag_10 = 0;

                            do{
                                /* TEXT: lineNumber: 11 */
                                out.write("\r\n            ");

                                /* NODE START: lineNumber: 12, offset: 11, length: 30, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_12 */
                                /* <c:if test="${1 == 1}">...</c:if> */
                                com.skin.ayada.jstl.core.IfTag _jsp_IfTag_12 = new com.skin.ayada.jstl.core.IfTag();
                                _jsp_IfTag_12.setParent(_jsp_IfTag_10);
                                _jsp_IfTag_12.setPageContext(pageContext);
                                _jsp_IfTag_12.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                                int _jsp_start_flag_12 = _jsp_IfTag_12.doStartTag();

                                if(_jsp_start_flag_12 == Tag.SKIP_PAGE){
                                    return;
                                }
                                if(_jsp_start_flag_12 != Tag.SKIP_BODY){
                                    int _jsp_flag_12 = 0;

                                    do{
                                        /* TEXT: lineNumber: 12 */
                                        out.write("\r\n                ");

                                        /* NODE START: lineNumber: 13, offset: 13, length: 26, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_14 */
                                        /* <c:if test="${1 == 1}">...</c:if> */
                                        com.skin.ayada.jstl.core.IfTag _jsp_IfTag_14 = new com.skin.ayada.jstl.core.IfTag();
                                        _jsp_IfTag_14.setParent(_jsp_IfTag_12);
                                        _jsp_IfTag_14.setPageContext(pageContext);
                                        _jsp_IfTag_14.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                                        int _jsp_start_flag_14 = _jsp_IfTag_14.doStartTag();

                                        if(_jsp_start_flag_14 == Tag.SKIP_PAGE){
                                            return;
                                        }
                                        if(_jsp_start_flag_14 != Tag.SKIP_BODY){
                                            int _jsp_flag_14 = 0;

                                            do{
                                                /* TEXT: lineNumber: 13 */
                                                out.write("\r\n                    ");

                                                /* NODE START: lineNumber: 14, offset: 15, length: 22, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_16 */
                                                /* <c:if test="${1 == 1}">...</c:if> */
                                                com.skin.ayada.jstl.core.IfTag _jsp_IfTag_16 = new com.skin.ayada.jstl.core.IfTag();
                                                _jsp_IfTag_16.setParent(_jsp_IfTag_14);
                                                _jsp_IfTag_16.setPageContext(pageContext);
                                                _jsp_IfTag_16.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                                                int _jsp_start_flag_16 = _jsp_IfTag_16.doStartTag();

                                                if(_jsp_start_flag_16 == Tag.SKIP_PAGE){
                                                    return;
                                                }
                                                if(_jsp_start_flag_16 != Tag.SKIP_BODY){
                                                    int _jsp_flag_16 = 0;

                                                    do{
                                                        /* TEXT: lineNumber: 14 */
                                                        out.write("\r\n                        ");

                                                        /* NODE START: lineNumber: 15, offset: 17, length: 18, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_18 */
                                                        /* <c:if test="${1 == 1}">...</c:if> */
                                                        com.skin.ayada.jstl.core.IfTag _jsp_IfTag_18 = new com.skin.ayada.jstl.core.IfTag();
                                                        _jsp_IfTag_18.setParent(_jsp_IfTag_16);
                                                        _jsp_IfTag_18.setPageContext(pageContext);
                                                        _jsp_IfTag_18.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                                                        int _jsp_start_flag_18 = _jsp_IfTag_18.doStartTag();

                                                        if(_jsp_start_flag_18 == Tag.SKIP_PAGE){
                                                            return;
                                                        }
                                                        if(_jsp_start_flag_18 != Tag.SKIP_BODY){
                                                            int _jsp_flag_18 = 0;

                                                            do{
                                                                /* TEXT: lineNumber: 15 */
                                                                out.write("\r\n                            ");

                                                                /* NODE START: lineNumber: 16, offset: 19, length: 14, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_20 */
                                                                /* <c:if test="${1 == 1}">...</c:if> */
                                                                com.skin.ayada.jstl.core.IfTag _jsp_IfTag_20 = new com.skin.ayada.jstl.core.IfTag();
                                                                _jsp_IfTag_20.setParent(_jsp_IfTag_18);
                                                                _jsp_IfTag_20.setPageContext(pageContext);
                                                                _jsp_IfTag_20.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                                                                int _jsp_start_flag_20 = _jsp_IfTag_20.doStartTag();

                                                                if(_jsp_start_flag_20 == Tag.SKIP_PAGE){
                                                                    return;
                                                                }
                                                                if(_jsp_start_flag_20 != Tag.SKIP_BODY){
                                                                    int _jsp_flag_20 = 0;

                                                                    do{
                                                                        /* TEXT: lineNumber: 16 */
                                                                        out.write("\r\n                                ");

                                                                        /* NODE START: lineNumber: 17, offset: 21, length: 10, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_22 */
                                                                        /* <c:if test="${1 == 1}">...</c:if> */
                                                                        com.skin.ayada.jstl.core.IfTag _jsp_IfTag_22 = new com.skin.ayada.jstl.core.IfTag();
                                                                        _jsp_IfTag_22.setParent(_jsp_IfTag_20);
                                                                        _jsp_IfTag_22.setPageContext(pageContext);
                                                                        _jsp_IfTag_22.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                                                                        int _jsp_start_flag_22 = _jsp_IfTag_22.doStartTag();

                                                                        if(_jsp_start_flag_22 == Tag.SKIP_PAGE){
                                                                            return;
                                                                        }
                                                                        if(_jsp_start_flag_22 != Tag.SKIP_BODY){
                                                                            int _jsp_flag_22 = 0;

                                                                            do{
                                                                                /* TEXT: lineNumber: 17 */
                                                                                out.write("\r\n                                    ");

                                                                                /* NODE START: lineNumber: 18, offset: 23, length: 6, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_24 */
                                                                                /* <c:if test="${1 == 1}">...</c:if> */
                                                                                com.skin.ayada.jstl.core.IfTag _jsp_IfTag_24 = new com.skin.ayada.jstl.core.IfTag();
                                                                                _jsp_IfTag_24.setParent(_jsp_IfTag_22);
                                                                                _jsp_IfTag_24.setPageContext(pageContext);
                                                                                _jsp_IfTag_24.setTest(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}"));
                                                                                int _jsp_start_flag_24 = _jsp_IfTag_24.doStartTag();

                                                                                if(_jsp_start_flag_24 == Tag.SKIP_PAGE){
                                                                                    return;
                                                                                }
                                                                                if(_jsp_start_flag_24 != Tag.SKIP_BODY){
                                                                                    int _jsp_flag_24 = 0;

                                                                                    do{
                                                                                        /* TEXT: lineNumber: 18 */
                                                                                        out.write("\r\n------------------------- StackTrace -------------------------\r\n");

                                                                                        /* NODE START: lineNumber: 20, offset: 25, length: 2, tagClassName: com.skin.ayada.jstl.core.StackTraceTag, tagInstanceName: _jsp_StackTraceTag_26 */
                                                                                        /* <c:stackTrace/> */
                                                                                        com.skin.ayada.jstl.core.StackTraceTag _jsp_StackTraceTag_26 = new com.skin.ayada.jstl.core.StackTraceTag();
                                                                                        _jsp_StackTraceTag_26.setParent(_jsp_IfTag_24);
                                                                                        _jsp_StackTraceTag_26.setPageContext(pageContext);
                                                                                        int _jsp_start_flag_26 = _jsp_StackTraceTag_26.doStartTag();

                                                                                        if(_jsp_start_flag_26 == Tag.SKIP_PAGE){
                                                                                            return;
                                                                                        }
                                                                                        if(_jsp_start_flag_26 != Tag.SKIP_BODY){
                                                                                            _jsp_StackTraceTag_26.doAfterBody();
                                                                                        }
                                                                                        _jsp_StackTraceTag_26.doEndTag();
                                                                                        _jsp_StackTraceTag_26.release();
                                                                                        /* NODE END: lineNumber: 20, tagClassName: com.skin.ayada.jstl.core.StackTraceTag, tagInstanceName: _jsp_StackTraceTag_26 */

                                                                                        /* TEXT: lineNumber: 20 */
                                                                                        out.write("\r\n                                    ");
                                                                                        _jsp_flag_24 = _jsp_IfTag_24.doAfterBody();
                                                                                    }
                                                                                    while(_jsp_flag_24 == IterationTag.EVAL_BODY_AGAIN);
                                                                                }
                                                                                _jsp_IfTag_24.doEndTag();
                                                                                _jsp_IfTag_24.release();
                                                                                /* NODE END: lineNumber: 18, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_24 */

                                                                                /* TEXT: lineNumber: 21 */
                                                                                out.write("\r\n                                ");
                                                                                _jsp_flag_22 = _jsp_IfTag_22.doAfterBody();
                                                                            }
                                                                            while(_jsp_flag_22 == IterationTag.EVAL_BODY_AGAIN);
                                                                        }
                                                                        _jsp_IfTag_22.doEndTag();
                                                                        _jsp_IfTag_22.release();
                                                                        /* NODE END: lineNumber: 17, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_22 */

                                                                        /* TEXT: lineNumber: 22 */
                                                                        out.write("\r\n                            ");
                                                                        _jsp_flag_20 = _jsp_IfTag_20.doAfterBody();
                                                                    }
                                                                    while(_jsp_flag_20 == IterationTag.EVAL_BODY_AGAIN);
                                                                }
                                                                _jsp_IfTag_20.doEndTag();
                                                                _jsp_IfTag_20.release();
                                                                /* NODE END: lineNumber: 16, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_20 */

                                                                /* TEXT: lineNumber: 23 */
                                                                out.write("\r\n                        ");
                                                                _jsp_flag_18 = _jsp_IfTag_18.doAfterBody();
                                                            }
                                                            while(_jsp_flag_18 == IterationTag.EVAL_BODY_AGAIN);
                                                        }
                                                        _jsp_IfTag_18.doEndTag();
                                                        _jsp_IfTag_18.release();
                                                        /* NODE END: lineNumber: 15, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_18 */

                                                        /* TEXT: lineNumber: 24 */
                                                        out.write("\r\n                    ");
                                                        _jsp_flag_16 = _jsp_IfTag_16.doAfterBody();
                                                    }
                                                    while(_jsp_flag_16 == IterationTag.EVAL_BODY_AGAIN);
                                                }
                                                _jsp_IfTag_16.doEndTag();
                                                _jsp_IfTag_16.release();
                                                /* NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_16 */

                                                /* TEXT: lineNumber: 25 */
                                                out.write("\r\n                ");
                                                _jsp_flag_14 = _jsp_IfTag_14.doAfterBody();
                                            }
                                            while(_jsp_flag_14 == IterationTag.EVAL_BODY_AGAIN);
                                        }
                                        _jsp_IfTag_14.doEndTag();
                                        _jsp_IfTag_14.release();
                                        /* NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_14 */

                                        /* TEXT: lineNumber: 26 */
                                        out.write("\r\n            ");
                                        _jsp_flag_12 = _jsp_IfTag_12.doAfterBody();
                                    }
                                    while(_jsp_flag_12 == IterationTag.EVAL_BODY_AGAIN);
                                }
                                _jsp_IfTag_12.doEndTag();
                                _jsp_IfTag_12.release();
                                /* NODE END: lineNumber: 12, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_12 */

                                /* TEXT: lineNumber: 27 */
                                out.write("\r\n        ");
                                _jsp_flag_10 = _jsp_IfTag_10.doAfterBody();
                            }
                            while(_jsp_flag_10 == IterationTag.EVAL_BODY_AGAIN);
                        }
                        _jsp_IfTag_10.doEndTag();
                        _jsp_IfTag_10.release();
                        /* NODE END: lineNumber: 11, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_10 */

                        /* TEXT: lineNumber: 28 */
                        out.write("\r\n    ");
                        _jsp_flag_8 = _jsp_IfTag_8.doAfterBody();
                    }
                    while(_jsp_flag_8 == IterationTag.EVAL_BODY_AGAIN);
                }
                _jsp_IfTag_8.doEndTag();
                _jsp_IfTag_8.release();
                /* NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_8 */

                /* TEXT: lineNumber: 29 */
                out.write("\r\n");
                _jsp_flag_6 = _jsp_IfTag_6.doAfterBody();
            }
            while(_jsp_flag_6 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_IfTag_6.doEndTag();
        _jsp_IfTag_6.release();
        /* NODE END: lineNumber: 9, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_6 */

        /* TEXT: lineNumber: 30 */
        out.write("\r\n\r\n");

        /* NODE START: lineNumber: 32, offset: 48, length: 4, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_49 */
        /* <c:if test="${user.userName == &#39;xuesong.net&#39;}">...</c:if> */
        com.skin.ayada.jstl.core.IfTag _jsp_IfTag_49 = new com.skin.ayada.jstl.core.IfTag();
        _jsp_IfTag_49.setParent((Tag)null);
        _jsp_IfTag_49.setPageContext(pageContext);
        _jsp_IfTag_49.setTest(ExpressionUtil.getBoolean(expressionContext, "${user.userName == \'xuesong.net\'}"));
        int _jsp_start_flag_49 = _jsp_IfTag_49.doStartTag();

        if(_jsp_start_flag_49 == Tag.SKIP_PAGE){
            return;
        }
        if(_jsp_start_flag_49 != Tag.SKIP_BODY){
            int _jsp_flag_49 = 0;

            do{
                /* TEXT: lineNumber: 32 */
                out.write("userName: ");
                /* EXPRESSION: lineNumber: 32 */
                out.write(expressionContext.getString("user.userName"));
                _jsp_flag_49 = _jsp_IfTag_49.doAfterBody();
            }
            while(_jsp_flag_49 == IterationTag.EVAL_BODY_AGAIN);
        }
        _jsp_IfTag_49.doEndTag();
        _jsp_IfTag_49.release();
        /* NODE END: lineNumber: 32, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_49 */

        /* TEXT: lineNumber: 32 */
        out.write("\r\n");

        /* NODE START: lineNumber: 33, offset: 53, length: 4, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_54 */
        /* <c:each items="${userList}" var="user">...</c:each> */
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_54 = new com.skin.ayada.jstl.core.ForEachTag();
        try{
            _jsp_ForEachTag_54.setParent((Tag)null);
            _jsp_ForEachTag_54.setPageContext(pageContext);
            _jsp_ForEachTag_54.setItems(ExpressionUtil.evaluate(expressionContext, "${userList}", null));
            _jsp_ForEachTag_54.setVar("user");
            int _jsp_start_flag_54 = _jsp_ForEachTag_54.doStartTag();

            if(_jsp_start_flag_54 == Tag.SKIP_PAGE){
                return;
            }
            if(_jsp_start_flag_54 != Tag.SKIP_BODY){
                int _jsp_flag_54 = 0;

                do{
                /* EXPRESSION: lineNumber: 33 */
                out.write(expressionContext.getString("user.userName"));
                /* TEXT: lineNumber: 33 */
                out.write(" ");
                    _jsp_flag_54 = _jsp_ForEachTag_54.doAfterBody();
                }
                while(_jsp_flag_54 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_ForEachTag_54.doEndTag();
            _jsp_ForEachTag_54.release();
        }
        catch(Throwable throwable){
            _jsp_ForEachTag_54.doCatch(throwable);
        }
        finally{
            _jsp_ForEachTag_54.doFinally();
        }
        /* NODE END: lineNumber: 33, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_54 */

        /* TEXT: lineNumber: 33 */
        out.write("\r\n");
        /* EXPRESSION: lineNumber: 34 */
        out.write(expressionContext.getString("user.userName"));
        /* TEXT: lineNumber: 34 */
        out.write("\r\n< test1\r\n\r\n</ test2 >\r\n\r\n</test3  >\r\n\r\n</body>\r\n</html>");
        out.flush();
        jspWriter.flush();
    }
}
