/*
 * $RCSfile: Test6Template.java,v $$
 * $Revision: 1.1 $
 * $Date: 2017-02-09 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: test6.jsp
 * lastModified: 2017-02-09 23:25:18 736
 * options: -fastJstl true
 * template.dependencies
 * -- /test6.jsp
 *
 * JSP generated by JspCompiler-1.0.1.4 (built 2017-02-09 23:33:35 542)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;
import java.util.List; // jsp:directive.import: lineNumber: 1


/**
 * <p>Title: Test6Template</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class Test6Template extends JspTemplate {
    /**
     * @param args
     */
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        Test6Template template = new Test6Template();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page import="java.util.List"/>

        // TEXT: lineNumber: 1
        // out.write("<div>\r\n<h1>");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);

        // jsp:expression: lineNumber: 3
        expressionContext.print(out, (pageContext.getAttribute("name")));
        // jsp:expression END

        // TEXT: lineNumber: 3
        // out.write("</h1>\r\n");
        out.write(_jsp_string_6, 0, _jsp_string_6.length);

        // jsp:scriptlet: lineNumber: 4
    java.util.List<String> data = ((List<String>)(pageContext.getAttribute("data")));

        // jsp:scriptlet END

        // TEXT: lineNumber: 6
        // out.write("<table border=\"");
        out.write(_jsp_string_9, 0, _jsp_string_9.length);
        // VARIABLE: lineNumber: 7
        expressionContext.print(out, pageContext.getAttribute("border"));
        // TEXT: lineNumber: 7
        // out.write("\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n");
        out.write(_jsp_string_11, 0, _jsp_string_11.length);

        // jsp:scriptlet: lineNumber: 11
        for(String cell : data) {
    
        // jsp:scriptlet END

        // TEXT: lineNumber: 13
        // out.write("        <tr>\r\n            <th>");
        out.write(_jsp_string_14, 0, _jsp_string_14.length);

        // jsp:expression: lineNumber: 15
        expressionContext.print(out, (cell));
        // jsp:expression END

        // TEXT: lineNumber: 15
        // out.write("</th>\r\n        </tr>\r\n");
        out.write(_jsp_string_17, 0, _jsp_string_17.length);

        // jsp:scriptlet: lineNumber: 17
}
        // jsp:scriptlet END

        // TEXT: lineNumber: 17
        // out.write("</table>\r\n\r\n<table border=\"");
        out.write(_jsp_string_20, 0, _jsp_string_20.length);
        // VARIABLE: lineNumber: 20
        expressionContext.print(out, pageContext.getAttribute("border"));
        // TEXT: lineNumber: 20
        // out.write("\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n");
        out.write(_jsp_string_22, 0, _jsp_string_22.length);

        // jsp:scriptlet: lineNumber: 24
        for(String cell : data) {
    
        // jsp:scriptlet END

        // TEXT: lineNumber: 26
        // out.write("        <tr>\r\n            <th>");
        out.write(_jsp_string_25, 0, _jsp_string_25.length);

        // jsp:expression: lineNumber: 28
        expressionContext.print(out, (cell));
        // jsp:expression END

        // TEXT: lineNumber: 28
        // out.write("</th>\r\n        </tr>\r\n");
        out.write(_jsp_string_28, 0, _jsp_string_28.length);

        // jsp:scriptlet: lineNumber: 30
}
        // jsp:scriptlet END

        // TEXT: lineNumber: 30
        // out.write("</table>\r\n\r\n<table border=\"");
        out.write(_jsp_string_31, 0, _jsp_string_31.length);
        // VARIABLE: lineNumber: 33
        expressionContext.print(out, pageContext.getAttribute("border"));
        // TEXT: lineNumber: 33
        // out.write("\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n");
        out.write(_jsp_string_33, 0, _jsp_string_33.length);

        // jsp:scriptlet: lineNumber: 37
        for(String cell : data) {
    
        // jsp:scriptlet END

        // TEXT: lineNumber: 39
        // out.write("        <tr>\r\n            <th>");
        out.write(_jsp_string_36, 0, _jsp_string_36.length);

        // jsp:expression: lineNumber: 41
        expressionContext.print(out, (cell));
        // jsp:expression END

        // TEXT: lineNumber: 41
        // out.write("</th>\r\n        </tr>\r\n");
        out.write(_jsp_string_39, 0, _jsp_string_39.length);

        // jsp:scriptlet: lineNumber: 43
}
        // jsp:scriptlet END

        // TEXT: lineNumber: 43
        // out.write("</table>\r\n\r\n<table border=\"");
        out.write(_jsp_string_42, 0, _jsp_string_42.length);
        // VARIABLE: lineNumber: 46
        expressionContext.print(out, pageContext.getAttribute("border"));
        // TEXT: lineNumber: 46
        // out.write("\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n");
        out.write(_jsp_string_44, 0, _jsp_string_44.length);

        // jsp:scriptlet: lineNumber: 50
        for(String cell : data) {
    
        // jsp:scriptlet END

        // TEXT: lineNumber: 52
        // out.write("        <tr>\r\n            <th>");
        out.write(_jsp_string_47, 0, _jsp_string_47.length);

        // jsp:expression: lineNumber: 54
        expressionContext.print(out, (cell));
        // jsp:expression END

        // TEXT: lineNumber: 54
        // out.write("</th>\r\n        </tr>\r\n");
        out.write(_jsp_string_50, 0, _jsp_string_50.length);

        // jsp:scriptlet: lineNumber: 56
}
        // jsp:scriptlet END

        // TEXT: lineNumber: 56
        // out.write("</table>\r\n</div>");
        out.write(_jsp_string_53, 0, _jsp_string_53.length);

        out.flush();
        jspWriter.flush();
    }

    protected static final char[] _jsp_string_3 = "<div>\r\n<h1>".toCharArray();
    protected static final char[] _jsp_string_6 = "</h1>\r\n".toCharArray();
    protected static final char[] _jsp_string_9 = "<table border=\"".toCharArray();
    protected static final char[] _jsp_string_11 = "\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_14 = "        <tr>\r\n            <th>".toCharArray();
    protected static final char[] _jsp_string_17 = "</th>\r\n        </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_20 = "</table>\r\n\r\n<table border=\"".toCharArray();
    protected static final char[] _jsp_string_22 = "\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_25 = "        <tr>\r\n            <th>".toCharArray();
    protected static final char[] _jsp_string_28 = "</th>\r\n        </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_31 = "</table>\r\n\r\n<table border=\"".toCharArray();
    protected static final char[] _jsp_string_33 = "\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_36 = "        <tr>\r\n            <th>".toCharArray();
    protected static final char[] _jsp_string_39 = "</th>\r\n        </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_42 = "</table>\r\n\r\n<table border=\"".toCharArray();
    protected static final char[] _jsp_string_44 = "\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_47 = "        <tr>\r\n            <th>".toCharArray();
    protected static final char[] _jsp_string_50 = "</th>\r\n        </tr>\r\n".toCharArray();
    protected static final char[] _jsp_string_53 = "</table>\r\n</div>".toCharArray();

}
