/*
 * $RCSfile: Test5Template.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /test5.jsp
 * lastModified: 2016-01-11 13:18:42 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-12 23:30:13 624)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: Test5Template</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class Test5Template extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        Test5Template template = new Test5Template();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // TEXT: lineNumber: 1
        // out.write("<div>\r\n<h1>");
        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        // VARIABLE: lineNumber: 2
        expressionContext.print(out, pageContext.getAttribute("name"));
        // TEXT: lineNumber: 2
        // out.write("</h1>\r\n<table border=\"");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);
        // VARIABLE: lineNumber: 3
        expressionContext.print(out, pageContext.getAttribute("border"));
        // TEXT: lineNumber: 3
        // out.write("\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);

        // NODE START: lineNumber: 7, offset: 5, length: 5, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_6
        // <c:forEach var=\"cell\" items=\"${data}\">...</c:forEach>
        Object _jsp_old_var_6 = pageContext.getAttribute("cell");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_6 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_6.setParent((Tag)null);
        _jsp_ForEachTag_6.setPageContext(pageContext);
        _jsp_ForEachTag_6.setVar("cell");
        _jsp_ForEachTag_6.setItems(pageContext.getAttribute("data"));
        if(_jsp_ForEachTag_6.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // TEXT: lineNumber: 7
                // out.write("        <tr>\r\n            <th>");
                out.write(_jsp_string_7, 0, _jsp_string_7.length);
                // VARIABLE: lineNumber: 9
                expressionContext.print(out, pageContext.getAttribute("cell"));
                // TEXT: lineNumber: 9
                // out.write("</th>\r\n        </tr>\r\n");
                out.write(_jsp_string_9, 0, _jsp_string_9.length);
                if(_jsp_ForEachTag_6.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_6.release();
        pageContext.setAttribute("cell", _jsp_old_var_6);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 7, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_6

        // TEXT: lineNumber: 11
        // out.write("</table>\r\n\r\n<table border=\"");
        out.write(_jsp_string_11, 0, _jsp_string_11.length);
        // VARIABLE: lineNumber: 14
        expressionContext.print(out, pageContext.getAttribute("border"));
        // TEXT: lineNumber: 14
        // out.write("\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n");
        out.write(_jsp_string_13, 0, _jsp_string_13.length);

        // NODE START: lineNumber: 18, offset: 13, length: 5, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_14
        // <c:forEach var=\"cell\" items=\"${data}\">...</c:forEach>
        Object _jsp_old_var_14 = pageContext.getAttribute("cell");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_14 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_14.setParent((Tag)null);
        _jsp_ForEachTag_14.setPageContext(pageContext);
        _jsp_ForEachTag_14.setVar("cell");
        _jsp_ForEachTag_14.setItems(pageContext.getAttribute("data"));
        if(_jsp_ForEachTag_14.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // TEXT: lineNumber: 18
                // out.write("        <tr>\r\n            <th>");
                out.write(_jsp_string_15, 0, _jsp_string_15.length);
                // VARIABLE: lineNumber: 20
                expressionContext.print(out, pageContext.getAttribute("cell"));
                // TEXT: lineNumber: 20
                // out.write("</th>\r\n        </tr>\r\n");
                out.write(_jsp_string_17, 0, _jsp_string_17.length);
                if(_jsp_ForEachTag_14.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_14.release();
        pageContext.setAttribute("cell", _jsp_old_var_14);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 18, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_14

        // TEXT: lineNumber: 22
        // out.write("</table>\r\n\r\n<table border=\"");
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        // VARIABLE: lineNumber: 25
        expressionContext.print(out, pageContext.getAttribute("border"));
        // TEXT: lineNumber: 25
        // out.write("\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n");
        out.write(_jsp_string_21, 0, _jsp_string_21.length);

        // NODE START: lineNumber: 29, offset: 21, length: 5, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_22
        // <c:forEach var=\"cell\" items=\"${data}\">...</c:forEach>
        Object _jsp_old_var_22 = pageContext.getAttribute("cell");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_22 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_22.setParent((Tag)null);
        _jsp_ForEachTag_22.setPageContext(pageContext);
        _jsp_ForEachTag_22.setVar("cell");
        _jsp_ForEachTag_22.setItems(pageContext.getAttribute("data"));
        if(_jsp_ForEachTag_22.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // TEXT: lineNumber: 29
                // out.write("        <tr>\r\n            <th>");
                out.write(_jsp_string_23, 0, _jsp_string_23.length);
                // VARIABLE: lineNumber: 31
                expressionContext.print(out, pageContext.getAttribute("cell"));
                // TEXT: lineNumber: 31
                // out.write("</th>\r\n        </tr>\r\n");
                out.write(_jsp_string_25, 0, _jsp_string_25.length);
                if(_jsp_ForEachTag_22.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_22.release();
        pageContext.setAttribute("cell", _jsp_old_var_22);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 29, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_22

        // TEXT: lineNumber: 33
        // out.write("</table>\r\n\r\n<table border=\"");
        out.write(_jsp_string_27, 0, _jsp_string_27.length);
        // VARIABLE: lineNumber: 36
        expressionContext.print(out, pageContext.getAttribute("border"));
        // TEXT: lineNumber: 36
        // out.write("\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n");
        out.write(_jsp_string_29, 0, _jsp_string_29.length);

        // NODE START: lineNumber: 40, offset: 29, length: 5, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_30
        // <c:forEach var=\"cell\" items=\"${data}\">...</c:forEach>
        Object _jsp_old_var_30 = pageContext.getAttribute("cell");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_30 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_30.setParent((Tag)null);
        _jsp_ForEachTag_30.setPageContext(pageContext);
        _jsp_ForEachTag_30.setVar("cell");
        _jsp_ForEachTag_30.setItems(pageContext.getAttribute("data"));
        if(_jsp_ForEachTag_30.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // TEXT: lineNumber: 40
                // out.write("        <tr>\r\n            <th>");
                out.write(_jsp_string_31, 0, _jsp_string_31.length);
                // VARIABLE: lineNumber: 42
                expressionContext.print(out, pageContext.getAttribute("cell"));
                // TEXT: lineNumber: 42
                // out.write("</th>\r\n        </tr>\r\n");
                out.write(_jsp_string_33, 0, _jsp_string_33.length);
                if(_jsp_ForEachTag_30.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_30.release();
        pageContext.setAttribute("cell", _jsp_old_var_30);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 40, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_30

        // TEXT: lineNumber: 44
        // out.write("</table>\r\n</div>");
        out.write(_jsp_string_35, 0, _jsp_string_35.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_1 = "<div>\r\n<h1>".toCharArray();
    public static final char[] _jsp_string_3 = "</h1>\r\n<table border=\"".toCharArray();
    public static final char[] _jsp_string_5 = "\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_7 = "        <tr>\r\n            <th>".toCharArray();
    public static final char[] _jsp_string_9 = "</th>\r\n        </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_11 = "</table>\r\n\r\n<table border=\"".toCharArray();
    public static final char[] _jsp_string_13 = "\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_15 = "        <tr>\r\n            <th>".toCharArray();
    public static final char[] _jsp_string_17 = "</th>\r\n        </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_19 = "</table>\r\n\r\n<table border=\"".toCharArray();
    public static final char[] _jsp_string_21 = "\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_23 = "        <tr>\r\n            <th>".toCharArray();
    public static final char[] _jsp_string_25 = "</th>\r\n        </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_27 = "</table>\r\n\r\n<table border=\"".toCharArray();
    public static final char[] _jsp_string_29 = "\">\r\n    <tr>\r\n        <th>&#160;</th>\r\n    </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_31 = "        <tr>\r\n            <th>".toCharArray();
    public static final char[] _jsp_string_33 = "</th>\r\n        </tr>\r\n".toCharArray();
    public static final char[] _jsp_string_35 = "</table>\r\n</div>".toCharArray();

}
