/*
 * $RCSfile: Test1Template.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /test1.jsp
 * lastModified: 2014-07-17 09:57:24 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-12 23:30:10 734)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: Test1Template</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class Test1Template extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        Test1Template template = new Test1Template();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // TEXT: lineNumber: 1
        // out.write("<html>\r\n<head>\r\n<title>test</title>\r\n</head>\r\n<body version=\"1.0\">\r\n<p>");
        out.write(_jsp_string_1, 0, _jsp_string_1.length);
        // EXPRESSION: lineNumber: 6
        expressionContext.print(out, expressionContext.getString("user.userName"));
        // TEXT: lineNumber: 6
        // out.write("</p>\r\n");
        out.write(_jsp_string_3, 0, _jsp_string_3.length);

        // NODE START: lineNumber: 7, offset: 3, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_4
        // <c:if test=\"${1 != 2}\">...</c:if>
        if(ExpressionUtil.getBoolean(expressionContext, "${1 != 2}")) {
        } // jsp.jstl.core.IfTag END
        // NODE END: lineNumber: 7, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_4

        // NODE START: lineNumber: 9, offset: 5, length: 4, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_6
        // <c:forEach items=\"${userList}\" var=\"user\">...</c:forEach>
        Object _jsp_old_var_6 = pageContext.getAttribute("user");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_6 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_6.setParent((Tag)null);
        _jsp_ForEachTag_6.setPageContext(pageContext);
        _jsp_ForEachTag_6.setVar("user");
        _jsp_ForEachTag_6.setItems(pageContext.getAttribute("userList"));
        if(_jsp_ForEachTag_6.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // NODE START: lineNumber: 10, offset: 6, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_7
                // <c:if test=\"${1 == 1}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${1 == 1}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 10, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_7

                if(_jsp_ForEachTag_6.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_6.release();
        pageContext.setAttribute("user", _jsp_old_var_6);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 9, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_6

        // TEXT: lineNumber: 11
        // out.write("<p>");
        out.write(_jsp_string_10, 0, _jsp_string_10.length);
        // EXPRESSION: lineNumber: 12
        expressionContext.print(out, expressionContext.getString("user.userName"));
        // TEXT: lineNumber: 12
        // out.write("</p>\r\n");
        out.write(_jsp_string_12, 0, _jsp_string_12.length);

        // NODE START: lineNumber: 13, offset: 12, length: 4, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_13
        // <c:forEach items=\"${userList}\" var=\"user\">...</c:forEach>
        Object _jsp_old_var_13 = pageContext.getAttribute("user");
        com.skin.ayada.jstl.core.ForEachTag _jsp_ForEachTag_13 = new com.skin.ayada.jstl.core.ForEachTag();
        _jsp_ForEachTag_13.setParent((Tag)null);
        _jsp_ForEachTag_13.setPageContext(pageContext);
        _jsp_ForEachTag_13.setVar("user");
        _jsp_ForEachTag_13.setItems(pageContext.getAttribute("userList"));
        if(_jsp_ForEachTag_13.doStartTag() != Tag.SKIP_BODY) {
            while(true) {
                // NODE START: lineNumber: 13, offset: 13, length: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_14
                // <c:if test=\"${user.userName == &#39;xuesong.net3&#39;}\">...</c:if>
                if(ExpressionUtil.getBoolean(expressionContext, "${user.userName == \'xuesong.net3\'}")) {
                } // jsp.jstl.core.IfTag END
                // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_14

                if(_jsp_ForEachTag_13.doAfterBody() != IterationTag.EVAL_BODY_AGAIN) {
                    break;
                }
            }
        }
        _jsp_ForEachTag_13.release();
        pageContext.setAttribute("user", _jsp_old_var_13);
        // jsp.jstl.core.ForEachTag END
        // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _jsp_ForEachTag_13

        // NODE START: lineNumber: 14, offset: 16, length: 2, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_17
        // <c:out value=\"123\"/>
        com.skin.ayada.jstl.core.OutTag.write(out, 123, false);
        // out.print(123);
        // jsp.jstl.core.OutTag END
        // NODE END: lineNumber: 14, tagClassName: com.skin.ayada.jstl.core.OutTag, tagInstanceName: _jsp_OutTag_17

        // TEXT: lineNumber: 14
        // out.write("\r\n\r\n/* */\r\n<p>");
        out.write(_jsp_string_19, 0, _jsp_string_19.length);
        // EXPRESSION: lineNumber: 17
        expressionContext.print(out, expressionContext.getString("user.userName"));
        // TEXT: lineNumber: 17
        // out.write("</p>\r\n// // //\r\n</body>\r\n</html>");
        out.write(_jsp_string_21, 0, _jsp_string_21.length);

        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_1 = "<html>\r\n<head>\r\n<title>test</title>\r\n</head>\r\n<body version=\"1.0\">\r\n<p>".toCharArray();
    public static final char[] _jsp_string_3 = "</p>\r\n".toCharArray();
    public static final char[] _jsp_string_10 = "<p>".toCharArray();
    public static final char[] _jsp_string_12 = "</p>\r\n".toCharArray();
    public static final char[] _jsp_string_19 = "\r\n\r\n/* */\r\n<p>".toCharArray();
    public static final char[] _jsp_string_21 = "</p>\r\n// // //\r\n</body>\r\n</html>".toCharArray();

}
