/*
 * $RCSfile: TryCatchFinallyTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-09 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /tryCatchFinallyTest.jsp
 * lastModified: 2014-04-02 13:39:32 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-09 14:41:33 758)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: TryCatchFinallyTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class TryCatchFinallyTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        TryCatchFinallyTestTemplate template = new TryCatchFinallyTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // jsp:directive.page: lineNumber: 1
        // <jsp:directive.page contentType="text/html; charset=UTF-8" buffer="8192" autoFlush="true"/>

        // NODE START: lineNumber: 2, offset: 2, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_3
        // <c:execute value=\"${pageContext.getOut().setBufferSize(4096)}\"/>
        ExpressionUtil.evaluate(expressionContext, "${pageContext.getOut().setBufferSize(4096)}", null);
        // jsp.jstl.core.ExecuteTag END
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_3

        // TEXT: lineNumber: 2
        // out.write("\r\n");
        out.write(_jsp_string_5, 0, _jsp_string_5.length);

        // NODE START: lineNumber: 3, offset: 5, length: 2, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_6
        // <c:execute value=\"${pageContext.getOut().setAutoFlush(true)}\"/>
        ExpressionUtil.evaluate(expressionContext, "${pageContext.getOut().setAutoFlush(true)}", null);
        // jsp.jstl.core.ExecuteTag END
        // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.ExecuteTag, tagInstanceName: _jsp_ExecuteTag_6

        // TEXT: lineNumber: 3
        // out.write("\r\n<!--\r\n功能测试\r\n    该测试仅针对解释模式， 编译模式不会存在这个问题。\r\n    测试项目:\r\n        1. 当Tag的doStartTag或者doEndTag返回Tag.SKIP_PAGE时, 父Tag如果是TryCatchFinally标签, 是否能够执行父Tag的doFinally\r\n        2. 如果父Tag的doFinally方法在执行的时候抛出了异常，那么整个执行过程是否能够正常终止。\r\n        3. 如果父Tag的doFinally方法在执行的时候抛出了异常，显示出来的错误信息是否正确。错误信息应该定位到TryCatchFinally标签上，而不应该定位到返回Tag.SKIP_PAGE的标签上。\r\n-->\r\n");
        out.write(_jsp_string_8, 0, _jsp_string_8.length);

        // NODE START: lineNumber: 12, offset: 8, length: 6, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_9
        // <c:tryCatchTest exception=\"doFinally\">...</c:tryCatchTest>
        com.skin.ayada.jstl.core.TryCatchTestTag _jsp_TryCatchTestTag_9 = new com.skin.ayada.jstl.core.TryCatchTestTag();
        try {
            _jsp_TryCatchTestTag_9.setPageContext(pageContext);
            _jsp_TryCatchTestTag_9.setParent((Tag)null);
            _jsp_TryCatchTestTag_9.setException("doFinally");
            int _jsp_start_flag_9 = _jsp_TryCatchTestTag_9.doStartTag();

            if(_jsp_start_flag_9 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_9 != Tag.SKIP_BODY) {
                int _jsp_flag_9 = 0;

                do {
                    // TEXT: lineNumber: 12
                    // out.write("\r\n    ");
                    out.write(_jsp_string_10, 0, _jsp_string_10.length);

                    // NODE START: lineNumber: 13, offset: 10, length: 2, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_11
                    // <c:exit/>
                    if(com.skin.ayada.jstl.core.ContinueTag.getTrue()) {
                        return;
                    }
                    // jsp.jstl.core.ExitTag END
                    // NODE END: lineNumber: 13, tagClassName: com.skin.ayada.jstl.core.ExitTag, tagInstanceName: _jsp_ExitTag_11

                    // TEXT: lineNumber: 13
                    // out.write("\r\n");
                    out.write(_jsp_string_13, 0, _jsp_string_13.length);
                    _jsp_flag_9 = _jsp_TryCatchTestTag_9.doAfterBody();
                }
                while(_jsp_flag_9 == IterationTag.EVAL_BODY_AGAIN);
            }
            _jsp_TryCatchTestTag_9.doEndTag();
            _jsp_TryCatchTestTag_9.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_TryCatchTestTag_9.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_TryCatchTestTag_9.doFinally();
        }
        // NODE END: lineNumber: 12, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_9


        out.flush();
        jspWriter.flush();
    }

    public static final char[] _jsp_string_5 = "\r\n".toCharArray();
    public static final char[] _jsp_string_8 = "\r\n<!--\r\n功能测试\r\n    该测试仅针对解释模式， 编译模式不会存在这个问题。\r\n    测试项目:\r\n        1. 当Tag的doStartTag或者doEndTag返回Tag.SKIP_PAGE时, 父Tag如果是TryCatchFinally标签, 是否能够执行父Tag的doFinally\r\n        2. 如果父Tag的doFinally方法在执行的时候抛出了异常，那么整个执行过程是否能够正常终止。\r\n        3. 如果父Tag的doFinally方法在执行的时候抛出了异常，显示出来的错误信息是否正确。错误信息应该定位到TryCatchFinally标签上，而不应该定位到返回Tag.SKIP_PAGE的标签上。\r\n-->\r\n".toCharArray();
    public static final char[] _jsp_string_10 = "\r\n    ".toCharArray();
    public static final char[] _jsp_string_13 = "\r\n".toCharArray();

}
