/*
 * $RCSfile: TryCatchTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2016-01-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:/WorkSpace/ayada/webapp
 * path: /tryCatchTest.jsp
 * lastModified: 2014-03-25 15:11:38 000
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.2 (built 2016-01-12 23:30:14 664)
 */
package _tpl._jsp;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: TryCatchTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class TryCatchTestTemplate extends JspTemplate {
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        TryCatchTestTemplate template = new TryCatchTestTemplate();

        try {
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable) {
            throwable.printStackTrace();
        }
    }

    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    @SuppressWarnings("unchecked")
    public void _execute(final PageContext pageContext) throws Throwable {
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();
        // NODE START: lineNumber: 1, offset: 0, length: 2, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_1
        // <c:tryCatchTest exception=\"doStartTag\"/>
        com.skin.ayada.jstl.core.TryCatchTestTag _jsp_TryCatchTestTag_1 = new com.skin.ayada.jstl.core.TryCatchTestTag();
        try {
            _jsp_TryCatchTestTag_1.setPageContext(pageContext);
            _jsp_TryCatchTestTag_1.setParent((Tag)null);
            _jsp_TryCatchTestTag_1.setException("doStartTag");
            int _jsp_start_flag_1 = _jsp_TryCatchTestTag_1.doStartTag();

            if(_jsp_start_flag_1 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_1 != Tag.SKIP_BODY) {
                _jsp_TryCatchTestTag_1.doAfterBody();
            }
            _jsp_TryCatchTestTag_1.doEndTag();
            _jsp_TryCatchTestTag_1.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_TryCatchTestTag_1.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_TryCatchTestTag_1.doFinally();
        }
        // NODE END: lineNumber: 1, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_1

        // NODE START: lineNumber: 2, offset: 2, length: 2, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_3
        // <c:tryCatchTest exception=\"doEndTag\"/>
        com.skin.ayada.jstl.core.TryCatchTestTag _jsp_TryCatchTestTag_3 = new com.skin.ayada.jstl.core.TryCatchTestTag();
        try {
            _jsp_TryCatchTestTag_3.setPageContext(pageContext);
            _jsp_TryCatchTestTag_3.setParent((Tag)null);
            _jsp_TryCatchTestTag_3.setException("doEndTag");
            int _jsp_start_flag_3 = _jsp_TryCatchTestTag_3.doStartTag();

            if(_jsp_start_flag_3 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_3 != Tag.SKIP_BODY) {
                _jsp_TryCatchTestTag_3.doAfterBody();
            }
            _jsp_TryCatchTestTag_3.doEndTag();
            _jsp_TryCatchTestTag_3.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_TryCatchTestTag_3.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_TryCatchTestTag_3.doFinally();
        }
        // NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_3

        // NODE START: lineNumber: 3, offset: 4, length: 2, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_5
        // <c:tryCatchTest exception=\"doStartTag, doCatch\"/>
        com.skin.ayada.jstl.core.TryCatchTestTag _jsp_TryCatchTestTag_5 = new com.skin.ayada.jstl.core.TryCatchTestTag();
        try {
            _jsp_TryCatchTestTag_5.setPageContext(pageContext);
            _jsp_TryCatchTestTag_5.setParent((Tag)null);
            _jsp_TryCatchTestTag_5.setException("doStartTag, doCatch");
            int _jsp_start_flag_5 = _jsp_TryCatchTestTag_5.doStartTag();

            if(_jsp_start_flag_5 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_5 != Tag.SKIP_BODY) {
                _jsp_TryCatchTestTag_5.doAfterBody();
            }
            _jsp_TryCatchTestTag_5.doEndTag();
            _jsp_TryCatchTestTag_5.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_TryCatchTestTag_5.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_TryCatchTestTag_5.doFinally();
        }
        // NODE END: lineNumber: 3, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_5

        // NODE START: lineNumber: 4, offset: 6, length: 2, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_7
        // <c:tryCatchTest exception=\"doStartTag, doFinally\"/>
        com.skin.ayada.jstl.core.TryCatchTestTag _jsp_TryCatchTestTag_7 = new com.skin.ayada.jstl.core.TryCatchTestTag();
        try {
            _jsp_TryCatchTestTag_7.setPageContext(pageContext);
            _jsp_TryCatchTestTag_7.setParent((Tag)null);
            _jsp_TryCatchTestTag_7.setException("doStartTag, doFinally");
            int _jsp_start_flag_7 = _jsp_TryCatchTestTag_7.doStartTag();

            if(_jsp_start_flag_7 == Tag.SKIP_PAGE) {
                return;
            }
            if(_jsp_start_flag_7 != Tag.SKIP_BODY) {
                _jsp_TryCatchTestTag_7.doAfterBody();
            }
            _jsp_TryCatchTestTag_7.doEndTag();
            _jsp_TryCatchTestTag_7.release();
        }
        catch(Throwable throwable) {
            try {
                _jsp_TryCatchTestTag_7.doCatch(throwable);
            } catch (Throwable t) {
                throw new Exception(t);
            }
        }
        finally {
            _jsp_TryCatchTestTag_7.doFinally();
        }
        // NODE END: lineNumber: 4, tagClassName: com.skin.ayada.jstl.core.TryCatchTestTag, tagInstanceName: _jsp_TryCatchTestTag_7


        out.flush();
        jspWriter.flush();
    }


}
