/*
 * $RCSfile: AllTagTestTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2013-11-8 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * JSP generated by JspCompiler-0.1.1 (built Wed Nov 13 13:13:29 CST 2013)
 *
 */
package jsp;

import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;

/**
 * <p>Title: AllTagTestTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
public class AllTagTestTemplate extends JspTemplate
{
    /**
     * @param pageContext
     * @throws Exception
     */
    @Override
    public void execute(final PageContext pageContext) throws Exception
    {
        JspWriter out = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /* TEXT: lineNumber: 5 */
        out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n<meta http-equiv=\"Pragma\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Cache-Control\" content=\"no-cache\"/>\r\n<meta http-equiv=\"Expires\" content=\"0\"/>\r\n<title>Select Workspace</title>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"");
        /* EXPRESSION: lineNumber: 13 */
        out.write(expressionContext.getString("domainConfig.resource"));
        /* TEXT: lineNumber: 13 */
        out.write("/resource/finder/css/style.css\"/>\r\n</head>\r\n<body>\r\n<div class=\"finder\">\r\n    <div class=\"menubar\"><h4>&nbsp;Select Workspace</h4></div>\r\n    <div class=\"h20\"></div>\r\n    <div>\r\n        <table class=\"finder\">\r\n            <tr style=\"background-color: #efefef;\">\r\n                <td class=\"icon\">&nbsp;</td>\r\n                <td>Workspace</td>\r\n            </tr>\r\n            ");

        /* NODE START: lineNumber: 25, offset: 3, length: 11, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _tag_instance_4 */
        /* <c:forEach varStatus="status" items="${workspaces}" var="workspace">...</c:forEach> */
        Object _for_each_old_var_4 = pageContext.getAttribute("workspace");
        Object _for_each_old_var_status_4 = pageContext.getAttribute("status");
        com.skin.ayada.jstl.core.ForEachTag _tag_instance_4 = new com.skin.ayada.jstl.core.ForEachTag();

        _tag_instance_4.setParent((Tag)null);
        _tag_instance_4.setPageContext(pageContext);
        _tag_instance_4.setItems(ExpressionUtil.evaluate(expressionContext, "${workspaces}"));
        pageContext.setAttribute("status", _tag_instance_4.getLoopStatus());
        _tag_instance_4.doStartTag();

        while(_tag_instance_4.hasNext()){
            pageContext.setAttribute("workspace", _tag_instance_4.next());
        /* TEXT: lineNumber: 25 */
        out.write("\r\n            <tr>\r\n                <td class=\"icon\"><img src=\"");
        /* EXPRESSION: lineNumber: 27 */
        out.write(expressionContext.getString("domainConfig.resource"));
        /* TEXT: lineNumber: 27 */
        out.write("/resource/finder/images/folder.gif\"/></td>\r\n                <td><a class=\"file\" href=\"/finder/index.srv?workspace=");
        /* EXPRESSION: lineNumber: 28 */
        out.write(expressionContext.getString("URLUtil.encode(workspace)"));
        /* TEXT: lineNumber: 28 */
        out.write("\" title=\"");
        /* EXPRESSION: lineNumber: 28 */
        out.write(expressionContext.getString("HtmlUtil.encode(workspace)"));
        /* TEXT: lineNumber: 28 */
        out.write("\">");
        /* EXPRESSION: lineNumber: 28 */
        out.write(expressionContext.getString("HtmlUtil.encode(workspace)"));
        /* TEXT: lineNumber: 28 */
        out.write("</a></td>\r\n            </tr>\r\n            ");
        }
        _tag_instance_4.release();
        pageContext.setAttribute("workspace", _for_each_old_var_4);
        pageContext.setAttribute("status", _for_each_old_var_status_4);
        /* jsp.jstl.core.ForEachTag END */
        /* NODE END: lineNumber: 25, tagClassName: com.skin.ayada.jstl.core.ForEachTag, tagInstanceName: _tag_instance_4 */

        /* TEXT: lineNumber: 30 */
        out.write("\r\n        </table>\r\n    </div>\r\n</div>\r\n</body>\r\n</html>\r\n");
        out.flush();
    }
}
