/*
 * $RCSfile: MyTestMacroTemplate.java,v $$
 * $Revision: 1.1 $
 * $Date: 2014-07-12 $
 *
 * Copyright (C) 2008 Skin, Inc. All rights reserved.
 *
 * This software is the proprietary information of Skin, Inc.
 * Use is subject to license terms.
 *
 * home: E:\WorkSpace\ayada\webapp
 * path: /macro/myTestMacro.jsp
 * lastModified: 2014-07-12 22:05:36 328
 * options: -fastJstl true
 * JSP generated by JspCompiler-1.0.1.0 (built 2014-07-12 22:08:05 460)
 */
package _tpl._jsp._macro;

import java.io.Writer;
import com.skin.ayada.runtime.ExpressionContext;
import com.skin.ayada.runtime.JspWriter;
import com.skin.ayada.runtime.PageContext;
import com.skin.ayada.tagext.BodyContent;
import com.skin.ayada.tagext.BodyTag;
import com.skin.ayada.tagext.IterationTag;
import com.skin.ayada.tagext.JspFragment;
import com.skin.ayada.tagext.Tag;
import com.skin.ayada.template.JspTemplate;
import com.skin.ayada.util.ExpressionUtil;


/**
 * <p>Title: MyTestMacroTemplate</p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2006</p>
 * @author JspCompiler
 * @version 1.0
 */
@SuppressWarnings("unused")
public class MyTestMacroTemplate extends JspTemplate{
    public static void main(String[] args){
        java.io.StringWriter writer = new java.io.StringWriter();
        PageContext pageContext = com.skin.ayada.runtime.JspFactory.getPageContext(writer);
        MyTestMacroTemplate template = new MyTestMacroTemplate();

        try{
            template.execute(pageContext);
            System.out.println(writer.toString());
        }
        catch(Throwable throwable)
        {
            throwable.printStackTrace();
        }
    }



    /**
     * @param pageContext
     * @throws Throwable
     */
    @Override
    public void _execute(final PageContext pageContext) throws Throwable{
        JspWriter out = pageContext.getOut();
        JspWriter jspWriter = pageContext.getOut();
        ExpressionContext expressionContext = pageContext.getExpressionContext();

        /* TEXT: lineNumber: 1 */
        out.write("Hello, ");
        /* EXPRESSION: lineNumber: 1 */
        out.write(expressionContext.getString("user.userName"));
        /* TEXT: lineNumber: 1 */
        out.write(" !\r\n");

        /* NODE START: lineNumber: 2, offset: 3, length: 3, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_4 */
        /* <c:if test="${user.userName == &#39;xuesong.net&#39;}">...</c:if> */
        if(ExpressionUtil.getBoolean(expressionContext, "${user.userName == \'xuesong.net\'}")){
            /* TEXT: lineNumber: 2 */
            out.write("Are you xuesong.net?");
        } /* jsp.jstl.core.IfTag END */
        /* NODE END: lineNumber: 2, tagClassName: com.skin.ayada.jstl.core.IfTag, tagInstanceName: _jsp_IfTag_4 */

        /* TEXT: lineNumber: 2 */
        out.write("\r\n<p>userName: <input type=\"text\" value=\"\"/></p>");


        out.flush();
        jspWriter.flush();
    }


}
